'use strict';
if (!window.i18n) {
    window.i18n = {};
}

if (!window.i18n.languages) {
    window.i18n.languages = {};
}

window.i18n.languages['English'] = {
    "label_text": {
        "Ads_getRewards_Title": "Get Rewards",
        "Ads_CountDown_tips": "Next Rewards in:",
        "Ads_watchAd_Title": "Watch Ad",
        "Auto_Game": "Auto",
        "Button_Guest_Facebook": "Login with Facebook",
        "Button_Guest_Continue": "Continue as Guest",
        "Button_Common_Confirm": "OK",
        "Button_Common_Yes": "Yes",
        "Button_Common_No": "No",
        "Button_Common_Next": "Next",
        "Button_Common_Restart": "Restart",
        "Button_Common_Return": "Back",
        "Button_Common_Share": "Share",
        "Button_Common_Start": "Start",
        "Button_Common_Facebook": "Login via Facebook",
        "Button_Common_Guest": "Guest",
        "Common_Guest_BindAccount": "Link your Facebook account?",
        "Common_Guest_BindAccountFail": "Facebook connection is failed. Please try it again later.",
        "Common_Guest_RepeatBind": "You have already linked a Facebook account. Log in with that account?",
        "Common_Guest_Confirm": "You are logged in as a guest and cannot play with your friends. \nLog in through Facebook to: \n1. Play with your friends \n2. Use your profile picture in game \n3. Play across multiple devices with the same accountYou are logged in as a guest and cannot play with your friends.",
        "Common_Online_ShareContent": "I ranked #{1} in {0} and won {2} coins!",
        "Common_Scene_Teamup_Teammateturn": "You can continue to play and help your teammate now!",
        "Common_Game_Props_GetTipsTitle_DoubleDice": "Double Distance",
        "Common_Game_Props_GetTipsContent_DoubleDice": "Roll dice and get double distance.",
        "Common_Game_Props_GetTipsTitle_AssignDice": "Dice Control",
        "Common_Game_Props_GetTipsContent_AssignDice": "Control what number you want on dice",
        "Common_Game_Props_GetTipsTitle_Protection": "Protection Shield",
        "Common_Game_Props_GetTipsContent_Protection": "Be protected from the other Tokens for 1 turn",
        "Common_Game_Props_GetTipsTitle_LuckyNumber": "Golden Number",
        "Common_Game_Props_GetTipsContent_LuckyNumber": "Within 1 round, any player who rolls this number can roll again.",
        "Common_Scene_Props_Introduce_Title": "Prop Mode Introduce",
        "Common_Scene_Props_introduce_luckyNumber": "Golden Number",
        "Common_Scene_Props_introduce_luckyNumber_": "Within 1 round, any player who rolls this number can roll again. Immediately effective and applies to all players.",
        "Common_Scene_Props_introduce_DoubleDice": "Double Distance",
        "Common_Scene_Props_introduce_DoubleDice_": "Doubles the number rolled. Player must move that many spaces immediately. After using this item, rolling a 6 does not give bonus rolls and cannot move out a tokens.",
        "Common_Scene_Props_introduce_AssignDice": "Controlled Dice",
        "Common_Scene_Props_introduce_AssignDice_": "Player chooses the number of the dice roll. A bonus roll is available when rolling a 6, kicking a tokens, or reaching the goal.",
        "Common_Scene_Props_introduce_Protection": "Shield",
        "Common_Scene_Props_introduce_Protection_": "Protects all tokens from being kicked for 1 round.",
        "Common_Game_Props_ShowTips_LuckyNumber": "Bonus Roll",
        "Common_Game_Props_ShowTips_LuckyNumber_": "Get an extra roll when you reach",
        "Common_Game_Props_ShowTips_DoubleDice": "Double Distance",
        "Common_Game_Props_ShowTips_DoubleDice_": "Travel double the distance you get in dice",
        "Common_Game_Props_ShowTips_AssignDice": "Dice Control",
        "Common_Game_Props_ShowTips_AssignDice_": "Control what number you want on dice",
        "Common_Game_Props_ShowTips_Protection": "Protection Shield",
        "Common_Game_Props_ShowTips_Protection_": "Be protected from the other Tokens for 1 turn",
        "Common_Game_Props_Haved": "Power items can only be used before you roll the dice.",
        "Common_Game_Props_NotHaved": "You don't have this Power item yet.",
        "Common_Team": "Team",
        "Common_Choose_Color": "Select Color",
        "Common_Game_Online_MyPlace": "You are here !",
        "Common_Choose_Number": "Select Players",
        "Common_Choose_Bet": "Choose Bet",
        "Common_Choose_Mode": "Select Mode",
        "Common_Choose_Number_players": "Players",
        "Common_Choose_Win": "Win:",
        "Common_Choose_Entry": "Entry:",
        "Common_Choose_Number_two": "2",
        "Common_Choose_Number_four": "4",
        "Common_Choose_Number_multi": "2~4",
        "Common_Choose_Number_Team": "Team up",
        "Common_Choose_Number_2v2": "2V2",
        "Common_Game_Props_share": "Share and get\nitems!",
        "Common_Game_Props_UseChooseNumber_AssignDice": "Choose Number",
        "Common_Game_Props_sharetogetprops_title": "Share with friends to get 3 free Power items!",
        "Common_Game_Props_sharetogetprops_share": "Share",
        "Common_Game_Props_sharetogetprops_aftershare": "Each game can only be shared once",
        "Friend_Room_Entering": "Entering the room...",
        "Friends_Invite": "Invite via:",
        "GameName": "Ludo World",
        "Game_Common_start": "Game Start",
        "Game_EndTitle_Win": "Win",
        "Game_EndTitle_Lose": "Lose",
        "Game_EndOrder_1": "1st",
        "Game_EndOrder_2": "2nd",
        "Game_EndOrder_3": "3rd",
        "Game_EndOrder_Win": "Win",
        "Game_EndOrder_4": "4th",
        "Game_EndOrder_5": "5th",
        "Game_EndOrder_6": "6th",
        "Game_EndOrder_Lose": "Lose",
        "Game_EndOrder_Playing": "Playing",
        "local_Result_title": "Result",
        "Game_Online_Auto1": "Auto Move",
        "Game_Online_Auto2": "Tap here to stop",
        "Game_Props_TopTitle_LuckyNumber": "Golden\n Number",
        "Game_Props_ItemTips_DoubleDice": "Double Distance:Doubles the number rolled. Player must move that many spaces immediately After using this item, rolling a 6 does not give bonus rolls and cannot move out a tokens.",
        "Game_Props_ItemTips_AssignDice": "Controlled Dice: Player chooses the number of the dice roll.A bonus roll is available when rolling a 6, kicking a tokens, or reaching the goal.",
        "Game_Props_ItemTips_Protection": "Shield: Protects all tokens from being kicked for 1 round.",
        "Game_leaderboard_title": "Leaderboard",
        "Game_leaderboard_global": "Global",
        "Game_leaderboard_NotRanked": "No Ranking",
        "Game_leaderboard_tips": "Stats will be updated every Monday.",
        "Game_leaderboard_tips2": "Only online games are counted.",
        "Game_leaderboard_tipsoneline": "Stats(Online games) update every Monday.",
        "Game_Computer_PlayerName1": "Computer1",
        "Game_Computer_PlayerName2": "Computer2",
        "Game_Computer_PlayerName3": "Computer3",
        "Game_Computer_level_choose": "Select level",
        "Game_Computer_Self": "You",
        "Game_Computer_level_easy": "Easy",
        "Game_Computer_level_normal": "Normal",
        "Game_Computer_level_hard": "Hard",
        "Game_Computer_PlayerNameEasy": "Computer{num} Easy",
        "Game_Computer_PlayerNamenormal": "Computer{num} Normal",
        "Game_Computer_PlayerNamehard": "Computer{num} Hard",

        "Game_local_Remove_comfirm": "Are you sure you want to remove this player?",
        "Game_local_Remove_guide_title": "Remove Player",
        "Game_local_Remove_guide_content1": "Who don't want to play",
        "Game_Friend_Pnael_Title": "Play With Friends",
        "Game_Friend_Select_Mode": "Select  Game Mode",
        "Game_Friend_Create": "Create",
        "Game_Friend_Join": "Join",
        "Game_Friend_Join_Clear": "Clear",
        "Game_Friend_GameMode": "Choose Game Mode",
        "Game_Friend_Enter_RoomCode": "Please enter the Room Code",
        "Game_friends_invite_code": "Room Code",
        "Game_friends_invite_tips_cannot": "Waiting for players...",
        "Game_friends_invite_tips_can": "Waiting for more or start right now.",
        "Game_friends_join_tips": "Enter Room Code",
        "Game_friends_join_join": "Join",
        "Game_friends_join_wait": "Waiting for {who} to start",
        "Game_friends_choose_classic": "Classic",
        "Game_friends_choose_power": "Power",
        "Game_friends_choose_mode": "Mode",
        "Game_friends_invite_waiting": "Waiting for players...",
        "Game_friends_invite_waitormore": "Waiting for more or start right now",
        "Game_friends_invite_start2V2": "You can start the game",
        "Game_friends_invite_share": "Invite your friends by sharing the Room Code",
        "Game_Ready": "Ready!",
        "Guest_Username": "Guest",
        "help_classic_title": "Classic",
        "help_powerUp_title": "Power",
        "InGame_PlayerInfo_Match": "Match",
        "InGame_PlayerInfo_Win": "Win",
        "InGame_PlayerInfo_Gift": "Gift (100 coins per gift)",
        "introduce_friendModel": "play with only friends",
        "LevelUp_Panel": "Level Up",
        "LevelProgressPanelExp": "Exp",
        "LoadGame_Button_Load": "Load",
        "Login_loading": "Logging in…",
        "Lobby_receive_award_coins": "Coins",
        "Lobby_invite_detail1": "Invite friends and get {num} coins for each friend that joins via the link",
        "Lobby_invite_detail2": "You will get a reward by Mail after your friends connect through Facebook (Max {times} times per day)",
        "Lobby_invite_btn": "Invite",
        "Lobby_invite_title": "Need More Coins?",
        "Lobby_invite_guestlogin": "Connect your Facebook account to continue?",
        "MainScenes_Fackback": "Feedback",
        "MainScenes_Ranking": "Ranking",
        "MainScenes_Invite": "Invite",
        "MainScenes_FreeCoins": "Free Coins",
        "MainScenes_Mission": "Mission",
        "modify_title": "Edit Profile",
        "Notice_Panel_Title": "Notice",
        "Notice_Panel": "Loading",
        "NotLogin": "Login failed. Please try again later.",
        "Offline_TeamA": "team A",
        "Offline_TeamB": "team B",
        "OffLine_PanelPlayer": "Players",
        "PropsShareTips": "Share and get \n items!",
        "Props_ShowTips": "EXAMPLE",
        "PersonalInfo_Win": "Win",
        "PersonalInfo_Total": "Total",
        "PersonalInfo_WinRate": "Win Rate",
        "PersonalInfo_Edit": "Edit",
        "PersonalInfo_Computer": "Computer",
        "PersonalInfo_ClassicOnline": "Classic Mode",
        "PersonalInfo_PropsOnline": "Power Mode",
        "PersonalInfo_Props2V2": "Power-2V2 Mode",
        "PersonalInfo_Classic2V2": "Classic-2V2 Mode",
        "PersonalInfo_Notenough_player": "Waiting for {Number} more players",
        "PersonalInfo_Friend": "Friends",
        "PersonalInfo_Level": "Lv.",
        "PersonalInfo_ClassicOnlineTitle": "Online-Classic",
        "PersonalInfo_PropsOnlineTitle": "Online-Power",
        "PersonalInfo_TeamUpOnline": "Team Up Mode",
        "PersonalInfo_MiniMapOnline": "Mini Map Mode",
        "PlayerProfile_LoginFB": "Login with Facebook",
        "PlayerProfile_Continue": "Continue",
        "Rank_PanelWin": "Win",
        "Select_Robot": "At least 2 humans are needed.",
        "SaveGame_Content": "Are you sure you want to end the game?",
        "SaveGame_Save": "Save",
        "ShareGame_EXP": "Share and get 10 EXP",
        "share_window_invite": "Invite Friends",
        "Scene_Online_Title": "Online",
        "Scene_local_Title": "Local",
        "Scene_local_ChooseMode": "Select Mode",
        "Scene_local_ChooseMode_Classic": "Classic",
        "Scene_local_ChooseMode_Props": "Power",
        "Scene_local_ChooseMode_TeamUp": "Team Up",
        "Scene_local_ChooseMode_TeamPower": "Team Power",
        "Scene_local_ChooseMode_TeamClassic": "Team Classic",
        "Scene_local_ChooseColorAndName": "Choose Color & Name",
        "Scene_Online_ChooseBet": "Choose Your Bet",
        "Scene_local_ChoosePlaers": "Select Players",
        "Scene_local_ChoosePlaers_2P": "2 Players",
        "Scene_local_ChoosePlaers_3P": "3 Players",
        "Scene_local_ChoosePlaers_4P": "4 Players",
        "Scene_local_PlayerName1": "Player 1",
        "Scene_local_PlayerName2": "Player 2",
        "Scene_local_PlayerName3": "Player 3",
        "Scene_local_PlayerName4": "Player 4",
        "Scene_local_ChooseTeam": "Choose Team",
        "Scene_ClassicOnline_Title": "Classic",
        "Scene_PropsOnline_Title": "Power Up",
        "Scene_MiniMapOnline_Title": "Mini Map",
        "Scene_TeamUpOnline_Title": "Team Up",
        "Scene_Computer_Title": "Computer",
        "Scene_Friend_Title": "Friends",
        "Scene_Online_ChoosePlaers_2P": "2 Players",
        "Scene_Online_ChoosePlaers_4P": "4 Players",
        "Scene_Online_matching": "Waiting for other players…",
        "Set_Panel_Title": "Setting",
        "Set_Panel_Music": "Music",
        "Set_Panel_Sound": "Sound",
        "Set_Panel_Version": "Version",
        "Set_Panel_About": "About",
        "Set_Panel_About_Detail": "Thank you for supporting\nLudo World! If you\nhave any feedback,\nplease contact us at\nhpludoworld@gmail.com",
        "Set_Panel_Help": "Help",
        "Set_Panel_Feedback": "Feedback",
        "Set_Panel_US": "Like Us",
        "Set_Panel_RATE": "Rate Us",
        "Set_Panel_Privacy": "Privacy Policy",
        "Set_Panel_Terms": "Terms of Service",
        "Set_FB_Login": "Login",
        "Set_FB_Logout": "Logout",
        "Set_FB_Bind": "Connect",
        "Set_Panel_Vibrate": "Vibration",
        "Set_Panel_Chat": "Chat",
        "Set_Panel_Help_minimap": "Same rules as Classic Mode.\nSmaller map, faster pace.\nOnly 4 safe squares, one each at the starting point of every color.",
        "Title_Load_Game": "Load game",
        "Title_PlayerProfile": "Profile",
        "Tips_Game__ThreeSixSkip": "3 times continuous\nsix,skip!",
        "Lucky_Wheel_Name": "Lucky Wheel",
        "Game_info_block": "Block",
        "Game_info_unblock": "Unblock",
        "Button_Item_Use": "Use",
        "Button_Item_Using": "Using",
        "Button_Item_gotouse": "Go to use",
        "Main_Backpack": "Backpack",
        "Item_Duration_Duration": "Duration:",
        "Item_Duration_Day": "d",
        "Item_Duration_Hour": "h",
        "Item_Duration_Min": "min",
        "Item_Duration_S": "s",
        "Item_Duration_Year": "y",
        "Item_Duration_Permanent": "Permanent",
        "NewPlayerBonus_Gift": "Gift",
        "Common_Game_item_purchase": "Purchase via Item Cards，your have {num} left",
        "Common_Game_item_purchaseoverbuy": "You can only exchange {num} times per game",
        "Common_Game_itemcard_notenought": "Not enough item cards! Purchase more from the Store?",
        "Lobby_mini": "Mini Map",
        "Common_IOS_Shop_LessConins": "Not enough coins. Get more through the event.",
        "ComputerAndLocal": "Computer&Local",
        "Common_Game_Undo_Lack": "lack",
        "Common_Game_Undo_Lack_Tip": "Not enough gems to undo",
        "Common_Game_Undo_Left": "Undo left",
        "Common_Game_Undo_Switch": "Undo on",
        "Common_Game_Undo_Title_Enable": "Undo Dice roll",
        "Common_Game_Undo_Title_Disable": "Undo is turned OFF",
        "Common_Game_Undo_Desc_Enable": "Tap this within {num} secs after rolling dice to undo dice result",
        "Common_Game_Undo_Desc_Disable": "You have disabled the undo option. Tap the box to enable it again",
        "Common_Game_Undo_Desc_Use_Up": "No times to undo",
        "Grand_Prix_Entry": "ENTRY FEE",
        "Grand_Prix_Endsin": "Ends in",
        "Grand_Prix_Play": "PLAY",
        "Grand_More_Coins":"More Coins",
        "Grand_More_Level":"Lv.{date} open",
        "Starter_Pack":"Starter Pack",
        "Gift_Bag_Time":"{date} hours left",
        "Lucky_Dice":"Lucky Dice",
        "Exclusive_Offert":"Exclusive Offer",
    },
    "AlertText": {
        "Button_Common_Confirm": "OK",
        "Button_Common_Yes": "Yes",
        "Button_Common_Cancel": "Cancel",
        "Button_Common_No": "No",
        "Button_Common_Upgrade": "Upgrade",
        "Button_Common_NoUpgrade": "Not Now",
        "Button_Common_ExitUpgrade": "Exit Game",
        "Bind_FB_Account": "Facebook connection is failed. Please try it again later.",
        "Bind_FB_Account2": "This Facebook account is already connected. Please try again with another account.",
        "Common_Game_Online_Leave": "You will lose if you leave the game. Leave anyway?",
        "Common_Game_Local_Leave": "Leave the current game?",
        "Common_Game_Local_SaveGame": "Save the current game?",
        "Common_Game_Computer_SaveGame": "Save the current game?",
        "Common_Game_Computer_EnterBySaveGame": "You have an unfinished game. Load it?",
        "Common_Notify_Client_Logout": "This account has been logged into another device. Log in again to continue playing on this device.",
        "Common_Netword_Fail": "Please check your network connection.",
        "Common_Netword_Fail_Offline": "Network connection failed. Go to play Local and Computer Mode?",
        "Common_Netword_FailRethy": "Network connection failed.Connect now?",
        "Common_Netword_Fail_timeout": "Network connection time out. Please try again later.",
        "Common_Netword_Fail_Reconnect": "You need to connect to the network to play online games.Connect now?",
        "Common_Lobby_ReturnGame": "You are playing in a room. Return to the room?",
        "Common_Lobby_ReturnFailed": "Your last game has ended.",
        "Common_Scene_Online_LessCoins": "Not enough coins. Purchase more from the Store.",
        "Common__Online_Matching_Failed": "Failed to enter room.Please try again later.",
        "Common_Scene_Online_Matching_TimeOut": "Timed out while trying to enter room. Please try again later.",
        "Common_Scene_Online_Sitting_Failed": "Failed to sit down. Please try again later.",
        "Common_No_Operation": "You will be removed from the game if you stay inactive for too long.",
        "Common_Delete": "Are you sure you want to delete the saved game?",
        "Common_Game_TeamUp_GetUserGuide": "Team Up is a new brand new mode! Enter tutorial?",
        "Facebook_Login_Faile": "Facebook login failed. Please check your network.",
        "Game_leaderboard_sendBean_success": "Coins are gifted successfully",
        "Game_leaderboard_sendBean_fail": "Failed to send coins",
        "Game_leaderboard_sendBean_Max": "You've reached maximum number of gifting coins today.",
        "Game_Reselect_bet": "Coins you have is more than the bet limit. Please start a new game in higher bet room.",
        "Game_chat_Common_Yes": "Turn on",
        "Game_chat_Common_MainText": "When chat is activated, other player may be able to see your conversations. Turn on chat now? Chat can be disabled later in settings.",
        "Game_Friend_Join_Not_Find": "Room not found. Please check the Room Code.",
        "Game_Friend_Join_Room_Closed": "The room is already dismissed. Please start a new game.",
        "Game_Friend_Join_Not_Enough_Coins": "You don't have enough coins to join the room. Get more from the store?",
        "Game_Friend_Join_No_Extra_Seat": "Oops, the room is fully occupied. Please start a new game.",
        "Game_Friend_Join_alreadybegin": "The game has already began.  Please start a new game.",
        "Game_Friend_Leave_Room": "The room will be closed if you leave. Leave anyway?",
        "Login_NO_IP": "Unfortunately based on your current location, we cannot offer our services to you at this time.",
        "Modify_HeadIcon_Fail": "Modify Fail, please try again later.",
        "Matching_Failed": "Game matching failed. Please try it again later.",
        "No_Operation_ConfirmText": "Stay",
        "No_Operation_CancelText": "Leave",
        "Quit_Game": "Are you sure you want to quit the game?",
        "Store_buy_tips": "Not enough coins. Get more from the store?",
        "Store_buy_latter": "Not now!",
        "Store_Open_Failed": "Failed to load data. Please try again later.",
        "Store_buy_go": "Go",
        "Store_Payment_Failed": "Payment failed. Error code:",
        "Store_Payment_IPFailed": "Payment failed, you can try to pay by PC Instant Game.",
        "ShortCut_go": "Create a Home Screen Shortcut?",
        "Client_Low_Version": "The room requires the latest version. Update Now?",
        "Client_High_Version": "Oops,your client version can not enter the room.",
        "Client_Deny_Version": "Oops,your client version can not enter the room.",
        "Play_Punish_In_Chat" : "You have been muted until {date} for violating the rules.",
        "Play_Punish_In_Room": "Your accdount is banned until {date} for violating the rules.",
        "Play_Punish_Enter_Room": "Your account has been banned due to violating the rules.",
        "Kicked_Player_Not_Enough_Coins": "Once you do not have enough coins, you will lose the match if kicked. Get more from the store?",
        "Kicked_Player_Game_Lose": "You lose. You don't have enough coins to continue the game.",
        "Backpack_items_empty": "No items yet. Get some from the store?",
        "Grand_Unlock_level": "Unlock when level reaches {date}",
        "Grand_Open_Hint": "Open the big win after {date}",
        "Grand_Less_Coins_recommend": "You have less than the recommended number of coins to enter the game {date}, continue to enter?",
        "Grand_Less_Coins_Hint": "You don't have enough coins to join the big win. Get more from the store?",
    },
    "Tips": {
        "Ads_times_tips": "Come back for more rewards tomorrow.",
        "Ads_times_tips_Gems": "Come back tomorrow for the gems.",
        "Ads_coolCd_tips": "Please try again later.",
        "Ads_none_tips": "No ads to play right now, please try again later.",
        "Ads_none_tips1": "No ads to play right now.",
        "Ads_notFull_tips": "Please watch the full video to get rewards!",
        "Common_Game_Props_UseChooseNumber_AssignDice": "Choose Number",
        "Friend_Err_Fetch_List_Fail": "Failed to load data. Please try again later.",
        "Friend_Err_Fetch_Online_Fail": "Failed to load data. Please try again later.",
        "Friend_Err_Fetch_Login_Time_Fail": "Failed to load data. Please try again later.",
        "Friend_Err_Not_Add_Player": "Processing failed，please try again later.",
        "Friend_Err_List_Full": "The number of your friends has reached the maximum. If you need to add this friend, please delete other friends.",
        "Friend_Err_Peer_Friend_List_Full": "{name} has reached the maximum number of friends and cannot be added.",
        "Friend_Err_Update_Friend_Fail": "Failed to load data. Please try again later.",
        "Friend_Err_Player_Refuse_Add": "{name} is not accepting any friend requests.",
        "Friend_Err_Already_In_Add_List": "",
        "Friend_Err_Already_In_Game_List": "You are already friends.",
        "Friend_Err_Already_In_Platform_List": "You are already friends.",
        "Friend_Err_Not_In_List": "Processing failed，please try again later.",
        "Friend_Err_Fetch_Game_Record_Fail": "Failed to load data. Please try again later.",
        "Friend_Err_Cannot_Add_Self": "Failed to add, please try again later.",
        "Game_Props_TopTitle_LuckyNumber": "Golden\n Number",
        "Game_Props_ItemTips_DoubleDice": "Double Distance:Doubles the number rolled. Player must move that many spaces immediately After using this item, rolling a 6 does not give bonus rolls and cannot move out a tokens.",
        "Game_Props_ItemTips_AssignDice": "Controlled Dice: Player chooses the number of the dice roll.A bonus roll is available when rolling a 6, kicking a tokens, or reaching the goal.",
        "Game_Props_ItemTips_Protection": "Shield: Protects all tokens from being kicked for 1 round.",
        "Game_gift_gift": "Send emoji",
        "Game_gift_giftprice": "100 coins per Emoji",
        "Game_gift_sendtoofast": "Take a break.",
        "Game_leaderboard_load_fail_tips": "Failed to load data. Please try again later.",
        "Game_classic_newusertips_moveout1": "Roll 6 to take off!",
        "Game_classic_newusertips_mesafe": "All star squares are safe!",
        "Game_classic_newusesrtip_bumptoken": "Kick this token!",
        "Game_Friend_JoinTips_Invalid_RoomCode": "Room Code is invalid. Please check it again.",
        "Lobby_unfinish_notice": "The Feature is coming soon!",
        "shortCut_create_succ": "Shortcut creation is successful.",
        "shortCut_create_fail": "Failed to create Shortcut. Please try it again",
        "shortCut_bubble_tips": "Click here to create the Shortcut in Home Screen",
        "Tips_Longin_Fail": "Login failed, please try again later!",
        "Tips_Netword_Fail_TryReconnect": "Network connection failed. Reconnecting",
        "Tips_Netword_Fail_Reconnected": "Reconnected. Welcome back!",
        "Tips_Game__ThreeSixSkip": "3 times continuous\nsix,skip!",
        "Tips_Game_Props_UseTips_DoubleDice": "Double Distance! Roll is doubled!",
        "Tips_Game_Props_UseTips_AssignDice": "Controlled Dice! You rolled a",
        "Tips_Game_Props_UseTips_Protection": "Protects all tokens from being kicked for 1 round.",
        "Tips_Game_Props_UseTips_LuckyNumber": "Bonus Roll, roll again!",
        "Tips_Game_Props_UseFail_DoubleDice": "No tokens to use this item on!",
        "Tips_Game_Props_UseFail_Protection": "No tokens to protect!",
        "Tips_Game_Props_OtherUseTips_DoubleDice": "Double Distance used!",
        "Tips_Game_Props_OtherUseTips_AssignDice": "Controlled Dice used!",
        "Tips_Not_Whatsapp": "This feature requires WhatsApp to be installed.",
        "Tips_NetWork_Connection": "Connecting",
        "Tips_Game_TeamUp_HelpTeammate": "Please go on to play for your teammate!",
        "task_load_fail_tips": "Failed to load data.Please try again later.",
        "Tips_Game_addFriendReq": "Request to add you as friend.",
        "Tips_Game_addFriendReq_accept": "Accept",
        "Tips_Game_addFriendReq_ignore": "Ignore",
        "Tips_Friend_Req": "Friend request has been sent",
        "Tips_Friend_AcceptSucc": "{name} has become your friends.",
        "Tips_Friend_AcceptFailed": "Fail to accept, you can accept from Friend Request later.",
        "Tips_Friend_IgnoreFailed": "Fail to ignore, you can ignore from Friend Request later.",
        "Tips_Friend_RemoveFriend": "Are you sure to delete this friend?",
        "Set_Panel_chatclosetips": "You have blocked all chats.",
        "Tips_Send_Gift": "Tap here to send emojis.",
        "Tips_Send_This_Player_Gift": "Tap here to send emojis to this player.",
        "Tips_Profile_Add_Friends": "Tap profile to add as friends.",
        "Tips_Here_Add_Friends_GamePage": "Tap here to add as friends.",
        "Tips_Here_Add_Friends_GameOver": "Tap here to add as friends.",
        "Tips_Send_Coin_friends": "Send free coin to friends.",
        "Tips_Collect_By_Mail": "Collect free coins from friends by mail.",
        "Item_Use_Success": "You have used {skin}.",
        "Kick_Player_No_Reward_Tips": "{name} is out of coins and has lost. No bonus this time.",
        "Common_Game_Mini_tips": "Get {num} stars to win！Kick or finish a token gets you a star.",
        "Lobby_mini_tips": "Compact&Intense"
    },
    "Chat": {
        "Game_emoji": "Emoji",
        "Game_chat": "Chat",
        "Game_chat_title": "Quick chat",
        "Game_chat_content1": "Hello!",
        "Game_chat_content2": "Play fast!",
        "Game_chat_content3": "Oh Teri!",
        "Game_chat_content4": "Well Play",
        "Game_chat_content5": "why!why!",
        "Game_chat_content6": "Sorry mate!",
        "Game_chat_tips": "Enter message",
        "Game_chat_send": "Send"
    },
    "DailyBonus": {
        "Lobby_Bonus_title": "Daily Bonus",
        "Lobby_Bonus_detail": "Get free coins everyday!",
        "Lobby_Bonus_collect": "Collect",
        "Lobby_Bonus_collected_tips": "Come back tomorrow for more coins.",
        "Lobby_Bonus_collect_failed": "Failed to collect, please try again later.",
        "Lobby_Bonus_reqFailed": "Failed to retrieve daily bonus. Please try again later.",
        "Lobby_Bonus_Day": "Day {num}",
        "Lobby_Bonus_Day_1": ""
    },
    "Props_Guide": {
        "Game_Props_TopTitle_Great": "Great",
        "Game_Props_TopTitle_LuckyNumber": "Golden\n Number",
        "Game_Props_ItemTips_DoubleDice": "Double Distance:Doubles the number rolled. Player must move that many spaces immediately After using this item, rolling a 6 does not give bonus rolls and cannot move out a tokens.",
        "Game_Props_ItemTips_AssignDice": "Controlled Dice: Player chooses the number of the dice roll.A bonus roll is available when rolling a 6, kicking a tokens, or reaching the goal.",
        "Game_Props_ItemTips_Protection": "Shield: Protects all tokens from being kicked for 1 round.",
        "Common_Game_Props_UseChooseNumber_AssignDice": "Choose Number",
        "Common_Game_Props_UserGuide_GoldenNo": "This is the Golden Number. Roll it to get another roll!",
        "Common_Game_Props_UserGuide_GoldenNo_content": "Get an extra roll if you reach here.",
        "Common_Game_Props_UserGuide_continue": "Tap to continue",
        "Common_Game_Props_UserGuide_begin_title": "Power Mode",
        "Common_Game_Props_UserGuide_begin_content": "Hi, I am Ludo World. I will introduce you how to play Power Mode!",
        "Common_Game_Props_UserGuide_roaditem": "Different Power items can be collected on board.",
        "Common_Game_Props_UserGuide_Items": "Here are all your Power items.",
        "Common_Game_Props_UserGuide_Dicecontrol_title": "Dice Control",
        "Common_Game_Props_UserGuide_Dicecontrol_content": "You can control what number you want on dice!",
        "Common_Game_Props_UserGuide_Dicecontrol_tips": "Roll a 6! A great start!",
        "Common_Game_Props_UserGuide_Doubledistance_title": "Double Distance",
        "Common_Game_Props_UserGuide_Doubledistance_content": "Doubles the number rolled. Travel twice as far!",
        "Common_Game_Props_UserGuide_GoldenNo_title": "Bonus Roll",
        "Common_Game_Props_UserGuide_GoldenNo_tips": "Get an extra roll when you reach. Who doesn't like an extra roll!",
        "Common_Game_Props_UserGuide_BumpProtection_title": "Protection Shield",
        "Common_Game_Props_UserGuide_BumpProtection_content": "Be protected from the other sneaky tokens for 1 turn.",
        "Common_Game_Props_UserGuide_BumpProtection_effect": "Great! Your token was protected!",
        "Common_Game_Props_UserGuide_finish_title": "You are ready!",
        "Common_Game_Props_UserGuide_finish_content": "Now that you know all about Items, time for a real game!",
        "Common_Game_Props_UserGuide_finish_botton": "Let's go!",
        "Common_Game_Props_GetUserGuide": "First time to play Power Mode? Please take a look at our tutorial."
    },
    "Feedback": {
        "Set_Feedbeck_Title": "Feedback",
        "Set_Feedbeck_Tips": "Thanks for your feedback and support!",
        "Set_Feedbeck_Submit": "Submit",
        "Set_Feedbeck_Submit_Succeed": "Your feedback has been submitted successfully.",
        "Set_Feedbeck_Submit_No": "Your must enter your feedback here."
    },
    "TeamUp_Guide": {
        "Common_Game_teamup_UserGuide_begin_title": "Team Up",
        "Common_Game_teamup_UserGuide_begin_content": "Let's team up! Here are the rules.",
        "Common_Game_teamup_UserGuide_teammate": "The diagonal green player is your teammate.",
        "Common_Game_teamup_UserGuide_competitor": "Red & Yellow team is your opponent.",
        "Common_Game_teamup_UserGuide_pawnstack": "Tokens of teammates can sit together.",
        "Common_Game_teamup_UserGuide_onefinish": "Help your teammate after all your 4 tokens have gone inside home.",
        "Common_Game_TeamUp_UserGuide_finish_title": "Well Done!",
        "Common_Game_TeamUp_UserGuide_finish_content": "You've learned how to play Team Up. Now let's play a real game!"
    },
    "SharePresentLottery": {
        "Lobby_Lottery_Hint": "Watch AD to get a free spin",
        "Lobby_Lottery_Btn_Share": "Play to Spin",
        "Lobby_Lottery_Btn_spin": "Spin",
        "Lobby_Lottery_Upper_Limit": "Come back tomorrow for the Lucky Wheel!",
        "Lobby_Lottery_Close": "The wheel is spinning!"
    },
    "ShareText": {
        "TitleTurnplate": "Are you ready for a game of Ludo? Let's play together right now!",
        "TitlePropsShare": "It's so much fun playing Ludo World! Come and join me now!",
        "TitleOver": "I just win in Ludo World.Come and join me now!",
        "FriendRoomInviteText": "{name} is inviting you to play Ludo World, Room code {RoomCode}.",
        "RankShareContent": "I won {num} [match|matches] this week, come and challenge me!",
        "Invite_gift_text1": "Hi, I am playing Ludo World, come and play together!",
        "Invite_gift_text2": "Who's the real champion?Come and challenge!",
        "Invite_gift_text3": "Your friends clicks on the link you just shared, you can get reward.",
        "friend_invite_details": "Come and join me in Ludo World. Room Code: {Number} Click to download or enter the room."
    },
    "LoginMainLabel": {
        "LoginMainLabel_Facebook": "Facebook",
        "LoginMainLabel_Google": "Google",
        "LoginMainLabel_Description": "By continuing i agree that Moon Active may store and process my data in accordance with the Privacy Policy",
        "LoginMainLabel_Guest": "Guest",
        "LoginMainLabel_Continue_Sure": "Are your sure?",
        "LoginMainLabel_Continue_Express": "Guest can't play with friends...",
        "LoginMainLabel_Continue_AsGuest": "Play as Guest",
        "LoginMainLabel_Continue_FbAward": "Guest can't play with friends or get a bonus of {coins} coins...",
        "LoginMainLabel_RewardPrompt": "{coins} coins free!",
        "LoginMainLabel_Continue_Warning": "By tapping \"Agree\",I confirm that I have read and agreed to the PRIVACY POLICY and TENCENT GAMES USER AGREEMENT",
        "LoginMainLabel_Continue": "<u><b>Continue as Guest<u><b>",
        "LoginMainLabel_Select": "Select login method",
        "FacebookConnect_Content1": "<b><color=#444987>Login with facebook：</color></b>",
        "FacebookConnect_Content2": "<b><color=#444987>1.Play with friends\n2.Save your progress\n3.Get <color=#d16004>{num}<color=#444987> coins free<b>",
        "FacebookConnect_Content3": "<u><b><color = #3f59b7 click=\"handler\">login with Facebook</color></b></u>",
        "FacebookConnect_Content4": "<b><color=#444987>Login via guest and<color=#d16004> can't <color=#d16004>",
    },
    "PropsPromtText": {
        "Game_classic_newusertips_dicecontrolmoveout": "Control your dice\n to take off!",
        "Game_classic_newusertips_dicecontrolbump": "Control your dice \nto kick!",
        "Game_classic_newusertips_dicecontrolfinish": "Control your dice to get \ninto the Home Square!",
        "Game_classic_newusertips_doubledistance": "Double your distance!",
        "Game_classic_newusertips_shild": "Shield your tokens!",
        "Game_classic_newusertips_dicecontrolrun": " Control your dice to run.",
        "Game_item_purchasetips": "Click to get items"
    },
    "MailPanel": {
        "Mail_Title": "Mail",
        "Mail_firend": "Friends",
        "Mail_system": "System",
        "Mail_collect": "Collect",
        "Mail_check": "Check",
        "Mail_collectAll": "Collect All",
        "Mail_Firend_Preservation_tips": "Save 60 messages and save for 30 days.",
        "Mail_System_Preservation_tips": "Save 60 messages and save for 30 days.",
        "Mail_NoMail_tips": "There are no more mails",
        "MailInfo_Title": "Details",
        "MailInfo_firend_Gift": "'s Gift",
        "Mail_firend_Get_limit": "You have already collected gifts from {num} friends today. Come back and collect more tomorrow.",
        "MailInfo_get_Failure": "Failed to collect rewards. Please try it again later.",
        "Mail_delete_Failure": "Failed to delete. Please try it again later.",
        "MailInfo_delete": "Delete"
    },
    "PrivacyPolicy": {
        "PrivacyPolicy_join1": "I have read and agreed to",
        "PrivacyPolicy_join2": "PRIVACY POLICY",
        "PrivacyPolicy_join3": "and",
        "PrivacyPolicy_join4": "USER AGREEMENT",
        "SelectNone": "By tapping Agree,I confirm that I have read and agreed to the PRIVACY POLICY and  USER AGREEMENT"
    },
    "HelpText": {
        "Game_classic_userguide_tokens": "Tokens:There are 4 kinds of tokens, each belong to one side.",
        "Game_classic_userguide_startpoint": "Starting position: This is the starting position.",
        "Game_classic_userguide_finishline": "Home Square: Token needs to walk around the board before entering the Home Square.",
        "Game_classic_userguide_safeplace": "Safe places: 8 pentagram positions are safe places, and the tokens will not be bumped here.",
        "Game_classic_userguide_dice": "Dice: Each of its six faces has different number of dots from 1 to 6.",
        "Game_classic_userguide_firsthand": "First hand rule: Random first, then proceed in clockwise order.",
        "Game_classic_userguide_moveout": "Move out: A token can only move out if the player roll a 6.",
        "Game_classic_userguide_move": "Move: After rolling dice, select any tokens on the path to move the corresponding points.",
        "Game_classic_userguide_automove": "Auto move: Token move automatically when there is no other choose.",
        "Game_classic_userguide_sixbonus": "Six bonus: Player gets another roll if a 6 is rolled. ; If a player gets 3 times continuous six, his third turn will be skipped.",
        "Game_classic_userguide_bumpbonus": "Bump bonus: Player gets another roll by bumping a token.",
        "Game_classic_userguide_finishbonus": "Finish bonus: Player gets another roll after moving a token into the Home Square.",
        "Game_classic_userguide_bump": "Bump: If a token lands on another token after moving, and they are not in the safe place, it will kick another token back to the starting position. But if two or more same color tokens are in the same square, they are immune to kicking.",
        "Game_classic_userguide_finish": "Token can move into the Home Square if the dice is just equal to Home Square distance.  If it is greater, than the token must not be moved.",
        "Game_classic_userguide_winner": "Winner:The player who first gets all the 4  tokens into the Home Squre wins. In 4 players match, both of the 1st and the 2nd players are winners.",
        "Game_classic_userguide_time": "Time:10s to roll, 10s to move.",
        "Game_classic_userguide_autohosted": "Auto Move: When you are time out or disconnected, computer will play for you. Click to regain control.",
        "Set_Help_newuser_powermode_begin": "On the basis of Classic Mode, add the following items to make the game more enjoyable!",
        "Set_Help_newuser_powermode_step1": "Double Distance:Travel double the distance you get in dice. Get going on double the pace! \nPlease be noted, bonus roll of rolling a 6 and moving out your token will not be applicable after using Double Distance.",
        "Set_Help_newuser_powermode_step2": "Dice Control:Control what number you want on dice.",
        "Set_Help_newuser_powermode_step3": "Protection Shield:Be protected from the other tokens for 1 turn.",
        "Set_Help_newuser_powermode_step4": "Bonus Roll:Get an extra roll when you reach.",
        "Set_Panel_Help_teamup_1": "Rule 1:You and the diagonal player form a team (Blue&Green VS Red&Yellow).",
        "Set_Panel_Help_teamup_2": "Rule 2:When your team's tokens sit together, the opponent's tokens can't team up to kick them.",
        "Set_Panel_Help_teamup_3": "Rule 3:Your teamed up tokens will not be kicked when they break.",
        "Set_Panel_Help_teamup_4": "Rule 4:After all your 4 tokens have gone inside home, you can go on to use your dice rolls to move your teammate's tokens.",
        "Set_Panel_Help_teamup_5": "Rule 5:Your team should move all the 8 tokens inside home firstly to win."
    },
    "PropGuidePanel": {
        "PropGuidePanel_TitleText": "Power Mode!",
        "PropGuidePanel_ContentText": "Come and try \nour unique Ludo mode now!",
        "PropGuidePanel_PlayBntText": "Start",
        "PropGuidePanel_AwardHint": "coins free!",
        "NewHandGuide_AwardHint": "You completed the tutorial of Power Mode!",
        "NewHandGuide_Get_Failure": "Failed to collect, please try again later.",
        "PropGuideTipsOpenText": "Item tips opened",
        "PropGuideTipsCloseText": "Item tips closed"
    },
    "GameGuide": {
        "GameGuideText1": "Welcome!",
        "GameGuideText2": "Let’s play online with other players!"
    },
    "GameGuideText": {
        "GameGuideTitle": "Select Mode",
        "GameGuideContent": "Familiar with Ludo? Try",
        "GameGuideClassicModeContent": "Classic",
        "GameGuidePowerModeContent": "Senior",
        "GameGuidePowerMode": "Power",
        "GameGuidePlay": "let's play!",
        "GameGuideClassicMode": "Classic",
        "GameGuideInnovative": "Innovative"
    },
    "GameTxpText": {
        "GameNoGetExp": "No kicking or reaching Home Square, you earn no exp.",
        "CloseTips": "Tap to close",
        "ShareLevelTips": "It's so much fun playing Ludo World! Come and join me now!"
    },
    "AssessPanelText": {
        "Rate_title": "Enjoy our game?",
        "Rate_content": "If you like us, rate us!",
        "Rate_Button": "Rate Us",
        "Rate_Button2": "Not Now",
        "ShareGame_exp_fail": "Failed to get EXP,please try again later.",
        "ShareGame_exp_Exceed": "You get too much EXP today, please come back tomorrow.",
    },
    "TaskPanel": {
        "Task_Title": "Mission",
        "Task_Daily": "Daily Mission",
        "Task_Growth": "Growth Mission",
        "Task_collect": "Collect",
        "Task_Play": "Go",
        "Task_Playing": "In Process",
        "Task_get_award_failed": "Failed to collect, please try again later.",
        "Task_Tips": "Daily mission will refresh at 24:00",
        "Task_Timeout": "Failed to collect, the mission has timed out.",
        "Task_Coins": "coins"
    },
    "TaskName": {
        "task_0": "Login",
        "task_1": "Send gifts to other\nplayers 5 times in\nOnline Mode",
        "task_2": "Send coins to friends\n5 times on Friends\n list.",
        "task_3": "Kick 5 times in\nFriends Mode",
        "task_4": "Move tokens into\nHome 3 times in\nFriends Mode",
        "task_5": "Win 1 match in\nFriends-Classic\nMode",
        "task_6": "Win 1 match in\nFriends-Power Mode",
        "task_7": "Win 1 match in\nFriends Mode",
        "task_8": "Win 5 matches in\nOnline-Classic-2p\nMode",
        "task_9": "Win 3 matches in\nOnline-Classic-4p\nMode",
        "task_10": "Win 3 matches in\nOnline-Classic-2v2\nMode",
        "task_11": "Win 5 matches in\nOnline-Power-2p\nMode",
        "task_12": "Win 3 matches in\nOnline-Power-4p\nMode",
        "task_13": "Win 3 matches in\nOnline-Power-2v2\nMode",
        "task_14": "Win 5 matches in\nOnline Mode",
        "task_15": "Use Double Distance\n10 times in Online-\nPower Mode",
        "task_16": "Use Dice Control 10\ntimes in Online-\nPower Mode",
        "task_17": "Use Protection Shield\n 10 times in Online-Power\n Mode",
        "task_18": "Kick 5 times in\nOnline Mode",
        "task_19": "Move token into\nHome 3 times in\nOnline Mode",
        "task_20": "",
        "task_21": "Level up to level %{num}",
        "task_22": "Login %{num} days total",
        "task_23": "Win %{num} matches\nin Online Mode",
        "task_24": "Win %{num} matches\nin Computer Mode",
        "task_25": "Kick %{num} times in\nOnline Mode"
    },
    "TeamUp2V2": {
        "Common_Choose_Number_Team": "Team up",
        "Common_Choose_Number_2v2_titlepower": "Power 2V2",
        "Common_Choose_Number_2v2_titleclassic": "Classic 2V2",
        "Teamup_choose_tips1": "Invite a friend or auto matching",
        "Teamup_choose_tips2": "You can start now",
        "Teamup_choose_betchange_title": "Bet is changed",
        "Teamup_choose_betchange_content": "The bet is adjusted to {coins} because your friend doesn't have enough coins.",
        "Teamup_choose_join_leave_title": "Leave the game?",
        "Teamup_choose_join_leave_content": "Your team will be disbanded. Do you still want to leave?",
        "Teamup_Matching_leave_content": "Already matched, you can't exit now.",
        "Teamup_Game_inviting": "{name} is inviting you to team up in Online-2V2 mode."
    },
    "Region": {
        "Disgree_Content": "Unfortunately we are unable to offer Ludo World to you at this time. Our data is strored outside of the EEA and our support teams necessarily access that data from other jurisdictions in order to provide the service to you.",
        "Back": "Back",
        "Data_Agreement_Content_APK": "Ludo World is a product offered by Proxima Beta PTE.Limited, a Republic of Singapore company who will process your data outside the European Economic Area(including in the People's Republic of China) in order to provide the service. Please note that there are risks in such a transfer including your data being subject to differentlegal regimes which may not afford it the same level of protection as that available in the country in which you are located. For more information please see our <b><u><i click=\"handler\">Privacy Policy</i></u></b>. By clicking on \"Agree\" below, you agree to the transfer of your data outside the European Economic Area.",
        "Data_Agreement_Content_FB": "Ludo World is a product offered by High Morale Development Limited, a Hong Kong company who will process your data outside the European Economic Area(including in the People's Republic of China) in order to provide the service. Please note that there are risks in such a transfer including your data being subject to differing legal regimes which may not afford it the same level of protection as that available in the country in which you are located. For more information please see our <b><u><i click=\"handler\">Privacy Policy</i></u></b>. By clicking on \"Agree\" below, you agree to the transfer of your data outside the European Economic Area.",
        "Agree": "Agree",
        "Disagree": "Disagree",
        "Under_Age_Content": "Since you are under {age} years old, we are unfortunately unable to provide Ludo World service to you at this time.",
        "Data_Outside_Content": "Do you agree to transfer your data outside the European Economic Area?",
        "Data_Outside_Title": "Data Transfer Outside EEA",
        "Delete_Notice_Title": "Notice",
        "Delete_Notice_Content": "Unfortunately we are unable to offer Ludo World to you at this time. Our data is strored outside of the EEA and our support teams necessarily access that data from other jurisdictions in order to provide the service to you. Click \"Back\" to reconsider or click \"Delete Account \" to delete.",
        "Delete_Account": "Delete Account",
        "Delete_Delete": "Delete",
        "Delete_Content": "Do you wish to delete your account? The system will automatically delete your account and data after 7 days. You can cancel the deletion by re-logging into game within 7 days.",
        "Chat_Off_Title": "Turn on chat now?",
        "Chat_Off_Content": "When chat is activated, other player may be able to see your conversations. Chat can be disabled later in settings.",
        "Region_Title": "Region",
        "Region_Content": "Please select the region/country where you\nare primarily located.",
        "Agree_Title": "Data of birth",
        "Agree_Content": "In order for us to optimize your experience.Please tell us if you are at least {age} years old?",
        "Privacy_Title": "Privacy Policy",
        "Privacy_Content": "By tapping \"Agree\" below, I confirm that\nI have read and agreed to Ludo World's\n<b><u><color = #535BBF click=\"handler\">Privacy Policy.</color></u></b>",
        "Privacy_Disagree": "Unfortunately without your agreement on Privacy Policy, we are unable to offer Ludo World services to you at this time.",
        "Agreement_Title": "End User License Agreement",
        "Agreement_Content": "By tapping \"Agree\" below, I confirm that\nI have read and agreed to Ludo World's\n<b><u><color = #535BBF click=\"handler\"> End User License Agreement.</color></u></b>",
        "Agreement_Disagree": "Unfortunately without your agreement on End User Licence Agreement, we are unable to offer Ludo World services to you at this time.",
        "YES": "Yes",
        "NO": "NO"
    },
    "FriendSystem": {
        "Friend_Main_title": "Friends",
        "Friend_Main_list": "List",
        "Friend_Main_add": "Add",
        "Friend_Main_request": "Request",
        "Friend_Main_list_FB": "FB Friends",
        "Friend_Main_list_Game": "Game Friends",
        "Friend_Main_list_reciveandsend": "Send all",
        "Friend_Main_list_reciveandsend_Detail": "Coins sent to friends are not deducted from your balance.",
        "Friend_Main_Add_Recent": "Recent",
        "Friend_Select_Tip_NewRequest": "{num} [Friend Request|Friend Requests]",
        "Friend_Main_Request_Num_Tip": "Save only the last 99 requests.",
        "Friend_list_nofbfirends": "No Facebook friend play yet,\ninvite them to join now!",
        "Friend_list_invitefirends": "Let's play Ludo World together right now!",
        "Friend_list_nogamefirends": "No game friend yet,\nadd some from the Add tab!",
        "Friend_Add_NoRecent": "No recent player",
        "Friend_Request_NoRequest": "No friend request",
        "Friend_list_online": "Online",
        "Friend_list_offline": "Offline",
        "Friend_list_playing": "Playing",
        "Friend_Not_Accept": "No longer accept friend requests.",
        "Friend_sendcoins_succeed": "Send 100 coins to {name}",
        "Friend_sendcoins_fail": "You have sent the max number of gifts today.",
        "Friend_collectandsendall_succeed": "Send  {num} coins",
        "Friend_collectandsendall_nofirendtosend": "No friend to send",
        "Friend_invite_title": "Invitation",
        "Friend_invite_bottoningame": "In-game",
        "Friend_invite_whoinvite": "{name} invite you to play a game!",
        "Friend_invite_reject": "Reject",
        "Friend_invite_accept": "Accept",
        "Friend_invite_friendpower": "Friend-Power",
        "Friend_invite_friendclassic": "Friend-Classic",
        "Friend_invite_teamuppower": "Friend-Power-2V2",
        "Friend_invite_teamupclassic": "Friend-Classic-2V2",
        "Friend_invite_sentsucceed": "Invitation sent",
        "Friend_invite_sentfail": "Invitation failed",
        "Friend_invite_more_btn": "Invite more:",
        "Friend_collectcoins_fail": "You have already collected coins from {num} friends today. Come back and collect more tomorrow.",
        "Friend_collectall_succeed": "Collect {coins} coins from friends!",
        "Friend_Add_Recent_Source1": "Online-Classic-2P",
        "Friend_Add_Recent_Source2": "Online-Classic-4P",
        "Friend_Add_Recent_Source3": "Online-Power-2P",
        "Friend_Add_Recent_Source4": "Online-Power-4P",
        "Friend_Add_Recent_Source5": "Online-Classic-2V2",
        "Friend_Add_Recent_Source6": "Online-Power-2V2",
        "Friend_Add_Recent_Source7": "Friend-Classic",
        "Friend_Add_Recent_Source8": "Friend-Power",
        "Friend_Add_Recent_Source9": "Friend-Classic-2V2",
        "Friend_Add_Recent_Source10": "Friend-Power-2V2",
        "Friend_Request_Source_Recent": "Recent Game",
        "Friend_Request_Source_Suggested": "Suggested",
        "Friend_Request_Source_Leaderboard": "Leaderboard",
        "Friend_gametime-year": " {num} y ago",
        "Friend_gametime-day": " {num} d ago",
        "Friend_gametime-hour": " {num} h ago",
        "Friend_gametime-minitue": "{num}min ago",

    },
    "APPAdsText": {
        "ItemsAddOne": "Items+1"
    },
    "Common": {
        "Lobby_Bonus_collecet": "Collect",
        "Common_Game_teamup_UserGuide_finish_title": "Well done!",
        "Game_friends_invite_start": "You can start now.",
        "": "",
        "Title_ModifyInfo": "Modify Info",
        "shortCut_create_success": "Shortcut creation is successful.",
        "MainScenes_Ranking": "Ranking",
        "MainScenes_FreeCoins": "Free Coins",
        "MainScenes_Mission": "Mission",
        "Settings_on": "On",
        "Settings_off": "Off",
        "Game_EndOrder_Congratulations": "Congratulations",
        "EM_ERR_FETCH_FRIEND_FAIL = -10002": "Failed to load data. Please try again later.",
        "EM_ERR_FETCH_ONLINE_FAIL = -10003": "Failed to load data. Please try again later.",
        "EM_ERR_FETCH_LOGIN_TIME_FAIL = -10004": "Failed to load data. Please try again later.",
        "EM_ERR_NOT_ADD_PLAYER = -10005": "Processing failed，please try again later.",
        "EM_ERR_FRIEND_LIST_FULL = -10006": "The number of your friends has reached the maximum. If you need to add this friend, please delete other friends.",
        "EM_ERR_PEER_FRIEND_LIST_FULL = -10007": "{name} has reached the maximum number of friends and cannot be added.",
        "EM_ERR_UPDATE_FRIEND_FAIL = -10008": "Failed to load data. Please try again later.",
        "EM_ERR_PLAYER_REFUSE_ADD = -10009": "{name} is not accepting any friend requests.",
        "EM_ERR_ALREADY_IN_ADD_LIST = -10010": "",
        "EM_ERR_ALREADY_IN_GAME_FRIEND_LIST = -10011": "You are already friends.",
        "EM_ERR_ALREADY_IN_PLAT_FRIEND_LIST = -10012": "You are already friends.",
        "EM_ERR_NOT_IN_FRIEND_LIST = -10013, //": "Processing failed，please try again later.",
        "EM_ERR_FETCH_GAME_RECORD_FAIL = -10014": "Failed to load data. Please try again later.",
        "EM_ERR_CANNOT_ADD_SELF = -10015": "Failed to add, please try again later.",
        "LoginMainLabel_Guest_Title": "Login via guest and can't",
        "Language_type": "English",
    },
    "GoodsName": {
        "GoodsName_Cricket": "Cricket",
        "GoodsName_Jewelry": "Jewelry",
        "GoodsName_Airdrop_box": "Airdrop",
        "GoodsName_Cupid": "Cupid",
        "GoodsName_Cat": "Cat",
        "GoodsName_Planet": "Planet",
        "GoodsName_Default": "Default",
        "Shop_luckybox": "Lucky Box",
        "Shop_luckybox_GiftCardtitle": "Gift Card",
        "Shop_luckybox_GiftCard": "Please check the gift card via in-game mail.",
        "GoodsName_Item_Cards": "Item Cards",
        "GoodsName_Item_Cards_num": "Item Cards x{num}",
        "GoodsName_Neon": "Neon",
        "GoodsName_Chick": "Chick",
        "GoodsName_First_AidKit": "First Aid Kit",
        "GoodsName_Machinery": "Machinery",
        "GoodsName_Diwali": "Diwali",
        "GoodsName_Christmas": "Christmas",
        "GoodsName_Gems": "Gems",
    },
    "AdsText": {
        "Btn_Lucky_Show_Ad": "Watch AD",
        "Lab_Lucky_Next": "Next reward:",
        "Lab_Lucky_Declare": " Watch ads to get free spins everyday!",
        "Btn_Double_Reward": "Double Bonus",
        "Btn_Reward_x2": "Get 2x!",
        "Btn_No_Thanks": "No, thanks",
        "Ad_Confirm_Cions": "Watch ads to get {num} coins.",
        "Ad_Confirm_Item": "Watch ads to get one of each item.",
        "Ad_Confirm_Task": "Watch ads to advance missions.",
        "Ad_Confirm_Spin": "Watch ads to get {spin}.",
    },
    "NewUserText": {
        "NewPlayerBonus_Title": "New player bonus",
        "NewPlayerBonus_Day": "Day",
        "NewPlayerBonus_Collect": "Collect",
        "NewPlayerBonus_Collected": "Collected",
        "NewPlayerBonus_LoginTips": "You have been logged in for {num} [day|days] ~",
        "NewPlayerBonus_EventTime": "Event time:",
        "NewPlayerBonus_Coins": "Coins",
        "NewPlayerBonus_Skins": "Skin",

    },
    "Shop": {
        "Shop_Tab_Coins": "Coins",
        "Shop_Tab_Spin": "Skin",
        "Shop_Tab_Items": "Items",
        "Shop_Tab_Spin_BubbleTab": "Bubble",
        "Shop_Tab_Spin_DiceTab": "Dice",
        "Shop_Tab_Spin_ThemeTab": "Theme",
        "Shop_Airdrop_box": "Airdrop",
        "Shop_Coins": "{num}",
        "Shop_Airdrop_box_day": "Airdrop ({num}d)",
        "Shop_Cricket": "Cricket",
        "Shop_Cricket_day": "Cricket ({num}d)",
        "Shop_Cupid": "Cupid",
        "Shop_Cupid_day": "Cupid ({num}d)",
        "Shop_Jewelry": "Jewelry",
        "Shop_Jewelry_day": "Jewelry ({num}d)",
        "Shop_Cat": "Cat",
        "Shop_Cat_day": "Cat ({num}d)",
        "Shop_Planet": "Planet",
        "Shop_Planet_day": "Planet ({num}d)",
        "Shop_Neon": "Neon",
        "Shop_Neon_day": "Neon ({num}d)",
        "Shop_Chick": "Chick",
        "Shop_Chick_day": "Chick ({num}d)",
        "Shop_First_AidKit": "First Aid Kit",
        "Shop_First_AidKit_day": "First Aid Kit ({num}d)",
        "Shop_Machinery": "Machinery",
        "Shop_Machinery_day": "Machinery ({num}d)",
        "Shop_Diwali": "Diwali",
        "Shop_Diwali_day": "Diwali ({num}d)",
        "Shop_Christmas":"Christmas",
        "Shop_Christmas_day":"Christmas({num}d)",
        "Shop_Item": "Item Cards ({num})",
        "Shop_Label_New": "New",
        "Shop_Label_Hot": "Hot",
        "Shop_Label_Off": "Off",
        "Shop_Label_Extar": "Extar",
        "Shop_Label_BestDeal": "Best Deal",
        "Shop_Day_day": "day",
        "Shop_Buy_Success": "Purchase successful, you have used {spin}.",
        "Shop_Backpack_Tip": "Go to use items in the backpack",
        "Button_Reload": "Reload",
        "Button_AD_Free": "Free",
        "Shop_Lucky": "Lucky",
        "Shop_BuyGift_Success": "Purchase successful,go to use in the backpack.",
        "Shop_Airdrop_box_Permanent": "Airdrop(Permanent)",
        "Shop_Cricket_Permanent": "Cricket(Permanent)",
        "Shop_Cupid_Permanent": "Cupid(Permanent)",
        "Shop_Jewelry_Permanent": "Jewelry(Permanent)",
        "Shop_Cat_Permanent": "Cat(Permanent)",
        "Shop_Planet_Permanent": "Planet(Permanent)",
        "Shop_Neon_Permanent": "Neon(Permanent)",
        "Shop_Chick_Permanent": "Chick(Permanent)",
        "Shop_First_ AidKit_Permanent": "First Aid Kit(Permanent)",
        "Shop_Machinery_Permanent": "Machinery(Permanent)",
        "Shop_Diwali_Permanent": "Diwali(Permanent)",
        "Shop_Lucky_Detail": "Cricket(1d),Jewelry(1d),Planet(1d)",
        "Shop_WatchTV_Detail": "Watch ads to get free item.",
        "Shop_Buy_Fail": "Purchase failed, please try again later.",
        "Shop_Buy_ItemFail": "Failed to send item. Please check again later.",
        "Shop_Buy_Success_Prop": "Purchase successful.",
        "Shop_Buy_Prop_Describe": "Item cards can be exchanged for items",
        "Shop_itemcard": "Item cards",
        "Shop_itemcard_number": "{num} [card|cards]",
        "Shop_Tab_Name": "Shop"
    },
    "ReportText": {
        "Report_Panel": "Report",
        "Report_Title": "Report",
        "Report_People": "Report {name}",
        "Report_Content1": "Verbal abuse",
        "Report_Content2": "Cheating",
        "Report_Content3": "Others",
        "Report_Success": "Reported",
        "Report_Res_Title": "Result",
        "Report_Res_Content": "{name}, the player whom you reported, has been muted/suspended."
    },
    "RetainUser": {
        "newsuserA_classic_tips": "Try Power Mode, It's more funny!",
        "newsuserA_power_tips": "Try Classic Mode? It's easier!",
        "newsuserA_tips_quit": "Quit",
        "newsuserA_tips_try": "Try",
        "newsuserB_tips_stay": "Complete {num1} games ({num2}/{num3}) to get the Green Crate.",
        "newsuserB_tips_minitips": "Draw an ₹100 Amazon Gift Card or Coins！",
        "newsuserB_tips_getluckybox_title": "Green Crate",
        "newsuserB_tips_getluckybox_content": "Draw an 100₹ Amazon Gift Card or \nCoins！Check it in your backpack.",
        "newsuserB_tips_getluckybox_tips": "Draw an ₹100 Amazon Gift Card or Coins！",
        "newsuserB_tips_getluckybox_cannotopen": "Open after {num}",
        "newsuserB_tips_getluckybox_openfail": "Open failed, please try it again later.",
        "newsuserB_tips_getluckyboxopen": "Open the Lucky Crate now to draw an \n100₹ Amazon Gift Card or Coins!",
        "newsuserA_tips_stay": "Stay",
        "newsuserA_tips_leave": "Leave?",
        "newsuserA_tips_open": "Open",
    },
    "MainChat": {
        "Button_Team_SendTeamRecruitment" : "Send Team Invite",
        "Chat_World_NoChatTypeTips" : "[This message type is not supported.]",
        "Chat_World_EmptyTips" : "Message cannot be empty.",
        "Chat_NoMessage_Tips" : "Click here to chat",
        "Chat_Tab_World" : "World",
        "Chat_Tab_Team" : "Team",
        "Chat_Tab_Friends" : "Friends",
        "Chat_World_DefaltTips" : "Enter message",
        "Button_Chat_Send" : "Send",
        "Chat_Team_Send_WorldChat" : "Send to World Chat",
        "Chat_Team_Join" : "Join",
        "Chat_Local_Tips" : "Local chat only",
        "Chat_Friends_NewMessageTips" : "New message",
        "Chat_Friends_ClickTips" : "Tap friend to chat.",
        "Chat_Friends_NoFriendsTips" : "You need some friends.",
        "Chat_World_LocalTips" : "Tap here to enter local chat",
        "Chat_Low_Level" : "Play more matches to reach Level {num} to chat!",
        "Chat_World_JoinTips" : "You joined World Chat",
        "Chat_Local_JoinTips" : "You joined Local Chat",
        "Chat_Close_Tips" : "Turn on chat now?",
        "Tips_Team_SendSuccess" : "Team invite has been sent to the world chat.",
        "Chat_SendTooFast" : "You are talking too fast. Please try again later.",
    },
    "RedEnvelope": {
        "HB_Bag_Title": "Lucky Bag",
        "HB_Coins_Tips": "{num1}~{num2} coins",
        "HB_Coins_Tipstop": "{num1} coins",
        "HB_Image_Text": "Share your luck and open the Lucky bag.",
        "HB_Open_Require": "Invite your friends to open together!",
        "HB_Open_Tips": "The more friends that join, the more coins you get!",
        "HB_NoOpen_Tips1": "Waiting for your friends to join via the link.",
        "HB_NoOpen_Tips2": "When a friend joins via the link, you can open the lucky bag.",
        "HB_Join_One": "The more friends that join, the more coins you get!",
        "HB_Join_More": "The more friends that join, the more coins you get!",
        "HB_Can_Open_Tips": "Open the lucky bag today",
        "HB_Share_Title1": "Coins in Ludo World，open the Coin bag to get your rewards.",
        "HB_Share_Title2": "You lucky bag in Ludo World,open and try your luck!",
        "HB_Btn_Open": "Open",
        "HB_Btn_Open_noinvite": "Invite",
        "HB_Collect_Fail": "Oops, no coins left."
    },
    "LuckyBag":{
        "Clearing_Win_Share_Title" : "Secret Box",
        "Clearing_Win_Share_Content" : "Invite friends to collect together",
        "Clearing_Loser_Share_Title" : "Free Coins",
        "Clearing_Loser_Share_Content" : "Invite friends to collect together",
        "Clearing_Win_Ads_Title" : "Secret Box",
        "Clearing_Win_Ads_Content" : "Watch AD to get",
        "Clearing_Loser_Ads_Title" : "Free Coins",
        "Clearing_Loser_Ads_Content" : "Watch AD to get",
        "Clearing_Welfare_Share_Title" : "Invite friends to collect",
        "Clearing_Share_Finish" : "Tap the link you just shared within {num} seconds to receive your reward!",
        "Clearing_Welfare_Ads_Title" : "Need More Coins？",
        "Clearing_Welfare_Ads_Content" : "Watch AD to get",
        "Clearing_Share_Loser" : "Shared link invalid, resend shared link",
    },
    "LuckSeven": {
        "Un_Lock_tips": "It takes {num1} more tosses to unlock more!",
        "Not_Enough_Gold":"Insufficient coins",
        "High_Laid":"The highest gear has been reached!",
        "Low_Laid":"The lowest gear has been reached!",
        "Show_FreeBet":"Free bet {num2} times!" ,
        "Coins":"COINS",
        "laid_start_To_end":"{start} TO {end}",
        "WIN":"WIN",
        "Get_Free_Bet":"get free bets!",
        "Double":"Double {point}",
        "Error":"Data error, please reopen the page"
    },
    "EliminatGame":
    {
        "Select_Hint": "Please select the coins you put in",
        "Not_Coins":"You don't have enough coins. Get more from the store?",
        "Min_Coins":"Already reached the minimum coins",
        "Max_Coins":"Already reached the maximum coins",
        "Win":"WIN" ,
        "Big_Win":"Big Win",
        "Super_Winner":"Super Winner",
        "Total_Win":"Total Win",
        "Fish_Party":"FishParty",
        "Quit_Hint":"You are in a match,are you sure you want to quit?",
        "AllIn":"All-in",
        "Auto":"auto",
        "Start":"Start",
        "Title":"Game instructions",
        "Game_Rules":"Game Rules",
        "Explain":"Fish Party instructions",
        "Party_Text":"  Three same fish in the same line adjacent to each other can be eliminated and rewarded.\n\nAfter elimination, the game will continue to replenish fish until they can not be eliminated.",
        "Select_Fish":"Select fish to bet on",
        "Eliminate_Award":"Eliminate and get coins!",
        "Records":"Check reward and records",
        "Settlement_Rules":"Settlement Rules",
        "Settlement_Rules_Text":"  Three same fish in the same line adjacent to each other can be eliminated and rewarded.\nEach fish independent calculation of the reward.\nThe type of fish and the number of elimination will affect the reward.\nEarnings are multiplied by the following multiplier.\nMore fish eliminated in the line,more rewards!",
        "Back_Game":"Back to game",
        "Game_Name":"Fish Party",
        "Activity_Ended":"The activity has ended."
    },
    "NewDiBao":
    {
        "Title": "LUCKY PACK",
        "Tip": "Get today's lucky coins",
        "mulit": "Collect",
        "extra":"EXTRA",
        "basic":"BASIC",
        "coins":"COINS",
        "togle": "Watch AD get {num} coins!",
        "Before_Game_GoldEnough":" You don't have enough coins",
        "StartGame":"Start Game",
    },
    "InsufficientCoin":
    {
        "title": "You need at least {num} coins to play.",
        "tip": "you now have {haveCoin} coins",
        "goScene":"Recommended game", 
        "toOtherModel":"You don't have enough gold to start {coins} games, choose other mode?",
        "friend":"Friends",
        "computer":"Computer",
        "toOfferPlay":"Your coins is not enough.Go to the recommend mode ?"
    }
}
let loadMessage = function (language, dataID, isChange) { 

};
exports.loadMessage = loadMessage;