'use strict';
if (!window.i18n) {
  window.i18n = {};
}

if (!window.i18n.languages) {
  window.i18n.languages = {};
}

window.i18n.languages['Arabic'] = {
  "label_text": {
    "Ads_getRewards_Title": "اربح مكافآت",
    "Ads_CountDown_tips": "المكافآت التالية في:",
    "Ads_watchAd_Title": "مشاهدة إعلان",
    "Auto_Game": "تلقائية",
    "Button_Guest_Facebook": "تسجيل الدخول عبر FB",
    "Button_Guest_Continue": "المتابعة كضيف",
    "Button_Common_Confirm": "موافق",
    "Button_Common_Yes": "نعم",
    "Button_Common_No": "لا",
    "Button_Common_Next": "التالي",
    "Button_Common_Restart": "إعادة البدء",
    "Button_Common_Return": "العودة",
    "Button_Common_Share": "مشاركة",
    "Button_Common_Start": "البدء",
    "Button_Common_Facebook": "تسجيل الدخول عبر FB",
    "Button_Common_Guest": "ضيف",
    "Common_Guest_BindAccount": "هل تريد ربط حسابك على FB؟",
    "Common_Guest_BindAccountFail": "فشل الاتصال بحساب Facebook. أعد المحاولة لاحقًا.",
    "Common_Guest_RepeatBind": "لقد ربطت حساب Facebook بالفعل. هل تريد تسجيل الدخول بهذا الحساب؟",
    "Common_Guest_Confirm": "لقد سجَّلت دخولك كضيف ولا يمكنك اللعب مع أصدقائك. \nسجِّل دخولك عبر Facebook لتتمكن مما يلي: \n1. اللعب مع أصدقائك \n2.استخدام صورة ملفك الشخصي في اللعبة \n3. اللعب على عدة أجهزة بالحساب نفسه.",
    "Common_Online_ShareContent": "حققت المركز {1} في {0} وربحت {2} من العملات!",
    "Common_Scene_Teamup_Teammateturn": "يمكنك متابعة اللعب ومساعدة زميلك الآن!",
    "Common_Game_Props_GetTipsTitle_DoubleDice": "ضعف المسافة",
    "Common_Game_Props_GetTipsContent_DoubleDice": "ارمِ النرد وتحرك ضعف المسافة.",
    "Common_Game_Props_GetTipsTitle_AssignDice": "اختيار الرقم",
    "Common_Game_Props_GetTipsContent_AssignDice": "اختر الرقم الذي تود الحصول عليه",
    "Common_Game_Props_GetTipsTitle_Protection": "درع الحماية",
    "Common_Game_Props_GetTipsContent_Protection": "تكتسب حماية من البيادق الأخرى لدور واحد",
    "Common_Game_Props_GetTipsTitle_LuckyNumber": "الرقم الذهبي",
    "Common_Game_Props_GetTipsContent_LuckyNumber": "إن حصل لاعب في دور واحد على هذا الرقم، فسيتمكن من رمي النرد مجددًا.",
    "Common_Scene_Props_Introduce_Title": "وضع التعزيز يتضمن",
    "Common_Scene_Props_introduce_luckyNumber": "الرقم الذهبي",
    "Common_Scene_Props_introduce_luckyNumber_": "إن حصل أي لاعب في دور واحد على هذا الرقم، فسيتمكن من رمي النرد مجددًا. يسري التأثير فورًا وينطبق على كل اللاعبين.",
    "Common_Scene_Props_introduce_DoubleDice": "ضعف المسافة",
    "Common_Scene_Props_introduce_DoubleDice_": "يضاعف الرقم الذي حصل عليه اللاعب، ويجب عليه التحرك المسافة التي حصل عليها فورًا. بعد استخدام هذا العنصر، الحصول على الرقم 6 لن يمنح مرات رمي إضافية ولا يمكن تحريك البيادق.",
    "Common_Scene_Props_introduce_AssignDice": "اختيار الرقم",
    "Common_Scene_Props_introduce_AssignDice_": "يختار اللاعب الرقم الذي سيحصل عليه. يكسب اللاعب مرة رمي إضافية عند الحصول على الرقم 6 أو طرد بيدق أو الوصول إلى الهدف.",
    "Common_Scene_Props_introduce_Protection": "الدرع",
    "Common_Scene_Props_introduce_Protection_": "يحمي كل البيادق من الطرد لدور واحد.",
    "Common_Game_Props_ShowTips_LuckyNumber": "رمية إضافية",
    "Common_Game_Props_ShowTips_LuckyNumber_": "تحصل على رمية إضافية عند الوصول",
    "Common_Game_Props_ShowTips_DoubleDice": "ضعف المسافة",
    "Common_Game_Props_ShowTips_DoubleDice_": "تحرك ضعف الرقم الذي تحصل عليه",
    "Common_Game_Props_ShowTips_AssignDice": "اختيار الرقم",
    "Common_Game_Props_ShowTips_AssignDice_": "اختر الرقم الذي تود الحصول عليه",
    "Common_Game_Props_ShowTips_Protection": "درع الحماية",
    "Common_Game_Props_ShowTips_Protection_": "تكتسب حماية من البيادق الأخرى لدور واحد",
    "Common_Game_Props_Haved": "لا يمكن استخدام عناصر التعزيز إلا قبل رمي النرد.",
    "Common_Game_Props_NotHaved": "لا تملك عنصر التعزيز هذا بعد.",
    "Common_Team": "فريق",
    "Common_Choose_Color": "اختر اللون",
    "Common_Game_Online_MyPlace": "أنت هنا!",
    "Common_Choose_Number": "اختر اللاعبين",
    "Common_Choose_Bet": "اختر رسم المشاركة",
    "Common_Choose_Mode": "اختر الوضع",
    "Common_Choose_Number_players": "اللاعبون",
    "Common_Choose_Win": "الفوز:",
    "Common_Choose_Entry": "الدخول:",
    "Common_Choose_Number_two": "2",
    "Common_Choose_Number_four": "4",
    "Common_Choose_Number_multi": "2 إلى 4",
    "Common_Choose_Number_Team": "فريق",
    "Common_Choose_Number_2v2": "2 ضد 2",
    "Common_Game_Props_share": "شارك واربح\nعناصر!",
    "Common_Game_Props_UseChooseNumber_AssignDice": "اختر الرقم",
    "Common_Game_Props_sharetogetprops_title": "شارك مع أصدقائك لربح 3 عناصر تعزيز مجانًا!",
    "Common_Game_Props_sharetogetprops_share": "مشاركة",
    "Common_Game_Props_sharetogetprops_aftershare": "يمكن مشاركة كل مباراة مرة واحدة فقط",
    "Friend_Room_Entering": "جارٍ دخول الغرفة...",
    "Friends_Invite": "الدعوة عبر:",
    "GameName": "Ludo World",
    "Game_Common_start": "بدء المباراة",
    "Game_EndTitle_Win": "الفوز",
    "Game_EndTitle_Lose": "الخسارة",
    "Game_EndOrder_1": "المركز 1",
    "Game_EndOrder_2": "المركز 2",
    "Game_EndOrder_3": "المركز 3",
    "Game_EndOrder_Win": "الفوز",
    "Game_EndOrder_4": "المركز 4",
    "Game_EndOrder_5": "الخامس",
    "Game_EndOrder_6": "السادس",
    "Game_EndOrder_Lose": "الخسارة",
    "Game_EndOrder_Playing": "يلعب",
    "local_Result_title": "النتيجة",
    "Game_Online_Auto1": "حركة تلقائية",
    "Game_Online_Auto2": "اضغط هنا للإيقاف",
    "Game_Props_TopTitle_LuckyNumber": "الرقم\n الذهبي",
    "Game_Props_ItemTips_DoubleDice": "ضعف المسافة: يَضاعف الرقم الذي حصل عليه اللاعب، ويجب عليه التحرك المسافة التي حصل عليها فورًا. بعد استخدام هذا العنصر، الحصول على الرقم 6 لن يمنح مرات رمي إضافية ولا يمكن تحريك البيادق.",
    "Game_Props_ItemTips_AssignDice": "اختيار الرقم: يختار اللاعب الرقم الذي سيحصل عليه. يكسب اللاعب مرة رمي إضافية عند الحصول على الرقم 6 أوطرد بيدق أو الوصول إلى الهدف.",
    "Game_Props_ItemTips_Protection": "الدرع: يحمي كل البيادق من الطرد لدور واحد.",
    "Game_leaderboard_title": "لوحة المتصدرين",
    "Game_leaderboard_global": "عالمي",
    "Game_leaderboard_NotRanked": "بلا ترتيب",
    "Game_leaderboard_tips": "يتم تحديث البيانات كل يوم اثنين.",
    "Game_leaderboard_tips2": "تُحتسب المباريات عبر الإنترنت فقط.",
    "Game_leaderboard_tipsoneline": "يتم تحديث البيانات (مباريات وضع الاتصال بالإنترنت) كل يوم اثنين.",
    "Game_Computer_PlayerName1": "الروبوت1",
    "Game_Computer_PlayerName2": "الروبوت2",
    "Game_Computer_PlayerName3": "الروبوت3",
    "Game_Computer_level_choose": "حدد مستوى",
    "Game_Computer_Self": "أنت",
    "Game_Computer_level_easy": "سهل",
    "Game_Computer_level_normal": "عادي",
    "Game_Computer_level_hard": "صعب",
    "Game_Computer_PlayerNameEasy": "الروبوت{num} - سهل",
    "Game_Computer_PlayerNamenormal": "الروبوت{num} - عادي",
    "Game_Computer_PlayerNamehard": "الروبوت{num} - صعب",

    "Game_local_Remove_comfirm": "هل تريد بالتأكيد إزالة هذا اللاعب؟",
    "Game_local_Remove_guide_title": "إزالة اللاعب",
    "Game_local_Remove_guide_content1": "الذين لا يريدون اللعب",
    "Game_Friend_Pnael_Title": "العب مع الأصدقاء",
    "Game_Friend_Select_Mode": "حدد وضع اللعب",
    "Game_Friend_Create": "إنشاء",
    "Game_Friend_Join": "انضمام",
    "Game_Friend_Join_Clear": "مسح",
    "Game_Friend_GameMode": "اختر وضع اللعب",
    "Game_Friend_Enter_RoomCode": "أدخِل رمز الغرفة من فضلك",
    "Game_friends_invite_code": "رمز الغرفة",
    "Game_friends_invite_tips_cannot": "بانتظار اللاعبين...",
    "Game_friends_invite_tips_can": "انتظر لاعبين أكثر أو ابدأ الآن.",
    "Game_friends_join_tips": "أدخِل رمز الغرفة",
    "Game_friends_join_join": "انضمام",
    "Game_friends_join_wait": "بانتظار {who} للبدء",
    "Game_friends_choose_classic": "كلاسيك",
    "Game_friends_choose_power": "تعزيز",
    "Game_friends_choose_mode": "الوضع",
    "Game_friends_invite_waiting": "بانتظار اللاعبين...",
    "Game_friends_invite_waitormore": "انتظر لاعبين أكثر أو ابدأ الآن",
    "Game_friends_invite_start2V2": "يمكنك بدء المباراة",
    "Game_friends_invite_share": "ادعُ أصدقاءك عبر مشاركة رمز الغرفة",
    "Game_Ready": "مستعد!",
    "Guest_Username": "ضيف",
    "help_classic_title": "كلاسيك",
    "help_powerUp_title": "تعزيز",
    "InGame_PlayerInfo_Match": "مباراة",
    "InGame_PlayerInfo_Win": "الفوز",
    "InGame_PlayerInfo_Gift": "هدية (سعر كل هدية 100 عملة)",
    "introduce_friendModel": "العب مع الأصدقاء فقط",
    "LevelUp_Panel": "رفع المستوى",
    "LevelProgressPanelExp": "الخبرة",
    "LoadGame_Button_Load": "تحميل",
    "Login_loading": "جارٍ تسجيل الدخول...",
    "Lobby_receive_award_coins": "العملات",
    "Lobby_invite_detail1": "ادع أصدقاءك واربح {num} من العملات مقابل كل صديق ينضم عبر الرابط",
    "Lobby_invite_detail2": "ستتلقى مكافأة عبر البريد بعد انضمام أصدقائك عبر Facebook (بحد أقصى {times} من المرات في اليوم)",
    "Lobby_invite_btn": "دعوة",
    "Lobby_invite_title": "هل تحتاج إلى عملات أكثر؟",
    "Lobby_invite_guestlogin": "هل تريد ربط حسابك على Facebook للمتابعة؟",
    "MainScenes_Fackback": "التعليقات",
    "MainScenes_Ranking": "الترتيب",
    "MainScenes_Invite": "دعوة",
    "MainScenes_FreeCoins": "عملات مجانية",
    "MainScenes_Mission": "المهمة",
    "modify_title": "تعديل الملف الشخصي",
    "Notice_Panel_Title": "إشعار",
    "Notice_Panel": "جارٍ التحميل",
    "NotLogin": "فشل التحميل. أعد المحاولة لاحقًا.",
    "Offline_TeamA": "الفريق A",
    "Offline_TeamB": "الفريق B",
    "OffLine_PanelPlayer": "اللاعبون",
    "PropsShareTips": "شارك واحصل على \n عناصر!",
    "Props_ShowTips": "مثال",
    "PersonalInfo_Win": "الفوز",
    "PersonalInfo_Total": "الإجمالي",
    "PersonalInfo_WinRate": "معدل الفوز",
    "PersonalInfo_Edit": "تعديل",
    "PersonalInfo_Computer": "الروبوت",
    "PersonalInfo_ClassicOnline": "وضع الكلاسيك",
    "PersonalInfo_PropsOnline": "وضع التعزيز",
    "PersonalInfo_Props2V2": "وضع التعزيز 2 ضد 2",
    "PersonalInfo_Classic2V2": "وضع الكلاسيك 2 ضد 2",
    "PersonalInfo_Notenough_player": "بانتظار {Number} من اللاعبين أكثر",
    "PersonalInfo_Friend": "الأصدقاء",
    "PersonalInfo_Level": "المستوى",
    "PersonalInfo_ClassicOnlineTitle": "الاتصال بالإنترنت-كلاسيك",
    "PersonalInfo_PropsOnlineTitle": "الاتصال بالإنترنت-تعزيز",
    "PersonalInfo_TeamUpOnline": "وضع الفريق",
    "PersonalInfo_MiniMapOnline": "وضع الخريطة المصغرة",
    "PlayerProfile_LoginFB": "تسجيل الدخول عبر FB",
    "PlayerProfile_Continue": "متابعة",
    "Rank_PanelWin": "الفوز",
    "Select_Robot": "مطلوب لاعبين حقيقيين كحد أدنى.",
    "SaveGame_Content": "هل تريد بالتأكيد إنهاء المباراة؟",
    "SaveGame_Save": "حفظ",
    "ShareGame_EXP": "شارك واكسب 10 نقاط خبرة",
    "share_window_invite": "دعوة الأصدقاء",
    "Scene_Online_Title": "الاتصال بالإنترنت",
    "Scene_local_Title": "محلي",
    "Scene_local_ChooseMode": "اختر الوضع",
    "Scene_local_ChooseMode_Classic": "كلاسيك",
    "Scene_local_ChooseMode_Props": "تعزيز",
    "Scene_local_ChooseMode_TeamUp": "فريق",
    "Scene_local_ChooseMode_TeamPower": "فريق-تعزيز",
    "Scene_local_ChooseMode_TeamClassic": "فريق-كلاسيك",
    "Scene_local_ChooseColorAndName": "اختر اللون والاسم",
    "Scene_Online_ChooseBet": "اختر رسم المشاركة",
    "Scene_local_ChoosePlaers": "اختر اللاعبين",
    "Scene_local_ChoosePlaers_2P": "لاعبان",
    "Scene_local_ChoosePlaers_3P": "3 لاعبين",
    "Scene_local_ChoosePlaers_4P": "4 لاعبين",
    "Scene_local_PlayerName1": "اللاعب 1",
    "Scene_local_PlayerName2": "اللاعب 2",
    "Scene_local_PlayerName3": "اللاعب 3",
    "Scene_local_PlayerName4": "اللاعب 4",
    "Scene_local_ChooseTeam": "اختر الفريق",
    "Scene_ClassicOnline_Title": "كلاسيك",
    "Scene_PropsOnline_Title": "تعزيز",
    "Scene_MiniMapOnline_Title": "خريطة مصغرة",
    "Scene_TeamUpOnline_Title": "فريق",
    "Scene_Computer_Title": "الروبوت",
    "Scene_Friend_Title": "الأصدقاء",
    "Scene_Online_ChoosePlaers_2P": "لاعبان",
    "Scene_Online_ChoosePlaers_4P": "4 لاعبين",
    "Scene_Online_matching": "في انتظار اللاعبين الآخرين...",
    "Set_Panel_Title": "الإعدادات",
    "Set_Panel_Music": "الموسيقى",
    "Set_Panel_Sound": "الصوت",
    "Set_Panel_Version": "الإصدار",
    "Set_Panel_About": "نبذة حول",
    "Set_Panel_About_Detail": "نشكرك على دعم \!nLudo World إن كان لديك أي تعليقات،\nفيرجى إرسالها إلينا عبر\nhpludoworld@gmail.com",
    "Set_Panel_Help": "مساعدة",
    "Set_Panel_Feedback": "التعليقات",
    "Set_Panel_US": "تابعنا",
    "Set_Panel_RATE": "قيّم اللعبة",
    "Set_Panel_Privacy": "سياسة الخصوصية",
    "Set_Panel_Terms": "شروط الخدمة",
    "Set_FB_Login": "تسجيل الدخول",
    "Set_FB_Logout": "تسجيل الخروج",
    "Set_FB_Bind": "ربط",
    "Set_Panel_Vibrate": "اهتزاز",
    "Set_Panel_Chat": "الدردشة",
    "Set_Panel_Help_minimap": "تنطبق قواعد وضع الكلاسيك نفسها،\nلكنها خريطة أصغر بوتيرة لعب أسرع.\nهناك 4 مربعات آمنة فقط، ويوجد كل منها عند نقطة بداية كل لون.",
    "Title_Load_Game": "تحميل اللعبة",
    "Title_PlayerProfile": "الملف الشخصي",
    "Tips_Game__ThreeSixSkip": "عند الحصول على 6 ثلاث\nمرات متتالية، يتم تخطي الثالثة!",
    "Lucky_Wheel_Name": "عجلة الحظ",
    "Game_info_block": "حظر",
    "Game_info_unblock": "إلغاء الحظر",
    "Button_Item_Use": "استخدام",
    "Button_Item_Using": "مستخدم",
    "Button_Item_gotouse": "انتقال للاستخدام",
    "Main_Backpack": "حقيبة الظهر",
    "Item_Duration_Duration": "المدة",
    "Item_Duration_Day": "ي",
    "Item_Duration_Hour": "س",
    "Item_Duration_Min": "د",
    "Item_Duration_S": "ث",
    "Item_Duration_Year": "ع",
    "Item_Duration_Permanent": "دائم",
    "NewPlayerBonus_Gift": "هدية",
    "Common_Game_item_purchase": "اشترِ باستخدام بطاقات العناصر. يتبقى لديك {num}",
    "Common_Game_item_purchaseoverbuy": "يمكنك الاستبدال عدد {num} من المرات لكل مباراة",
    "Common_Game_itemcard_notenought": "ليس لديك بطاقات عناصر كافية! أتريد الشراء من المتجر؟",
    "Lobby_mini": "خريطة مصغرة",
    "Common_IOS_Shop_LessConins": "العملات غير كافية. اجمع المزيد من الفعالية.",
    "ComputerAndLocal": "روبوت ومحلي",
    "Common_Game_Undo_Lack": "ينقص",
    "Common_Game_Undo_Lack_Tip": "الجواهر لا تكفي للإلغاء",
    "Common_Game_Undo_Left": "مرات الإلغاء المتبقية",
    "Common_Game_Undo_Switch": "تفعيل الإلغاء",
    "Common_Game_Undo_Title_Enable": "إلغاء رمية النرد",
    "Common_Game_Undo_Title_Disable": "الإلغاء معطل",
    "Common_Game_Undo_Desc_Enable": "اضغط على هذا في غضون {num} ث بعد رمي النرد لإلغاء نتيجة النرد",
    "Common_Game_Undo_Desc_Disable": "عطلت خيار الإلغاء. اضغط على المربع لتفعيله مرة أخرى.",
    "Common_Game_Undo_Desc_Use_Up": "لا تتوفر محاولات للإلغاء",
    "Grand_Prix_Entry": "رسوم المشاركة",
    "Grand_Prix_Endsin": "ينتهي خلال",
    "Grand_Prix_Play": "العب",
    "Grand_More_Coins": "المزيد من العملات",
    "Grand_More_Level": "المستوى {date} مفتوح",
    "Starter_Pack": "حزمة المبتدئ",
    "Gift_Bag_Time": "يتبقى {date} س",
    "Lucky_Dice": "نرد محظوظ",
    "Exclusive_Offert": "عرض حصري",
  },
  "AlertText": {
    "Button_Common_Confirm": "موافق",
    "Button_Common_Yes": "نعم",
    "Button_Common_Cancel": "إلغاء",
    "Button_Common_No": "لا",
    "Button_Common_Upgrade": "ترقية",
    "Button_Common_NoUpgrade": "ليس الآن",
    "Button_Common_ExitUpgrade": "الخروج من اللعبة",
    "Bind_FB_Account": "فشل ربط حساب Facebook. أعد المحاولة لاحقًا.",
    "Bind_FB_Account2": "حساب Facebook هذا مربوط بالفعل. أعد المحاولة بحساب آخر.",
    "Common_Game_Online_Leave": "ستخسر إن خرجت من المباراة. هل تريد الخروج على أي حال؟",
    "Common_Game_Local_Leave": "الخروج من المباراة الحالية؟",
    "Common_Game_Local_SaveGame": "حفظ المباراة الحالية؟",
    "Common_Game_Computer_SaveGame": "حفظ المباراة الحالية؟",
    "Common_Game_Computer_EnterBySaveGame": "لديك مباراة لم تنتهِ. هل تريد تحميلها؟",
    "Common_Notify_Client_Logout": "تم تسجيل الدخول على جهاز آخر باستخدام هذا الحساب. سجِّل دخولك مجددًا لمتابعة اللعب على هذا الجهاز.",
    "Common_Netword_Fail": "يُرجى التحقق من اتصال الشبكة.",
    "Common_Netword_Fail_Offline": "فشل الاتصال بالشبكة. أتريد اللعب في وضع \"محلي أو روبوت\"؟",
    "Common_Netword_FailRethy": "فشل الاتصال بالشبكة. أتريد الاتصال الآن؟",
    "Common_Netword_Fail_timeout": "انتهت مهلة الاتصال بالشبكة. أعد المحاولة لاحقًا.",
    "Common_Netword_Fail_Reconnect": "يجب الاتصال بالشبكة للعب مباريات عبر الإنترنت. هل تريد الاتصال الآن؟",
    "Common_Lobby_ReturnGame": "أنت تلعب حاليًا في غرفة. أتود العودة إليها؟",
    "Common_Lobby_ReturnFailed": "انتهت مباراتك الأخيرة.",
    "Common_Scene_Online_LessCoins": "ليس لديك عملات كافية. اشترِ المزيد منها من المتجر.",
    "Common__Online_Matching_Failed": "فشل دخول الغرفة. أعد المحاولة لاحقًا.",
    "Common_Scene_Online_Matching_TimeOut": "انتهت المهلة خلال محاولة دخول الغرفة. أعد المحاولة لاحقًا.",
    "Common_Scene_Online_Sitting_Failed": "فشل الانضمام. أعد المحاولة لاحقًا.",
    "Common_No_Operation": "ستجري إزالتك من اللعبة إن ظللت غير نشط لفترة طويلة.",
    "Common_Delete": "هل تريد بالتأكيد حذف اللعبة المحفوظة؟",
    "Common_Game_TeamUp_GetUserGuide": "إن \"الفريق\" وضع لعب جديد! أتريد دخول العرض التوضيحي؟",
    "Facebook_Login_Faile": "فشل تسجيل الدخول إلى FB. تحقق من اتصالك بالشبكة.",
    "Game_leaderboard_sendBean_success": "تم إهداء العملات بنجاح",
    "Game_leaderboard_sendBean_fail": "فشل إرسال العملات",
    "Game_leaderboard_sendBean_Max": "لقد وصلت إلى الحد الأقصى لإهداء العملات اليوم.",
    "Game_Reselect_bet": "عملاتك أكثر من رسم المشاركة. يُرجى بدء مباراة جديدة في غرفة ذات رسم مشاركة أعلى!",
    "Game_chat_Common_Yes": "تشغيل",
    "Game_chat_Common_MainText": "عند تفعيل وظيفة الدردشة، يمكن للاعبين الآخرين رؤية محادثاتك. هل تريد تشغيل ميزة الدردشة الآن؟ يمكنك تعطيلها لاحقًا في الإعدادات.",
    "Game_Friend_Join_Not_Find": "الغرفة غير موجودة. تأكد من رمز الغرفة.",
    "Game_Friend_Join_Room_Closed": "تم إغلاق الغرفة بالفعل. يرجى بدء مباراة جديدة.",
    "Game_Friend_Join_Not_Enough_Coins": "لا تملك عملات كافية للانضمام إلى الغرفة. أتريد شراء المزيد من المتجر؟",
    "Game_Friend_Join_No_Extra_Seat": "للأسف الغرفة مكتملة العدد. يرجى بدء مباراة جديدة.",
    "Game_Friend_Join_alreadybegin": "لقد بدأت المباراة بالفعل. يرجى بدء مباراة جديدة.",
    "Game_Friend_Leave_Room": "ستُغلق الغرفة إن خرجت منها. أتريد الخروج على أي حال؟",
    "Login_NO_IP": "عذرًا، ولكن وفقًا لموقعك الحالي، لا يمكننا تقديم خدماتنا لك حاليًا.",
    "Modify_HeadIcon_Fail": "فشل التعديل. أعد المحاولة لاحقًا.",
    "Matching_Failed": "فشلت مطابقة اللاعبين. أعد المحاولة لاحقًا.",
    "No_Operation_ConfirmText": "بقاء",
    "No_Operation_CancelText": "خروج",
    "Quit_Game": "هل تريد بالتأكيد الخروج من المباراة؟",
    "Store_buy_tips": "ليس لديك عملات كافية. أتريد شراء المزيد منها من المتجر؟",
    "Store_buy_latter": "ليس الآن!",
    "Store_Open_Failed": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "Store_buy_go": "انتقال",
    "Store_Payment_Failed": "فشل الدفع. رمز الخطأ:",
    "Store_Payment_IPFailed": "فشل الدفع. يمكنك الدفع من خلال الألعاب الفورية على الكمبيوتر.",
    "ShortCut_go": "أتريد إنشاء اختصار للشاشة الرئيسية؟",
    "Client_Low_Version": "تتطلب الغرفة وجود أحدث إصدار من اللعبة. التحديث الآن؟",
    "Client_High_Version": "عذرًا، لا يمكنك دخول الغرفة بإصدار وكيلك الحالي.",
    "Client_Deny_Version": "عذرًا، لا يمكنك دخول الغرفة بإصدار وكيلك الحالي.",
    "Play_Punish_In_Chat": "أنت مكتوم حتى {date} بسبب انتهاكك القواعد.",
    "Play_Punish_In_Room": "حسابك محظور حتى {date} بسبب انتهاكك القواعد.",
    "Play_Punish_Enter_Room": "تم حظر حسابك بسبب انتهاكك القواعد.",
    "Kicked_Player_Not_Enough_Coins": "عندما لا تكفي عملاتك، ستخسر المباراة إن طُردت. هل تريد الحصول على المزيد من المتجر؟",
    "Kicked_Player_Game_Lose": "خسرت. ليس لديك عملات كافية لمتابعة لعب المباراة.",
    "Backpack_items_empty": "لا توجد عناصر. أتريد شراء بعضها من المتجر؟",
    "Grand_Unlock_level": "يُفتح عند بلوغ المستوى {date}",
    "Grand_Open_Hint": "افتح الفوز الكبير بعد {date}",
    "Grand_Less_Coins_recommend": "لا يمكنك المشاركة في المباراة لأن لديك أقل من {date} من العملات. هل تريد الاستمرار للمشاركة؟",
    "Grand_Less_Coins_Hint": "لا تملك عملات كافية للانضمام إلى الفوز الكبير. أتريد شراء المزيد من المتجر؟",
  },
  "Tips": {
    "Ads_times_tips": "عُد غدًا لمزيد من المكافآت.",
    "Ads_times_tips_Gems": "عُد غدًا للحصول على جواهر.",
    "Ads_coolCd_tips": "أعد المحاولة لاحقًا.",
    "Ads_none_tips": "لا توجد إعلانات لتشغيلها. أعد المحاولة لاحقًا.",
    "Ads_none_tips1": "لا توجد إعلانات لتشغيلها.",
    "Ads_notFull_tips": "شاهد الفيديو كاملاً من فضلك لتلقي المكافآت!",
    "Common_Game_Props_UseChooseNumber_AssignDice": "اختر الرقم",
    "Friend_Err_Fetch_List_Fail": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "Friend_Err_Fetch_Online_Fail": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "Friend_Err_Fetch_Login_Time_Fail": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "Friend_Err_Not_Add_Player": "فشلت المعالجة. أعد المحاولة لاحقًا.",
    "Friend_Err_List_Full": "لقد وصل عدد أصدقائك إلى الحد الأقصى. إن كنت تريد إضافة هذا الصديق، فيرجى حذف أصدقاء آخرين.",
    "Friend_Err_Peer_Friend_List_Full": "وصل {name} إلى أقصى عدد من الأصدقاء ولا يمكن إضافته.",
    "Friend_Err_Update_Friend_Fail": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "Friend_Err_Player_Refuse_Add": "{name} يرفض أي طلبات صداقة.",
    "Friend_Err_Already_In_Add_List": "",
    "Friend_Err_Already_In_Game_List": "أنتما صديقان بالفعل.",
    "Friend_Err_Already_In_Platform_List": "أنتما صديقان بالفعل.",
    "Friend_Err_Not_In_List": "فشلت المعالجة. أعد المحاولة لاحقًا.",
    "Friend_Err_Fetch_Game_Record_Fail": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "Friend_Err_Cannot_Add_Self": "فشلت الإضافة. أعد المحاولة لاحقًا.",
    "Game_Props_TopTitle_LuckyNumber": "الرقم\n الذهبي",
    "Game_Props_ItemTips_DoubleDice": "ضعف المسافة: يَضاعف الرقم الذي حصل عليه اللاعب، ويجب عليه التحرك المسافة التي حصل عليها فورًا. بعد استخدام هذا العنصر، الحصول على الرقم 6 لن يمنح مرات رمي إضافية ولا يمكن تحريك البيادق.",
    "Game_Props_ItemTips_AssignDice": "اختيار الرقم: يختار اللاعب الرقم الذي سيحصل عليه. يكسب اللاعب مرة رمي إضافية عند الحصول على الرقم 6 أوطرد بيدق أو الوصول إلى الهدف.",
    "Game_Props_ItemTips_Protection": "الدرع: يحمي كل البيادق من الطرد لدور واحد.",
    "Game_gift_gift": "إرسال إيموجي",
    "Game_gift_giftprice": "100 عملة لكل إيموجي",
    "Game_gift_sendtoofast": "خُذ استراحة.",
    "Game_leaderboard_load_fail_tips": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "Game_classic_newusertips_moveout1": "ارمِ 6 للانطلاق!",
    "Game_classic_newusertips_mesafe": "المربعات المحددة بنجمة آمنة!",
    "Game_classic_newusesrtip_bumptoken": "اطرد هذا البيدق!",
    "Game_Friend_JoinTips_Invalid_RoomCode": "رمز الغرفة غير صالح. ترجى إعادة التحقق منه.",
    "Lobby_unfinish_notice": "ستتوفر الميزة قريبًا!",
    "shortCut_create_succ": "نجح إنشاء الاختصار.",
    "shortCut_create_fail": "فشل إنشاء الاختصار. أعد المحاولة لاحقًا.",
    "shortCut_bubble_tips": "اضغط هنا لإنشاء اختصار في الشاشة الرئيسية",
    "Tips_Longin_Fail": "فشل تسجيل الدخول. أعد المحاولة لاحقًا!",
    "Tips_Netword_Fail_TryReconnect": "فشل الاتصال بالشبكة. جارٍ إعادة الاتصال",
    "Tips_Netword_Fail_Reconnected": "استعدت الاتصال. مرحبًا بعودتك!",
    "Tips_Game__ThreeSixSkip": "عند الحصول على 6 ثلاث\nمرات متتالية، يتم تخطي الثالثة!",
    "Tips_Game_Props_UseTips_DoubleDice": "ضعف المسافة! تتحرك ضعف الرقم!",
    "Tips_Game_Props_UseTips_AssignDice": "اخترت الرقم! رميت",
    "Tips_Game_Props_UseTips_Protection": "يحمي كل البيادق من الطرد لدور واحد.",
    "Tips_Game_Props_UseTips_LuckyNumber": "رمية إضافية. ارمِ مجددًا!",
    "Tips_Game_Props_UseFail_DoubleDice": "لا توجد بيادق لاستخدام هذا العنصر لها!",
    "Tips_Game_Props_UseFail_Protection": "لا توجد بيادق لحمايتها!",
    "Tips_Game_Props_OtherUseTips_DoubleDice": "استخدمت ضعف المسافة!",
    "Tips_Game_Props_OtherUseTips_AssignDice": "استخدمت اختيار الرقم!",
    "Tips_Not_Whatsapp": "تتطلب هذه الميزة تثبيت WhatsApp.",
    "Tips_NetWork_Connection": "جارٍ الاتصال",
    "Tips_Game_TeamUp_HelpTeammate": "ساعد زميلك من فضلك!",
    "task_load_fail_tips": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "Tips_Game_addFriendReq": "يطلب إضافتك كصديق.",
    "Tips_Game_addFriendReq_accept": "قبول",
    "Tips_Game_addFriendReq_ignore": "رفض",
    "Tips_Friend_Req": "تم إرسال طلب الصداقة",
    "Tips_Friend_AcceptSucc": "أصبح {name} صديقك.",
    "Tips_Friend_AcceptFailed": "تعذر القبول. يمكنك القبول من \"طلب صداقة\" لاحقًا.",
    "Tips_Friend_IgnoreFailed": "تعذر الرفض. يمكنك الرفض من \"طلب صداقة\" لاحقًا.",
    "Tips_Friend_RemoveFriend": "هل تريد بالتأكيد حذف هذا الصديق؟",
    "Set_Panel_chatclosetips": "لقد حظرت كل الدردشات.",
    "Tips_Send_Gift": "اضغط هنا لإرسال إيموجي.",
    "Tips_Send_This_Player_Gift": "اضغط هنا لإرسال إيموجي إلى هذا اللاعب.",
    "Tips_Profile_Add_Friends": "اضغط على الملف الشخصي للإضافة كصديق.",
    "Tips_Here_Add_Friends_GamePage": "اضغط هنا للإضافة كصديق.",
    "Tips_Here_Add_Friends_GameOver": "اضغط هنا للإضافة كصديق.",
    "Tips_Send_Coin_friends": "أرسل عملات مجانية للأصدقاء.",
    "Tips_Collect_By_Mail": "اجمع العملات المجانية من أصدقائك من البريد.",
    "Item_Use_Success": "لقد استخدمت {skin}.",
    "Kick_Player_No_Reward_Tips": "نفدت عملات {name} وخسر. لا توجد مكافأة إضافية هذه المرة.",
    "Common_Game_Mini_tips": "اجمع {num} من النجوم للفوز! طرد بيدق أو إدخال بيدقك المنزل يمنحك نجمة.",
    "Lobby_mini_tips": "صغيرة وحماسية",
  },
  "Chat": {
    "Game_emoji": "إيموجي",
    "Game_chat": "الدردشة",
    "Game_chat_title": "الدردشة السريعة",
    "Game_chat_content1": "مرحبًا!",
    "Game_chat_content2": "العب بسرعة!",
    "Game_chat_content3": "هذا سيئ!",
    "Game_chat_content4": "أحسنت",
    "Game_chat_content5": "لماذاااا!",
    "Game_chat_content6": "آسف!",
    "Game_chat_tips": "أدخل رسالتك",
    "Game_chat_send": "إرسال",
  },
  "DailyBonus": {
    "Lobby_Bonus_title": "المكافأة اليومية",
    "Lobby_Bonus_detail": "اربح عملات مجانية يوميًا!",
    "Lobby_Bonus_collect": "جمع",
    "Lobby_Bonus_collected_tips": "عُد غدًا للحصول على عملات أكثر.",
    "Lobby_Bonus_collect_failed": "فشل الجمع. أعد المحاولة لاحقًا.",
    "Lobby_Bonus_reqFailed": "فشل الحصول على المكافأة اليومية. أعد المحاولة لاحقًا.",
    "Lobby_Bonus_Day": "اليوم {num}",
    "Lobby_Bonus_Day_1": ""
  },
  "Props_Guide": {
    "Game_Props_TopTitle_Great": "رائع",
    "Game_Props_TopTitle_LuckyNumber": "الرقم\n الذهبي",
    "Game_Props_ItemTips_DoubleDice": "ضعف المسافة: يَضاعف الرقم الذي حصل عليه اللاعب، ويجب عليه التحرك المسافة التي حصل عليها فورًا. بعد استخدام هذا العنصر، الحصول على الرقم 6 لن يمنح مرات رمي إضافية ولا يمكن تحريك البيادق.",
    "Game_Props_ItemTips_AssignDice": "اختيار الرقم: يختار اللاعب الرقم الذي سيحصل عليه. يكسب اللاعب مرة رمي إضافية عند الحصول على الرقم 6 أوطرد بيدق أو الوصول إلى الهدف.",
    "Game_Props_ItemTips_Protection": "الدرع: يحمي كل البيادق من الطرد لدور واحد.",
    "Common_Game_Props_UseChooseNumber_AssignDice": "اختر الرقم",
    "Common_Game_Props_UserGuide_GoldenNo": "هذا الرقم الذهبي. ارمِه للحصول على رمية أخرى!",
    "Common_Game_Props_UserGuide_GoldenNo_content": "احصل على رمية إضافية إن وصلت إلى هنا.",
    "Common_Game_Props_UserGuide_continue": "اضغط للمتابعة",
    "Common_Game_Props_UserGuide_begin_title": "وضع التعزيز",
    "Common_Game_Props_UserGuide_begin_content": "مرحبًا بك، أنا مساعد Ludo World. سأشرح لك كيفية لعب وضع التعزيز!",
    "Common_Game_Props_UserGuide_roaditem": "يمكن جمع مختلف عناصر التعزيز على اللوحة.",
    "Common_Game_Props_UserGuide_Items": "تجد هنا كل عناصر التعزيز خاصتك.",
    "Common_Game_Props_UserGuide_Dicecontrol_title": "اختيار الرقم",
    "Common_Game_Props_UserGuide_Dicecontrol_content": "يمكنك اختيار الرقم الذي تود الحصول عليه!",
    "Common_Game_Props_UserGuide_Dicecontrol_tips": "رميت 6! هذه بداية رائعة!",
    "Common_Game_Props_UserGuide_Doubledistance_title": "ضعف المسافة",
    "Common_Game_Props_UserGuide_Doubledistance_content": "تتحرك ضعف الرقم الذي تحصل عليه!",
    "Common_Game_Props_UserGuide_GoldenNo_title": "رمية إضافية",
    "Common_Game_Props_UserGuide_GoldenNo_tips": "احصل على رمية إضافية عندما تصل! الكل يود الحصول على رمية إضافية!",
    "Common_Game_Props_UserGuide_BumpProtection_title": "درع الحماية",
    "Common_Game_Props_UserGuide_BumpProtection_content": "تكتسب حماية من البيادق المتسللة الأخرى لدور واحد.",
    "Common_Game_Props_UserGuide_BumpProtection_effect": "رائع! بيدقك محمٍ!",
    "Common_Game_Props_UserGuide_finish_title": "أنت مستعد!",
    "Common_Game_Props_UserGuide_finish_content": "الآن وقد عرفت استخدامات كل العناصر، حان الوقت للعب مباراة حقيقية!",
    "Common_Game_Props_UserGuide_finish_botton": "هيا بنا!",
    "Common_Game_Props_GetUserGuide": "هل تلعب وضع التعزيز لأول مرة؟ ألقِ نظرة على عرضنا التوضيحي.",
  },
  "Feedback": {
    "Set_Feedbeck_Title": "التعليقات",
    "Set_Feedbeck_Tips": "شكرًا على تعليقاتك ودعمك!",
    "Set_Feedbeck_Submit": "إرسال",
    "Set_Feedbeck_Submit_Succeed": "تم إرسال تعليقاتك بنجاح.",
    "Set_Feedbeck_Submit_No": "يجب أن تدخل تعليقاتك هنا.",
  },
  "TeamUp_Guide": {
    "Common_Game_teamup_UserGuide_begin_title": "فريق",
    "Common_Game_teamup_UserGuide_begin_content": "لنشكّل فريقًا! إليك القواعد.",
    "Common_Game_teamup_UserGuide_teammate": "اللاعب الأخضر المقابل لك هو زميلك في الفريق.",
    "Common_Game_teamup_UserGuide_competitor": "اللاعبان باللونين الأحمر والأصفر هما خصماك.",
    "Common_Game_teamup_UserGuide_pawnstack": "يمكن أن تقف بيادق زملاء الفريق معًا.",
    "Common_Game_teamup_UserGuide_onefinish": "ساعد زميلك في الفريق بعدما تُدخِل بيادقك الأربعة المنزل.",
    "Common_Game_TeamUp_UserGuide_finish_title": "أحسنت!",
    "Common_Game_TeamUp_UserGuide_finish_content": "لقد تعلمت كيفية لعب وضع الفريق. لنلعب الآن مباراة حقيقية!",
  },
  "SharePresentLottery": {
    "Lobby_Lottery_Hint": "شاهد إعلانًا لربح لفة مجانية",
    "Lobby_Lottery_Btn_Share": "العب للف",
    "Lobby_Lottery_Btn_spin": "لف",
    "Lobby_Lottery_Upper_Limit": "عُد غدًا للف عجلة الحظ!",
    "Lobby_Lottery_Close": "العجلة تلف!",
  },
  "ShareText": {
    "TitleTurnplate": "هل أنت مستعد للعب مباراة Ludo؟ لنلعب معًا الآن!",
    "TitlePropsShare": "لعبة Ludo World ممتعة للغاية! تعال والعب معي الآن!",
    "TitleOver": "لقد فزت بمباراة في Ludo World. تعالي والعب معي!",
    "FriendRoomInviteText": "يدعوك {name} للعب Ludo World. رمز الغرفة {RoomCode}.",
    "RankShareContent": "ربحت {num} من المباريات هذا الأسبوع. تعال وتحداني!",
    "Invite_gift_text1": "أهلاً، أنا ألعب Ludo World. تعال والعب معي!",
    "Invite_gift_text2": "مَن بطل اللعبة الحقيقي؟ تعال وتحداني!",
    "Invite_gift_text3": "إذا ضغط أصدقاؤك على الرابط الذي شاركته للتو، فستحصل على مكافأة.",
    "friend_invite_details": "تعال والعب معي Ludo World. رمز الغرفة: {Number}. اضغط للتنزيل أو دخول غرفة.",
  },
  "LoginMainLabel": {
    "LoginMainLabel_Facebook": "Facebook",
    "LoginMainLabel_Google": "Google",
    "LoginMainLabel_Description": "عن طريق المتابعة، أوافق على تخزين Moon Active لبياناتي ومعالجتها لها وفقًا لسياسة الخصوصية.",
    "LoginMainLabel_Guest": "ضيف",
    "LoginMainLabel_Continue_Sure": "هل أنت متأكد؟",
    "LoginMainLabel_Continue_Express": "لا يستطيع الضيوف اللعب مع الأصدقاء...",
    "LoginMainLabel_Continue_AsGuest": "اللعب كضيف",
    "LoginMainLabel_Continue_FbAward": "لا يستطيع الضيوف اللعب مع الأصدقاء أو ربح {coins} من العملات كمكافأة...",
    "LoginMainLabel_RewardPrompt": "{coins} من العملات مجانًا!",
    "LoginMainLabel_Continue_Warning": "من خلال الضغط على \"أوافق\"، أؤكد أنني قرأت سياسة الخصوصية واتفاقية مستخدم TENCENT GAMES وأوافق عليهما",
    "LoginMainLabel_Continue": "<u><b>المتابعة كضيف<u><b>",
    "LoginMainLabel_Select": "حدد طريقة تسجيل الدخول",
    "FacebookConnect_Content1": "<b><color=#444987>تسجيل الدخول عبر FB: </color></b>",
    "FacebookConnect_Content2": "<b><color=#444987>1>. العب مع الأصدقاء\n2. احفظ تقدمك\n3. اربح <color=#d16004>{num}<color=#444987> من العملات مجانًا<b>",
    "FacebookConnect_Content3": "<u><b><color = #3f59b7 click=\"handler\">تسجيل الدخول عبر FB</color></b></u>",
    "FacebookConnect_Content4": "<b><color=#444987>إن سجلت الدخول كضيف، <color=#d16004>لن يمكنك <color=#d16004>",
  },
  "PropsPromtText": {
    "Game_classic_newusertips_dicecontrolmoveout": "تحكّم في النرد\n للانطلاق!",
    "Game_classic_newusertips_dicecontrolbump": "تحكّم في النرد\n لطرد بيدق!",
    "Game_classic_newusertips_dicecontrolfinish": "تحكّم في النرد\n لدخول المنزل!",
    "Game_classic_newusertips_doubledistance": "ضاعف المسافة!",
    "Game_classic_newusertips_shild": "احمِ بيادقك!",
    "Game_classic_newusertips_dicecontrolrun": "تحكّم في النرد للهرب.",
    "Game_item_purchasetips": "اضغط للحصول على عناصر",
  },
  "MailPanel": {
    "Mail_Title": "البريد",
    "Mail_firend": "الأصدقاء",
    "Mail_system": "النظام",
    "Mail_collect": "جمع",
    "Mail_check": "تحقق",
    "Mail_collectAll": "جمع الكل",
    "Mail_Firend_Preservation_tips": "يمكن حفظ 60 رسالة لمدة 30 يومًا.",
    "Mail_System_Preservation_tips": "يمكن حفظ 60 رسالة لمدة 30 يومًا.",
    "Mail_NoMail_tips": "لا توجد رسائل بريد أخرى.",
    "MailInfo_Title": "التفاصيل",
    "MailInfo_firend_Gift": "هدية",
    "Mail_firend_Get_limit": "لقد جمعت بالفعل هدايا من {num} من الأصدقاء اليوم. عُد غدًا لجمع المزيد من الهدايا.",
    "MailInfo_get_Failure": "فشل جمع الهدايا. أعد المحاولة لاحقًا.",
    "Mail_delete_Failure": "فشل الحذف. أعد المحاولة لاحقًا.",
    "MailInfo_delete": "حذف",
  },
  "PrivacyPolicy": {
    "PrivacyPolicy_join1": "قرأت وأوافق على",
    "PrivacyPolicy_join2": "سياسة الخصوصية",
    "PrivacyPolicy_join3": "و",
    "PrivacyPolicy_join4": "اتفاقية المستخدم",
    "SelectNone": "من خلال الضغط على أوافق، أؤكد أنني قرأت سياسة الخصوصية واتفاقية المستخدم وأوافق عليهما",
  },
  "HelpText": {
    "Game_classic_userguide_tokens": "البيادق: كل جانب يمتلك 4 بيادق مختلفة.",
    "Game_classic_userguide_startpoint": "نقطة البدء: النقطة التي تبدأ منها البيادق.",
    "Game_classic_userguide_finishline": "المنزل: يجب أن تتحرك البيادق حول اللوحة قبل أن تتمكن من دخول المنزل.",
    "Game_classic_userguide_safeplace": "المربعات الآمنة: توجد 8 مربعات محددة بنجوم تعتبر مربعات آمنة، ولا يمكن طرد البيادق من عليها.",
    "Game_classic_userguide_dice": "النرد: كل جانب من جوانبه الستة مكتوب عليه رقم من 1 إلى 6.",
    "Game_classic_userguide_firsthand": "أول رمية: يُحدد أول لاعب عشوائيًا، ثم تتم المتابعة في اتجاه عقارب الساعة.",
    "Game_classic_userguide_moveout": "الخروج: يمكن للبيدق الخروج إن حصل اللاعب على 6.",
    "Game_classic_userguide_move": "الحركة: بعد رمي النرد، حدد أي بيدق موجود بالخارج ليتحرك تبعًا للرقم الذي حصلت عليه.",
    "Game_classic_userguide_automove": "الحركة التلقائية: يتحرك البيدق تلقائيًا عند وجوده وحده على اللوحة.",
    "Game_classic_userguide_sixbonus": "مكافأة الحصول على 6: يحصل اللاعب على رمية أخرى إن حصل على 6. وإن حصل اللاعب على 6 ثلاث مرات متتالية، فسيتم تخطي المرة الثالثة.",
    "Game_classic_userguide_bumpbonus": "مكافأة الطرد: يحصل اللاعب على رمية أخرى إن طرد بيدقًا.",
    "Game_classic_userguide_finishbonus": "مكافأة الإنهاء: يحصل اللاعب على رمية أخرى بعد إدخال بيدق إلى المنزل.",
    "Game_classic_userguide_bump": "الطرد: إن تحرك بيدق نحو مربع يقف عليه بيدق آخر، ولم يكن ذاك المربع نقطة آمنة، فسيطرد البيدق الآخر ويعيده إلى نقطة البدء. إن كان هناك بيدقان أو أكثر من اللون نفسه على المربع نفسه، فسيكونان محصنين من الطرد.",
    "Game_classic_userguide_finish": "يمكن للبيدق دخول المنزل فقط إن كان الرقم على النرد يساوي المسافة إلى المنزل. إن كان الرقم أكبر من المسافة المتبقية، فلا يمكن تحريك البيدق.",
    "Game_classic_userguide_winner": "الفائز: يفوز اللاعب الذي يُدخِل بيادقه الأربعة إلى المنزل. وخلال المباريات المكونة من 4 لاعبين، يفوز اللاعبان صاحبا المركزين الأول والثاني.",
    "Game_classic_userguide_time": "الوقت: 10 ث لكل رمية و10 ث لكل حركة.",
    "Game_classic_userguide_autohosted": "الحركة التلقائية: عندما تنفد المهلة المحددة لك أو ينقطع اتصالك، سيلعب الروبوت بدلاً عنك. اضغط لتستعيد التحكم.",
    "Set_Help_newuser_powermode_begin": "في حال لعب وضع الكلاسيك، أضِف العناصر التالية لجعل اللعبة أمتع!",
    "Set_Help_newuser_powermode_step1": "ضعف المسافة: تحرك ضعف المسافة التي تحصل عليها من النرد. واجعل وتيرة تحركك الضعف! \nيرجى ملاحظة أنه لن تنطبق مرة الرمي الإضافية للحصول على رقم 6 وإخراج بيدقك من المنزل بعد استخدام ضعف المسافة.",
    "Set_Help_newuser_powermode_step2": "اختيار الرقم: اختر الرقم الذي تود الحصول عليه.",
    "Set_Help_newuser_powermode_step3": "درع الحماية: تكتسب حماية من البيادق الأخرى لدور واحد.",
    "Set_Help_newuser_powermode_step4": "الرمية الإضافية: اكسب رمية إضافية عند الوصول.",
    "Set_Panel_Help_teamup_1": "القاعدة الأولى: تكوّن أنت واللاعب المقابل فريقًا (الأخضر والأزرق ضد الأحمر والأصفر).",
    "Set_Panel_Help_teamup_2": "القاعدة الثانية: عندما تقف بيادق فريقك معًا، لا يمكن لبيادق الفريق الآخر التجمع معًا لطردها.",
    "Set_Panel_Help_teamup_3": "القاعدة الثالثة: لا يمكن طرد بيادق فريقك التي كانت واقفة معًا إن تحركت.",
    "Set_Panel_Help_teamup_4": "القاعدة الرابعة: بعدما تُدخِل بيادقك الأربعة المنزل، يمكنك استخدام رميات نردك لتحريك بيادق زميلك في الفريق.",
    "Set_Panel_Help_teamup_5": "القاعدة الخامسة: يجب أن يُدخِل فريقك بيادقه الثمانية المنزل أولاً للفوز.",
  },
  "PropGuidePanel": {
    "PropGuidePanel_TitleText": "وضع التعزيز!",
    "PropGuidePanel_ContentText": "تعال وجرّب لعب\nوضع Ludo المميز الآن!",
    "PropGuidePanel_PlayBntText": "البدء",
    "PropGuidePanel_AwardHint": "من العملات مجانًا!",
    "NewHandGuide_AwardHint": "لقد أكملت العرض التوضيحي لوضع التعزيز!",
    "NewHandGuide_Get_Failure": "فشل الجمع. أعد المحاولة لاحقًا.",
    "PropGuideTipsOpenText": "شغّلت النصائح",
    "PropGuideTipsCloseText": "أوقفت النصائح",
  },
  "GameGuide": {
    "GameGuideText1": "مرحبًا بك!",
    "GameGuideText2": "لنلعب عبر الإنترنت مع لاعبين آخرين!",
  },
  "GameGuideText": {
    "GameGuideTitle": "اختر الوضع",
    "GameGuideContent": "أتعرف كيف تلعب Ludo؟ جرب",
    "GameGuideClassicModeContent": "كلاسيك",
    "GameGuidePowerModeContent": "خبير",
    "GameGuidePowerMode": "تعزيز",
    "GameGuidePlay": "لنلعب!",
    "GameGuideClassicMode": "كلاسيك",
    "GameGuideInnovative": "مبتكَر",
  },
  "GameTxpText": {
    "GameNoGetExp": "إن لم تطرد بيادق أو تدخل المنزل، فلن تحصل على نقاط خبرة.",
    "CloseTips": "اضغط للإغلاق",
    "ShareLevelTips": "لعبة Ludo World ممتعة للغاية! تعال والعب معي الآن!",
  },
  "AssessPanelText": {
    "Rate_title": "هل تستمتع باللعبة؟",
    "Rate_content": "إن أعجبتك اللعبة، فقيّمها!",
    "Rate_Button": "قيّم اللعبة",
    "Rate_Button2": "ليس الآن",
    "ShareGame_exp_fail": "فشل الحصول على نقاط خبرة. أعد المحاولة لاحقًا.",
    "ShareGame_exp_Exceed": "حصلت على الكثير من نقاط الخبرة اليوم. عُد غدًا.",
  },
  "TaskPanel": {
    "Task_Title": "المهمة",
    "Task_Daily": "المهمة اليومية",
    "Task_Growth": "مهمة التقدم",
    "Task_collect": "جمع",
    "Task_Play": "انطلق",
    "Task_Playing": "قيد التقدم",
    "Task_get_award_failed": "فشل الجمع. أعد المحاولة لاحقًا.",
    "Task_Tips": "يعاد تعيين المهمة اليومية في الساعة 24:00",
    "Task_Timeout": "فشل الجمع لأن مدة المهمة انقضت.",
    "Task_Coins": "عملات",
  },
  "TaskName": {
    "task_0": "تسجيل الدخول",
    "task_1": "إرسال هدايا إلى اللاعبين\nالآخرين 5 مرات في\nوضع الاتصال بالإنترنت",
    "task_2": "إرسال عملات إلى الأصدقاء\n5 مرات في\nقائمة الأصدقاء.",
    "task_3": "طرد بيادق 5 مرات\nفي وضع الأصدقاء",
    "task_4": "إدخال البيادق\nالمنزل 3 مرات في\nوضع الأصدقاء",
    "task_5": "الفوز بمباراة واحدة\nفي وضع\nالأصدقاء-كلاسيك",
    "task_6": "الفوز بمباراة واحدة\nفي وضع\nالأصدقاء-تعزيز",
    "task_7": "الفوز بمباراة واحدة\nفي وضع الأصدقاء",
    "task_8": "الفوز بخمس مباريات\nفي وضع\nالاتصال بالإنترنت-كلاسيك-لاعبان",
    "task_9": "الفوز بثلاث مباريات\nفي وضع\nالاتصال بالإنترنت-كلاسيك-4 لاعبين",
    "task_10": "الفوز بثلاث مباريات\nفي وضع\nالاتصال بالإنترنت-\nكلاسيك-2 ضد 2",
    "task_11": "الفوز بخمس مباريات\nفي وضع\nالاتصال بالإنترنت-تعزيز-لاعبان",
    "task_12": "الفوز بثلاث مباريات\nفي وضع\nالاتصال بالإنترنت-تعزيز-4 لاعبين",
    "task_13": "الفوز بثلاث مباريات\nفي وضع\nالاتصال بالإنترنت-\nتعزيز-2 ضد 2",
    "task_14": "الفوز بخمس مباريات في\nوضع الاتصال بالإنترنت",
    "task_15": "استخدام ضعف المسافة\n10 مرات في وضع\nالاتصال بالإنترنت-تعزيز",
    "task_16": "استخدام اختيار الرقم\n10 مرات في وضع\nالاتصال بالإنترنت-تعزيز",
    "task_17": "استخدام درع الحماية\n10 مرات في وضع\nالاتصال بالإنترنت-تعزيز",
    "task_18": "طرد بيادق 5 مرات\nفي وضع الاتصال بالإنترنت",
    "task_19": "إدخال البيادق\nالمنزل 3 مرات في\nوضع الاتصال بالإنترنت",
    "task_20": "",
    "task_21": "بلوغ المستوى {num}%",
    "task_22": "تسجيل الدخول في {num}% ي إجمالاً",
    "task_23": "الفوز في {num}% من المباريات\nفي وضع الاتصال بالإنترنت",
    "task_24": "الفوز في {num}% من المباريات\nفي وضع الروبوت",
    "task_25": "طرد بيادق %{num} من المرات\nفي وضع الاتصال بالإنترنت",
  },
  "TeamUp2V2": {
    "Common_Choose_Number_Team": "فريق",
    "Common_Choose_Number_2v2_titlepower": "تعزيز-2 ضد 2",
    "Common_Choose_Number_2v2_titleclassic": "كلاسيك-2 ضد 2",
    "Teamup_choose_tips1": "ادعُ صديقًا أو سنطابقك تلقائيًا",
    "Teamup_choose_tips2": "يمكنك البدء الآن",
    "Teamup_choose_betchange_title": "تغير رسم المشاركة",
    "Teamup_choose_betchange_content": "تم تعديل رسم المشاركة إلى {coins} لأن صديقك لا يملك عملات كافية.",
    "Teamup_choose_join_leave_title": "هل تريد الخروج من المباراة؟",
    "Teamup_choose_join_leave_content": "سيتم حل فريقك. ألا تزال تريد الخروج؟",
    "Teamup_Matching_leave_content": "تمت مطابقتك بالفعل. لا يمكنك الخروج الآن.",
    "Teamup_Game_inviting": "يدعوك {name} لتكوين فريق في وضع الاتصال بالإنترنت-2 ضد 2.",
  },
  "Region": {
    "Disgree_Content": "نعتذر عن عدم تمكننا من إتاحة Ludo World لك في الوقت الحالي. يجري حفظ بيناتنا خارج المنطقة الاقتصادية الأوروبية، وتحتاج فرق الدعم لدينا إلى الوصول إلى تلك البيانات من مناطق ذات سلطات قضائية أخرى لتوفير الخدمة لك.",
    "Back": "العودة",
    "Data_Agreement_Content_APK": "إن لعبة Ludo World منتج تقدمه Proxima Beta PTE.Limited، وهي شركة في سنغافورة ستعالج بياناتك خارج المنطقة الاقتصادية الأوروبية (بما في ذلك جمهورية الصين الشعبية) كي نقدم لك الخدمة. يُرجى ملاحظة أن عملية نقل البيانات تنطوي على مخاطر تتضمن خضوع بياناتك لأنظمة قانونية مختلفة قد لا توفر مستوى الحماية نفسه للبيانات المتوفر في البلد الذي توجد فيه.لمزيد من المعلومات، يرجى الاطلاع على <b><u><i click=\"handler\">سياسية الخصوصية</i></u></b> لدينا. من خلال الضغط على \"أوافق\"، فانت توافق على نقل بياناتك خارج المنطقة الاقتصادية الأوروبية.",
    "Data_Agreement_Content_FB": "إن لعبة Ludo World منتج تقدمه High Morale Development Limited، وهي شركة في هونغ كونغ ستعالج بياناتك خارج المنطقة الاقتصادية الأوروبية (بما في ذلك جمهورية الصين الشعبية) كي نقدم لك الخدمة. يُرجى ملاحظة أن عملية نقل البيانات تنطوي على مخاطر تتضمن خضوع بياناتك لأنظمة قانونية مختلفة قد لا توفر مستوى الحماية نفسه للبيانات المتوفر في البلد الذي توجد فيه.لمزيد من المعلومات، يرجى الاطلاع على <b><u><i click=\"handler\">سياسة الخصوصية</i></u></b> لدينا. من خلال الضغط على \"أوافق\" أدناه، فانت توافق على نقل بياناتك خارج المنطقة الاقتصادية الأوروبية.",
    "Agree": "أوافق",
    "Disagree": "أرفض",
    "Under_Age_Content": "بما أنك لم تبلغ {age} من العمر، فلا يمكننا إتاحة خدمة Ludo World لك حاليًا.",
    "Data_Outside_Content": "هل توافق على نقل بياناتك خارج المنطقة الاقتصادية الأوروبية؟",
    "Data_Outside_Title": "نقل البيانات خارج المنطقة الاقتصادية الأوروبية",
    "Delete_Notice_Title": "إشعار",
    "Delete_Notice_Content": "نعتذر عن عدم تمكننا من إتاحة Ludo World لك في الوقت الحالي. يجري حفظ بيناتنا خارج المنطقة الاقتصادية الأوروبية، وتحتاج فرق الدعم لدينا إلى الوصول إلى تلك البيانات من مناطق ذات سلطات قضائية أخرى لتوفير الخدمة لك. اضغط على \"العودة\" لإعادة التفكير بالأمر أو \"حذف الحساب\" للحذف.",
    "Delete_Account": "حذف الحساب",
    "Delete_Delete": "حذف",
    "Delete_Content": "هل ترغب في حذف حسابك؟ سيحذف النظام حسابك وبياناتك تلقائيًا بعد 7 أيام. يمكنك إلغاء الحذف عن طريق إعادة تسجيل دخولك إلى اللعبة خلال السبعة أيام.",
    "Chat_Off_Title": "تشغيل الدردشة الآن؟",
    "Chat_Off_Content": "عند تفعيل وظيفة الدردشة، يمكن للاعبين الآخرين رؤية محادثاتك. يمكنك تعطيلها لاحقًا في الإعدادات.",
    "Region_Title": "المنطقة",
    "Region_Content": "يُرجى تحديد المنطقة/البلد\nحيث توجد.",
    "Agree_Title": "تاريخ الميلاد",
    "Agree_Content": "كي نجعل تجربتك أفضل، يرجي التأكيد أنك تبلغ {age} من العمر على الأقل.",
    "Privacy_Title": "سياسة الخصوصية",
    "Privacy_Content": "من خلال الضغط على \"أوافق\" أدناه، أؤكد أنني قرأت\n<b><u><color = #535BBF click=\"handler\">سياسة الخصوصية</color></u></b>\nفي Ludo World وأوافق عليها.",
    "Privacy_Disagree": "لن نتمكن من توفير خدمات Ludo World إليك إن لم توافق على سياسة الخصوصية.",
    "Agreement_Title": "اتفاقية ترخيص المستخدم النهائي",
    "Agreement_Content": "من خلال الضغط على \"أوافق\" أدناه، أؤكد أنني قرأت\n<b><u><color = #535BBF click=\"handler\">اتفاقية ترخيص المستخدم النهائي</color></u></b>\nفي Ludo World وأوافق عليها.",
    "Agreement_Disagree": "لن نتمكن من توفير خدمات Ludo World إليك إن لم توافق على اتفاقية ترخيص المستخدم النهائي.",
    "YES": "نعم",
    "NO": "لا",
  },
  "FriendSystem": {
    "Friend_Main_title": "الأصدقاء",
    "Friend_Main_list": "القائمة",
    "Friend_Main_add": "إضافة",
    "Friend_Main_request": "طلب",
    "Friend_Main_list_FB": "أصدقاء FB",
    "Friend_Main_list_Game": "أصدقاء اللعبة",
    "Friend_Main_list_reciveandsend": "إرسال للكل",
    "Friend_Main_list_reciveandsend_Detail": "لا تُخصم العملات المرسلة إلى الأصدقاء من رصيدك.",
    "Friend_Main_Add_Recent": "مؤخرًا",
    "Friend_Select_Tip_NewRequest": "{num} من طلبات الصداقة",
    "Friend_Main_Request_Num_Tip": "احفظ آخر 99 طلبًا فقط.",
    "Friend_list_nofbfirends": "لا يوجد أصدقاء من FB للعب معهم،\nادعُهم للانضمام الآن!",
    "Friend_list_invitefirends": "لنلعب Ludo World معًا الآن!",
    "Friend_list_nogamefirends": "لا يوجد أصدقاء من اللعبة،\nأضِف بعضهم من علامة تبويب الإضافة!",
    "Friend_Add_NoRecent": "لا يوجد لاعب حديث",
    "Friend_Request_NoRequest": "لا يوجد طلب صداقة",
    "Friend_list_online": "متصل",
    "Friend_list_offline": "غير متصل",
    "Friend_list_playing": "يلعب",
    "Friend_Not_Accept": "لم يعد يقبل طلبات الصداقة.",
    "Friend_sendcoins_succeed": "أرسل 100 عملة إلى {name}",
    "Friend_sendcoins_fail": "لقد أرسلت أقصى عدد من الهدايا اليوم.",
    "Friend_collectandsendall_succeed": "أرسل {num} من العملات",
    "Friend_collectandsendall_nofirendtosend": "لا يوجد صديق للإرسال إليه",
    "Friend_invite_title": "الدعوة",
    "Friend_invite_bottoningame": "داخل اللعبة",
    "Friend_invite_whoinvite": "يدعوك {name} للعب مباراة!",
    "Friend_invite_reject": "رفض",
    "Friend_invite_accept": "قبول",
    "Friend_invite_friendpower": "أصدقاء-تعزيز",
    "Friend_invite_friendclassic": "أصدقاء-كلاسيك",
    "Friend_invite_teamuppower": "أصدقاء-تعزيز-2 ضد 2",
    "Friend_invite_teamupclassic": "أصدقاء-كلاسيك-2 ضد 2",
    "Friend_invite_sentsucceed": "تم إرسال الدعوة",
    "Friend_invite_sentfail": "فشل إرسال الدعوة",
    "Friend_invite_more_btn": "دعوة المزيد:",
    "Friend_collectcoins_fail": "لقد جمعت بالفعل عملات من {num} من الأصدقاء اليوم. عُد غدًا لجمع المزيد من الهدايا.",
    "Friend_collectall_succeed": "اجمع {coins} من العملات من الأصدقاء!",
    "Friend_Add_Recent_Source1": "اتصال بالإنترنت-كلاسيك-لاعبان",
    "Friend_Add_Recent_Source2": "اتصال بالإنترنت-كلاسيك-4 لاعبين",
    "Friend_Add_Recent_Source3": "اتصال بالإنترنت-تعزيز-لاعبان",
    "Friend_Add_Recent_Source4": "اتصال بالإنترنت-تعزيز-4 لاعبين",
    "Friend_Add_Recent_Source5": "اتصال بالإنترنت-كلاسيك-2 ضد 2",
    "Friend_Add_Recent_Source6": "اتصال بالإنترنت-تعزيز-2 ضد 2",
    "Friend_Add_Recent_Source7": "أصدقاء-كلاسيك",
    "Friend_Add_Recent_Source8": "أصدقاء-تعزيز",
    "Friend_Add_Recent_Source9": "أصدقاء-كلاسيك-2 ضد 2",
    "Friend_Add_Recent_Source10": "أصدقاء-تعزيز-2 ضد 2",
    "Friend_Request_Source_Recent": "آخر لعبة",
    "Friend_Request_Source_Suggested": "المقترح",
    "Friend_Request_Source_Leaderboard": "لوحة المتصدرين",
    "Friend_gametime-year": "منذ {num} ع",
    "Friend_gametime-day": "منذ {num} ي",
    "Friend_gametime-hour": "منذ {num} س",
    "Friend_gametime-minitue": "منذ {num} د",

  },
  "APPAdsText": {
    "ItemsAddOne": "عناصر+1",
  },
  "Common": {
    "Lobby_Bonus_collecet": "جمع",
    "Common_Game_teamup_UserGuide_finish_title": "أحسنت!",
    "Game_friends_invite_start": "يمكنك البدء الآن.",
    "": "",
    "Title_ModifyInfo": "تعديل المعلومات",
    "shortCut_create_success": "نجح إنشاء الاختصار.",
    "MainScenes_Ranking": "الترتيب",
    "MainScenes_FreeCoins": "عملات مجانية",
    "MainScenes_Mission": "المهمة",
    "Settings_on": "تشغيل",
    "Settings_off": "إيقاف",
    "Game_EndOrder_Congratulations": "تهانينا",
    "EM_ERR_FETCH_FRIEND_FAIL = -10002": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "EM_ERR_FETCH_ONLINE_FAIL = -10003": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "EM_ERR_FETCH_LOGIN_TIME_FAIL = -10004": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "EM_ERR_NOT_ADD_PLAYER = -10005": "فشلت المعالجة. أعد المحاولة لاحقًا.",
    "EM_ERR_FRIEND_LIST_FULL = -10006": "لقد وصل عدد أصدقائك إلى الحد الأقصى. إن كنت تريد إضافة هذا الصديق، فيرجى حذف أصدقاء آخرين.",
    "EM_ERR_PEER_FRIEND_LIST_FULL = -10007": "وصل {name} إلى أقصى عدد من الأصدقاء ولا يمكن إضافته.",
    "EM_ERR_UPDATE_FRIEND_FAIL = -10008": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "EM_ERR_PLAYER_REFUSE_ADD = -10009": "{name} يرفض أي طلبات صداقة.",
    "EM_ERR_ALREADY_IN_ADD_LIST = -10010": "",
    "EM_ERR_ALREADY_IN_GAME_FRIEND_LIST = -10011": "أنتما صديقان بالفعل.",
    "EM_ERR_ALREADY_IN_PLAT_FRIEND_LIST = -10012": "أنتما صديقان بالفعل.",
    "EM_ERR_NOT_IN_FRIEND_LIST = -10013, //": "فشلت المعالجة. أعد المحاولة لاحقًا.",
    "EM_ERR_FETCH_GAME_RECORD_FAIL = -10014": "فشل تحميل البيانات. أعد المحاولة لاحقًا.",
    "EM_ERR_CANNOT_ADD_SELF = -10015": "فشلت الإضافة. أعد المحاولة لاحقًا.",
    "LoginMainLabel_Guest_Title": "إن سجلت الدخول كضيف، لن يمكنك",
    "Language_type": "لعربية",
  },
  "GoodsName": {
    "GoodsName_Cricket": "كريكت",
    "GoodsName_Jewelry": "مجوهرات",
    "GoodsName_Airdrop_box": "إنزال جوي",
    "GoodsName_Cupid": "كيوبد",
    "GoodsName_Cat": "قطة",
    "GoodsName_Planet": "كوكب",
    "GoodsName_Default": "الافتراضي",
    "Shop_luckybox": "صندوق الحظ",
    "Shop_luckybox_GiftCardtitle": "بطاقة هدايا",
    "Shop_luckybox_GiftCard": "تحقق من بطاقة الهدايا داخل البريد في اللعبة.",
    "GoodsName_Item_Cards": "بطاقات عناصر",
    "GoodsName_Item_Cards_num": "بطاقات عناصر ×{num}",
    "GoodsName_Neon": "نيون",
    "GoodsName_Chick": "كتكوت",
    "GoodsName_First_AidKit": "صندوق إسعافات",
    "GoodsName_Machinery": "آلي",
    "GoodsName_Diwali": "مهرجان",
    "GoodsName_Christmas": "عيد الميلاد",
    "GoodsName_Gems": "جواهر",
  },
  "AdsText": {
    "Btn_Lucky_Show_Ad": "مشاهدة إعلان",
    "Lab_Lucky_Next": "المكافأة التالية:",
    "Lab_Lucky_Declare": "شاهد إعلانات لربح مرات لف مجانية يوميًا!",
    "Btn_Double_Reward": "مكافأة إضافية",
    "Btn_Reward_x2": "احصل على الضعف!",
    "Btn_No_Thanks": "لا، شكرًا",
    "Ad_Confirm_Cions": "شاهد إعلانات لربح {num} من العملات.",
    "Ad_Confirm_Item": "شاهد إعلانات لربح عنصر من كل نوع.",
    "Ad_Confirm_Task": "شاهد إعلانات للتقدم في المهام.",
    "Ad_Confirm_Spin": "شاهد إعلانات لربح {spin}.",
  },
  "NewUserText": {
    "NewPlayerBonus_Title": "مكافأة اللاعب الجديد",
    "NewPlayerBonus_Day": "يوم",
    "NewPlayerBonus_Collect": "جمع",
    "NewPlayerBonus_Collected": "جمعت",
    "NewPlayerBonus_LoginTips": "لقد سجلت دخولك لعدد {num} من الأيام بالفعل",
    "NewPlayerBonus_EventTime": "كل مرة:",
    "NewPlayerBonus_Coins": "عملات",
    "NewPlayerBonus_Skins": "مظهر",

  },
  "Shop": {
    "Shop_Tab_Coins": "عملات",
    "Shop_Tab_Spin": "مظهر",
    "Shop_Tab_Items": "عناصر",
    "Shop_Tab_Spin_BubbleTab": "فقاعة",
    "Shop_Tab_Spin_DiceTab": "نرد",
    "Shop_Tab_Spin_ThemeTab": "سمة",
    "Shop_Airdrop_box": "إنزال جوي",
    "Shop_Coins": "{num}",
    "Shop_Airdrop_box_day": "إنزال جوي ({num}ي)",
    "Shop_Cricket": "كريكت",
    "Shop_Cricket_day": "كريكت ({num}ي)",
    "Shop_Cupid": "كيوبد",
    "Shop_Cupid_day": "كيوبد ({num}ي)",
    "Shop_Jewelry": "مجوهرات",
    "Shop_Jewelry_day": "مجوهرات ({num}ي)",
    "Shop_Cat": "قطة",
    "Shop_Cat_day": "قطة ({num}ي)",
    "Shop_Planet": "كوكب",
    "Shop_Planet_day": "كوكب ({num}ي)",
    "Shop_Neon": "نيون",
    "Shop_Neon_day": "نيون ({num}ي)",
    "Shop_Chick": "كتكوت",
    "Shop_Chick_day": "كتكوت ({num}ي)",
    "Shop_First_AidKit": "صندوق إسعافات",
    "Shop_First_AidKit_day": "صندوق إسعافات ({num}ي)",
    "Shop_Machinery": "آلي",
    "Shop_Machinery_day": "آلي ({num}ي)",
    "Shop_Diwali": "مهرجان",
    "Shop_Diwali_day": "مهرجان ({num}ي)",
    "Shop_Christmas": "عيد الميلاد",
    "Shop_Christmas_day": "عيد الميلاد ({num}ي)",
    "Shop_Item": "بطاقات عناصر ({num})",
    "Shop_Label_New": "جديد",
    "Shop_Label_Hot": "رائج",
    "Shop_Label_Off": "إيقاف",
    "Shop_Label_Extar": "إضافي",
    "Shop_Label_BestDeal": "أفضل عرض",
    "Shop_Day_day": "يوم",
    "Shop_Buy_Success": "نجح الشراء. استخدمت {spin}.",
    "Shop_Backpack_Tip": "انتقل لاستخدام العناصر في حقيبة الظهر",
    "Button_Reload": "إعادة التحميل",
    "Button_AD_Free": "مجانًا",
    "Shop_Lucky": "حظ",
    "Shop_BuyGift_Success": "نجح الشراء. انتقل للاستخدام في حقيبة الظهر.",
    "Shop_Airdrop_box_Permanent": "إنزال جوي (دائم)",
    "Shop_Cricket_Permanent": "كريكت (دائم)",
    "Shop_Cupid_Permanent": "كيوبد (دائم)",
    "Shop_Jewelry_Permanent": "مجوهرات (دائم)",
    "Shop_Cat_Permanent": "قطة (دائم)",
    "Shop_Planet_Permanent": "كوكب (دائم)",
    "Shop_Neon_Permanent": "نيون (دائم)",
    "Shop_Chick_Permanent": "كتكوت (دائم)",
    "Shop_First_ AidKit_Permanent": "صندوق إسعافات (دائم)",
    "Shop_Machinery_Permanent": "آلي (دائم)",
    "Shop_Diwali_Permanent": "مهرجان (دائم)",
    "Shop_Lucky_Detail": "كريكت (1ي)، مجوهرات (1ي)، كوكب (1ي)",
    "Shop_WatchTV_Detail": "شاهد إعلانات لربح عنصر مجاني.",
    "Shop_Buy_Fail": "فشل الشراء. أعد المحاولة لاحقًا.",
    "Shop_Buy_ItemFail": "فشل إرسال العنصر. أعد المحاولة لاحقًا.",
    "Shop_Buy_Success_Prop": "نجح الشراء.",
    "Shop_Buy_Prop_Describe": "يمكن استبدال بطاقات العناصر بعناصر.",
    "Shop_itemcard": "بطاقات عناصر",
    "Shop_itemcard_number": "{num} من البطاقات",
    "Shop_Tab_Name": "المتجر",
  },
  "ReportText": {
    "Report_Panel": "إبلاغ",
    "Report_Title": "إبلاغ",
    "Report_People": "إبلاغ عن {name}",
    "Report_Content1": "إساءة لفظية",
    "Report_Content2": "غش",
    "Report_Content3": "آخر",
    "Report_Success": "أبلغت",
    "Report_Res_Title": "النتيجة",
    "Report_Res_Content": "تم كتم/إيقاف اللاعب {name} الذي أبلغت عنه.",
  },
  "RetainUser": {
    "newsuserA_classic_tips": "جرِّب وضع التعزيز. إنه أمتع!",
    "newsuserA_power_tips": "جرِّب وضع الكلاسيك. إنه أسهل!",
    "newsuserA_tips_quit": "خروج",
    "newsuserA_tips_try": "جرب",
    "newsuserB_tips_stay": "أكمل {num1} من المباريات ({num2}/{num3}) لربح الصندوق الأخضر.",
    "newsuserB_tips_minitips": "اسحب بطاقة هدايا Amazon بقيمة 100₹ أو عملات!",
    "newsuserB_tips_getluckybox_title": "صندوق أخضر",
    "newsuserB_tips_getluckybox_content": "اسحب بطاقة هدايا Amazon بقيمة 100₹ أو \nعملات! تحقق من حقيبة ظهرك.",
    "newsuserB_tips_getluckybox_tips": "اسحب بطاقة هدايا Amazon بقيمة 100₹ أو عملات!",
    "newsuserB_tips_getluckybox_cannotopen": "يفتح بعد {num}",
    "newsuserB_tips_getluckybox_openfail": "فشل الفتح. أعد المحاولة لاحقًا.",
    "newsuserB_tips_getluckyboxopen": "افتح صندوق الحظ الآن لسحب بطاقة \nهدايا Amazon بقيمة 100₹ أو عملات!",
    "newsuserA_tips_stay": "بقاء",
    "newsuserA_tips_leave": "الخروج؟",
    "newsuserA_tips_open": "فتح",
  },
  "MainChat": {
    "Button_Team_SendTeamRecruitment": "إرسال دعوة فريق",
    "Chat_World_NoChatTypeTips": "[نوع الرسالة هذا غير مدعوم.]",
    "Chat_World_EmptyTips": "يجب ألا تكون الرسالة فارغة.",
    "Chat_NoMessage_Tips": "اضغط هنا للدردشة",
    "Chat_Tab_World": "العالم",
    "Chat_Tab_Team": "الفريق",
    "Chat_Tab_Friends": "الأصدقاء",
    "Chat_World_DefaltTips": "أدخل رسالتك",
    "Button_Chat_Send": "إرسال",
    "Chat_Team_Send_WorldChat": "إرسال لدردشة العالم",
    "Chat_Team_Join": "انضمام",
    "Chat_Local_Tips": "دردشة محلية فقط",
    "Chat_Friends_NewMessageTips": "رسالة جديدة",
    "Chat_Friends_ClickTips": "اضغط على صديق للدردشة.",
    "Chat_Friends_NoFriendsTips": "تحتاج إلى أصدقاء.",
    "Chat_World_LocalTips": "اضغط هنا لدخول الدردشة المحلية",
    "Chat_Low_Level": "العب مباريات أكثر للوصول للمستوى {num} للدردشة!",
    "Chat_World_JoinTips": "انضممت إلى دردشة العالم",
    "Chat_Local_JoinTips": "انضممت إلى دردشة محلية",
    "Chat_Close_Tips": "تشغيل الدردشة الآن؟",
    "Tips_Team_SendSuccess": "أُرسلت دعوة الفريق إلى دردشة العالم.",
    "Chat_SendTooFast": "أنت تتحدث بسرعة. يُرجى المحاولة لاحقًا.",
  },
  "RedEnvelope": {
    "HB_Bag_Title": "كيس الحظ",
    "HB_Coins_Tips": "{num1} ~ {num2} من العملات",
    "HB_Coins_Tipstop": "{num1} من العملات",
    "HB_Image_Text": "شارك حظك وافتح كيس الحظ.",
    "HB_Open_Require": "ادع أصدقاءك لفتحه معًا!",
    "HB_Open_Tips": "كلما زاد عدد الأصدقاء المنضمين، زاد عدد العملات التي ستحصل عليها!",
    "HB_NoOpen_Tips1": "في انتظار انضمام أصدقائك عبر الرابط.",
    "HB_NoOpen_Tips2": "عندما ينضم صديق عبر الرابط، يمكنك فتح كيس الحظ.",
    "HB_Join_One": "كلما زاد عدد الأصدقاء المنضمين، زاد عدد العملات التي ستحصل عليها!",
    "HB_Join_More": "كلما زاد عدد الأصدقاء المنضمين، زاد عدد العملات التي ستحصل عليها!",
    "HB_Can_Open_Tips": "افتح كيس الحظ اليوم",
    "HB_Share_Title1": "العملات في Ludo World، افتح كيس العملات لتحصل على مكافآتك.",
    "HB_Share_Title2": "كيس الحظ في Ludo World، افتحه وجرّب حظك!",
    "HB_Btn_Open": "فتح",
    "HB_Btn_Open_noinvite": "دعوة",
    "HB_Collect_Fail": "يا لسوء الحظ، نفدت العملات.",
  },
  "LuckyBag": {
    "Clearing_Win_Share_Title": "الصندوق السري",
    "Clearing_Win_Share_Content": "ادع الأصدقاء للجمع معًا",
    "Clearing_Loser_Share_Title": "عملات مجانية",
    "Clearing_Loser_Share_Content": "ادع الأصدقاء للجمع معًا",
    "Clearing_Win_Ads_Title": "الصندوق السري",
    "Clearing_Win_Ads_Content": "شاهد إعلانًا لربح",
    "Clearing_Loser_Ads_Title": "عملات مجانية",
    "Clearing_Loser_Ads_Content": "شاهد إعلانًا لربح",
    "Clearing_Welfare_Share_Title": "ادع الأصدقاء لجمع",
    "Clearing_Share_Finish": "اضغط على الرابط الذي شاركته للتو في غضون {num} ث لاستلام مكافأتك!",
    "Clearing_Welfare_Ads_Title": "هل تحتاج إلى عملات أكثر؟",
    "Clearing_Welfare_Ads_Content": "شاهد إعلانًا لربح",
    "Clearing_Share_Loser": "الرابط الذي شاركته غير صالح، أعد إرسال الرابط",
  },
  "LuckSeven": {
    "Un_Lock_tips": "يتطلب {num1} من مرات الرمي الإضافية لفتح المزيد!",
    "Not_Enough_Gold": "العملات غير كافية",
    "High_Laid": "وصلت إلى الحد الأعلى!",
    "Low_Laid": "وصلت إلى الحد الأدنى!",
    "Show_FreeBet": "رمي النرد مجانًا عدد {num2} من المرات!",
    "Coins": "عملات",
    "laid_start_To_end": "{start} حتى {end}",
    "WIN": "فوز",
    "Get_Free_Bet": "احصل على مرات رمي مجانية!",
    "Double": "ضعف {point}",
    "Error": "خطأ في البيانات، يُرجى إعادة فتح الصفحة",
  },
  "EliminatGame": {
    "Select_Hint": "يُرجى اختيار العملات التي ستشارك بها",
    "Not_Coins": "ليست لديك عملات كافية. أتريد شراء المزيد من المتجر؟",
    "Min_Coins": "وصلت إلى الحد الأدنى من العملات بالفعل",
    "Max_Coins": "وصلت إلى الحد الأقصى من العملات بالفعل",
    "Win": "فوز",
    "Big_Win": "فوز كبير",
    "Super_Winner": "فوز خارق",
    "Total_Win": "فوز كامل",
    "Fish_Party": "حفلة السمك",
    "Quit_Hint": "لا تزال المباراة جارية. هل تريد بالتأكيد المغادرة؟",
    "AllIn": "المشاركة بالكل",
    "Auto": "تلقائي",
    "Start": "البدء",
    "EliminatGameTitle": "تعليمات المباراة",
    "Game_Rules": "قواعد اللعبة",
    "Explain": "تعليمات حفلة السمك",
    "Party_Text": "يمكن استبعاد ثلاث أسماك متماثلة متجاورة في الخط نفسه للحصول على المكافآت.\n\nبعد استبعادها، ستعيد اللعبة تجديد الأسماك تلقائيًا إلى أن يصبح استبعادها غير ممكن.",
    "Select_Fish": "حدد السمكة المرغوبة",
    "Eliminate_Award": "استبعد واربح عملات!",
    "Records": "إلقاء نظرة على المكافآت والسجلات",
    "Settlement_Rules": "قواعد التسوية",
    "Settlement_Rules_Text": "يمكن استبعاد ثلاث أسماك متماثلة متجاورة في الخط نفسه للحصول على المكافآت.\nتُحتسب المكافآت بشكل مستقل لكل سمكة.\nسيؤثر نوع السمكة وعدد مرات الاستبعاد على المكافة.\nتُضاعف المكاسب باستخدام المُضاعِف التالي.\nكلما زاد عدد الأسماء التي تستبعدها في الخط، زادت المكافآت!",
    "Back_Game": "العودة إلى المباراة",
    "Game_Name": "حفلة السمك",
    "Activity_Ended": "انتهى النشاط.",
  },
  "NewDiBao": {
    "NewDiBaoTitle": "حزمة الحظ",
    "Tip": "احصل على عملات حظ اليوم",
    "mulit": "جمع",
    "extra": "إضافي",
    "basic": "أساسي",
    "coins": "عملات",
    "togle": "شاهد إعلانًا للحصول على {num} من العملات!",
    "Before_Game_GoldEnough": "ليس لديك عملات كافية",
    "StartGame": "بدء المباراة",
  },
  "InsufficientCoin": {
    "title": "تحتاج إلى {num} من العملات على الأقل للعب.",
    "tip": "لديك الآن {haveCoin} من العملات",
    "goScene": "المباراة الموصى بها",
    "toOtherModel": "ليس معك ما يكفي من الذهب ({coins}) لبدء مباريات، أتريد اختيار وضع لعب آخر؟",
    "friend": "الأصدقاء",
    "computer": "الروبوت",
    "toOfferPlay": "عملاتك غير كافية. أتريد الانتقال إلى الوضع الموصى به؟",
  }
}
let loadMessage = function(language, dataID, isChange) {

};
exports.loadMessage = loadMessage;