'use strict';
if (!window.i18n) {
  window.i18n = {};
}

if (!window.i18n.languages) {
  window.i18n.languages = {};
}

window.i18n.languages['BrazilianPortuguese'] = {
  "label_text": {
    "Ads_getRewards_Title": "Receba recompensas",
    "Ads_CountDown_tips": "Próx. recompensas em:",
    "Ads_watchAd_Title": "Assista a um anúncio",
    "Auto_Game": "Automático",
    "Button_Guest_Facebook": "Fazer login com Facebook",
    "Button_Guest_Continue": "Continuar como convidado",
    "Button_Common_Confirm": "OK",
    "Button_Common_Yes": "Sim",
    "Button_Common_No": "Não",
    "Button_Common_Next": "Próximo",
    "Button_Common_Restart": "Reiniciar",
    "Button_Common_Return": "Voltar",
    "Button_Common_Share": "Compartilhar",
    "Button_Common_Start": "Iniciar",
    "Button_Common_Facebook": "Fazer login com Facebook",
    "Button_Common_Guest": "Convidado",
    "Common_Guest_BindAccount": "Vincular sua conta do Facebook?",
    "Common_Guest_BindAccountFail": "Falha ao conectar com o Facebook. Tente mais tarde.",
    "Common_Guest_RepeatBind": "Você já vinculou sua conta do Facebook. Conectar com a mesma?",
    "Common_Guest_Confirm": "Você está conectado como convidado e não pode jogar com seus amigos. \nFaça login pelo Facebook para: \n1. Jogar com seus amigos \n2. Usar sua foto de perfil no jogo \n3. Jogar entre dispositivos com a mesma conta. Você está conectado como convidado e não pode jogar com seus amigos.",
    "Common_Online_ShareContent": "Fiquei na posição #{1} em {0} e ganhei {2} moedas!",
    "Common_Scene_Teamup_Teammateturn": "Agora é possivel continuar jogando com seus colegas de equipe!",
    "Common_Game_Props_GetTipsTitle_DoubleDice": "Distância Dupla",
    "Common_Game_Props_GetTipsContent_DoubleDice": "Roles os dados para obter distância em dobro.",
    "Common_Game_Props_GetTipsTitle_AssignDice": "Controle de Dados",
    "Common_Game_Props_GetTipsContent_AssignDice": "Selecione o número desejado nos dados",
    "Common_Game_Props_GetTipsTitle_Protection": "Escudo de Proteção",
    "Common_Game_Props_GetTipsContent_Protection": "Proteja-se de outros peões por 1 turno",
    "Common_Game_Props_GetTipsTitle_LuckyNumber": "Número dourado",
    "Common_Game_Props_GetTipsContent_LuckyNumber": "Dentro de 1 rodada, ao obter este número um jogador poderá rolar de novo.",
    "Common_Scene_Props_Introduce_Title": "Apresentação do Modo Poder",
    "Common_Scene_Props_introduce_luckyNumber": "Número dourado",
    "Common_Scene_Props_introduce_luckyNumber_": "Dentro de 1 rodada, ao obter este número um jogador poderá rolar de novo. Ativação imediata e aplica-se a todos os jogadores.",
    "Common_Scene_Props_introduce_DoubleDice": "Distância Dupla",
    "Common_Scene_Props_introduce_DoubleDice_": "Dobra o número rolado. O jogador imediatamente deve mover-se o número de espaços indicados. Após o uso deste item, rolar um 6 não concederá rolagens bônus nem permitirá a saída de peões.",
    "Common_Scene_Props_introduce_AssignDice": "Dados controlados",
    "Common_Scene_Props_introduce_AssignDice_": "O jogador escolhe o número da rolagem. Uma rolagem bônus é garantida ao rolar 6, chutar um peão ou alcançar a meta.",
    "Common_Scene_Props_introduce_Protection": "Escudo",
    "Common_Scene_Props_introduce_Protection_": "Protege todos os peões contra chutes por 1 rodada.",
    "Common_Game_Props_ShowTips_LuckyNumber": "Rolagem bônus",
    "Common_Game_Props_ShowTips_LuckyNumber_": "Ganhe uma rolagem extra na chegada",
    "Common_Game_Props_ShowTips_DoubleDice": "Distância Dupla",
    "Common_Game_Props_ShowTips_DoubleDice_": "Percorra o dobro da distância obtida nos dados",
    "Common_Game_Props_ShowTips_AssignDice": "Controle de Dados",
    "Common_Game_Props_ShowTips_AssignDice_": "Selecione o número desejado nos dados",
    "Common_Game_Props_ShowTips_Protection": "Escudo de Proteção",
    "Common_Game_Props_ShowTips_Protection_": "Proteja-se de outros peões por 1 turno",
    "Common_Game_Props_Haved": "Itens de poder só podem ser utilizados antes de rolar os dados.",
    "Common_Game_Props_NotHaved": "Você não possui este item de poder ainda.",
    "Common_Team": "Equipe",
    "Common_Choose_Color": "Selecionar cor",
    "Common_Game_Online_MyPlace": "Você está aqui!",
    "Common_Choose_Number": "Selecionar jogadores",
    "Common_Choose_Bet": "Escolher aposta",
    "Common_Choose_Mode": "Selecionar modo",
    "Common_Choose_Number_players": "Jogadores",
    "Common_Choose_Win": "Vitória:",
    "Common_Choose_Entry": "Entrada:",
    "Common_Choose_Number_two": "2",
    "Common_Choose_Number_four": "4",
    "Common_Choose_Number_multi": "2-4",
    "Common_Choose_Number_Team": "Formar equipe",
    "Common_Choose_Number_2v2": "2x2",
    "Common_Game_Props_share": "Compartilhe e\nganhe itens!",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Escolha um número",
    "Common_Game_Props_sharetogetprops_title": "Compartilhe com amigos para ganhar 3 itens de poder grátis!",
    "Common_Game_Props_sharetogetprops_share": "Compartilhe",
    "Common_Game_Props_sharetogetprops_aftershare": "Cada jogo só pode ser compartilhado uma vez",
    "Friend_Room_Entering": "Entrando na sala...",
    "Friends_Invite": "Convite via:",
    "GameName": "Ludo World",
    "Game_Common_start": "Início do jogo",
    "Game_EndTitle_Win": "Vitória",
    "Game_EndTitle_Lose": "Derrota",
    "Game_EndOrder_1": "1.º",
    "Game_EndOrder_2": "2.º",
    "Game_EndOrder_3": "3.º",
    "Game_EndOrder_Win": "Vitória",
    "Game_EndOrder_4": "4.º",
    "Game_EndOrder_5": "5º",
    "Game_EndOrder_6": "6º",
    "Game_EndOrder_Lose": "Derrota",
    "Game_EndOrder_Playing": "Jogando",
    "local_Result_title": "Resultado",
    "Game_Online_Auto1": "Automático",
    "Game_Online_Auto2": "Toque aqui para parar",
    "Game_Props_TopTitle_LuckyNumber": "Número\n dourado",
    "Game_Props_ItemTips_DoubleDice": "Distância Dupla: dobra o número rolado. O jogador imediatamente deve mover-se o número de espaços indicados. Após o uso deste item, rolar um 6 não concederá rolagens bônus nem permitirá a saída de peões.",
    "Game_Props_ItemTips_AssignDice": "Dados controlados: o jogador escolhe o número do rolagem. Uma rolagem bônus é garantida ao rolar 6, chutar um peão ou alcançar a meta.",
    "Game_Props_ItemTips_Protection": "Escudo: protege todos os peões contra chutes por 1 rodada.",
    "Game_leaderboard_title": "Placar de líderes",
    "Game_leaderboard_global": "Global",
    "Game_leaderboard_NotRanked": "Sem posição",
    "Game_leaderboard_tips": "Os dados são atualizados toda segunda-feira.",
    "Game_leaderboard_tips2": "Apenas os jogos on-line são contados.",
    "Game_leaderboard_tipsoneline": "Dados (jogos online) atualizados toda segunda-feira",
    "Game_Computer_PlayerName1": "Computador1",
    "Game_Computer_PlayerName2": "Computador2",
    "Game_Computer_PlayerName3": "Computador3",
    "Game_Computer_level_choose": "Selecione o nível",
    "Game_Computer_Self": "Você",
    "Game_Computer_level_easy": "Fácil",
    "Game_Computer_level_normal": "Normal",
    "Game_Computer_level_hard": "Difícil",
    "Game_Computer_PlayerNameEasy": "Computador{num} Fácil",
    "Game_Computer_PlayerNamenormal": "Computador{num} Normal",
    "Game_Computer_PlayerNamehard": "Computador{num} Difícil",

    "Game_local_Remove_comfirm": "Deseja mesmo remover este jogador?",
    "Game_local_Remove_guide_title": "Remover jogador",
    "Game_local_Remove_guide_content1": "Quem não quer jogar",
    "Game_Friend_Pnael_Title": "Jogar com amigos",
    "Game_Friend_Select_Mode": "Selecionar modo de jogo",
    "Game_Friend_Create": "Criar",
    "Game_Friend_Join": "Entrar",
    "Game_Friend_Join_Clear": "Remover",
    "Game_Friend_GameMode": "Escolher modo de jogo",
    "Game_Friend_Enter_RoomCode": "Insira o código da sala",
    "Game_friends_invite_code": "Código da sala",
    "Game_friends_invite_tips_cannot": "Aguardando jogadores...",
    "Game_friends_invite_tips_can": "Aguardando outros ou iniciar agora.",
    "Game_friends_join_tips": "Insira o código da sala",
    "Game_friends_join_join": "Entrar",
    "Game_friends_join_wait": "Aguardando {who} para iniciar",
    "Game_friends_choose_classic": "Clássico",
    "Game_friends_choose_power": "Poder",
    "Game_friends_choose_mode": "Modo",
    "Game_friends_invite_waiting": "Aguardando jogadores...",
    "Game_friends_invite_waitormore": "Aguardando outros ou iniciar agora.",
    "Game_friends_invite_start2V2": "Você pode iniciar o jogo.",
    "Game_friends_invite_share": "Convide seus amigos compartilhando o código da sala",
    "Game_Ready": "Prepare-se!",
    "Guest_Username": "Convidado",
    "help_classic_title": "Clássico",
    "help_powerUp_title": "Poder",
    "InGame_PlayerInfo_Match": "Partida",
    "InGame_PlayerInfo_Win": "Vitória",
    "InGame_PlayerInfo_Gift": "Presente (100 moedas por presente)",
    "introduce_friendModel": "jogue apenas com amigos",
    "LevelUp_Panel": "Avanço de nível",
    "LevelProgressPanelExp": "Exp",
    "LoadGame_Button_Load": "Carregar",
    "Login_loading": "Fazendo login...",
    "Lobby_receive_award_coins": "Moedas",
    "Lobby_invite_detail1": "Convide amigos e ganhe {num} moedas por cada amigo que participar pelo link",
    "Lobby_invite_detail2": "Você ganhará uma recompensa por mensagem depois que seus amigos conectarem com o Facebook (máx. de {times} vezes por dia)",
    "Lobby_invite_btn": "Convidar",
    "Lobby_invite_title": "Precisa de mais moedas?",
    "Lobby_invite_guestlogin": "Conectar a sua conta do Facebook para continuar?",
    "MainScenes_Fackback": "Sugestões e opiniões",
    "MainScenes_Ranking": "Posição",
    "MainScenes_Invite": "Convite",
    "MainScenes_FreeCoins": "Moedas grátis",
    "MainScenes_Mission": "Missão",
    "modify_title": "Editar perfil",
    "Notice_Panel_Title": "Aviso",
    "Notice_Panel": "Carregando",
    "NotLogin": "Falha de login. Tente mais tarde.",
    "Offline_TeamA": "equipe A",
    "Offline_TeamB": "equipe B",
    "OffLine_PanelPlayer": "Jogadores",
    "PropsShareTips": "Compartilhe e\n ganhe itens!",
    "Props_ShowTips": "EXEMPLO",
    "PersonalInfo_Win": "Vitória",
    "PersonalInfo_Total": "Total",
    "PersonalInfo_WinRate": "Taxa de vitórias",
    "PersonalInfo_Edit": "Editar",
    "PersonalInfo_Computer": "Computador",
    "PersonalInfo_ClassicOnline": "Modo Clássico",
    "PersonalInfo_PropsOnline": "Modo Poder",
    "PersonalInfo_Props2V2": "Modo Poder 2x2",
    "PersonalInfo_Classic2V2": "Modo Clássico 2x2",
    "PersonalInfo_Notenough_player": "Aguardando mais {Number} jogadores",
    "PersonalInfo_Friend": "Amigos",
    "PersonalInfo_Level": "Nv.",
    "PersonalInfo_ClassicOnlineTitle": "Clássico On-line",
    "PersonalInfo_PropsOnlineTitle": "Poder On-line",
    "PersonalInfo_TeamUpOnline": "Modo Equipes",
    "PersonalInfo_MiniMapOnline": "Modo Minimapa",
    "PlayerProfile_LoginFB": "Fazer login com Facebook",
    "PlayerProfile_Continue": "Continuar",
    "Rank_PanelWin": "Vitória",
    "Select_Robot": "É necessário pelo menos 2 humanos.",
    "SaveGame_Content": "Deseja mesmo encerrar o jogo?",
    "SaveGame_Save": "Salvar",
    "ShareGame_EXP": "Compartilhe e ganhe 10 EXP",
    "share_window_invite": "Convidar amigos",
    "Scene_Online_Title": "On-line",
    "Scene_local_Title": "Local",
    "Scene_local_ChooseMode": "Selecionar modo",
    "Scene_local_ChooseMode_Classic": "Clássico",
    "Scene_local_ChooseMode_Props": "Poder",
    "Scene_local_ChooseMode_TeamUp": "Equipes",
    "Scene_local_ChooseMode_TeamPower": "Poder em Equipes",
    "Scene_local_ChooseMode_TeamClassic": "Clássico em Equipes",
    "Scene_local_ChooseColorAndName": "Escolha cor e nome",
    "Scene_Online_ChooseBet": "Faça sua aposta",
    "Scene_local_ChoosePlaers": "Selecionar jogadores",
    "Scene_local_ChoosePlaers_2P": "2 jogadores",
    "Scene_local_ChoosePlaers_3P": "3 jogadores",
    "Scene_local_ChoosePlaers_4P": "4 jogadores",
    "Scene_local_PlayerName1": "Jogador 1",
    "Scene_local_PlayerName2": "Jogador 2",
    "Scene_local_PlayerName3": "Jogador 3",
    "Scene_local_PlayerName4": "Jogador 4",
    "Scene_local_ChooseTeam": "Escolha a equipe",
    "Scene_ClassicOnline_Title": "Clássico",
    "Scene_PropsOnline_Title": "Poder",
    "Scene_MiniMapOnline_Title": "Minimapa",
    "Scene_TeamUpOnline_Title": "Equipes",
    "Scene_Computer_Title": "Computador",
    "Scene_Friend_Title": "Amigos",
    "Scene_Online_ChoosePlaers_2P": "2 jogadores",
    "Scene_Online_ChoosePlaers_4P": "4 jogadores",
    "Scene_Online_matching": "Aguardando outros jogadores...",
    "Set_Panel_Title": "Opções",
    "Set_Panel_Music": "Música",
    "Set_Panel_Sound": "Som",
    "Set_Panel_Version": "Versão",
    "Set_Panel_About": "Sobre",
    "Set_Panel_About_Detail": "Obrigado por apoiar\nLudo World! Se você\ntiver qualquer sugestão ou opinião,\nentre em contato conosco em\nhpludoworld@gmail.com",
    "Set_Panel_Help": "Ajuda",
    "Set_Panel_Feedback": "Sugestões e opiniões",
    "Set_Panel_US": "Curta",
    "Set_Panel_RATE": "Avalie",
    "Set_Panel_Privacy": "Política de privacidade",
    "Set_Panel_Terms": "Termos de serviço",
    "Set_FB_Login": "Fazer login",
    "Set_FB_Logout": "Fazer logout",
    "Set_FB_Bind": "Conectar",
    "Set_Panel_Vibrate": "Vibração",
    "Set_Panel_Chat": "Bate-papo",
    "Set_Panel_Help_minimap": "Mesmas regras do Modo Clássico.\nMapa menor, mais rápido.\nApenas 4 casas seguras, uma em cada ponto inicial de cada cor.",
    "Title_Load_Game": "Carregar jogo",
    "Title_PlayerProfile": "Perfil",
    "Tips_Game__ThreeSixSkip": "Número seis por\n3 vezes seguidas, pula!",
    "Lucky_Wheel_Name": "Roda da fortuna",
    "Game_info_block": "Bloquear",
    "Game_info_unblock": "Desbloquear",
    "Button_Item_Use": "Usar",
    "Button_Item_Using": "Usando",
    "Button_Item_gotouse": "Ir para usar",
    "Main_Backpack": "Mochila",
    "Item_Duration_Duration": "Duração:",
    "Item_Duration_Day": "d",
    "Item_Duration_Hour": "h",
    "Item_Duration_Min": "min",
    "Item_Duration_S": "s",
    "Item_Duration_Year": "ano",
    "Item_Duration_Permanent": "Permanente",
    "NewPlayerBonus_Gift": "Presente",
    "Common_Game_item_purchase": "Compre com cartas de itens, você ainda tem {num}",
    "Common_Game_item_purchaseoverbuy": "A troca só é possível {num} vezes por jogo",
    "Common_Game_itemcard_notenought": "Cartas insuficientes! Comprar mais na loja?",
    "Lobby_mini": "Minimapa",
    "Common_IOS_Shop_LessConins": "Moedas insuficientes. Obtenha mais no evento.",
    "ComputerAndLocal": "Computador e local",
    "Common_Game_Undo_Lack": "falta",
    "Common_Game_Undo_Lack_Tip": "Não há gemas suficientes para cancelar",
    "Common_Game_Undo_Left": "Cancelamentos restantes",
    "Common_Game_Undo_Switch": "Cancelamento ativado",
    "Common_Game_Undo_Title_Enable": "Cancelar rolagem de dados",
    "Common_Game_Undo_Title_Disable": "O Cancelamento está DESATIVADO",
    "Common_Game_Undo_Desc_Enable": "Toque aqui em até {num} segundos após rolar os dados para cancelar o resultado",
    "Common_Game_Undo_Desc_Disable": "Você desativou a opção de cancelamento. Toque na caixa para ativar novamente",
    "Common_Game_Undo_Desc_Use_Up": "Não há mais cancelamentos",
    "Grand_Prix_Entry": "CUSTO DE ENTRADA",
    "Grand_Prix_Endsin": "Termina em",
    "Grand_Prix_Play": "JOGAR",
    "Grand_More_Coins": "Mais moedas",
    "Grand_More_Level": "Nv. {date} aberto",
    "Starter_Pack": "Pacote inicial",
    "Gift_Bag_Time": "{date} horas restantes",
    "Lucky_Dice": "Dado da Sorte",
    "Exclusive_Offert": "Oferta exclusiva",
  },
  "AlertText": {
    "Button_Common_Confirm": "OK",
    "Button_Common_Yes": "Sim",
    "Button_Common_Cancel": "Cancelar",
    "Button_Common_No": "Não",
    "Button_Common_Upgrade": "Melhorar",
    "Button_Common_NoUpgrade": "Agora não",
    "Button_Common_ExitUpgrade": "Sair do jogo",
    "Bind_FB_Account": "Falha ao conectar com o Facebook. Tente mais tarde.",
    "Bind_FB_Account2": "Esta conta do Facebook já está conectada. Tente de novo com outra conta.",
    "Common_Game_Online_Leave": "Você perderá caso deixe a partida. Sair mesmo assim?",
    "Common_Game_Local_Leave": "Deixar a partida atual?",
    "Common_Game_Local_SaveGame": "Salvar o jogo atual?",
    "Common_Game_Computer_SaveGame": "Salvar o jogo atual?",
    "Common_Game_Computer_EnterBySaveGame": "Existe um jogo não concluído. Carregá-lo?",
    "Common_Notify_Client_Logout": "Esta conta conectou-se em outro dispositivo. Faça login novamente para continuar jogando neste dispositivo.",
    "Common_Netword_Fail": "Verifique sua conexão de rede.",
    "Common_Netword_Fail_Offline": "Falha ao conectar-se com a rede. Jogar no Modo Local ou Computador?",
    "Common_Netword_FailRethy": "Falha ao conectar-se com a rede. Conectar agora?",
    "Common_Netword_Fail_timeout": "Tempo limite de conexão. Tente mais tarde.",
    "Common_Netword_Fail_Reconnect": "É necessário conectar-se à rede para jogar online. Conectar agora?",
    "Common_Lobby_ReturnGame": "Você está jogando em uma sala. Voltar à sala?",
    "Common_Lobby_ReturnFailed": "Seu último jogo terminou.",
    "Common_Scene_Online_LessCoins": "Moedas insuficientes. Comprar mais na loja?",
    "Common__Online_Matching_Failed": "Falha ao entrar na sala. Tente mais tarde.",
    "Common_Scene_Online_Matching_TimeOut": "Tempo limite ao tentar entrar na sala. Tente mais tarde.",
    "Common_Scene_Online_Sitting_Failed": "Falha ao sentar-se. Tente mais tarde.",
    "Common_No_Operation": "Inatividade por muito tempo causará sua remoção do jogo.",
    "Common_Delete": "Deseja mesmo apagar o jogo salvo?",
    "Common_Game_TeamUp_GetUserGuide": "Equipes é um modo de jogo novo! Entrar no tutorial?",
    "Facebook_Login_Faile": "Falha ao fazer login com Facebook. Verifique sua rede.",
    "Game_leaderboard_sendBean_success": "Moedas presenteadas com sucesso",
    "Game_leaderboard_sendBean_fail": "Falha ao enviar moedas",
    "Game_leaderboard_sendBean_Max": "Você atingiu o número máximo de moedas presenteadas por hoje.",
    "Game_Reselect_bet": "Suas moedas são maiores do que o limite de aposta. Inicie um novo jogo em uma sala de apostas maiores.",
    "Game_chat_Common_Yes": "Ligar",
    "Game_chat_Common_MainText": "Enquanto o bate-papo estiver ativo, outros jogadores poderão ver as suas conversas. Ligar o bate-papo? É possível desativá-lo depois nas opções.",
    "Game_Friend_Join_Not_Find": "Sala não encontrada. Verifique o código da sala.",
    "Game_Friend_Join_Room_Closed": "A sala já foi desfeita. Comece um jogo novo.",
    "Game_Friend_Join_Not_Enough_Coins": "Moedas insuficientes para entrar na sala. Obter mais na loja?",
    "Game_Friend_Join_No_Extra_Seat": "Ops, a sala está cheia. Inicie um jogo novo.",
    "Game_Friend_Join_alreadybegin": "O jogo já começou. Inicie um jogo novo.",
    "Game_Friend_Leave_Room": "A sala vai se fechar se você sair. Sair mesmo assim?",
    "Login_NO_IP": "Infelizmente, com base no seu local atual, nossos serviços estão indisponíveis no momento.",
    "Modify_HeadIcon_Fail": "Falha de modificação, tente mais tarde.",
    "Matching_Failed": "Falha ao buscar um jogo. Tente mais tarde.",
    "No_Operation_ConfirmText": "Ficar",
    "No_Operation_CancelText": "Sair",
    "Quit_Game": "Deseja mesmo sair do jogo?",
    "Store_buy_tips": "Moedas insuficientes. Obter mais na loja?",
    "Store_buy_latter": "Agora não!",
    "Store_Open_Failed": "Falha ao carregar os dados. Tente mais tarde.",
    "Store_buy_go": "Ir",
    "Store_Payment_Failed": "Falha de pagamento. Código do erro:",
    "Store_Payment_IPFailed": "Falha de pagamento, você pode tentar pagar com PC Instant Game.",
    "ShortCut_go": "Criar um atalho na tela inicial?",
    "Client_Low_Version": "A sala requer a versão mais recente. Atualizar agora?",
    "Client_High_Version": "Oops, sua versão do jogo não permite entrada na sala.",
    "Client_Deny_Version": "Oops, sua versão do jogo não permite entrada na sala.",
    "Play_Punish_In_Chat": "Você foi silenciado até {date} por violação de regras.",
    "Play_Punish_In_Room": "Sua conta foi banida até {date} por violação de regras.",
    "Play_Punish_Enter_Room": "Sua conta foi banida por violação de regras.",
    "Kicked_Player_Not_Enough_Coins": "Caso você fique com moedas insuficientes, você perderá a partida se chutado. Obter mais na loja?",
    "Kicked_Player_Game_Lose": "Você perdeu. Moedas insuficientes para continuar o jogo.",
    "Backpack_items_empty": "Nenhum item ainda. Obter alguns na loja?",
    "Grand_Unlock_level": "É desbloqueado ao alcançar o nível {date}",
    "Grand_Open_Hint": "Abra o grande prêmio após {date}",
    "Grand_Less_Coins_recommend": "Você tem menos moedas do que o recomendado para entrar no jogo ({date}). Entrar mesmo assim?",
    "Grand_Less_Coins_Hint": "Moedas insuficientes para entrar no grande prêmio. Obter mais na loja?",
  },
  "Tips": {
    "Ads_times_tips": "Volte amanhã para mais recompensas.",
    "Ads_times_tips_Gems": "Volte amanhã para pegar gemas.",
    "Ads_coolCd_tips": "Tente de novo mais tarde.",
    "Ads_none_tips": "Sem anúncios para ver agora, tente mais tarde.",
    "Ads_none_tips1": "Sem anúncios para ver agora.",
    "Ads_notFull_tips": "Veja o vídeo inteiro para ganhar recompensas!",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Escolha um número",
    "Friend_Err_Fetch_List_Fail": "Falha ao carregar os dados. Tente mais tarde.",
    "Friend_Err_Fetch_Online_Fail": "Falha ao carregar os dados. Tente mais tarde.",
    "Friend_Err_Fetch_Login_Time_Fail": "Falha ao carregar os dados. Tente mais tarde.",
    "Friend_Err_Not_Add_Player": "Falhar de processamento, tente mais tarde.",
    "Friend_Err_List_Full": "Você atingiu o número limite de amigos. Caso precise adicionar amigos, exclua outros amigos.",
    "Friend_Err_Peer_Friend_List_Full": "Não é possível adicionar {name} pois o número de amigos desta pessoa atingiu o limite.",
    "Friend_Err_Update_Friend_Fail": "Falha ao carregar os dados. Tente mais tarde.",
    "Friend_Err_Player_Refuse_Add": "{name} não está aceitando pedidos de amizade.",
    "Friend_Err_Already_In_Add_List": "",
    "Friend_Err_Already_In_Game_List": "Vocês já são amigos.",
    "Friend_Err_Already_In_Platform_List": "Vocês já são amigos.",
    "Friend_Err_Not_In_List": "Falhar de processamento, tente mais tarde.",
    "Friend_Err_Fetch_Game_Record_Fail": "Falha ao carregar os dados. Tente mais tarde.",
    "Friend_Err_Cannot_Add_Self": "Falha ao adicionar, tente mais tarde.",
    "Game_Props_TopTitle_LuckyNumber": "Número\n dourado",
    "Game_Props_ItemTips_DoubleDice": "Distância Dupla: dobra o número rolado. O jogador imediatamente deve mover-se o número de espaços indicados. Após o uso deste item, rolar um 6 não concederá rolagens bônus nem permitirá a saída de peões.",
    "Game_Props_ItemTips_AssignDice": "Dados controlados: o jogador escolhe o número do rolagem. Uma rolagem bônus é garantida ao rolar 6, chutar um peão ou alcançar a meta.",
    "Game_Props_ItemTips_Protection": "Escudo: protege todos os peões contra chutes por 1 rodada.",
    "Game_gift_gift": "Enviar emoji",
    "Game_gift_giftprice": "100 moedas por emoji",
    "Game_gift_sendtoofast": "Vai com calma.",
    "Game_leaderboard_load_fail_tips": "Falha ao carregar os dados. Tente mais tarde.",
    "Game_classic_newusertips_moveout1": "Role um 6 para decolar!",
    "Game_classic_newusertips_mesafe": "Todas casas de estrela são seguras!",
    "Game_classic_newusesrtip_bumptoken": "Chute este peão!",
    "Game_Friend_JoinTips_Invalid_RoomCode": "Código da sala inválido. Verifique de novo.",
    "Lobby_unfinish_notice": "Esta função chegará em breve!",
    "shortCut_create_succ": "Atalho criado com sucesso.",
    "shortCut_create_fail": "Falha ao criar o atalho. Tente de novo.",
    "shortCut_bubble_tips": "Clique aqui para criar um atalho na tela inicial",
    "Tips_Longin_Fail": "Falho ao fazer login, tente mais tarde!",
    "Tips_Netword_Fail_TryReconnect": "Falha de conexão de rede. Reconectando.",
    "Tips_Netword_Fail_Reconnected": "Reconectado. Boas-vindas!",
    "Tips_Game__ThreeSixSkip": "Número seis por\n3 vezes seguidas, pula!",
    "Tips_Game_Props_UseTips_DoubleDice": "Distância Dupla! Rolagem dobrada!",
    "Tips_Game_Props_UseTips_AssignDice": "Dados controlados! Você rolou um",
    "Tips_Game_Props_UseTips_Protection": "Protege todos peões contra chutes por 1 rodada.",
    "Tips_Game_Props_UseTips_LuckyNumber": "Jogada Bônus, role de novo!",
    "Tips_Game_Props_UseFail_DoubleDice": "Sem peões para usar este item!",
    "Tips_Game_Props_UseFail_Protection": "Sem peões para proteger!",
    "Tips_Game_Props_OtherUseTips_DoubleDice": "Distância Dupla usada!",
    "Tips_Game_Props_OtherUseTips_AssignDice": "Dados controlados usados!",
    "Tips_Not_Whatsapp": "Este recurso requer a instação do WhatsApp.",
    "Tips_NetWork_Connection": "Conectando",
    "Tips_Game_TeamUp_HelpTeammate": "Prossiga para jogar por seu colega de equipe!",
    "task_load_fail_tips": "Falha ao carregar os dados. Tente mais tarde.",
    "Tips_Game_addFriendReq": "Pedido de amizade.",
    "Tips_Game_addFriendReq_accept": "Aceitar",
    "Tips_Game_addFriendReq_ignore": "Ignorar",
    "Tips_Friend_Req": "Pedido de amizade enviado",
    "Tips_Friend_AcceptSucc": "Você e {name} agora são amigos.",
    "Tips_Friend_AcceptFailed": "Falha ao aceitar, você pode aceitar o pedido de amizade mais tarde.",
    "Tips_Friend_IgnoreFailed": "Falha ao ignorar, você pode ignorar o pedido de amizade mais tarde.",
    "Tips_Friend_RemoveFriend": "Deseja mesmo excluir este amigo?",
    "Set_Panel_chatclosetips": "Você bloqueou todos os bate-papos.",
    "Tips_Send_Gift": "Toque aqui para enviar emojis.",
    "Tips_Send_This_Player_Gift": "Toque aqui para enviar emojis para este jogador.",
    "Tips_Profile_Add_Friends": "Toque no perfil para adicionar aos amigos.",
    "Tips_Here_Add_Friends_GamePage": "Toque aqui para adicionar aos amigos.",
    "Tips_Here_Add_Friends_GameOver": "Toque aqui para adicionar aos amigos.",
    "Tips_Send_Coin_friends": "Envie moedas grátis para amigos.",
    "Tips_Collect_By_Mail": "Colete moedas grátis de amigos por mensagem.",
    "Item_Use_Success": "Você usou {skin}.",
    "Kick_Player_No_Reward_Tips": "{name} está sem moedas e perdeu. Sem bônus desta vez.",
    "Common_Game_Mini_tips": "Ganhe {num} estrelas ao vencer！Chutar ou finalizar um peão concede uma estrela.",
    "Lobby_mini_tips": "Compacto&Intenso",
  },
  "Chat": {
    "Game_emoji": "Emoji",
    "Game_chat": "Bate-papo",
    "Game_chat_title": "Bate-papo rápido",
    "Game_chat_content1": "Olá!",
    "Game_chat_content2": "Jogue rápido!",
    "Game_chat_content3": "Nossa!",
    "Game_chat_content4": "Bem jogado",
    "Game_chat_content5": "Por quê?! Por quê?!",
    "Game_chat_content6": "Foi mal!",
    "Game_chat_tips": "Insira a mensagem",
    "Game_chat_send": "Enviar",
  },
  "DailyBonus": {
    "Lobby_Bonus_title": "Bônus diário",
    "Lobby_Bonus_detail": "Ganhe moedas grátis todo dia!",
    "Lobby_Bonus_collect": "Coletar",
    "Lobby_Bonus_collected_tips": "Volte amanhã para mais moedas.",
    "Lobby_Bonus_collect_failed": "Falha ao coletar, tente mais tarde.",
    "Lobby_Bonus_reqFailed": "Falha ao resgatar o bônus diário. Tente mais tarde.",
    "Lobby_Bonus_Day": "Dia {num}",
    "Lobby_Bonus_Day_1": ""
  },
  "Props_Guide": {
    "Game_Props_TopTitle_Great": "Ótimo",
    "Game_Props_TopTitle_LuckyNumber": "Número\n dourado",
    "Game_Props_ItemTips_DoubleDice": "Distância Dupla: dobra o número rolado. O jogador imediatamente deve mover-se o número de espaços indicados. Após o uso deste item, rolar um 6 não concederá rolagens bônus nem permitirá a saída de peões.",
    "Game_Props_ItemTips_AssignDice": "Dados controlados: o jogador escolhe o número do rolagem. Uma rolagem bônus é garantida ao rolar 6, chutar um peão ou alcançar a meta.",
    "Game_Props_ItemTips_Protection": "Escudo: protege todos os peões contra chutes por 1 rodada.",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Escolha um número",
    "Common_Game_Props_UserGuide_GoldenNo": "Este é o número dourado. Ao tirar o número, ganhe outra rolagem!",
    "Common_Game_Props_UserGuide_GoldenNo_content": "Ganhe uma rolagem extra ao chegar aqui.",
    "Common_Game_Props_UserGuide_continue": "Toque para continuar",
    "Common_Game_Props_UserGuide_begin_title": "Modo Poder",
    "Common_Game_Props_UserGuide_begin_content": "Oi, eu sou o Ludo World. Vou apresentar como se joga o Modo Poder!",
    "Common_Game_Props_UserGuide_roaditem": "Diferentes itens de poder são coletados no tabuleiro.",
    "Common_Game_Props_UserGuide_Items": "Estes são todos os itens de poder.",
    "Common_Game_Props_UserGuide_Dicecontrol_title": "Controle de Dados",
    "Common_Game_Props_UserGuide_Dicecontrol_content": "Você pode controlar os números desejados nos dados!",
    "Common_Game_Props_UserGuide_Dicecontrol_tips": "Rolou um 6! Ótimo início!",
    "Common_Game_Props_UserGuide_Doubledistance_title": "Distância Dupla",
    "Common_Game_Props_UserGuide_Doubledistance_content": "Dobra o número rolado. Percorra o dobro da distância!",
    "Common_Game_Props_UserGuide_GoldenNo_title": "Jogada Bônus",
    "Common_Game_Props_UserGuide_GoldenNo_tips": "Ganhe uma rolagem extra na chegada. Quem não gosta de uma jogada bônus?!",
    "Common_Game_Props_UserGuide_BumpProtection_title": "Escudo de Proteção",
    "Common_Game_Props_UserGuide_BumpProtection_content": "Proteja-se de outros peões espertinhos por 1 turno.",
    "Common_Game_Props_UserGuide_BumpProtection_effect": "Ótimo! Seu peão está protegido!",
    "Common_Game_Props_UserGuide_finish_title": "Você está pronto!",
    "Common_Game_Props_UserGuide_finish_content": "Agora que você já sabe tudo sobre itens, hora de uma partida real!",
    "Common_Game_Props_UserGuide_finish_botton": "Vamos lá!",
    "Common_Game_Props_GetUserGuide": "Primeira vez jogando o Modo Poder? Veja o nosso tutorial.",
  },
  "Feedback": {
    "Set_Feedbeck_Title": "Sugestões e opiniões",
    "Set_Feedbeck_Tips": "Obrigado pela sua mensagem e apoio!",
    "Set_Feedbeck_Submit": "Enviar",
    "Set_Feedbeck_Submit_Succeed": "Sua mensagem foi enviada com sucesso.",
    "Set_Feedbeck_Submit_No": "É preciso inserir a sua mensagem aqui.",
  },
  "TeamUp_Guide": {
    "Common_Game_teamup_UserGuide_begin_title": "Equipes",
    "Common_Game_teamup_UserGuide_begin_content": "Hora das equipes! Aqui estão as regras.",
    "Common_Game_teamup_UserGuide_teammate": "O jogador diagonal verde faz parte da sua equipe.",
    "Common_Game_teamup_UserGuide_competitor": "A equipe vermelha e amarela é a oposição.",
    "Common_Game_teamup_UserGuide_pawnstack": "Peões de mesma equipe podem sentar juntos.",
    "Common_Game_teamup_UserGuide_onefinish": "Ajuda um colega de equipe assim que todos os seus 4 peões entrarem na chegada.",
    "Common_Game_TeamUp_UserGuide_finish_title": "Parabéns!",
    "Common_Game_TeamUp_UserGuide_finish_content": "Você aprendeu a jogar o Modo Equipes. Hora de uma partida de verdade!",
  },
  "SharePresentLottery": {
    "Lobby_Lottery_Hint": "Assista um anúncio para ganhar um giro grátis",
    "Lobby_Lottery_Btn_Share": "Jogue para girar",
    "Lobby_Lottery_Btn_spin": "Girar",
    "Lobby_Lottery_Upper_Limit": "Volte amanhã para uma Roda da Fortuna!",
    "Lobby_Lottery_Close": "A roda está girando!",
  },
  "ShareText": {
    "TitleTurnplate": "Pronto para uma partida de Ludo? Vamos jogar juntos agora!",
    "TitlePropsShare": "É tão divertido jogar Ludo World! Vem jogar comigo!",
    "TitleOver": "Acabei de vencer no Ludo World. Vem jogar comigo!",
    "FriendRoomInviteText": "{name} está convidando você para jogar Ludo World, o código da sala é {RoomCode}.",
    "RankShareContent": "Venci {num} [partida|partidas] esta semana, vem me desafiar!",
    "Invite_gift_text1": "Oi, eu estou jogando Ludo World, vamos jogar juntos!",
    "Invite_gift_text2": "Quem é que domina esse jogo? Vem aceitar meu desafio!",
    "Invite_gift_text3": "Você poderá ganhar uma recompensa se seus amigos clicarem no link que você acabou de compartilhar.",
    "friend_invite_details": "Venha comigo em Ludo World. Código da sala: {Number} Clique para baixar ou entrar na sala.",
  },
  "LoginMainLabel": {
    "LoginMainLabel_Facebook": "Facebook",
    "LoginMainLabel_Google": "Google",
    "LoginMainLabel_Description": "Ao continuar eu concordo que Moon Active pode armazenar e processar meus dados de acordo com a Política de Privacidade.",
    "LoginMainLabel_Guest": "Convidado",
    "LoginMainLabel_Continue_Sure": "Tem certeza?",
    "LoginMainLabel_Continue_Express": "Convidados não podem jogar com amigos...",
    "LoginMainLabel_Continue_AsGuest": "Jogar como convidado",
    "LoginMainLabel_Continue_FbAward": "Convidados não podem jogar com amigos nem ganhar um bônus de {coins} moedas...",
    "LoginMainLabel_RewardPrompt": "{coins} moedas grátis!",
    "LoginMainLabel_Continue_Warning": "Ao selecionar \"Concordo\", confirmo que li e concordo com a POLÍTICA DE PRIVACIDADE e o CONTRATO DE USUÁRIO DA TENCENT GAMES",
    "LoginMainLabel_Continue": "<u><b>Continuar como convidado<u><b>",
    "LoginMainLabel_Select": "Selecionar o método de login",
    "FacebookConnect_Content1": "<b><color=#444987>Login com Facebook：</color></b>",
    "FacebookConnect_Content2": "<b><color=#444987>1.Jogue com amigos\n2.Salve o seu progresso\n3.Ganhe <color=#d16004>{num}<color=#444987> moedas grátis<b>",
    "FacebookConnect_Content3": "<u><b><color = #3f59b7 click=\"handler\">Login com Facebook</color></b></u>",
    "FacebookConnect_Content4": "<b><color=#444987>Login como convidado e<color=#d16004> não é possível <color=#d16004>",
  },
  "PropsPromtText": {
    "Game_classic_newusertips_dicecontrolmoveout": "Controle seus dados\n para decolar!",
    "Game_classic_newusertips_dicecontrolbump": "Controle os seus dados \npara chutar!",
    "Game_classic_newusertips_dicecontrolfinish": "Controle os seus dados para \nentrar na casa de chegada!",
    "Game_classic_newusertips_doubledistance": "Dobre a sua distância!",
    "Game_classic_newusertips_shild": "Proteja seus peões!",
    "Game_classic_newusertips_dicecontrolrun": "Controle seus dados para correr.",
    "Game_item_purchasetips": "Clique para ganhar itens",
  },
  "MailPanel": {
    "Mail_Title": "Mensagens",
    "Mail_firend": "Amigos",
    "Mail_system": "Sistema",
    "Mail_collect": "Coletar",
    "Mail_check": "Verificar",
    "Mail_collectAll": "Coletar tudo",
    "Mail_Firend_Preservation_tips": "Guarde 60 mensagens e guarde por 30 dias.",
    "Mail_System_Preservation_tips": "Guarde 60 mensagens e guarde por 30 dias.",
    "Mail_NoMail_tips": "Não há mais mensagens.",
    "MailInfo_Title": "Detalhes",
    "MailInfo_firend_Gift": "deu de Presente",
    "Mail_firend_Get_limit": "Você já resgatou presentes de {num} amigos hoje. Volte amanhã para resgatar mais.",
    "MailInfo_get_Failure": "Falha ao resgatar as recompensas. Tente mais tarde.",
    "Mail_delete_Failure": "Falha ao excluir. Tente mais tarde.",
    "MailInfo_delete": "Excluir",
  },
  "PrivacyPolicy": {
    "PrivacyPolicy_join1": "Eu li e aceitei a",
    "PrivacyPolicy_join2": "POLÍTICA DE PRIVACIDADE",
    "PrivacyPolicy_join3": "e",
    "PrivacyPolicy_join4": "CONTRATO DE USUÁRIO",
    "SelectNone": "Ao selecionar Concordo, eu confirmo que li e concordo com a POLÍTICA DE PRIVACIDADE e o CONTRATO DE USUÁRIO",
  },
  "HelpText": {
    "Game_classic_userguide_tokens": "Peões: existem 4 tipos de peões, cada um de um lado.",
    "Game_classic_userguide_startpoint": "Posição inicial: esta é a posição do começo.",
    "Game_classic_userguide_finishline": "Casa de chegada: os peões precisam dar a volta no tabuleiro antes de entrar na casa de chegada.",
    "Game_classic_userguide_safeplace": "Casas seguras: as 8 posições do pentagrama são casas seguras, onde os peões não podem ser chutados.",
    "Game_classic_userguide_dice": "Dados: cada uma das seis faces tem uma contagem diferente de pontos de 1 a 6.",
    "Game_classic_userguide_firsthand": "Regra de prioridade: aleatório primeiro, depois prossegue em sentido horário.",
    "Game_classic_userguide_moveout": "Saída: um peão só pode sair se o jogador rolar um 6.",
    "Game_classic_userguide_move": "Movimento: após rolar os dados, selecione um peão no caminho e mova o número correspondente de pontos.",
    "Game_classic_userguide_automove": "Automático: Peões movem-se automaticamente caso não haja outro como opção.",
    "Game_classic_userguide_sixbonus": "Bônus do 6: um jogador ganha outra rolagem ao rolar um 6. Se um jogador conseguir 3 vezes seguidas o número 6, seu terceiro turno será pulado.",
    "Game_classic_userguide_bumpbonus": "Bônus de chute: um jogador ganha outra rolagem ao chutar um peão.",
    "Game_classic_userguide_finishbonus": "Bônus de chegada: um jogador ganha outra rolagem após entrar na casa de chegada com um peão.",
    "Game_classic_userguide_bump": "Chute: se um peão terminar o movimento na mesma casa de outro e não for um espaço seguro, ele vai chutar o outro peão de volta para a posição inicial. Mas se dois peões de mesma cor estiverem juntos, eles são imunes ao chute.",
    "Game_classic_userguide_finish": "Peões podem entrar na casa de chegada se o resultado dos dados for igual à distância. Se o número for maior, o peão não se move.",
    "Game_classic_userguide_winner": "Vencedor: o jogador que colocar primeiro todos os 4 peões na casa de chegada vence. Em partidas de 4 jogadores, tanto o 1º quanto o 2º jogador são vencedores.",
    "Game_classic_userguide_time": "Tempo: 10s para rolar, 10s para mover.",
    "Game_classic_userguide_autohosted": "Automático: caso sua conexão caia ou seu tempo acabe, o computador vai jogar por você. Clique para recuperar o controle.",
    "Set_Help_newuser_powermode_begin": "No Modo Clássico, adicione os seguintes itens para deixar o jogo mais interessante!",
    "Set_Help_newuser_powermode_step1": "Distância Dupla: percorre o dobro da distância obtida nos dados. Avance no dobro do ritmo! \nMas lembre-se: rolar um 6 e sair com um peão não estarão disponíveis ao usar a Distância Dupla.",
    "Set_Help_newuser_powermode_step2": "Controle de Dados: selecione o número desejado nos dados.",
    "Set_Help_newuser_powermode_step3": "Escudo de Proteção: proteja-se de outros peões por 1 turno.",
    "Set_Help_newuser_powermode_step4": "Jogada Bônus: ganhe uma rolagem extra na chegada.",
    "Set_Panel_Help_teamup_1": "Regra 1: você e o jogador diagonal formam uma equipe (Azul e Verde x Vermelho e Amarelo)",
    "Set_Panel_Help_teamup_2": "Regra 2: quando os peões da sua equipe estiverem juntos, os peões adversários não podem se unir para chutá-los.",
    "Set_Panel_Help_teamup_3": "Regra 3: os peões da equipe não serão chutados ao quebrar.",
    "Set_Panel_Help_teamup_4": "Regra 4: após seus 4 peões entrarem na chegada, você pode usar os seus dados para mover os peões do seu colega de equipe.",
    "Set_Panel_Help_teamup_5": "Regra 5: sua equipe precisa mover todos os 8 peões para dentro da chegada primeiro para vencer.",
  },
  "PropGuidePanel": {
    "PropGuidePanel_TitleText": "Modo Poder!",
    "PropGuidePanel_ContentText": "Venha experimentar \nnosso modo de Ludo exclusivo!",
    "PropGuidePanel_PlayBntText": "Iniciar",
    "PropGuidePanel_AwardHint": "moedas grátis",
    "NewHandGuide_AwardHint": "Você concluiu o tutorial do Modo Poder!",
    "NewHandGuide_Get_Failure": "Falha ao conectar, tente mais tarde.",
    "PropGuideTipsOpenText": "Dicas de itens abertas",
    "PropGuideTipsCloseText": "Dicas de itens fechadas",
  },
  "GameGuide": {
    "GameGuideText1": "Boas-vindas!",
    "GameGuideText2": "Vamos jogar on-line com outros jogadores!",
  },
  "GameGuideText": {
    "GameGuideTitle": "Selecione o modo",
    "GameGuideContent": "Conhece Ludo? Experimente",
    "GameGuideClassicModeContent": "Clássico",
    "GameGuidePowerModeContent": "Sênior",
    "GameGuidePowerMode": "Poder",
    "GameGuidePlay": "vamos jogar!",
    "GameGuideClassicMode": "Clássico",
    "GameGuideInnovative": "Inovador",
  },
  "GameTxpText": {
    "GameNoGetExp": "Sem chutes ou casa de chegada, você não recebe experiência.",
    "CloseTips": "Toque para fechar",
    "ShareLevelTips": "É tão legal jogar Ludo World! Vem comigo!",
  },
  "AssessPanelText": {
    "Rate_title": "Gostou do nosso jogo?",
    "Rate_content": "Se gostou, deixe uma nota!",
    "Rate_Button": "Avaliar",
    "Rate_Button2": "Agora não",
    "ShareGame_exp_fail": "Falha ao obter EXP, tente mais tarde.",
    "ShareGame_exp_Exceed": "Você ganhou EXP demais hoje, volte amanhã.",
  },
  "TaskPanel": {
    "Task_Title": "Missão",
    "Task_Daily": "Missão diária",
    "Task_Growth": "Missão de avanço",
    "Task_collect": "Coletar",
    "Task_Play": "Ir",
    "Task_Playing": "Em processo",
    "Task_get_award_failed": "Falha ao conectar, tente mais tarde.",
    "Task_Tips": "A missão diária atualiza às 24:00",
    "Task_Timeout": "Falha ao coletar, o tempo da missão acabou.",
    "Task_Coins": "moedas",
  },
  "TaskName": {
    "task_0": "Login",
    "task_1": "Envie presentes para outros\njogadores 5 vezes no\nModo On-line",
    "task_2": "Envie moedas para amigos\n5 vezes na lista\n de amigos.",
    "task_3": "Chute 5 vezes no\nModo Amigos",
    "task_4": "Entre com peões na\ncasa de chegada 3 vezes\nno Modo Amigos",
    "task_5": "Vença 1 partida\nno Modo\nClássico Amigos",
    "task_6": "Vença 1 partida no\nModo Poder Amigos",
    "task_7": "Vença 1 partida no\nModo Amigos",
    "task_8": "Vença 5 partidas\nno Modo Clássico\nOn-line de 2J",
    "task_9": "Vença 3 partidas\nno Modo Clássico\nOn-line de 4J",
    "task_10": "Vença 3 partidas\nno Modo Clássico\nOn-line 2x2",
    "task_11": "Vença 5 partidas\nno Modo Poder\nOn-line de 2J",
    "task_12": "Vença 3 partidas\nno Modo Poder\nOn-line de 4J",
    "task_13": "Vença 3 partidas\nno Modo Poder\nOn-line 2x2",
    "task_14": "Vença 5 partidas\nno Modo On-line",
    "task_15": "Use Distância Dupla\n10 vezes no Modo-\nPoder On-line",
    "task_16": "Use Controle de Dados\n10 vezes no\nModo Poder On-line",
    "task_17": "Use Escudo de Proteção\n10 vezes no\nModo Poder On-line",
    "task_18": "Chute 5 vezes no\nModo On-line",
    "task_19": "Entre com peões na\ncasa de chegada 3 vezes\nno Modo On-line",
    "task_20": "",
    "task_21": "Suba até o nível %{num}",
    "task_22": "Faça login por um total de %{num} dias",
    "task_23": "Vença %{num} partidas\nno Modo On-line",
    "task_24": "Vença %{num} partidas\nno Modo Computador",
    "task_25": "Chute %{num} vezes no\nModo On-line",
  },
  "TeamUp2V2": {
    "Common_Choose_Number_Team": "Formar equipe",
    "Common_Choose_Number_2v2_titlepower": "Poder 2x2",
    "Common_Choose_Number_2v2_titleclassic": "Clássico 2x2",
    "Teamup_choose_tips1": "Convide um amigo ou busque uma partida",
    "Teamup_choose_tips2": "Já pode começar",
    "Teamup_choose_betchange_title": "Aposta alterada",
    "Teamup_choose_betchange_content": "Aposta alterada para {coins} porque o seu amigo não possui moedas suficientes.",
    "Teamup_choose_join_leave_title": "Deixar a partida?",
    "Teamup_choose_join_leave_content": "Sua equipe será desfeita. Deseja sair mesmo assim?",
    "Teamup_Matching_leave_content": "Partida encontrada, não é possível sair.",
    "Teamup_Game_inviting": "{name} está convidando você para uma equipe no modo On-line 2x2.",
  },
  "Region": {
    "Disgree_Content": "Infelizmente, não podemos oferecer o Ludo World para você no momento. Nossos dados são armazenados fora do EEE e nossas equipes de suporte necessariamente acessam esses dados de outras jurisdições para lhe fornecer o serviço.",
    "Back": "Voltar",
    "Data_Agreement_Content_APK": "Ludo World é um produto oferecido pela Proxima Beta PTE.Limited, uma empresa da República de Singapura que processará seus dados fora do Espaço Econômico Europeu (incluindo na República Popular da China) para fornecer o serviço. Observe que há riscos em tal transferência, incluindo seus dados estarem sujeitos a diferentes regimes legais que podem não oferecer a eles o mesmo nível de proteção disponível no país no qual você está. Para mais informações, consulte nossa <b><u><i click=\"handler\">Política de Privacidade</i></u></b>. Ao clicar em \"Concordo\" abaixo, você concorda com a transferência de seus dados para fora do Espaço Econômico Europeu.",
    "Data_Agreement_Content_FB": "Ludo World é um produto oferecido pela High Morale Development Limited, uma empresa de Hong Kong que processará seus dados fora do Espaço Econômico Europeu (incluindo na República Popular da China) para fornecer o serviço. Observe que há riscos em tal transferência, incluindo seus dados estarem sujeitos a diferentes regimes legais que podem não oferecer a eles o mesmo nível de proteção disponível no país no qual você está. Para mais informações, consulte nossa <b><u><i click=\"handler\">Política de Privacidade</i></u></b>. Ao clicar em \"Concordo\" abaixo, você concorda com a transferência de seus dados para fora do Espaço Econômico Europeu.",
    "Agree": "Concordo",
    "Disagree": "Não concordo",
    "Under_Age_Content": "Como você tem menos de {age} anos, infelizmente não podemos fornecer o serviço Ludo World no momento.",
    "Data_Outside_Content": "Você concorda em transferir seus dados para fora do Espaço Econômico Europeu?",
    "Data_Outside_Title": "Transferência de dados fora do EEE",
    "Delete_Notice_Title": "Aviso",
    "Delete_Notice_Content": "Infelizmente, não podemos oferecer o Ludo World para você no momento. Nossos dados são armazenados fora do EEE e nossas equipes de suporte necessariamente acessam esses dados de outras jurisdições para lhe fornecer o serviço. Clique \"Voltar\" para reconsiderar ou clique \"Excluir conta \" para exclusão.",
    "Delete_Account": "Excluir conta",
    "Delete_Delete": "Excluir",
    "Delete_Content": "Deseja excluir sua conta? O sistema excluirá automaticamente sua conta e dados após 7 dias. Você pode cancelar a exclusão ao fazer login de novo no jogo dentro de 7 dias.",
    "Chat_Off_Title": "Ativar o bate-papo?",
    "Chat_Off_Content": "Com o bate-papo ativo, outros jogadores poderão ver suas conversas. O bate-papo pode ser desativado nas opções.",
    "Region_Title": "Região",
    "Region_Content": "Selecione a região/país de \nsua localização principal.",
    "Agree_Title": "Data de nascimento",
    "Agree_Content": "Para que possamos otimizar sua experiência, informe-nos se você tem pelo menos {age} anos de idade.",
    "Privacy_Title": "Política de Privacidade",
    "Privacy_Content": "Ao selecionar \"Concordo\" abaixo, confirmo que\nli e concordo com a\n<b><u><color = #535BBF click=\"handler\">Política de Privacidade</color></u></b> do Ludo World.",
    "Privacy_Disagree": "Infelizmente, sem o seu consentimento com a Política de Privacidade, não podemos oferecer os serviços do Ludo World no momento.",
    "Agreement_Title": "Contrato de Licença do Usuário Final",
    "Agreement_Content": "Ao selecionar \"Concordo\" abaixo, confirmo que\nli e concordo com o\n<b><u><color = #535BBF click=\"handler\">Contrato de Licença do Usuário Final</color></u></b> do Ludo World.",
    "Agreement_Disagree": "Infelizmente, sem o seu consentimento com o Contrato de Licença do Usuário Final, não podemos oferecer os serviços do Ludo World no momento.",
    "YES": "Sim",
    "NO": "NÃO",
  },
  "FriendSystem": {
    "Friend_Main_title": "Amigos",
    "Friend_Main_list": "Lista",
    "Friend_Main_add": "Adicionar",
    "Friend_Main_request": "Pedido",
    "Friend_Main_list_FB": "Amigos do FB",
    "Friend_Main_list_Game": "Amigos de jogo",
    "Friend_Main_list_reciveandsend": "Enviar a todos",
    "Friend_Main_list_reciveandsend_Detail": "As moedas enviadas a amigos não são deduzidas do seu saldo",
    "Friend_Main_Add_Recent": "Recente",
    "Friend_Select_Tip_NewRequest": "{num} [Pedido de amizade|Pedidos de amizade]",
    "Friend_Main_Request_Num_Tip": "Guardar apenas os últimos 99 pedidos.",
    "Friend_list_nofbfirends": "Sem amigos do Facebook que jogam,\nchame-os para participar!",
    "Friend_list_invitefirends": "Vamos jogar Ludo World juntos agora!",
    "Friend_list_nogamefirends": "Nenhum amigo no jogo ainda,\nadicione alguns na aba Adicionar!",
    "Friend_Add_NoRecent": "Sem jogadores recentes",
    "Friend_Request_NoRequest": "Sem pedidos de amizade",
    "Friend_list_online": "On-line",
    "Friend_list_offline": "Off-line",
    "Friend_list_playing": "Jogando",
    "Friend_Not_Accept": "Não aceitar mais pedidos de amizade.",
    "Friend_sendcoins_succeed": "Enviar 100 moedas para {name}",
    "Friend_sendcoins_fail": "Você enviou o máximo de presentes de hoje.",
    "Friend_collectandsendall_succeed": "Enviar  {num} moedas",
    "Friend_collectandsendall_nofirendtosend": "Nenhum amigo para enviar",
    "Friend_invite_title": "Convite",
    "Friend_invite_bottoningame": "Em jogo",
    "Friend_invite_whoinvite": "{name} convidou você para jogar!",
    "Friend_invite_reject": "Recusar",
    "Friend_invite_accept": "Aceitar",
    "Friend_invite_friendpower": "Poder Amigos",
    "Friend_invite_friendclassic": "Clássico Amigos",
    "Friend_invite_teamuppower": "Poder Amigos 2x2",
    "Friend_invite_teamupclassic": "Clássico Amigos 2x2",
    "Friend_invite_sentsucceed": "Convite enviado",
    "Friend_invite_sentfail": "Falha de convite",
    "Friend_invite_more_btn": "Convidar mais:",
    "Friend_collectcoins_fail": "Você já coletou moedas de {num} amigos hoje. Volte amanhã para coletar mais.",
    "Friend_collectall_succeed": "Colete {coins} moedas de amigos!",
    "Friend_Add_Recent_Source1": "Clássico On-line 2J",
    "Friend_Add_Recent_Source2": "Clássico On-line 4J",
    "Friend_Add_Recent_Source3": "Poder On-line 2J",
    "Friend_Add_Recent_Source4": "Poder On-line 4J",
    "Friend_Add_Recent_Source5": "Clássico On-line 2x2",
    "Friend_Add_Recent_Source6": "Poder On-line 2x2",
    "Friend_Add_Recent_Source7": "Clássico Amigos",
    "Friend_Add_Recent_Source8": "Poder Amigos",
    "Friend_Add_Recent_Source9": "Clássico Amigos 2x2",
    "Friend_Add_Recent_Source10": "Poder Amigos 2x2",
    "Friend_Request_Source_Recent": "Jogo recente",
    "Friend_Request_Source_Suggested": "Sugerido",
    "Friend_Request_Source_Leaderboard": "Placar de líderes",
    "Friend_gametime-year": "{num} a atrás",
    "Friend_gametime-day": "{num} d atrás",
    "Friend_gametime-hour": "{num} h atrás",
    "Friend_gametime-minitue": "{num} min atrás",

  },
  "APPAdsText": {
    "ItemsAddOne": "Itens+1",
  },
  "Common": {
    "Lobby_Bonus_collecet": "Coletar",
    "Common_Game_teamup_UserGuide_finish_title": "Muito bom!",
    "Game_friends_invite_start": "Já pode começar.",
    "": "",
    "Title_ModifyInfo": "Modificar informações",
    "shortCut_create_success": "Atalho criado com sucesso.",
    "MainScenes_Ranking": "Posição",
    "MainScenes_FreeCoins": "Moedas grátis",
    "MainScenes_Mission": "Missão",
    "Settings_on": "Lig.",
    "Settings_off": "Desl.",
    "Game_EndOrder_Congratulations": "Parabéns",
    "EM_ERR_FETCH_FRIEND_FAIL = -10002": "Falha ao carregar os dados. Tente mais tarde.",
    "EM_ERR_FETCH_ONLINE_FAIL = -10003": "Falha ao carregar os dados. Tente mais tarde.",
    "EM_ERR_FETCH_LOGIN_TIME_FAIL = -10004": "Falha ao carregar os dados. Tente mais tarde.",
    "EM_ERR_NOT_ADD_PLAYER = -10005": "Falha de processamento, tente mais tarde.",
    "EM_ERR_FRIEND_LIST_FULL = -10006": "Você atingiu o número limite de amigos. Caso precise adicionar amigos, exclua outros amigos.",
    "EM_ERR_PEER_FRIEND_LIST_FULL = -10007": "Não é possível adicionar {name} pois o número de amigos desta pessoa atingiu o limite.",
    "EM_ERR_UPDATE_FRIEND_FAIL = -10008": "Falha ao carregar os dados. Tente mais tarde.",
    "EM_ERR_PLAYER_REFUSE_ADD = -10009": "{name} não está aceitando pedidos de amizade.",
    "EM_ERR_ALREADY_IN_ADD_LIST = -10010": "",
    "EM_ERR_ALREADY_IN_GAME_FRIEND_LIST = -10011": "Vocês já são amigos.",
    "EM_ERR_ALREADY_IN_PLAT_FRIEND_LIST = -10012": "Vocês já são amigos.",
    "EM_ERR_NOT_IN_FRIEND_LIST = -10013, //": "Falhar de processamento, tente mais tarde.",
    "EM_ERR_FETCH_GAME_RECORD_FAIL = -10014": "Falha ao carregar os dados. Tente mais tarde.",
    "EM_ERR_CANNOT_ADD_SELF = -10015": "Falha ao adicionar, tente mais tarde.",
    "LoginMainLabel_Guest_Title": "Entrou como convidado e não pode",
    "Language_type": "Português",
  },
  "GoodsName": {
    "GoodsName_Cricket": "Grilo",
    "GoodsName_Jewelry": "Joias",
    "GoodsName_Airdrop_box": "Entrega",
    "GoodsName_Cupid": "Cupido",
    "GoodsName_Cat": "Gato",
    "GoodsName_Planet": "Planeta",
    "GoodsName_Default": "Padrão",
    "Shop_luckybox": "Caixa da sorte",
    "Shop_luckybox_GiftCardtitle": "Cartão de presentes",
    "Shop_luckybox_GiftCard": "Encontre o cartão de presentes no correio do jogo.",
    "GoodsName_Item_Cards": "Cartas de itens",
    "GoodsName_Item_Cards_num": "Cartas de itens x{num}",
    "GoodsName_Neon": "Néon",
    "GoodsName_Chick": "Frango",
    "GoodsName_First_AidKit": "Kit de primeiros socorros",
    "GoodsName_Machinery": "Maquinário",
    "GoodsName_Diwali": "Diwali",
    "GoodsName_Christmas": "Natal",
    "GoodsName_Gems": "Gemas",
  },
  "AdsText": {
    "Btn_Lucky_Show_Ad": "Assistir anúncio",
    "Lab_Lucky_Next": "Próx. recompensa:",
    "Lab_Lucky_Declare": "Assista anúncios para ganhar giros grátis todo dia!",
    "Btn_Double_Reward": "Bônus duplo",
    "Btn_Reward_x2": "Obter 2x!",
    "Btn_No_Thanks": "Não, obrigado",
    "Ad_Confirm_Cions": "Assista anúncios para ganhar {num} moedas.",
    "Ad_Confirm_Item": "Assista anúncios para ganhar um de cada item.",
    "Ad_Confirm_Task": "Assista anúncios para avançar nas missões.",
    "Ad_Confirm_Spin": "Assista anúncios para ganhar {spin}.",
  },
  "NewUserText": {
    "NewPlayerBonus_Title": "Bônus de jogador novo",
    "NewPlayerBonus_Day": "Dia",
    "NewPlayerBonus_Collect": "Coletar",
    "NewPlayerBonus_Collected": "Coletado",
    "NewPlayerBonus_LoginTips": "Você está conectado há {num} [dia|dias] ~",
    "NewPlayerBonus_EventTime": "Duração do evento:",
    "NewPlayerBonus_Coins": "Moedas",
    "NewPlayerBonus_Skins": "Visual",

  },
  "Shop": {
    "Shop_Tab_Coins": "Moedas",
    "Shop_Tab_Spin": "Visual",
    "Shop_Tab_Items": "Itens",
    "Shop_Tab_Spin_BubbleTab": "Bolha",
    "Shop_Tab_Spin_DiceTab": "Dados",
    "Shop_Tab_Spin_ThemeTab": "Tema",
    "Shop_Airdrop_box": "Entrega",
    "Shop_Coins": "{num}",
    "Shop_Airdrop_box_day": "Entrega ({num} d)",
    "Shop_Cricket": "Grilo",
    "Shop_Cricket_day": "Grilo ({num} d)",
    "Shop_Cupid": "Cupido",
    "Shop_Cupid_day": "Cupido ({num} d)",
    "Shop_Jewelry": "Joias",
    "Shop_Jewelry_day": "Joias ({num} d)",
    "Shop_Cat": "Gato",
    "Shop_Cat_day": "Gato ({num} d)",
    "Shop_Planet": "Planeta",
    "Shop_Planet_day": "Planeta ({num} d)",
    "Shop_Neon": "Néon",
    "Shop_Neon_day": "Néon ({num} d)",
    "Shop_Chick": "Frango",
    "Shop_Chick_day": "Frango ({num}d)",
    "Shop_First_AidKit": "Kit de primeiros socorros",
    "Shop_First_AidKit_day": "Kit de primeiros socorros ({num} d)",
    "Shop_Machinery": "Maquinário",
    "Shop_Machinery_day": "Maquinário ({num} d)",
    "Shop_Diwali": "Diwali",
    "Shop_Diwali_day": "Diwali ({num} d)",
    "Shop_Christmas": "Natal",
    "Shop_Christmas_day": "Natal ({num} d)",
    "Shop_Item": "Cartas de itens ({num} d)",
    "Shop_Label_New": "Novo",
    "Shop_Label_Hot": "Boa",
    "Shop_Label_Off": "Off",
    "Shop_Label_Extar": "Extra",
    "Shop_Label_BestDeal": "Melhor oferta",
    "Shop_Day_day": "dia",
    "Shop_Buy_Success": "Compra com sucesso, você usou {spin}.",
    "Shop_Backpack_Tip": "Use o seus itens na mochila.",
    "Button_Reload": "Recarregar",
    "Button_AD_Free": "Grátis",
    "Shop_Lucky": "Sorte",
    "Shop_BuyGift_Success": "Compra com sucesso, use na sua mochila.",
    "Shop_Airdrop_box_Permanent": "Entrega (Permanente)",
    "Shop_Cricket_Permanent": "Grilo (Permanente)",
    "Shop_Cupid_Permanent": "Cupido (Permanente)",
    "Shop_Jewelry_Permanent": "Joias (Permanente)",
    "Shop_Cat_Permanent": "Gato (Permanente)",
    "Shop_Planet_Permanent": "Planeta (Permanente)",
    "Shop_Neon_Permanent": "Néon (Permanente)",
    "Shop_Chick_Permanent": "Frango (Permanente)",
    "Shop_First_ AidKit_Permanent": "Primeiros socorros (Permanente)",
    "Shop_Machinery_Permanent": "Maquinário (Permanente)",
    "Shop_Diwali_Permanent": "Diwali (Permanente)",
    "Shop_Lucky_Detail": "Grilo (1 d), Joia (1 d), Planeta (1 d)",
    "Shop_WatchTV_Detail": "Assista a anúncios para ganhar um item.",
    "Shop_Buy_Fail": "Falhar ao comprar, tente mais tarde.",
    "Shop_Buy_ItemFail": "Falhar ao enviar item. Verifique mais tarde.",
    "Shop_Buy_Success_Prop": "Compra com sucesso.",
    "Shop_Buy_Prop_Describe": "Cartas de itens podem ser trocadas por itens.",
    "Shop_itemcard": "Cartas de itens",
    "Shop_itemcard_number": "{num} [carta|cartas]",
    "Shop_Tab_Name": "Loja",
  },
  "ReportText": {
    "Report_Panel": "Denúncia",
    "Report_Title": "Denunciar",
    "Report_People": "Denunciar {name}",
    "Report_Content1": "Abuso verbal",
    "Report_Content2": "Trapaça",
    "Report_Content3": "Outros",
    "Report_Success": "Denunciado",
    "Report_Res_Title": "Resultado",
    "Report_Res_Content": "{name}, o jogador que você denunciou, foi silenciado/suspenso.",
  },
  "RetainUser": {
    "newsuserA_classic_tips": "Experimente o Modo Poder, é mais engraçado!",
    "newsuserA_power_tips": "Experimentar o Modo Clássico? É mais fácil!",
    "newsuserA_tips_quit": "Sair",
    "newsuserA_tips_try": "Experimente",
    "newsuserB_tips_stay": "Conclua {num1} jogos ({num2}/{num3}) para ganhar a caixa verde.",
    "newsuserB_tips_minitips": "Sorteie um vale-presente da Amazon de ₹100 ou moedas！",
    "newsuserB_tips_getluckybox_title": "Caixa verde",
    "newsuserB_tips_getluckybox_content": "Sorteie um vale-presente da Amazon de ₹100 ou \nmoedas！Veja na sua mochila!",
    "newsuserB_tips_getluckybox_tips": "Sorteie um vale-presente da Amazon de ₹100 ou moedas！",
    "newsuserB_tips_getluckybox_cannotopen": "Abra depois de {num}",
    "newsuserB_tips_getluckybox_openfail": "Falhar ao abrir, tente mais tarde.",
    "newsuserB_tips_getluckyboxopen": "Abra uma caixa da sorte para sortear um \nvale-presente da Amazon de ₹100 ou moedas!",
    "newsuserA_tips_stay": "Ficar",
    "newsuserA_tips_leave": "Sair?",
    "newsuserA_tips_open": "Abrir",
  },
  "MainChat": {
    "Button_Team_SendTeamRecruitment": "Enviar convite de equipe",
    "Chat_World_NoChatTypeTips": "[Tipo de mensagem sem suporte.]",
    "Chat_World_EmptyTips": "É preciso inserir uma mensagem.",
    "Chat_NoMessage_Tips": "Clique aqui para conversar",
    "Chat_Tab_World": "Global",
    "Chat_Tab_Team": "Equipe",
    "Chat_Tab_Friends": "Amigos",
    "Chat_World_DefaltTips": "Insira mensagem",
    "Button_Chat_Send": "Enviar",
    "Chat_Team_Send_WorldChat": "Enviar para o bate-papo global",
    "Chat_Team_Join": "Entrar",
    "Chat_Local_Tips": "Apenas bate-papo local",
    "Chat_Friends_NewMessageTips": "Mensagem nova",
    "Chat_Friends_ClickTips": "Selecione um amigo para conversar.",
    "Chat_Friends_NoFriendsTips": "Você precisa de amigos.",
    "Chat_World_LocalTips": "Selecione para entrar no bate-papo local",
    "Chat_Low_Level": "Jogue mais partidas para chegar no nível {num} e conversar!",
    "Chat_World_JoinTips": "Você entrou no bate-papo global",
    "Chat_Local_JoinTips": "Você entrou no bate-papo local",
    "Chat_Close_Tips": "Ativar o bate-papo?",
    "Tips_Team_SendSuccess": "Convite de equipe enviado ao bate-papo global.",
    "Chat_SendTooFast": "Você está mandando mensagens rápido demais. Tente novamente mais tarde.",
  },
  "RedEnvelope": {
    "HB_Bag_Title": "Bolsa da sorte",
    "HB_Coins_Tips": "{num1} a {num2} moedas",
    "HB_Coins_Tipstop": "{num1} moedas",
    "HB_Image_Text": "Compartilhe sua sorte e abra a Bolsa da sorte.",
    "HB_Open_Require": "Convide seus amigos para abrirem juntos!",
    "HB_Open_Tips": "Quanto mais amigos participarem, mais moedas você ganha!",
    "HB_NoOpen_Tips1": "Aguardando seus amigos participarem pelo link.",
    "HB_NoOpen_Tips2": "Quando um amigo participa pelo link, você pode abrir a Bolsa da sorte.",
    "HB_Join_One": "Quanto mais amigos participarem, mais moedas você ganha!",
    "HB_Join_More": "Quanto mais amigos participarem, mais moedas você ganha!",
    "HB_Can_Open_Tips": "Abra a Bolsa da sorte hoje",
    "HB_Share_Title1": "Ganhe moedas no Ludo World! Abra a Bolsa da sorte para obter suas recompensas.",
    "HB_Share_Title2": "Aqui está sua Bolsa da sorte do Ludo World. Abra-a e tente a sorte!",
    "HB_Btn_Open": "Abrir",
    "HB_Btn_Open_noinvite": "Convidar",
    "HB_Collect_Fail": "Ops! Não há mais moedas.",
  },
  "LuckyBag": {
    "Clearing_Win_Share_Title": "Caixa secreta",
    "Clearing_Win_Share_Content": "Convide amigos para coletarem juntos",
    "Clearing_Loser_Share_Title": "Moedas grátis",
    "Clearing_Loser_Share_Content": "Convide amigos para coletarem juntos",
    "Clearing_Win_Ads_Title": "Caixa secreta",
    "Clearing_Win_Ads_Content": "Assista a um anúncio para ganhar",
    "Clearing_Loser_Ads_Title": "Moedas grátis",
    "Clearing_Loser_Ads_Content": "Assista a um anúncio para ganhar",
    "Clearing_Welfare_Share_Title": "Convide amigos para coletar",
    "Clearing_Share_Finish": "Toque no link que você acabou de compartilhar em até {num} segundos para obter sua recompensa!",
    "Clearing_Welfare_Ads_Title": "Precisa de mais moedas?",
    "Clearing_Welfare_Ads_Content": "Assista a um anúncio para ganhar",
    "Clearing_Share_Loser": "O link compartilhado é inválido. Reenvie o link compartilhado.",
  },
  "LuckSeven": {
    "Un_Lock_tips": "São necessários {num1} lançamentos a mais para desbloquear mais!",
    "Not_Enough_Gold": "Moedas insuficientes",
    "High_Laid": "A marcha mais alta foi atingida!",
    "Low_Laid": "A marcha mais baixa foi atingida!",
    "Show_FreeBet": "Aposte gratuitamente {num2} vezes!",
    "Coins": "MOEDAS",
    "laid_start_To_end": "{start} A {end}",
    "WIN": "VITÓRIA",
    "Get_Free_Bet": "Obtenha apostas gratuitas!",
    "Double": "Dobro de {point}",
    "Error": "Erro de dados. Recarregue a página",
  },
  "EliminatGame": {
    "Select_Hint": "Selecione a quantidade de moedas que deseja apostar",
    "Not_Coins": "Moedas insuficientes. Obter mais na loja?",
    "Min_Coins": "Você atingiu a quantidade mínima de moedas",
    "Max_Coins": "Você atingiu a quantidade máxima de moedas",
    "Win": "VITÓRIA",
    "Big_Win": "Grande vitória",
    "Super_Winner": "Supercampeão",
    "Total_Win": "Vitória total",
    "Fish_Party": "Disputa dos Peixes",
    "Quit_Hint": "Você está em uma partida. Sair mesmo assim?",
    "AllIn": "Aposta máxima",
    "Auto": "automático",
    "Start": "Iniciar",
    "EliminatGameTitle": "Instruções do jogo",
    "Game_Rules": "Regras do jogo",
    "Explain": "Instruções da Disputa dos Peixes",
    "Party_Text": "Três peixes idênticos competem na mesma faixa, um ao lado do outro. Se um for eliminado, você ganhará recompensas.\n\nApós a eliminação, o jogo continuará adicionando peixes até que nenhum outro possa ser eliminado.",
    "Select_Fish": "Selecione um peixe para apostar",
    "Eliminate_Award": "Elimine os outros e ganhe moedas!",
    "Records": "Confira recompensas e recordes",
    "Settlement_Rules": "Regras de pagamento",
    "Settlement_Rules_Text": "Três peixes idênticos competem na mesma faixa, um ao lado do outro. Se um for eliminado, você ganhará recompensas.\nA recompensa é calculada com base em cada peixe.\nO tipo de peixe e o número de eliminações afetarão a recompensa.\nOs ganhos são multiplicados com base no seguinte multiplicador.\nQuanto mais peixes forem eliminados da pista, mais recompensas você ganhará!",
    "Back_Game": "Voltar ao jogo",
    "Game_Name": "Disputa dos Peixes",
    "Activity_Ended": "A atividade terminou.",
  },
  "NewDiBao": {
    "NewDiBaoTitle": "PACOTE DA SORTE",
    "Tip": "Obtenha as moedas da sorte de hoje",
    "mulit": "Coletar",
    "extra": "EXTRA",
    "basic": "BÁSICO",
    "coins": "MOEDAS",
    "togle": "Assista a um anúncio e obtenha {num} moedas!",
    "Before_Game_GoldEnough": "Você não tem moedas suficientes",
    "StartGame": "Começar jogo",
  },
  "InsufficientCoin": {
    "title": "Você precisa de pelo menos {num} moedas para jogar.",
    "tip": "Você tem {haveCoin} moedas agora",
    "goScene": "Jogo recomendado",
    "toOtherModel": "Você não tem ouro suficiente ({coins}) para começar jogos. Escolher outro modo?",
    "friend": "Amigos",
    "computer": "Computador",
    "toOfferPlay": "Suas moedas não são suficientes. Ir para o modo recomendado?",
  }
}
let loadMessage = function(language, dataID, isChange) {

};
exports.loadMessage = loadMessage;