'use strict';
if (!window.i18n) {
  window.i18n = {};
}

if (!window.i18n.languages) {
  window.i18n.languages = {};
}

window.i18n.languages['French'] = {
  "label_text": {
    "Ads_getRewards_Title": "Obtenir des récompenses",
    "Ads_CountDown_tips": "Prochaines récompenses dans :",
    "Ads_watchAd_Title": "Visionner une pub",
    "Auto_Game": "Auto",
    "Button_Guest_Facebook": "Se connecter avec FB",
    "Button_Guest_Continue": "Jouer en invité(e)",
    "Button_Common_Confirm": "OK",
    "Button_Common_Yes": "Oui",
    "Button_Common_No": "Non",
    "Button_Common_Next": "Suivant",
    "Button_Common_Restart": "Rejouer",
    "Button_Common_Return": "Retour",
    "Button_Common_Share": "Partager",
    "Button_Common_Start": "Jouer",
    "Button_Common_Facebook": "Se connecter via FB",
    "Button_Common_Guest": "Invité(e)",
    "Common_Guest_BindAccount": "Associer à votre compte FB ?",
    "Common_Guest_BindAccountFail": "Échec de connexion à Facebook. Réessayez plus tard.",
    "Common_Guest_RepeatBind": "Un compte Facebook est déjà associé. Continuer avec ce compte ?",
    "Common_Guest_Confirm": "En tant qu'invité(e), vous ne pouvez pas jouer avec vos amis. \nConnectez-vous à Facebook pour : \n1. Jouer avec vos amis. \n2. Ajouter une photo de profil. \n3. Jouer sur des plateformes différentes avec le même compte. Votre statut d'invité(e) ne vous permet pas de jouer avec vos contacts.",
    "Common_Online_ShareContent": "Je suis n° {1} sur {0} et j'ai gagné {2} pièces !",
    "Common_Scene_Teamup_Teammateturn": "Vous pouvez continuer de jouer et aider votre partenaire !",
    "Common_Game_Props_GetTipsTitle_DoubleDice": "Distance doublée",
    "Common_Game_Props_GetTipsContent_DoubleDice": "Lancez un dé et avancez deux fois.",
    "Common_Game_Props_GetTipsTitle_AssignDice": "Choix de dé",
    "Common_Game_Props_GetTipsContent_AssignDice": "Choisissez la face du dé que vous désirez.",
    "Common_Game_Props_GetTipsTitle_Protection": "Champ de protection",
    "Common_Game_Props_GetTipsContent_Protection": "Protégez-vous des autres pions pendant 1 tour.",
    "Common_Game_Props_GetTipsTitle_LuckyNumber": "Nombre d'or",
    "Common_Game_Props_GetTipsContent_LuckyNumber": "Pendant 1 tour, si un joueur obtient la même face, il peut rejouer.",
    "Common_Scene_Props_Introduce_Title": "Intro au mode spécial",
    "Common_Scene_Props_introduce_luckyNumber": "Nombre d'or",
    "Common_Scene_Props_introduce_luckyNumber_": "Pendant 1 tour, si un joueur obtient ce chiffre, il peut rejouer. S'active immédiatement et s'applique à tous les joueurs.",
    "Common_Scene_Props_introduce_DoubleDice": "Distance doublée",
    "Common_Scene_Props_introduce_DoubleDice_": "Double le nombre de la face obtenue. Le joueur bouge d'autant de cases. Après l'utilisation de cet objet, obtenir un 6 ne donne pas de lancer supplémentaire et ne permet pas de bouger un pion.",
    "Common_Scene_Props_introduce_AssignDice": "Choix de dé",
    "Common_Scene_Props_introduce_AssignDice_": "Le joueur choisit la face du dé. Il est toujours possible de relancer après avoir obtenu un 6, renvoyé des pions ou atteint la maison.",
    "Common_Scene_Props_introduce_Protection": "Protection",
    "Common_Scene_Props_introduce_Protection_": "Protège tous vos pions d'un renvoi pendant 1 tour.",
    "Common_Game_Props_ShowTips_LuckyNumber": "Lancer bonus",
    "Common_Game_Props_ShowTips_LuckyNumber_": "Gagnez un lancer supplémentaire.",
    "Common_Game_Props_ShowTips_DoubleDice": "Distance doublée",
    "Common_Game_Props_ShowTips_DoubleDice_": "Doublez le nombre de cases parcourues par votre pion.",
    "Common_Game_Props_ShowTips_AssignDice": "Choix de dé",
    "Common_Game_Props_ShowTips_AssignDice_": "Choisissez la face du dé que vous désirez.",
    "Common_Game_Props_ShowTips_Protection": "Champ de protection",
    "Common_Game_Props_ShowTips_Protection_": "Protégez-vous des autres pions pendant 1 tour.",
    "Common_Game_Props_Haved": "Les objets spéciaux ne peuvent être utilisés qu'avant de lancer.",
    "Common_Game_Props_NotHaved": "Vous n'avez pas encore cet objet spécial.",
    "Common_Team": "Équipe",
    "Common_Choose_Color": "Choisir une couleur",
    "Common_Game_Online_MyPlace": "Vous êtes ici !",
    "Common_Choose_Number": "Choisir les joueurs",
    "Common_Choose_Bet": "Choisir une mise",
    "Common_Choose_Mode": "Choisir un mode",
    "Common_Choose_Number_players": "joueurs",
    "Common_Choose_Win": "Victoire :",
    "Common_Choose_Entry": "Partie :",
    "Common_Choose_Number_two": "2",
    "Common_Choose_Number_four": "4",
    "Common_Choose_Number_multi": "2 à 4",
    "Common_Choose_Number_Team": "Équipe",
    "Common_Choose_Number_2v2": "2c2",
    "Common_Game_Props_share": "Partagez et obtenez\ndes objets !",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Choisir une face",
    "Common_Game_Props_sharetogetprops_title": "Partagez avec vos contacts et gagnez 3 objets spéciaux !",
    "Common_Game_Props_sharetogetprops_share": "Partager",
    "Common_Game_Props_sharetogetprops_aftershare": "Une partie ne peut être partagée qu’une fois.",
    "Friend_Room_Entering": "En cours de chargement…",
    "Friends_Invite": "Inviter par :",
    "GameName": "Ludo World",
    "Game_Common_start": "Début du jeu",
    "Game_EndTitle_Win": "Victoire",
    "Game_EndTitle_Lose": "Défaite",
    "Game_EndOrder_1": "1e",
    "Game_EndOrder_2": "2e",
    "Game_EndOrder_3": "3e",
    "Game_EndOrder_Win": "Victoire",
    "Game_EndOrder_4": "4e",
    "Game_EndOrder_5": "5e",
    "Game_EndOrder_6": "6e",
    "Game_EndOrder_Lose": "Défaite",
    "Game_EndOrder_Playing": "Rejouer",
    "local_Result_title": "Résultat",
    "Game_Online_Auto1": "Déplacement auto",
    "Game_Online_Auto2": "Appuyez ici pour arrêter.",
    "Game_Props_TopTitle_LuckyNumber": "Nombre\nd'or",
    "Game_Props_ItemTips_DoubleDice": "Distance doublée : double le nombre de la face obtenue. Le joueur avance d'autant de cases. Après l'utilisation de cet objet, obtenir un 6 ne donne pas de lancer supplémentaire et ne permet pas de bouger un pion.",
    "Game_Props_ItemTips_AssignDice": "Choix de dé : le joueur choisit la face du dé. Il est toujours possible de relancer après avoir obtenu un 6, renvoyé des pions ou atteint la maison.",
    "Game_Props_ItemTips_Protection": "Protection : protège tous vos pions d'un renvoi pendant 1 tour.",
    "Game_leaderboard_title": "Classement",
    "Game_leaderboard_global": "Mondial",
    "Game_leaderboard_NotRanked": "Pas de classement",
    "Game_leaderboard_tips": "Mis à jour chaque lundi.",
    "Game_leaderboard_tips2": "Ne comprend que les parties en ligne.",
    "Game_leaderboard_tipsoneline": "Parties en ligne mises à jour chaque lundi.",
    "Game_Computer_PlayerName1": "Ordinateur 1",
    "Game_Computer_PlayerName2": "Ordinateur 2",
    "Game_Computer_PlayerName3": "Ordinateur 3",
    "Game_Computer_level_choose": "Choisir un niveau",
    "Game_Computer_Self": "Vous",
    "Game_Computer_level_easy": "Facile",
    "Game_Computer_level_normal": "Normal",
    "Game_Computer_level_hard": "Difficile",
    "Game_Computer_PlayerNameEasy": "Ordinateur {num} facile",
    "Game_Computer_PlayerNamenormal": "Ordinateur {num} normal",
    "Game_Computer_PlayerNamehard": "Ordinateur {num} difficile",

    "Game_local_Remove_comfirm": "Voulez-vous vraiment exclure ce joueur ?",
    "Game_local_Remove_guide_title": "Exclure le joueur",
    "Game_local_Remove_guide_content1": "qui ne veulent pas jouer",
    "Game_Friend_Pnael_Title": "Jouer avec des contacts",
    "Game_Friend_Select_Mode": "Choisir un mode de jeu",
    "Game_Friend_Create": "Créer",
    "Game_Friend_Join": "Rejoindre",
    "Game_Friend_Join_Clear": "Effacer",
    "Game_Friend_GameMode": "Choisir un mode de jeu",
    "Game_Friend_Enter_RoomCode": "Entrez le code d'invitation.",
    "Game_friends_invite_code": "Code d'invitation",
    "Game_friends_invite_tips_cannot": "En attente de joueurs…",
    "Game_friends_invite_tips_can": "Attendre ou démarrer la partie ?",
    "Game_friends_join_tips": "Entrer le code d'invitation",
    "Game_friends_join_join": "Rejoindre",
    "Game_friends_join_wait": "En attente de {who} pour commencer.",
    "Game_friends_choose_classic": "Classique",
    "Game_friends_choose_power": "Spécial",
    "Game_friends_choose_mode": "Mode",
    "Game_friends_invite_waiting": "En attente de joueurs…",
    "Game_friends_invite_waitormore": "Attendre ou démarrer la partie ?",
    "Game_friends_invite_start2V2": "Vous pouvez commencer la partie.",
    "Game_friends_invite_share": "Invitez vos contacts en partageant le code d'invitation.",
    "Game_Ready": "C'est prêt !",
    "Guest_Username": "Invité(e)",
    "help_classic_title": "Classique",
    "help_powerUp_title": "Spécial",
    "InGame_PlayerInfo_Match": "Partie",
    "InGame_PlayerInfo_Win": "Victoire",
    "InGame_PlayerInfo_Gift": "Cadeau (100 pièces par cadeau)",
    "introduce_friendModel": "ne jouer qu'avec les contacts",
    "LevelUp_Panel": "Niveau supérieur",
    "LevelProgressPanelExp": "EXP",
    "LoadGame_Button_Load": "Chargement",
    "Login_loading": "Connexion en cours…",
    "Lobby_receive_award_coins": "Pièces",
    "Lobby_invite_detail1": "Invitez des amis et obtenez {num} pièces à chaque nouvelle inscription à partir du lien.",
    "Lobby_invite_detail2": "Vous recevrez votre récompense par message après validation de la connexion via Facebook de vos amis (maximum {times} fois par jour).",
    "Lobby_invite_btn": "Inviter",
    "Lobby_invite_title": "Besoin de pièces ?",
    "Lobby_invite_guestlogin": "Voulez-vous connecter votre compte Facebook pour continuer ?",
    "MainScenes_Fackback": "Commentaire",
    "MainScenes_Ranking": "Classement",
    "MainScenes_Invite": "Inviter",
    "MainScenes_FreeCoins": "Pièces gratuites",
    "MainScenes_Mission": "Défi",
    "modify_title": "Modifier le profil",
    "Notice_Panel_Title": "Annonce",
    "Notice_Panel": "Chargement",
    "NotLogin": "Échec de connexion. Réessayez plus tard.",
    "Offline_TeamA": "équipe A",
    "Offline_TeamB": "équipe B",
    "OffLine_PanelPlayer": "Joueurs",
    "PropsShareTips": "Partagez et obtenez\ndes objets !",
    "Props_ShowTips": "EXEMPLE",
    "PersonalInfo_Win": "Victoires",
    "PersonalInfo_Total": "Parties",
    "PersonalInfo_WinRate": "Taux de victoire",
    "PersonalInfo_Edit": "Modifier",
    "PersonalInfo_Computer": "Ordinateur",
    "PersonalInfo_ClassicOnline": "Mode classique",
    "PersonalInfo_PropsOnline": "Mode spécial",
    "PersonalInfo_Props2V2": "Mode 2c2 spécial",
    "PersonalInfo_Classic2V2": "Mode 2c2 classique",
    "PersonalInfo_Notenough_player": "Il manque {Number} joueur(s).",
    "PersonalInfo_Friend": "Contacts",
    "PersonalInfo_Level": "Niv.",
    "PersonalInfo_ClassicOnlineTitle": "Classique en ligne",
    "PersonalInfo_PropsOnlineTitle": "Spécial en ligne",
    "PersonalInfo_TeamUpOnline": "Mode équipe",
    "PersonalInfo_MiniMapOnline": "Mode rapide",
    "PlayerProfile_LoginFB": "Se connecter avec Facebook",
    "PlayerProfile_Continue": "Continuer",
    "Rank_PanelWin": "Victoires",
    "Select_Robot": "Au moins 2 humains sont requis.",
    "SaveGame_Content": "Voulez-vous vraiment terminer cette partie ?",
    "SaveGame_Save": "Sauvegarder",
    "ShareGame_EXP": "Partagez et obtenez 10 points d'EXP !",
    "share_window_invite": "Inviter des amis",
    "Scene_Online_Title": "En ligne",
    "Scene_local_Title": "Local",
    "Scene_local_ChooseMode": "Choisir un mode",
    "Scene_local_ChooseMode_Classic": "Classique",
    "Scene_local_ChooseMode_Props": "Spécial",
    "Scene_local_ChooseMode_TeamUp": "En équipe",
    "Scene_local_ChooseMode_TeamPower": "Spécial en équipe",
    "Scene_local_ChooseMode_TeamClassic": "Classique en équipe",
    "Scene_local_ChooseColorAndName": "Choisir la couleur et le nom",
    "Scene_Online_ChooseBet": "Choisir une mise",
    "Scene_local_ChoosePlaers": "Choisir les joueurs",
    "Scene_local_ChoosePlaers_2P": "2 joueurs",
    "Scene_local_ChoosePlaers_3P": "3 joueurs",
    "Scene_local_ChoosePlaers_4P": "4 joueurs",
    "Scene_local_PlayerName1": "Pion 1",
    "Scene_local_PlayerName2": "Pion 2",
    "Scene_local_PlayerName3": "Pion 3",
    "Scene_local_PlayerName4": "Pion 4",
    "Scene_local_ChooseTeam": "Choisir l'équipe",
    "Scene_ClassicOnline_Title": "Classique",
    "Scene_PropsOnline_Title": "Spécial",
    "Scene_MiniMapOnline_Title": "Partie rapide",
    "Scene_TeamUpOnline_Title": "En équipe",
    "Scene_Computer_Title": "Ordinateur",
    "Scene_Friend_Title": "Contacts",
    "Scene_Online_ChoosePlaers_2P": "2 joueurs",
    "Scene_Online_ChoosePlaers_4P": "4 joueurs",
    "Scene_Online_matching": "En attente d'autres joueurs…",
    "Set_Panel_Title": "Paramètres",
    "Set_Panel_Music": "Musique",
    "Set_Panel_Sound": "Effet",
    "Set_Panel_Version": "Version",
    "Set_Panel_About": "À propos",
    "Set_Panel_About_Detail": "Merci de soutenir\nLudo World ! Si vous souhaitez\nnous faire part de vos retours,\ncontactez-nous par mail à\nhpludoworld@gmail.com.",
    "Set_Panel_Help": "Aide",
    "Set_Panel_Feedback": "Commentaire",
    "Set_Panel_US": "Aimer",
    "Set_Panel_RATE": "Noter",
    "Set_Panel_Privacy": "Politique de confidentialité",
    "Set_Panel_Terms": "Conditions d'utilisation",
    "Set_FB_Login": "Se connecter",
    "Set_FB_Logout": "Se déconnecter",
    "Set_FB_Bind": "Associer",
    "Set_Panel_Vibrate": "Vibration",
    "Set_Panel_Chat": "Discussion",
    "Set_Panel_Help_minimap": "Pareil que le mode classique.\nUne partie plus rapide sur un plateau plus petit.\nSeulement 4 cases d'immunité, à l'entrée de chaque base.",
    "Title_Load_Game": "Charger la partie",
    "Title_PlayerProfile": "Profil",
    "Tips_Game__ThreeSixSkip": "Au 3e six consécutif,\nc'est fini !",
    "Lucky_Wheel_Name": "Roue de la chance",
    "Game_info_block": "Bloquer",
    "Game_info_unblock": "Débloquer",
    "Button_Item_Use": "Utiliser",
    "Button_Item_Using": "En usage",
    "Button_Item_gotouse": "L'utiliser",
    "Main_Backpack": "Sac",
    "Item_Duration_Duration": "Durée :",
    "Item_Duration_Day": "j",
    "Item_Duration_Hour": "h",
    "Item_Duration_Min": "min",
    "Item_Duration_S": "s",
    "Item_Duration_Year": "a",
    "Item_Duration_Permanent": "Permanent",
    "NewPlayerBonus_Gift": "Cadeau",
    "Common_Game_item_purchase": "Obtenez-en grâce à des cartes d'objets, vous pouvez encore en acheter {num}.",
    "Common_Game_item_purchaseoverbuy": "Vous ne pouvez en échanger que {num} fois par partie.",
    "Common_Game_itemcard_notenought": "Pas assez de cartes d'objet ! En acheter à la boutique ?",
    "Lobby_mini": "Partie rapide",
    "Common_IOS_Shop_LessConins": "Pas assez de pièces. Obtenez-en davantage à partir de l'événement.",
    "ComputerAndLocal": "Ordinateur et local",
    "Common_Game_Undo_Lack": "manquant",
    "Common_Game_Undo_Lack_Tip": "Pas assez de gemmes pour annuler.",
    "Common_Game_Undo_Left": "Annulations restantes",
    "Common_Game_Undo_Switch": "Annulation activée",
    "Common_Game_Undo_Title_Enable": "Annuler le lancer",
    "Common_Game_Undo_Title_Disable": "Les annulations sont DÉSACTIVÉES",
    "Common_Game_Undo_Desc_Enable": "Appuyez sous {num} s après le lancer pour annuler le résultat.",
    "Common_Game_Undo_Desc_Disable": "L'annulation est désactivée. Appuyez sur la case pour la réactiver.",
    "Common_Game_Undo_Desc_Use_Up": "Aucune tentative pour annuler",
    "Grand_Prix_Entry": "FRAIS D'ENTRÉE",
    "Grand_Prix_Endsin": "Fin dans :",
    "Grand_Prix_Play": "JOUER",
    "Grand_More_Coins": "Plus de pièces",
    "Grand_More_Level": "Ouvrir au niv. {date}",
    "Starter_Pack": "Pack de départ",
    "Gift_Bag_Time": "{date} heures restantes",
    "Lucky_Dice": "Dé d'or",
    "Exclusive_Offert": "Offre exclusive",
  },
  "AlertText": {
    "Button_Common_Confirm": "OK",
    "Button_Common_Yes": "Oui",
    "Button_Common_Cancel": "Annuler",
    "Button_Common_No": "Non",
    "Button_Common_Upgrade": "Améliorer",
    "Button_Common_NoUpgrade": "Pas maintenant",
    "Button_Common_ExitUpgrade": "Quitter la partie",
    "Bind_FB_Account": "Échec de connexion à Facebook. Réessayez plus tard.",
    "Bind_FB_Account2": "Un autre compte est déjà associé à ce compte Facebook. Essayez un autre compte.",
    "Common_Game_Online_Leave": "Vous perdrez si vous quittez la partie. Continuer ?",
    "Common_Game_Local_Leave": "Quitter la partie actuelle ?",
    "Common_Game_Local_SaveGame": "Sauvegarder la partie actuelle ?",
    "Common_Game_Computer_SaveGame": "Sauvegarder la partie actuelle ?",
    "Common_Game_Computer_EnterBySaveGame": "Vous n'avez pas fini une partie. La charger ?",
    "Common_Notify_Client_Logout": "Ce compte est connecté sur un autre appareil. Reconnectez-vous pour continuer à jouer sur cet appareil.",
    "Common_Netword_Fail": "Vérifiez votre connexion internet.",
    "Common_Netword_Fail_Offline": "Échec de la connexion au réseau. Jouer en mode local et contre des ordinateurs ?",
    "Common_Netword_FailRethy": "Échec de la connexion au réseau. Réessayer ?",
    "Common_Netword_Fail_timeout": "Délai de connexion dépassé. Réessayez plus tard.",
    "Common_Netword_Fail_Reconnect": "Une connexion internet est nécessaire pour jouer en ligne. Se connecter ?",
    "Common_Lobby_ReturnGame": "Vous êtes en pleine partie. Revenir à la partie ?",
    "Common_Lobby_ReturnFailed": "Votre dernière partie est terminée.",
    "Common_Scene_Online_LessCoins": "Pas assez de pièces. Achetez-en à la boutique.",
    "Common__Online_Matching_Failed": "Échec de chargement de la partie. Réessayez plus tard.",
    "Common_Scene_Online_Matching_TimeOut": "Temps d'attente écoulé. Réessayez plus tard.",
    "Common_Scene_Online_Sitting_Failed": "Impossible de rejoindre. Réessayez plus tard.",
    "Common_No_Operation": "Vous quitterez automatiquement la partie après un trop long moment d'inactivité.",
    "Common_Delete": "Voulez-vous vraiment supprimer la partie sauvegardée ?",
    "Common_Game_TeamUp_GetUserGuide": "Le mode équipe est tout nouveau ! Voir comment jouer ?",
    "Facebook_Login_Faile": "Échec de connexion à Facebook. Vérifiez votre internet.",
    "Game_leaderboard_sendBean_success": "Les pièces ont été remises avec succès.",
    "Game_leaderboard_sendBean_fail": "Impossible d'envoyer les pièces.",
    "Game_leaderboard_sendBean_Max": "La limite quotidienne de don de pièces a été atteinte.",
    "Game_Reselect_bet": "Vous avez plus de pièces que la limite de mise. Veuillez commencer une nouvelle partie où la mise est plus élevée.",
    "Game_chat_Common_Yes": "Activer",
    "Game_chat_Common_MainText": "Lorsque la discussion, les autres joueurs peuvent voir vos messages. Activer la discussion maintenant ? Elle pourra être désactivée dans les paramètres.",
    "Game_Friend_Join_Not_Find": "Impossible de trouver la partie. Vérifiez le code d'invitation.",
    "Game_Friend_Join_Room_Closed": "La partie n'existe plus. Commencez une nouvelle partie.",
    "Game_Friend_Join_Not_Enough_Coins": "Pas assez de pièces pour rejoindre la partie. En obtenir à la boutique ?",
    "Game_Friend_Join_No_Extra_Seat": "Oups, il n'y a plus de place. Commencez une nouvelle partie.",
    "Game_Friend_Join_alreadybegin": "La partie a déjà commencé. Commencez une nouvelle partie.",
    "Game_Friend_Leave_Room": "La partie se fermera si vous partez. Quitter ?",
    "Login_NO_IP": "Malheureusement, compte tenu de votre emplacement, vous ne pouvez pas accéder au jeu pour le moment.",
    "Modify_HeadIcon_Fail": "Échec de la modification. Réessayez plus tard.",
    "Matching_Failed": "Impossible de trouver des joueurs. Réessayez plus tard.",
    "No_Operation_ConfirmText": "Rester",
    "No_Operation_CancelText": "Quitter",
    "Quit_Game": "Voulez-vous vraiment quitter le jeu ?",
    "Store_buy_tips": "Pas assez de pièces. En obtenir à la boutique ?",
    "Store_buy_latter": "Pas maintenant !",
    "Store_Open_Failed": "Échec du chargement des données. Réessayez plus tard.",
    "Store_buy_go": "Aller",
    "Store_Payment_Failed": "Échec du paiement. Erreur :",
    "Store_Payment_IPFailed": "Échec du paiement, vous pouvez réessayer sur PC Instant Game.",
    "ShortCut_go": "Créer un raccourci sur le bureau ?",
    "Client_Low_Version": "La dernière version du jeu est nécessaire. Mettre à jour maintenant ?",
    "Client_High_Version": "Oups, impossible de jouer avec cette version du jeu.",
    "Client_Deny_Version": "Oups, impossible de jouer avec cette version du jeu.",
    "Play_Punish_In_Chat": "Vos communications sont restreintes jusqu'au {date} pour non-respect des règles.",
    "Play_Punish_In_Room": "Votre compte a été banni jusqu'au {date} pour non-respect des règles.",
    "Play_Punish_Enter_Room": "Votre compte a été banni pour non-respect des règles.",
    "Kicked_Player_Not_Enough_Coins": "Si vous n'avez pas assez de pièces, vous perdrez la partie en la quittant. En obtenir à la boutique ?",
    "Kicked_Player_Game_Lose": "Vous avez perdu. Vous n'avez pas assez de pièces pour continuer.",
    "Backpack_items_empty": "Pas d'objet possédé. En obtenir à la boutique ?",
    "Grand_Unlock_level": "Se débloque une fois le niveau {date} atteint.",
    "Grand_Open_Hint": "Ouvrez le gros lot après le {date}.",
    "Grand_Less_Coins_recommend": "Quantité de pièces inférieure au montant recommandé pour participer au jeu ({date}), voulez-vous quand même continuer ?",
    "Grand_Less_Coins_Hint": "Vous n'avez pas assez de pièces pour tenter de gagner le gros lot. En obtenir à la boutique ?",
  },
  "Tips": {
    "Ads_times_tips": "Revenez demain pour plus de récompenses.",
    "Ads_times_tips_Gems": "Revenez demain pour plus de gemmes.",
    "Ads_coolCd_tips": "Réessayez plus tard.",
    "Ads_none_tips": "Aucune publicité disponible, réessayez plus tard.",
    "Ads_none_tips1": "Aucune publicité disponible.",
    "Ads_notFull_tips": "Visionnez la vidéo en entier pour obtenir des récompenses !",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Choisir une face",
    "Friend_Err_Fetch_List_Fail": "Échec du chargement des données. Réessayez plus tard.",
    "Friend_Err_Fetch_Online_Fail": "Échec du chargement des données. Réessayez plus tard.",
    "Friend_Err_Fetch_Login_Time_Fail": "Échec du chargement des données. Réessayez plus tard.",
    "Friend_Err_Not_Add_Player": "Échec de l'action, réessayez plus tard.",
    "Friend_Err_List_Full": "Votre liste de contacts est pleine. Supprimez un contact pour en ajouter un nouveau.",
    "Friend_Err_Peer_Friend_List_Full": "Impossible d'ajouter {name}, sa liste de contacts est pleine.",
    "Friend_Err_Update_Friend_Fail": "Échec du chargement des données. Réessayez plus tard.",
    "Friend_Err_Player_Refuse_Add": "{name} n'accepte pas de demande de contact.",
    "Friend_Err_Already_In_Add_List": "",
    "Friend_Err_Already_In_Game_List": "Ce contact est déjà dans votre liste.",
    "Friend_Err_Already_In_Platform_List": "Ce contact est déjà dans votre liste.",
    "Friend_Err_Not_In_List": "Échec de l'action, réessayez plus tard.",
    "Friend_Err_Fetch_Game_Record_Fail": "Échec du chargement des données. Réessayez plus tard.",
    "Friend_Err_Cannot_Add_Self": "Échec de l'ajout, réessayez plus tard.",
    "Game_Props_TopTitle_LuckyNumber": "Nombre\nd'or",
    "Game_Props_ItemTips_DoubleDice": "Distance doublée : double le nombre de la face obtenue. Le joueur avance d'autant de cases. Après l'utilisation de cet objet, obtenir un 6 ne donne pas de lancer supplémentaire et ne permet pas de bouger un pion.",
    "Game_Props_ItemTips_AssignDice": "Choix de dé : le joueur choisit la face du dé. Il est toujours possible de relancer après avoir obtenu un 6, renvoyé des pions ou atteint la maison.",
    "Game_Props_ItemTips_Protection": "Protection : protège tous vos pions d'un renvoi pendant 1 tour.",
    "Game_gift_gift": "Envoyer des émoticônes",
    "Game_gift_giftprice": "100 pièces par émoticône",
    "Game_gift_sendtoofast": "Ralentissez un peu.",
    "Game_leaderboard_load_fail_tips": "Échec du chargement des données. Réessayez plus tard.",
    "Game_classic_newusertips_moveout1": "Obtenez un 6 pour sortir un pion !",
    "Game_classic_newusertips_mesafe": "Rien n'arrive aux pions sur une case étoile !",
    "Game_classic_newusesrtip_bumptoken": "Renvoyez ce pion !",
    "Game_Friend_JoinTips_Invalid_RoomCode": "Code d'invitation invalide. Vérifiez le code.",
    "Lobby_unfinish_notice": "Cette nouveauté arrive bientôt !",
    "shortCut_create_succ": "Le raccourci a été créé.",
    "shortCut_create_fail": "Impossible de créer le raccourci. Veuillez réessayer.",
    "shortCut_bubble_tips": "Appuyer ici pour créer le raccourci sur la page d'accueil",
    "Tips_Longin_Fail": "Échec de la connexion. Réessayez plus tard !",
    "Tips_Netword_Fail_TryReconnect": "Échec de la connexion au réseau. Nouvelle tentative…",
    "Tips_Netword_Fail_Reconnected": "Reconnexion réussie. Vous revoilà !",
    "Tips_Game__ThreeSixSkip": "Au 3e six consécutif,\nc'est fini !",
    "Tips_Game_Props_UseTips_DoubleDice": "Distance doublée ! La face est doublée !",
    "Tips_Game_Props_UseTips_AssignDice": "Choix de dé ! Vous obtenez un",
    "Tips_Game_Props_UseTips_Protection": "Protège tous vos pions d'un renvoi pendant 1 tour.",
    "Tips_Game_Props_UseTips_LuckyNumber": "Lancer bonus, lancez à nouveau !",
    "Tips_Game_Props_UseFail_DoubleDice": "Aucun pion disponible pour utiliser cet objet !",
    "Tips_Game_Props_UseFail_Protection": "Pas de pion à protéger !",
    "Tips_Game_Props_OtherUseTips_DoubleDice": "Distance doublée utilisée !",
    "Tips_Game_Props_OtherUseTips_AssignDice": "Choix de dé utilisé !",
    "Tips_Not_Whatsapp": "Cette fonctionnalité nécessite WhatsApp.",
    "Tips_NetWork_Connection": "Connexion",
    "Tips_Game_TeamUp_HelpTeammate": "Jouez avec votre partenaire !",
    "task_load_fail_tips": "Échec du chargement des données. Réessayez plus tard.",
    "Tips_Game_addFriendReq": "Envoyer une demande de contact.",
    "Tips_Game_addFriendReq_accept": "Accepter",
    "Tips_Game_addFriendReq_ignore": "Ignorer",
    "Tips_Friend_Req": "Demande de contact envoyée.",
    "Tips_Friend_AcceptSucc": "{name} a accepté votre demande.",
    "Tips_Friend_AcceptFailed": "Impossible d'accepter, réessayez plus tard dans l'onglet Demandes.",
    "Tips_Friend_IgnoreFailed": "Impossible d'ignorer, réessayez plus tard dans l'onglet Demandes.",
    "Tips_Friend_RemoveFriend": "Voulez-vous vraiment supprimer ce contact ?",
    "Set_Panel_chatclosetips": "Vous avez bloqué tous les groupes de discussion.",
    "Tips_Send_Gift": "Appuyez ici pour envoyer des émoticônes.",
    "Tips_Send_This_Player_Gift": "Appuyez ici pour envoyer des émoticônes à cette personne.",
    "Tips_Profile_Add_Friends": "Appuyez sur un profil pour ajouter un contact.",
    "Tips_Here_Add_Friends_GamePage": "Appuyez ici pour ajouter un contact.",
    "Tips_Here_Add_Friends_GameOver": "Appuyez ici pour ajouter un contact.",
    "Tips_Send_Coin_friends": "Envoyez des pièces gratuites à des contacts.",
    "Tips_Collect_By_Mail": "Recevez des pièces gratuites de contact par message.",
    "Item_Use_Success": "Vous avez utilisé {skin}.",
    "Kick_Player_No_Reward_Tips": "{name} n'a plus de pièces et a perdu. Pas de bonus disponible.",
    "Common_Game_Mini_tips": "Obtenez {num} étoiles pour gagner ! Renvoyer un pion ou atteindre la maison offre une étoile.",
    "Lobby_mini_tips": "Rapide et intense",
  },
  "Chat": {
    "Game_emoji": "Émoticône",
    "Game_chat": "Discussion",
    "Game_chat_title": "Quitter la discussion",
    "Game_chat_content1": "Salut !",
    "Game_chat_content2": "Plus vite !",
    "Game_chat_content3": "Mince !",
    "Game_chat_content4": "Bien joué",
    "Game_chat_content5": "Pourquoiiiiii !",
    "Game_chat_content6": "Pardon !",
    "Game_chat_tips": "Écrire un message",
    "Game_chat_send": "Envoyer",
  },
  "DailyBonus": {
    "Lobby_Bonus_title": "Bonus quotidien",
    "Lobby_Bonus_detail": "Obtenez des pièces gratuites tous les jours !",
    "Lobby_Bonus_collect": "Récupérer",
    "Lobby_Bonus_collected_tips": "Revenez demain pour plus de pièces.",
    "Lobby_Bonus_collect_failed": "Échec de récupération, réessayez plus tard.",
    "Lobby_Bonus_reqFailed": "Récupération du bonus quotidien impossible. Réessayez plus tard.",
    "Lobby_Bonus_Day": "Jour {num}",
    "Lobby_Bonus_Day_1": ""
  },
  "Props_Guide": {
    "Game_Props_TopTitle_Great": "Super",
    "Game_Props_TopTitle_LuckyNumber": "Nombre\nd'or",
    "Game_Props_ItemTips_DoubleDice": "Distance doublée : double le nombre de la face obtenue. Le joueur avance d'autant de cases. Après l'utilisation de cet objet, obtenir un 6 ne donne pas de lancer supplémentaire et ne permet pas de bouger un pion.",
    "Game_Props_ItemTips_AssignDice": "Choix de dé : le joueur choisit la face du dé. Il est toujours possible de relancer après avoir obtenu un 6, renvoyé des pions ou atteint la maison.",
    "Game_Props_ItemTips_Protection": "Protection : protège tous vos pions d'un renvoi pendant 1 tour.",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Choisir une face",
    "Common_Game_Props_UserGuide_GoldenNo": "Voici le nombre d'or. Obtenez-le pour avoir un autre lancer !",
    "Common_Game_Props_UserGuide_GoldenNo_content": "Obtenez un lancer supplémentaire lorsque vous atteignez cettte case.",
    "Common_Game_Props_UserGuide_continue": "Appuyez pour continuer.",
    "Common_Game_Props_UserGuide_begin_title": "Mode spécial",
    "Common_Game_Props_UserGuide_begin_content": "Bonjour, je suis l'assistant Ludo World. Je vais vous expliquer comment jouer au mode spécial !",
    "Common_Game_Props_UserGuide_roaditem": "Vous pouvez récupérer différents objets spéciaux sur le plateau.",
    "Common_Game_Props_UserGuide_Items": "Voici tous les objets spéciaux.",
    "Common_Game_Props_UserGuide_Dicecontrol_title": "Choix de dé",
    "Common_Game_Props_UserGuide_Dicecontrol_content": "Vous pouvez choisir la face du dé !",
    "Common_Game_Props_UserGuide_Dicecontrol_tips": "Lancer un 6 permet de bien commencer !",
    "Common_Game_Props_UserGuide_Doubledistance_title": "Distance doublée",
    "Common_Game_Props_UserGuide_Doubledistance_content": "Double le nombre de la face et la distance parcourue !",
    "Common_Game_Props_UserGuide_GoldenNo_title": "Lancer bonus",
    "Common_Game_Props_UserGuide_GoldenNo_tips": "Obtenez un lancer supplémentaire. Qui n'aime pas rejouer !",
    "Common_Game_Props_UserGuide_BumpProtection_title": "Champ de protection",
    "Common_Game_Props_UserGuide_BumpProtection_content": "Protégez-vous des autres pions sournois pendant 1 tour.",
    "Common_Game_Props_UserGuide_BumpProtection_effect": "Super ! Votre pion est protégé !",
    "Common_Game_Props_UserGuide_finish_title": "Tout est bon !",
    "Common_Game_Props_UserGuide_finish_content": "Vous savez tout des objets, lancez-vous dans une vraie partie !",
    "Common_Game_Props_UserGuide_finish_botton": "C'est parti !",
    "Common_Game_Props_GetUserGuide": "Vous jouez au mode spécial pour la 1re fois ? Regardez notre tuto.",
  },
  "Feedback": {
    "Set_Feedbeck_Title": "Commentaire",
    "Set_Feedbeck_Tips": "Merci pour votre retour et votre soutien !",
    "Set_Feedbeck_Submit": "Envoyer",
    "Set_Feedbeck_Submit_Succeed": "Votre commentaire a bien été envoyé.",
    "Set_Feedbeck_Submit_No": "Entrez vos retours ici.",
  },
  "TeamUp_Guide": {
    "Common_Game_teamup_UserGuide_begin_title": "En équipe",
    "Common_Game_teamup_UserGuide_begin_content": "Jouez en équipe ! Voici les règles.",
    "Common_Game_teamup_UserGuide_teammate": "Vous faites équipe avec les verts, en diagonale de vous.",
    "Common_Game_teamup_UserGuide_competitor": "L'équipe des rouges et des jaunes est votre adversaire.",
    "Common_Game_teamup_UserGuide_pawnstack": "Les pions alliés peuvent s'arrêter sur la même case.",
    "Common_Game_teamup_UserGuide_onefinish": "Aidez votre partenaire après que vos 4 pions ont atteint la maison.",
    "Common_Game_TeamUp_UserGuide_finish_title": "Bien joué !",
    "Common_Game_TeamUp_UserGuide_finish_content": "Vous avez appris à jouer en équipe. Commencez une vraie partie !",
  },
  "SharePresentLottery": {
    "Lobby_Lottery_Hint": "Visionner une publicité pour tourner la roue",
    "Lobby_Lottery_Btn_Share": "Visionner",
    "Lobby_Lottery_Btn_spin": "Tourner",
    "Lobby_Lottery_Upper_Limit": "Revenez demain pour obtenir de nouvelles tentatives !",
    "Lobby_Lottery_Close": "La roue tourne !",
  },
  "ShareText": {
    "TitleTurnplate": "Vous voulez jouer au Ludo ? Jouons ensemble dès maintenant !",
    "TitlePropsShare": "C'est si amusant de jouer à Ludo World ! Rejoignez-moi !",
    "TitleOver": "Je viens de gagner sur Ludo World. Rejoignez-moi !",
    "FriendRoomInviteText": "{name} vous invite à jouer à Ludo World, code d'invitation : {RoomCode}.",
    "RankShareContent": "J'ai gagné {num} [partie|parties] cette semaine, affrontez-moi !",
    "Invite_gift_text1": "Salut, je joue à Ludo World, rejoignez-moi !",
    "Invite_gift_text2": "Qui est au top du top ? Affrontez-moi !",
    "Invite_gift_text3": "Vous pouvez obtenir des récompenses lorsque vos contacts ouvrent le lien partagé.",
    "friend_invite_details": "Rejoignez-moi sur Ludo World. Code d'invitation : {Number} Cliquez ici pour télécharger ou entrer dans le jeu.",
  },
  "LoginMainLabel": {
    "LoginMainLabel_Facebook": "Facebook",
    "LoginMainLabel_Google": "Google",
    "LoginMainLabel_Description": "En continuant, j'accepte que Moon Active enregistre et traite mes données conformément à la politique de confidentialité.",
    "LoginMainLabel_Guest": "Invité(e)",
    "LoginMainLabel_Continue_Sure": "Confirmez-vous votre choix ?",
    "LoginMainLabel_Continue_Express": "Vous ne pouvez pas jouer avec des contacts en tant qu'invité(e)…",
    "LoginMainLabel_Continue_AsGuest": "Jouer en tant qu'invité(e)",
    "LoginMainLabel_Continue_FbAward": "En tant qu'invité(e) vous ne pouvez pas jouer avec des contacts ou obtenir {coins} pièces bonus…",
    "LoginMainLabel_RewardPrompt": "{coins} pièces gratuites !",
    "LoginMainLabel_Continue_Warning": "En appuyant sur \"Accepter\", je confirme avoir lu et accepté la POLITIQUE DE CONFIDENTIALITÉ et les CONDITIONS GÉNÉRALES D'UTILISATION DES JEUX TENCENT.",
    "LoginMainLabel_Continue": "<u><b>Continuer en tant qu'invité(e)<u><b>",
    "LoginMainLabel_Select": "Choisir la méthode de connexion",
    "FacebookConnect_Content1": "<b><color=#444987>Se connecter avec Facebook ：</color></b>",
    "FacebookConnect_Content2": "<b><color=#444987>1. Jouez avec des amis.\n2. Sauvegardez votre progression.\n3. Obtenez <color=#d16004>{num}<color=#444987> pièces.<b>",
    "FacebookConnect_Content3": "<u><b><color = #3f59b7 click=\handler\>se connecter avec Facebook</color></b></u>",
    "FacebookConnect_Content4": "<b><color=#444987>Se connecter en tant qu'invité(e).<color=#d16004> Impossible de <color=#d16004>",
  },
  "PropsPromtText": {
    "Game_classic_newusertips_dicecontrolmoveout": "Choisissez la face du dé et\nsortez de la base !",
    "Game_classic_newusertips_dicecontrolbump": "Choisissez la face du dé pour\nrenvoyer l'adversaire",
    "Game_classic_newusertips_dicecontrolfinish": "Choisissez la face du dé\npour atteindre la maison !",
    "Game_classic_newusertips_doubledistance": "Doublez votre distance parcourue !",
    "Game_classic_newusertips_shild": "Protégez vos pions !",
    "Game_classic_newusertips_dicecontrolrun": "Choisissez de combien vous avancerez.",
    "Game_item_purchasetips": "Appuyez pour obtenir l'objet",
  },
  "MailPanel": {
    "Mail_Title": "Messages",
    "Mail_firend": "Contacts",
    "Mail_system": "Système",
    "Mail_collect": "Récupérer",
    "Mail_check": "Ouvrir",
    "Mail_collectAll": "Tout récupérer",
    "Mail_Firend_Preservation_tips": "Enregistrer 60 messages pendant 30 jours.",
    "Mail_System_Preservation_tips": "Enregistrer 60 messages pendant 30 jours.",
    "Mail_NoMail_tips": "Pas de messages",
    "MailInfo_Title": "Détails",
    "MailInfo_firend_Gift": "vous offre un cadeau",
    "Mail_firend_Get_limit": "Vous avez déjà obtenu des cadeaux de {num} contacts aujourd'hui. Revenez demain pour plus de cadeaux.",
    "MailInfo_get_Failure": "Échec de récupération. Réessayez plus tard.",
    "Mail_delete_Failure": "Échec de suppression. Réessayez plus tard.",
    "MailInfo_delete": "Effacer",
  },
  "PrivacyPolicy": {
    "PrivacyPolicy_join1": "J'ai lu et accepté la",
    "PrivacyPolicy_join2": "POLITIQUE DE CONFIDENTIALITÉ",
    "PrivacyPolicy_join3": "et les",
    "PrivacyPolicy_join4": "CONDITIONS GÉNÉRALES D'UTILISATIONS",
    "SelectNone": "En appuyant sur Accepter, je confirme avoir lu et accepté la POLITIQUE DE CONFIDENTIALITÉ et les CONDITIONS GÉNÉRALES D'UTILISATION.",
  },
  "HelpText": {
    "Game_classic_userguide_tokens": "Pions : tout le monde possède 4 pions.",
    "Game_classic_userguide_startpoint": "Position de départ : Voilà le point de départ.",
    "Game_classic_userguide_finishline": "Maison : les pions doivent faire le tour du plateau avant d'entrer dans la maison.",
    "Game_classic_userguide_safeplace": "Case d'immunité : il y a 8 cases étoiles qui offrent aux pions l'immunité, ils ne peuvent pas être renvoyés à la base.",
    "Game_classic_userguide_dice": "Dé : chaque face a un nombre différent allant de 1 à 6.",
    "Game_classic_userguide_firsthand": "Début de partie : la personne qui commence est choisie au hasard, puis le tour suit le sens des aiguilles d'une montre.",
    "Game_classic_userguide_moveout": "Sortir : un pion ne peut sortir de la base qu'à l'obtention d'un 6.",
    "Game_classic_userguide_move": "Avancer : après un lancer de dé, sélectionnez le pion que vous désirez avancer d'autant de cases.",
    "Game_classic_userguide_automove": "Avancée automatique : un pion bouge automatiquement lorsqu'il n'y a pas d'autre choix.",
    "Game_classic_userguide_sixbonus": "Bonus des six : vous obtenez un lancer supplémentaire après avoir obtenu un 6. Si vous obtenez trois 6 d'affilée, votre dernier tour sera sauté.",
    "Game_classic_userguide_bumpbonus": "Bonus de renvoi : vous obtenez un lancer supplémentaire si vous renvoyez un pion à sa base.",
    "Game_classic_userguide_finishbonus": "Bonus de fin : vous obtenez un lancer supplémentaire après qu'un de vos pions a atteint la maison.",
    "Game_classic_userguide_bump": "Renvoi : si un pion finit sa course sur un autre pion, et qu'ils ne sont pas sur une case d'immunité, il renverra l'autre pion à la base. Mais si deux ou plusieurs pions de même couleur se trouvent sur la même case, ils sont immunisés contre les renvois.",
    "Game_classic_userguide_finish": "Le pion ne peut entrer dans la maison que si le nombre du lancer est égal au nombre de cases entre lui et la maison. S'il est supérieur, le pion ne peut pas être déplacé.",
    "Game_classic_userguide_winner": "Victoire : la première personne à atteindre la maison avec ses 4 pions gagne. Dans une partie à 4 joueurs, la victoire est partagée entre la 1re et 2e personne à avoir terminé.",
    "Game_classic_userguide_time": "Chrono : 10 s pour lancer, 10 s pour avancer.",
    "Game_classic_userguide_autohosted": "Déplacement auto : à la fin du chrono ou en cas de déconnexion, l'ordinateur jouera à votre place. Appuyez pour reprendre le contrôle.",
    "Set_Help_newuser_powermode_begin": "Pareil que le mode classique, mais avec des objets pour encore plus de fun !",
    "Set_Help_newuser_powermode_step1": "Distance doublée : doublez le nombre de cases parcourues par votre pion. Allez deux fois plus vite !\nAttention : Après l'utilisation de Distance doublée, obtenir un 6 ne donne pas de lancer supplémentaire et ne permet pas de sortir un pion.",
    "Set_Help_newuser_powermode_step2": "Choix de dé : choisissez la face du dé que vous désirez.",
    "Set_Help_newuser_powermode_step3": "Champ de protection : protégez-vous des autres pions pendant 1 tour.",
    "Set_Help_newuser_powermode_step4": "Lancer bonus : gagnez un lancer supplémentaire.",
    "Set_Panel_Help_teamup_1": "Règle 1 : vous faites équipe avec la couleur en diagonale de vous (bleu et vert contre rouge et jaune).",
    "Set_Panel_Help_teamup_2": "Règle 2 : lorsque des pions de la même équipe se trouvent sur la même case, les pions de l'adversaire ne peuvent pas les renvoyer.",
    "Set_Panel_Help_teamup_3": "Règle 3 : les pions d'une même équipe sur une même case ne seront pas renvoyés lors du départ d'un des pions.",
    "Set_Panel_Help_teamup_4": "Règle 4 : une fois vos pions à la maison, vous pouvez utiliser vos lancers pour bouger les pions de votre partenaire.",
    "Set_Panel_Help_teamup_5": "Règle 5 : la première équipe à avoir ses 8 pions à la maison a gagné.",
  },
  "PropGuidePanel": {
    "PropGuidePanel_TitleText": "Mode spécial !",
    "PropGuidePanel_ContentText": "Essayez dès maintenant ce \nmode unique de Ludo !",
    "PropGuidePanel_PlayBntText": "Jouer",
    "PropGuidePanel_AwardHint": "pièces gratuites !",
    "NewHandGuide_AwardHint": "Vous avez fini le tuto du mode spécial !",
    "NewHandGuide_Get_Failure": "Échec de récupération. Réessayez plus tard.",
    "PropGuideTipsOpenText": "Astuces activées",
    "PropGuideTipsCloseText": "Astuces désactivées",
  },
  "GameGuide": {
    "GameGuideText1": "Bienvenue !",
    "GameGuideText2": "Jouons en ligne avec d'autres joueurs !",
  },
  "GameGuideText": {
    "GameGuideTitle": "Choisir un mode",
    "GameGuideContent": "Vous connaissez le Ludo ? Essayez.",
    "GameGuideClassicModeContent": "Classique",
    "GameGuidePowerModeContent": "Confirmé",
    "GameGuidePowerMode": "Spécial",
    "GameGuidePlay": "Jouons ensemble !",
    "GameGuideClassicMode": "Classique",
    "GameGuideInnovative": "Innovant",
  },
  "GameTxpText": {
    "GameNoGetExp": "Aucun pion renvoyé ou à la maison, aucun point d'EXP gagné.",
    "CloseTips": "Appuyer pour fermer",
    "ShareLevelTips": "C'est si amusant de jouer à Ludo World ! Rejoignez-moi !",
  },
  "AssessPanelText": {
    "Rate_title": "Vous aimez jouer ?",
    "Rate_content": "Dans ce cas, notez-nous !",
    "Rate_Button": "Noter",
    "Rate_Button2": "Pas maintenant",
    "ShareGame_exp_fail": "Impossible d'obtenir l'EXP. Réessayez plus tard.",
    "ShareGame_exp_Exceed": "Limite d'EXP quotidienne atteinte, revenez demain.",
  },
  "TaskPanel": {
    "Task_Title": "Défi",
    "Task_Daily": "Défi quotidien",
    "Task_Growth": "Défi principal",
    "Task_collect": "Récupérer",
    "Task_Play": "Aller",
    "Task_Playing": "En cours",
    "Task_get_award_failed": "Échec de récupération. Réessayez plus tard.",
    "Task_Tips": "Les défis quotidiens se réinitialisent à minuit",
    "Task_Timeout": "Échec de récupération, la mission a expiré.",
    "Task_Coins": "pièces",
  },
  "TaskName": {
    "task_0": "Connexion",
    "task_1": "Envoyer 5 fois des cadeaux\nà d'autres joueurs\nlors de parties en ligne",
    "task_2": "Envoyez 5 fois\ndes pièces à\ndes contacts.",
    "task_3": "Renvoyer 5 pions\nen mode amical",
    "task_4": "Atteindre la maison\navec 3 pions\nen mode amical",
    "task_5": "Gagner 1 partie\nclassique contre\ndes contacts",
    "task_6": "Gagner 1 partie spéciale\n contre des contacts",
    "task_7": "Gagner 1 partie\ncontre des contacts",
    "task_8": "Gagner 5 parties\nclassiques en ligne\nà 2 joueurs",
    "task_9": "Gagner 3 parties\nlocales classiques\nà 4 joueurs",
    "task_10": "Gagner 3 parties\nlocales classiques\nen équipe",
    "task_11": "Gagner 5 parties\nlocales spéciales\nà 2 joueurs",
    "task_12": "Gagner 3 parties\nspéciales en ligne\nà 4 joueurs",
    "task_13": "Gagner 3 parties\ncspéciales en ligne\nen équipe",
    "task_14": "Gagner 5 parties\nen ligne",
    "task_15": "Utiliser Distance doublée\n10 fois dans le mode\nSpécial en ligne",
    "task_16": "Utiliser Choix de dé\n10 fois en mode\nspécial en ligne",
    "task_17": "Utiliser Champ de protection\n10 fois en mode\nspécial en ligne",
    "task_18": "Renvoyer 5 pions\nen jouant en ligne",
    "task_19": "Atteindre la maison\navec 3 pions\nen jouant en ligne",
    "task_20": "",
    "task_21": "Atteindre le niveau %{num}",
    "task_22": "Se connecter %{num} jours",
    "task_23": "Gagner %{num} parties\nen jouant en ligne",
    "task_24": "Gagner %{num} parties\ncontre un ordinateur",
    "task_25": "Renvoyer %{num} pions\nen jouant en ligne",
  },
  "TeamUp2V2": {
    "Common_Choose_Number_Team": "Équipe",
    "Common_Choose_Number_2v2_titlepower": "Spécial 2c2",
    "Common_Choose_Number_2v2_titleclassic": "Classique 2c2",
    "Teamup_choose_tips1": "Invitez un contact ou lancez la recherche automatique.",
    "Teamup_choose_tips2": "Vous pouvez jouer maintenant.",
    "Teamup_choose_betchange_title": "La mise a changé.",
    "Teamup_choose_betchange_content": "La mise a été ajustée à {coins}, car votre adversaire n'a pas assez de pièces.",
    "Teamup_choose_join_leave_title": "Quitter la partie ?",
    "Teamup_choose_join_leave_content": "Votre équipe sera dissoute. Quitter ?",
    "Teamup_Matching_leave_content": "Partie en cours, impossible de quitter.",
    "Teamup_Game_inviting": "{name} vous invite à une partie en équipe en ligne.",
  },
  "Region": {
    "Disgree_Content": "Malheureusement, Ludo World vous est inaccessible pour le moment. Nos données sont stockées en dehors de l'EEE et nos équipes ont besoin d'accéder à ces données à partir d'autres juridictions afin de vous fournir nos services.",
    "Back": "Retour",
    "Data_Agreement_Content_APK": "Ludo World est un produit proposé par Proxima Beta PTE.Limited, une société basée dans la République de Singapour, qui traitera vos données en dehors de l'Espace économique européen (y compris en République populaire de Chine) afin de fournir nos services. Veuillez noter qu'un tel transfert comporte des risques, notamment la soumission de vos données à des régimes juridiques différents, dont le niveau de protection est différent que celui proposé dans le pays où vous vous trouvez.Pour plus d'informations, veuillez consulter notre  <b><u><i click=\"handler\">Politique de confidentialité</i></u></b>. En appuyant sur Accepter, vous acceptez le transfert de vos données dans une zone en dehors de l'Espace économique européen.",
    "Data_Agreement_Content_FB": "Ludo World est un produit proposé par High Morale Development Limited, une société basée à Hong Kong, qui traitera vos données en dehors de l'Espace économique européen (y compris en République populaire de Chine) afin de fournir nos services. Veuillez noter qu'un tel transfert comporte des risques, notamment la soumission de vos données à des régimes juridiques différents, dont le niveau de protection est différent que celui proposé dans le pays où vous vous trouvez.Pour plus d'informations, veuillez consulter notre  <b><u><i click=\"handler\">Politique de confidentialité</i></u></b>. En appuyant sur Accepter, vous acceptez le transfert de vos données dans une zone en dehors de l'Espace économique européen.",
    "Agree": "Accepter",
    "Disagree": "Refuser",
    "Under_Age_Content": "Vous avez moins de {age} ans, vous ne pouvez donc malheureusement pas accéder à Ludo World pour le moment.",
    "Data_Outside_Content": "Acceptez-vous de transférer vos données en dehors de l'Espace économique européen ?",
    "Data_Outside_Title": "Données transférées en dehors de l'EEE",
    "Delete_Notice_Title": "Remarque",
    "Delete_Notice_Content": "Malheureusement, Ludo World vous est inaccessible pour le moment. Nos données sont stockées en dehors de l'EEE et nos équipes ont besoin d'accéder à ces données à partir d'autres juridictions afin de vous fournir nos services. Appuyez sur \"Retour\" pour changer d'avis ou appuyez sur Supprimer le compte pour effacer votre compte.",
    "Delete_Account": "Supprimer le compte",
    "Delete_Delete": "Supprimer",
    "Delete_Content": "Souhaitez-vous supprimer votre compte ? Le système supprimera automatiquement votre compte et vos données après 7 jours. Vous pouvez annuler la suppression en vous reconnectant au jeu dans ces 7 jours.",
    "Chat_Off_Title": "Activer le fil de discussion ?",
    "Chat_Off_Content": "Lorsque le fil de discussion est activé, les autres joueurs peuvent voir vos messages. Il peut être désactivé dans les paramètres.",
    "Region_Title": "Région",
    "Region_Content": "Sélectionnez votre région/pays de résidence.",
    "Agree_Title": "Date de naissance",
    "Agree_Content": "Afin d'optimiser votre expérience, veuillez nous indiquer si vous avez au moins {age} ans.",
    "Privacy_Title": "Politique de confidentialité",
    "Privacy_Content": "En appuyant sur \"Accepter\", je confirme\navoir lu et accepté la\n<b><u><color = #535BBF click=\"handler\">Politique de confidentialité</color></u></b> de Ludo World.",
    "Privacy_Disagree": "Malheureusement, sans accepter notre politique de confidentialité, il vous est impossible de profiter des services de Ludo World.",
    "Agreement_Title": "Conditions générales d'utilisation",
    "Agreement_Content": "En appuyant sur \"Accepter\", je confirme\navoir lu et accepté les\n<b><u><color = #535BBF click=\"handler\">Conditions générales d'utilisation</color></u></b>.",
    "Agreement_Disagree": "Malheureusement, sans accepter nos conditions générales d'utilisation, il vous est impossible de profiter des services de Ludo World.",
    "YES": "Oui",
    "NO": "Non",
  },
  "FriendSystem": {
    "Friend_Main_title": "Contacts",
    "Friend_Main_list": "Liste",
    "Friend_Main_add": "Ajouter",
    "Friend_Main_request": "Demandes",
    "Friend_Main_list_FB": "Amis FB",
    "Friend_Main_list_Game": "Contacts du jeu",
    "Friend_Main_list_reciveandsend": "Tout envoyer",
    "Friend_Main_list_reciveandsend_Detail": "Les pièces envoyées à vos contacts ne sont pas déduites de votre solde.",
    "Friend_Main_Add_Recent": "Récent",
    "Friend_Select_Tip_NewRequest": "{num} [demande d'amis|demandes d'amis]",
    "Friend_Main_Request_Num_Tip": "Dernières 99 demandes sauvegardées.",
    "Friend_list_nofbfirends": "Aucun ami Facebook en contact,\ninvitez-les à vous rejoindre !",
    "Friend_list_invitefirends": "Jouons à Ludo World ensemble !",
    "Friend_list_nogamefirends": "Aucun contact,\najoutez-en dans l'onglet Ajouter !",
    "Friend_Add_NoRecent": "Aucun affrontement récent",
    "Friend_Request_NoRequest": "Aucune demande d'amis",
    "Friend_list_online": "En ligne",
    "Friend_list_offline": "Hors ligne",
    "Friend_list_playing": "En jeu",
    "Friend_Not_Accept": "Ne plus accepter de demande d'amis.",
    "Friend_sendcoins_succeed": "Envoyer 100 pièces à {name}",
    "Friend_sendcoins_fail": "La limite de cadeaux quotidienne a été atteinte.",
    "Friend_collectandsendall_succeed": "Envoyer {num} pièces",
    "Friend_collectandsendall_nofirendtosend": "Aucun contact à qui l'envoyer",
    "Friend_invite_title": "Invitation",
    "Friend_invite_bottoningame": "En jeu",
    "Friend_invite_whoinvite": "{name} vous invite à jouer !",
    "Friend_invite_reject": "Refuser",
    "Friend_invite_accept": "Accepter",
    "Friend_invite_friendpower": "Spécial amical",
    "Friend_invite_friendclassic": "Classique amical",
    "Friend_invite_teamuppower": "Spécial amical en équipe",
    "Friend_invite_teamupclassic": "Classique amical en équipe",
    "Friend_invite_sentsucceed": "Invitation envoyée",
    "Friend_invite_sentfail": "Échec de l'envoi",
    "Friend_invite_more_btn": "Inviter aussi :",
    "Friend_collectcoins_fail": "Vous avez déjà obtenu des pièces de {num} contacts aujourd'hui. Revenez demain pour plus de cadeaux.",
    "Friend_collectall_succeed": "Récupérer {coins} pièces d'amis !",
    "Friend_Add_Recent_Source1": "Classique en ligne à 2 joueurs",
    "Friend_Add_Recent_Source2": "Classique en ligne à 4 joueurs",
    "Friend_Add_Recent_Source3": "Spécial en ligne à 2 joueurs",
    "Friend_Add_Recent_Source4": "Spécial en ligne à 4 joueurs",
    "Friend_Add_Recent_Source5": "Classique en ligne en équipe",
    "Friend_Add_Recent_Source6": "Spécial en ligne en équipe",
    "Friend_Add_Recent_Source7": "Classique amical",
    "Friend_Add_Recent_Source8": "Spécial amical",
    "Friend_Add_Recent_Source9": "Classique amical en équipe",
    "Friend_Add_Recent_Source10": "Spécial amical en équipe",
    "Friend_Request_Source_Recent": "Partie récente",
    "Friend_Request_Source_Suggested": "Suggestion",
    "Friend_Request_Source_Leaderboard": "Classement",
    "Friend_gametime-year": "Il y a {num} a",
    "Friend_gametime-day": "Il y a {num} j",
    "Friend_gametime-hour": "Il y a {num} h",
    "Friend_gametime-minitue": "Il y a {num} min",

  },
  "APPAdsText": {
    "ItemsAddOne": "Objets +1",
  },
  "Common": {
    "Lobby_Bonus_collecet": "Récupérer",
    "Common_Game_teamup_UserGuide_finish_title": "Bien joué !",
    "Game_friends_invite_start": "Vous pouvez jouer maintenant.",
    "": "",
    "Title_ModifyInfo": "Modifier les infos",
    "shortCut_create_success": "Le raccourci a été créé.",
    "MainScenes_Ranking": "Classement",
    "MainScenes_FreeCoins": "Pièces gratuites",
    "MainScenes_Mission": "Défi",
    "Settings_on": "Activé",
    "Settings_off": "Désactivé",
    "Game_EndOrder_Congratulations": "Félicitations",
    "EM_ERR_FETCH_FRIEND_FAIL = -10002": "Échec du chargement des données. Réessayez plus tard.",
    "EM_ERR_FETCH_ONLINE_FAIL = -10003": "Échec du chargement des données. Réessayez plus tard.",
    "EM_ERR_FETCH_LOGIN_TIME_FAIL = -10004": "Échec du chargement des données. Réessayez plus tard.",
    "EM_ERR_NOT_ADD_PLAYER = -10005": "Échec de l'action, réessayez plus tard.",
    "EM_ERR_FRIEND_LIST_FULL = -10006": "Votre liste de contacts est pleine. Supprimez un contact pour en ajouter un nouveau.",
    "EM_ERR_PEER_FRIEND_LIST_FULL = -10007": "Impossible d'ajouter {name}, sa liste de contacts est pleine.",
    "EM_ERR_UPDATE_FRIEND_FAIL = -10008": "Échec du chargement des données. Réessayez plus tard.",
    "EM_ERR_PLAYER_REFUSE_ADD = -10009": "{name} n'accepte pas de demande de contact.",
    "EM_ERR_ALREADY_IN_ADD_LIST = -10010": "",
    "EM_ERR_ALREADY_IN_GAME_FRIEND_LIST = -10011": "Ce contact est déjà dans votre liste.",
    "EM_ERR_ALREADY_IN_PLAT_FRIEND_LIST = -10012": "Ce contact est déjà dans votre liste.",
    "EM_ERR_NOT_IN_FRIEND_LIST = -10013, //": "Échec de l'action, réessayez plus tard.",
    "EM_ERR_FETCH_GAME_RECORD_FAIL = -10014": "Échec du chargement des données. Réessayez plus tard.",
    "EM_ERR_CANNOT_ADD_SELF = -10015": "Échec de l'ajout, réessayez plus tard.",
    "LoginMainLabel_Guest_Title": "Connexion en tant qu'invité(e). Impossible de",
    "Language_type": "Français",
  },
  "GoodsName": {
    "GoodsName_Cricket": "Cricket",
    "GoodsName_Jewelry": "Fantaisie",
    "GoodsName_Airdrop_box": "Parachute",
    "GoodsName_Cupid": "Cupidon",
    "GoodsName_Cat": "Chat",
    "GoodsName_Planet": "Planète",
    "GoodsName_Default": "Par défaut",
    "Shop_luckybox": "Boîte à surprise",
    "Shop_luckybox_GiftCardtitle": "Carte cadeau",
    "Shop_luckybox_GiftCard": "Récupérez votre carte cadeau dans vos messages.",
    "GoodsName_Item_Cards": "Cartes d'objets",
    "GoodsName_Item_Cards_num": "Cartes d'objets x {num}",
    "GoodsName_Neon": "Néon",
    "GoodsName_Chick": "Poulet",
    "GoodsName_First_AidKit": "Premiers secours",
    "GoodsName_Machinery": "Méca",
    "GoodsName_Diwali": "Diwali",
    "GoodsName_Christmas": "Noël",
    "GoodsName_Gems": "Gemmes",
  },
  "AdsText": {
    "Btn_Lucky_Show_Ad": "Visionner une pub",
    "Lab_Lucky_Next": "Prochaine récompense :",
    "Lab_Lucky_Declare": "Visionnez une publicité pour tourner la roue !",
    "Btn_Double_Reward": "Bonus double",
    "Btn_Reward_x2": "2 fois plus !",
    "Btn_No_Thanks": "Non merci",
    "Ad_Confirm_Cions": "Visionnez des pubs pour obtenir {num} pièces.",
    "Ad_Confirm_Item": "Visionnez des pubs pour obtenir un exemplaire de chaque objet.",
    "Ad_Confirm_Task": "Visionnez des pubs pour avancer dans les défis.",
    "Ad_Confirm_Spin": "Visionnez des pubs pour obtenir {spin}.",
  },
  "NewUserText": {
    "NewPlayerBonus_Title": "Bonus du débutant",
    "NewPlayerBonus_Day": "Jour",
    "NewPlayerBonus_Collect": "Récupérer",
    "NewPlayerBonus_Collected": "Récupéré",
    "NewPlayerBonus_LoginTips": "{num} [jour|jours] de connexion ~",
    "NewPlayerBonus_EventTime": "Durée de l'événement :",
    "NewPlayerBonus_Coins": "Pièces",
    "NewPlayerBonus_Skins": "Style",

  },
  "Shop": {
    "Shop_Tab_Coins": "Pièces",
    "Shop_Tab_Spin": "Style",
    "Shop_Tab_Items": "Objets",
    "Shop_Tab_Spin_BubbleTab": "Bulle",
    "Shop_Tab_Spin_DiceTab": "Dé",
    "Shop_Tab_Spin_ThemeTab": "Thème",
    "Shop_Airdrop_box": "Parachute",
    "Shop_Coins": "{num}",
    "Shop_Airdrop_box_day": "Parachute ({num} j)",
    "Shop_Cricket": "Cricket",
    "Shop_Cricket_day": "Cricket ({num} j)",
    "Shop_Cupid": "Cupidon",
    "Shop_Cupid_day": "Cupidon ({num} j)",
    "Shop_Jewelry": "Fantaisie",
    "Shop_Jewelry_day": "Fantaisie ({num} j)",
    "Shop_Cat": "Chat",
    "Shop_Cat_day": "Chat ({num} j)",
    "Shop_Planet": "Planète",
    "Shop_Planet_day": "Planète ({num} j)",
    "Shop_Neon": "Néon",
    "Shop_Neon_day": "Néon ({num} j)",
    "Shop_Chick": "Poulet",
    "Shop_Chick_day": "Poulet ({num} j)",
    "Shop_First_AidKit": "Premiers secours",
    "Shop_First_AidKit_day": "Premiers secours ({num} j)",
    "Shop_Machinery": "Méca",
    "Shop_Machinery_day": "Méca ({num} j)",
    "Shop_Diwali": "Diwali",
    "Shop_Diwali_day": "Diwali ({num} j)",
    "Shop_Christmas": "Noël",
    "Shop_Christmas_day": "Noël ({num} j)",
    "Shop_Item": "Cartes d'objets ({num})",
    "Shop_Label_New": "Nouv.",
    "Shop_Label_Hot": "Wow",
    "Shop_Label_Off": "Réduc",
    "Shop_Label_Extar": "Extra",
    "Shop_Label_BestDeal": "Meilleure offre",
    "Shop_Day_day": "jour",
    "Shop_Buy_Success": "Achat validé, vous avez utilisé {spin}.",
    "Shop_Backpack_Tip": "Allez voir les objets dans votre sac.",
    "Button_Reload": "Recharger",
    "Button_AD_Free": "Gratuit",
    "Shop_Lucky": "Au hasard",
    "Shop_BuyGift_Success": "Achat validé, allez dans le sac pour l'utiliser.",
    "Shop_Airdrop_box_Permanent": "Parachute (permanent)",
    "Shop_Cricket_Permanent": "Cricket (permanent)",
    "Shop_Cupid_Permanent": "Cupidon (permanent)",
    "Shop_Jewelry_Permanent": "Fantaisie (permanent)",
    "Shop_Cat_Permanent": "Chat (permanent)",
    "Shop_Planet_Permanent": "Planète (permanent)",
    "Shop_Neon_Permanent": "Néon (permanent)",
    "Shop_Chick_Permanent": "Poulet (permanent)",
    "Shop_First_ AidKit_Permanent": "Premiers secours (permanent)",
    "Shop_Machinery_Permanent": "Méca (permanent)",
    "Shop_Diwali_Permanent": "Diwali (permanent)",
    "Shop_Lucky_Detail": "Cricket (1 j), Fantaisie (1 j), Planète (1 j)",
    "Shop_WatchTV_Detail": "Visionnez une publicité pour obtenir un objet !",
    "Shop_Buy_Fail": "Échec de l'achat. Réessayez plus tard.",
    "Shop_Buy_ItemFail": "Échec du chargement des données. Réessayez plus tard.",
    "Shop_Buy_Success_Prop": "Achat validé.",
    "Shop_Buy_Prop_Describe": "Les cartes d'objets peuvent être échangées contre des objets.",
    "Shop_itemcard": "Cartes d'objets",
    "Shop_itemcard_number": "{num} [carte|cartes]",
    "Shop_Tab_Name": "Boutique",
  },
  "ReportText": {
    "Report_Panel": "Signalement",
    "Report_Title": "Signalement",
    "Report_People": "Signaler : {name}",
    "Report_Content1": "Violence verbale",
    "Report_Content2": "Tricherie",
    "Report_Content3": "Autres",
    "Report_Success": "Signalé",
    "Report_Res_Title": "Sanction",
    "Report_Res_Content": "La personne que vous avez signalée, {name}, a été restreinte/suspendue.",
  },
  "RetainUser": {
    "newsuserA_classic_tips": "Essayez le mode spécial pour encore plus de fun !",
    "newsuserA_power_tips": "Essayez le mode classique, c'est facile !",
    "newsuserA_tips_quit": "Quitter",
    "newsuserA_tips_try": "Essayer",
    "newsuserB_tips_stay": "Terminez {num1} parties ({num2}/{num3}) pour obtenir la caisse verte.",
    "newsuserB_tips_minitips": "Obtenez des pièces ou une carte cadeau de 100 ₹ (environ 1 €) !",
    "newsuserB_tips_getluckybox_title": "Caisse verte",
    "newsuserB_tips_getluckybox_content": "Obtenez une carte cadeau de 100 ₹ (environ 1 €) \nou des pièces ! Récupérez le tout dans votre sac.",
    "newsuserB_tips_getluckybox_tips": "Obtenez des pièces ou une carte cadeau de 100 ₹ (environ 1 €) !",
    "newsuserB_tips_getluckybox_cannotopen": "Ouvrir après {num}",
    "newsuserB_tips_getluckybox_openfail": "Échec de l'ouverture. Réessayez plus tard.",
    "newsuserB_tips_getluckyboxopen": "Ouvrir la caisse cadeau et obtenez des pièces ou une carte cadeau de 100 ₹ (environ 1 €) !",
    "newsuserA_tips_stay": "Rester",
    "newsuserA_tips_leave": "Quitter ?",
    "newsuserA_tips_open": "Ouvrir",
  },
  "MainChat": {
    "Button_Team_SendTeamRecruitment": "Proposer de faire équipe",
    "Chat_World_NoChatTypeTips": "[Ce genre de message n'est pas pris en charge.]",
    "Chat_World_EmptyTips": "Le message ne peut pas être vide.",
    "Chat_NoMessage_Tips": "Appuyez ici pour discuter.",
    "Chat_Tab_World": "Monde",
    "Chat_Tab_Team": "Équipe",
    "Chat_Tab_Friends": "Contacts",
    "Chat_World_DefaltTips": "Écrire un message",
    "Button_Chat_Send": "Envoyer",
    "Chat_Team_Send_WorldChat": "Envoyer au fil mondial",
    "Chat_Team_Join": "Rejoindre",
    "Chat_Local_Tips": "Discussion locale",
    "Chat_Friends_NewMessageTips": "Nouveau message",
    "Chat_Friends_ClickTips": "Appuyez sur le contact pour lui parler.",
    "Chat_Friends_NoFriendsTips": "Vous devez avoir des contacts.",
    "Chat_World_LocalTips": "Appuyez ici pour discuter en local.",
    "Chat_Low_Level": "Jouez plus de parties pour atteindre le niveau {num} et discuter !",
    "Chat_World_JoinTips": "Vous avez rejoint le fil mondial.",
    "Chat_Local_JoinTips": "Vous avez rejoint le fil local.",
    "Chat_Close_Tips": "Activer le fil de discussion ?",
    "Tips_Team_SendSuccess": "La proposition d'équipe a été envoyée dans le fil de discussion mondial.",
    "Chat_SendTooFast": "Vous envoyez trop de messages. Veuillez réessayer plus tard.",
  },
  "RedEnvelope": {
    "HB_Bag_Title": "Sac d'or",
    "HB_Coins_Tips": "{num1} ~ {num2} pièces",
    "HB_Coins_Tipstop": "{num1} pièces",
    "HB_Image_Text": "Partagez votre chance et ouvrez le sac d'or !",
    "HB_Open_Require": "Invitez vos contacts à l'ouvrir ensemble !",
    "HB_Open_Tips": "Plus vous avez de contacts qui acceptent l'invitation, plus vous obtenez de pièces !",
    "HB_NoOpen_Tips1": "En attente d'acceptation de vos contacts à partir du lien envoyé.",
    "HB_NoOpen_Tips2": "Une fois qu'un contact accepte l'invitation à partir du lien envoyé, vous pouvez ouvrir le sac d'or.",
    "HB_Join_One": "Plus vous avez de contacts qui acceptent l'invitation, plus vous obtenez de pièces !",
    "HB_Join_More": "Plus vous avez de contacts qui acceptent l'invitation, plus vous obtenez de pièces !",
    "HB_Can_Open_Tips": "Ouvrez le sac d'or aujourd'hui !",
    "HB_Share_Title1": "Des pièces dans Ludo World, ouvrez le sac d'or pour obtenir des récompenses.",
    "HB_Share_Title2": "Ouvrez votre sac d'or dans Ludo World et tentez votre chance !",
    "HB_Btn_Open": "Ouvrir",
    "HB_Btn_Open_noinvite": "Inviter",
    "HB_Collect_Fail": "Oups, vous n'avez plus de pièces.",
  },
  "LuckyBag": {
    "Clearing_Win_Share_Title": "Boîte mystère",
    "Clearing_Win_Share_Content": "Invitez vos contacts à l'obtenir ensemble.",
    "Clearing_Loser_Share_Title": "Pièces gratuites",
    "Clearing_Loser_Share_Content": "Invitez vos contacts à les obtenir ensemble.",
    "Clearing_Win_Ads_Title": "Boîte mystère",
    "Clearing_Win_Ads_Content": "Regardez une PUB pour l'obtenir.",
    "Clearing_Loser_Ads_Title": "Pièces gratuites",
    "Clearing_Loser_Ads_Content": "Regardez une PUB pour les obtenir.",
    "Clearing_Welfare_Share_Title": "Invitez vos contacts à obtenir",
    "Clearing_Share_Finish": "Appuyez sur le lien reçu sous {num} s pour recevoir votre récompense !",
    "Clearing_Welfare_Ads_Title": "Besoin de pièces ?",
    "Clearing_Welfare_Ads_Content": "Regardez une PUB pour en obtenir.",
    "Clearing_Share_Loser": "Lien envoyé invalide, veuillez renvoyer le lien partagé.",
  },
  "LuckSeven": {
    "Un_Lock_tips": "Encore {num1} lancer pour débloquer plus !",
    "Not_Enough_Gold": "Pièces insuffisantes",
    "High_Laid": "Palier maximum atteint !",
    "Low_Laid": "Palier minimum atteint !",
    "Show_FreeBet": "Misez gratuitement {num2} fois !",
    "Coins": "PIÈCES",
    "laid_start_To_end": "{start} À {end}",
    "WIN": "VICTOIRE",
    "Get_Free_Bet": "obtenez des mises gratuites !",
    "Double": "Double {point}",
    "Error": "Erreur de données, veuillez rafraîchir la page.",
  },
  "EliminatGame": {
    "Select_Hint": "Veuillez choisir le nombre de pièces à miser.",
    "Not_Coins": "Vous n'avez pas assez de pièces. En obtenir à la boutique ?",
    "Min_Coins": "Montant minimum de pièces déjà atteint.",
    "Max_Coins": "Montant maximum de pièces déjà atteint.",
    "Win": "VICTOIRE",
    "Big_Win": "Gros lot",
    "Super_Winner": "Super victoire",
    "Total_Win": "Victoire totale",
    "Fish_Party": "Mare-à-thon",
    "Quit_Hint": "Vous êtes actuellement dans une partie. Voulez-vous vraiment quitter ?",
    "AllIn": "Tout miser",
    "Auto": "auto",
    "Start": "Jouer",
    "EliminatGameTitle": "Règles du jeu",
    "Game_Rules": "Règles du jeu",
    "Explain": "Règles de la Mare-à-thon",
    "Party_Text": "Vous pouvez faire disparaître trois poissons identiques situés côte à côte sur la même ligne et obtenir des récompenses.\n\nAprès leur disparition, le jeu continuera de générer des poissons jusqu'à ce qu'il soit impossible de les faire disparaître.",
    "Select_Fish": "Choisissez sur quel poisson parier",
    "Eliminate_Award": "Éliminez et obtenez des pièces !",
    "Records": "Voir la récompense et les records",
    "Settlement_Rules": "Règlement",
    "Settlement_Rules_Text": "Vous pouvez faire disparaître trois poissons identiques situés côte à côte sur la même ligne et obtenir des récompenses.\nChaque poisson compte de manière indépendante dans le calcul de la récompense.\nLe type de poisson et le nombre de disparitions influencent la récompense.\nLes gains sont multipliés en fonction du multiplicateur suivant.\nPlus vous faites disparaître de poissons sur la ligne, plus vous obtiendrez de récompenses !",
    "Back_Game": "Retour au jeu",
    "Game_Name": "Mare-à-thon",
    "Activity_Ended": "L'activité est terminée.",
  },
  "NewDiBao": {
    "NewDiBaoTitle": "PACK D'OR",
    "Tip": "Obtenez les pièces d'or du jour.",
    "mulit": "Récupérer",
    "extra": "EXTRA",
    "basic": "BASIQUE",
    "coins": "PIÈCES",
    "togle": "Regardez une PUB pour obtenir {num} pièces !",
    "Before_Game_GoldEnough": "Vous n'avez pas assez de pièces.",
    "StartGame": "Lancer le jeu",
  },
  "InsufficientCoin": {
    "title": "Il vous faut au moins {num} pièces pour jouer.",
    "tip": "Vous possédez désormais {haveCoin} pièces.",
    "goScene": "Jeu recommandé",
    "toOtherModel": "Vous n'avez pas assez de pièces ({coins}) pour commencer à jouer. Choisir un autre mode ?",
    "friend": "Contacts",
    "computer": "Ordinateur",
    "toOfferPlay": "Vous n'avez pas assez de pièces. Aller au mode recommandé ?",
  }
}
let loadMessage = function(language, dataID, isChange) {

};
exports.loadMessage = loadMessage;