'use strict';
if (!window.i18n) {
  window.i18n = {};
}

if (!window.i18n.languages) {
  window.i18n.languages = {};
}

window.i18n.languages['Indonesian'] = {
  "label_text": {
    "Ads_getRewards_Title": "Ambil Hadiah",
    "Ads_CountDown_tips": "Hadiah Selanjutnya Dalam:",
    "Ads_watchAd_Title": "Tonton Iklan",
    "Auto_Game": "Otomatis",
    "Button_Guest_Facebook": "Login Dengan Facebook",
    "Button_Guest_Continue": "Lanjut Sebagai Tamu",
    "Button_Common_Confirm": "Oke",
    "Button_Common_Yes": "Ya",
    "Button_Common_No": "Tidak",
    "Button_Common_Next": "Selanjutnya",
    "Button_Common_Restart": "Restart",
    "Button_Common_Return": "Kembali",
    "Button_Common_Share": "Bagikan",
    "Button_Common_Start": "Mulai",
    "Button_Common_Facebook": "Login Melalui Facebook",
    "Button_Common_Guest": "Tamu",
    "Common_Guest_BindAccount": "Hubungkan Akun Facebook?",
    "Common_Guest_BindAccountFail": "Gagal Menghubungkan Ke Facebook. Coba Lagi Nanti, Ya!",
    "Common_Guest_RepeatBind": "Udah Ada Akun Facebook Yang Terhubung. Mau Log In Dengan Akun Facebook Itu?",
    "Common_Guest_Confirm": "Karena Log In sebagai tamu, kamu tidak bisa main bareng teman.\nLog In dengan Facebook agar bisa:\n1. Main bareng teman\n2. Memasang foto profil dalam game\n3. Main di berbagai perangkat menggunakan satu akun.",
    "Common_Online_ShareContent": "Mantep! Karena aku peringkat #{1} di {0}, aku jadi dapet {2} Koin!",
    "Common_Scene_Teamup_Teammateturn": "Kamu Bisa Lanjut Main Dan Bantuin Rekan Tim. Yuk, Gas!",
    "Common_Game_Props_GetTipsTitle_DoubleDice": "Dadu Kembar",
    "Common_Game_Props_GetTipsContent_DoubleDice": "Lempar Dua Dadu Dengan Angka Yang Sama.",
    "Common_Game_Props_GetTipsTitle_AssignDice": "Kontrol Dadu",
    "Common_Game_Props_GetTipsContent_AssignDice": "Atur Angka Berapa Yang Ingin Kamu Dapatkan",
    "Common_Game_Props_GetTipsTitle_Protection": "Tameng Perlindungan",
    "Common_Game_Props_GetTipsContent_Protection": "Lindungi Bidakmu Dari Bidak Pemain Lain Selama 1 Putaran",
    "Common_Game_Props_GetTipsTitle_LuckyNumber": "Dadu Emas",
    "Common_Game_Props_GetTipsContent_LuckyNumber": "Selama 1 Babak, Semua Pemain Yang Mendapatkan Angka Ini Bisa Melempar Dadu Lagi.",
    "Common_Scene_Props_Introduce_Title": "Info Prop Mode",
    "Common_Scene_Props_introduce_luckyNumber": "Dadu Emas",
    "Common_Scene_Props_introduce_luckyNumber_": "Selama 1 Babak, semua pemain yang mendapatkan angka ini langsung bisa melempar Dadu lagi.",
    "Common_Scene_Props_introduce_DoubleDice": "Dadu Kembar",
    "Common_Scene_Props_introduce_DoubleDice_": "Angka yang keluar pada Dadu akan di-double. Pemain harus maju sebanyak angka yang keluar. Setelah menggunakan Item ini, jika pemain mendapatkan Mata Dadu 6, maka pemain tidak akan mendapatkan bonus melempar Dadu dan tidak bisa menggerakkan Bidak.",
    "Common_Scene_Props_introduce_AssignDice": "Kontrol Dadu",
    "Common_Scene_Props_introduce_AssignDice_": "Pemain memilih jumlah angka yang akan didapatkan di Dadu. Jika mendapatkan angka 6, memulangkan Bidak lawan, atau mencapai Garis Finish, pemain akan mendapatkan bonus jatah melempar Dadu.",
    "Common_Scene_Props_introduce_Protection": "Tameng",
    "Common_Scene_Props_introduce_Protection_": "Melindungi semua Bidak agar tidak dipulangkan lawan. Aktif selama 1 Babak.",
    "Common_Game_Props_ShowTips_LuckyNumber": "Bonus Lempar Dadu",
    "Common_Game_Props_ShowTips_LuckyNumber_": "Mendapatkan Satu Jatah Lempar Dadu Saat Ada Bidak Yang Mencapai Garis Finish",
    "Common_Game_Props_ShowTips_DoubleDice": "Dadu Kembar",
    "Common_Game_Props_ShowTips_DoubleDice_": "Angka Dadu Yang Didapatkan Dan Gerakan Bidak Akan Di-double",
    "Common_Game_Props_ShowTips_AssignDice": "Kontrol Dadu",
    "Common_Game_Props_ShowTips_AssignDice_": "Atur Angka Berapa Yang Ingin Kamu Dapatkan",
    "Common_Game_Props_ShowTips_Protection": "Tameng Perlindungan",
    "Common_Game_Props_ShowTips_Protection_": "Lindungi Bidakmu Dari Bidak Pemain Lain Selama 1 Putaran",
    "Common_Game_Props_Haved": "Item Power Hanya Bisa Digunakan Sebelum Kamu Melempar Dadu.",
    "Common_Game_Props_NotHaved": "Kamu Belum Punya Item Power Ini.",
    "Common_Team": "Tim",
    "Common_Choose_Color": "Pilih Warna",
    "Common_Game_Online_MyPlace": "Akhirnya Online Juga!",
    "Common_Choose_Number": "Jumlah Pemain",
    "Common_Choose_Bet": "Bayar Tiket",
    "Common_Choose_Mode": "Pilih Mode",
    "Common_Choose_Number_players": "Pemain",
    "Common_Choose_Win": "Berhasil:",
    "Common_Choose_Entry": "Harga:",
    "Common_Choose_Number_two": "2",
    "Common_Choose_Number_four": "4",
    "Common_Choose_Number_multi": "2~4",
    "Common_Choose_Number_Team": "Tim",
    "Common_Choose_Number_2v2": "2V2",
    "Common_Game_Props_share": "Bagikan Untuk Mendapatkan\nItem!",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Pilih Angka",
    "Common_Game_Props_sharetogetprops_title": "Bagikan Ke Temanmu Dan Dapatkan 3 Item Power GRATIS!",
    "Common_Game_Props_sharetogetprops_share": "Bagikan",
    "Common_Game_Props_sharetogetprops_aftershare": "Setiap Laga Hanya Bisa Dibagikan Satu Kali",
    "Friend_Room_Entering": "Memasuki Room...",
    "Friends_Invite": "Ajak Lewat:",
    "GameName": "Ludo World",
    "Game_Common_start": "Mulai Laga",
    "Game_EndTitle_Win": "Berhasil",
    "Game_EndTitle_Lose": "Gagal",
    "Game_EndOrder_1": "Juara 1",
    "Game_EndOrder_2": "Juara 2",
    "Game_EndOrder_3": "Juara 3",
    "Game_EndOrder_Win": "Berhasil",
    "Game_EndOrder_4": "Juara 4",
    "Game_EndOrder_5": "Ke-5",
    "Game_EndOrder_6": "Ke-6",
    "Game_EndOrder_Lose": "Gagal",
    "Game_EndOrder_Playing": "Main",
    "local_Result_title": "Hasil",
    "Game_Online_Auto1": "Maju Otomatis",
    "Game_Online_Auto2": "Tap Di Sini Untuk Berhenti",
    "Game_Props_TopTitle_LuckyNumber": "Dadu\nEmas",
    "Game_Props_ItemTips_DoubleDice": "Dadu Kembar: Gunakan untuk melemparkan dua Dadu dengan angka yang sama. Pemain harus maju sebanyak angka yang keluar. Setelah menggunakan Item ini, jika pemain mendapatkan Mata Dadu 6, maka pemain tidak akan mendapatkan bonus melempar Dadu dan tidak bisa menggerakkan Bidak.",
    "Game_Props_ItemTips_AssignDice": "Kontrol Dadu: Pemain memilih jumlah angka yang akan didapatkan di Dadu. Jika mendapatkan angka 6, memulangkan Bidak lawan, atau mencapai Garis Finish, pemain akan mendapatkan bonus jatah melempar Dadu.",
    "Game_Props_ItemTips_Protection": "Tameng: Melindungi semua Bidak agar tidak dipulangkan lawan. Aktif selama 1 Babak.",
    "Game_leaderboard_title": "Papan Peringkat",
    "Game_leaderboard_global": "Global",
    "Game_leaderboard_NotRanked": "Tidak Ada Peringkat",
    "Game_leaderboard_tips": "Stat Akan Di-update Setiap Hari Senin.",
    "Game_leaderboard_tips2": "Hanya Mode Online Yang Akan Dihitung.",
    "Game_leaderboard_tipsoneline": "Stat (Mode Online) Akan Di-update Setiap Hari Senin.",
    "Game_Computer_PlayerName1": "AI1",
    "Game_Computer_PlayerName2": "AI2",
    "Game_Computer_PlayerName3": "AI3",
    "Game_Computer_level_choose": "Pilih Level",
    "Game_Computer_Self": "Kamu",
    "Game_Computer_level_easy": "Mudah",
    "Game_Computer_level_normal": "Standar",
    "Game_Computer_level_hard": "Sulit",
    "Game_Computer_PlayerNameEasy": "AI{num} Mudah",
    "Game_Computer_PlayerNamenormal": "AI{num} Standar",
    "Game_Computer_PlayerNamehard": "AI{num} Sulit",

    "Game_local_Remove_comfirm": "Yakin Mau Mengeluarkan Pemain Ini?",
    "Game_local_Remove_guide_title": "Keluarkan Pemain",
    "Game_local_Remove_guide_content1": "Yang Tidak Mau Main",
    "Game_Friend_Pnael_Title": "Main Bareng Teman",
    "Game_Friend_Select_Mode": "Pilih Mode Permainan",
    "Game_Friend_Create": "Buat Room",
    "Game_Friend_Join": "Gabung",
    "Game_Friend_Join_Clear": "Hapus",
    "Game_Friend_GameMode": "Pilih Mode Permainan",
    "Game_Friend_Enter_RoomCode": "Masukkan Kode Room",
    "Game_friends_invite_code": "ID Room",
    "Game_friends_invite_tips_cannot": "Menunggu Pemain...",
    "Game_friends_invite_tips_can": "Tunggu Lagi Atau Mulai Sekarang.",
    "Game_friends_join_tips": "Masukkan ID Room",
    "Game_friends_join_join": "Gabung",
    "Game_friends_join_wait": "Menunggu {who} Sebelum Mulai",
    "Game_friends_choose_classic": "Klasik",
    "Game_friends_choose_power": "Power",
    "Game_friends_choose_mode": "Mode",
    "Game_friends_invite_waiting": "Menunggu Pemain...",
    "Game_friends_invite_waitormore": "Tunggu Lagi Atau Mulai Sekarang",
    "Game_friends_invite_start2V2": "Kamu Udah Bisa Mulai",
    "Game_friends_invite_share": "Undang Temanmu Menggunakan ID Room",
    "Game_Ready": "Bersiap!",
    "Guest_Username": "Tamu",
    "help_classic_title": "Klasik",
    "help_powerUp_title": "Power",
    "InGame_PlayerInfo_Match": "Match",
    "InGame_PlayerInfo_Win": "Berhasil",
    "InGame_PlayerInfo_Gift": "Hadiah (100 Koin Per Hadiah)",
    "introduce_friendModel": "Hanya Main Dengan Teman",
    "LevelUp_Panel": "Naik Level",
    "LevelProgressPanelExp": "EXP",
    "LoadGame_Button_Load": "Muat",
    "Login_loading": "Sedang Log In...",
    "Lobby_receive_award_coins": "Koin",
    "Lobby_invite_detail1": "Ajak Teman Dan Dapatkan {num} Koin Tiap Kali Ada Teman Yang Gabung Lewat Link!",
    "Lobby_invite_detail2": "Setelah temanmu terhubung melalui Facebook, kamu akan mendapatkan Hadiah melalui Pesan (Maks. {times} kali Per Hari)",
    "Lobby_invite_btn": "Ajak",
    "Lobby_invite_title": "Mau Koin Lagi?",
    "Lobby_invite_guestlogin": "Lanjutkan Dengan Akun Facebook?",
    "MainScenes_Fackback": "Feedback",
    "MainScenes_Ranking": "Peringkat",
    "MainScenes_Invite": "Ajak",
    "MainScenes_FreeCoins": "Koin GRATIS",
    "MainScenes_Mission": "Misi",
    "modify_title": "Edit Profil",
    "Notice_Panel_Title": "Pemberitahuan",
    "Notice_Panel": "Memuat",
    "NotLogin": "Gagal Log In. Coba Lagi Nanti, Ya!",
    "Offline_TeamA": "Tim A",
    "Offline_TeamB": "Tim B",
    "OffLine_PanelPlayer": "Pemain",
    "PropsShareTips": "Bagikan Buat Dapetin\nItem!",
    "Props_ShowTips": "CONTOH",
    "PersonalInfo_Win": "Berhasil",
    "PersonalInfo_Total": "Total",
    "PersonalInfo_WinRate": "Win Rate",
    "PersonalInfo_Edit": "Edit",
    "PersonalInfo_Computer": "Mode AI",
    "PersonalInfo_ClassicOnline": "Mode Klasik",
    "PersonalInfo_PropsOnline": "Mode Power",
    "PersonalInfo_Props2V2": "Mode Power 2V2",
    "PersonalInfo_Classic2V2": "Mode Klasik 2V2",
    "PersonalInfo_Notenough_player": "Menunggu {Number} Pemain Lagi",
    "PersonalInfo_Friend": "Teman",
    "PersonalInfo_Level": "Lv.",
    "PersonalInfo_ClassicOnlineTitle": "Online-Klasik",
    "PersonalInfo_PropsOnlineTitle": "Online-Power",
    "PersonalInfo_TeamUpOnline": "Mode Tim",
    "PersonalInfo_MiniMapOnline": "Mode Peta Mini",
    "PlayerProfile_LoginFB": "Log In Dengan Facebook",
    "PlayerProfile_Continue": "Lanjut",
    "Rank_PanelWin": "Berhasil",
    "Select_Robot": "Perlu Setidaknya 2 Orang.",
    "SaveGame_Content": "Yakin Mau Mengakhiri Permainan?",
    "SaveGame_Save": "Simpan",
    "ShareGame_EXP": "Bagikan Dan Dapatkan 10 EXP",
    "share_window_invite": "Ajak Teman",
    "Scene_Online_Title": "Online",
    "Scene_local_Title": "Lokal",
    "Scene_local_ChooseMode": "Pilih Mode",
    "Scene_local_ChooseMode_Classic": "Klasik",
    "Scene_local_ChooseMode_Props": "Power",
    "Scene_local_ChooseMode_TeamUp": "Tim",
    "Scene_local_ChooseMode_TeamPower": "Tim Power",
    "Scene_local_ChooseMode_TeamClassic": "Tim Klasik",
    "Scene_local_ChooseColorAndName": "Pilih Warna & Nama",
    "Scene_Online_ChooseBet": "Bayar Tiket",
    "Scene_local_ChoosePlaers": "Jumlah Pemain",
    "Scene_local_ChoosePlaers_2P": "2 Pemain",
    "Scene_local_ChoosePlaers_3P": "3 Pemain",
    "Scene_local_ChoosePlaers_4P": "4 Pemain",
    "Scene_local_PlayerName1": "Pemain 1",
    "Scene_local_PlayerName2": "Pemain 2",
    "Scene_local_PlayerName3": "Pemain 3",
    "Scene_local_PlayerName4": "Pemain 4",
    "Scene_local_ChooseTeam": "Pilih Tim",
    "Scene_ClassicOnline_Title": "Klasik",
    "Scene_PropsOnline_Title": "Power Up",
    "Scene_MiniMapOnline_Title": "Peta Mini",
    "Scene_TeamUpOnline_Title": "Tim",
    "Scene_Computer_Title": "AI",
    "Scene_Friend_Title": "Teman",
    "Scene_Online_ChoosePlaers_2P": "2 Pemain",
    "Scene_Online_ChoosePlaers_4P": "4 Pemain",
    "Scene_Online_matching": "Menunggu Pemain Lain…",
    "Set_Panel_Title": "Setelan",
    "Set_Panel_Music": "Musik",
    "Set_Panel_Sound": "Suara",
    "Set_Panel_Version": "Versi",
    "Set_Panel_About": "Ringkasan",
    "Set_Panel_About_Detail": "Terima kasih atas dukunganmu untuk\nLudo World! Jika ada\nfeedback,\nkamu bisa hubungi kami di\nhpludoworld@gmail.com",
    "Set_Panel_Help": "Bantuan",
    "Set_Panel_Feedback": "Feedback",
    "Set_Panel_US": "Beri Like",
    "Set_Panel_RATE": "Beri Rating",
    "Set_Panel_Privacy": "Kebijakan Privasi",
    "Set_Panel_Terms": "Syarat dan Ketentuan",
    "Set_FB_Login": "Log In",
    "Set_FB_Logout": "Log Out",
    "Set_FB_Bind": "Hubungkan",
    "Set_Panel_Vibrate": "Getaran",
    "Set_Panel_Chat": "Chat",
    "Set_Panel_Help_minimap": "Peraturannya sama dengan Mode Klasik.\nNamun, Petanya lebih kecil dan tempo permainannya lebih cepat.\nHanya ada 4 kotak aman yang masing-masing terletak di kotak pertama setiap warna.",
    "Title_Load_Game": "Memuat Permainan",
    "Title_PlayerProfile": "Profil",
    "Tips_Game__ThreeSixSkip": "3 Kali Angka 6\nBerturut-turut, Lewati!",
    "Lucky_Wheel_Name": "Roda Gacha",
    "Game_info_block": "Blokir",
    "Game_info_unblock": "Buka Blokir",
    "Button_Item_Use": "Pakai",
    "Button_Item_Using": "Dipakai",
    "Button_Item_gotouse": "Buka Item Dipakai",
    "Main_Backpack": "Ransel",
    "Item_Duration_Duration": "Durasi:",
    "Item_Duration_Day": "Hari",
    "Item_Duration_Hour": "Jam",
    "Item_Duration_Min": "Menit",
    "Item_Duration_S": "Detik",
    "Item_Duration_Year": "Tahun",
    "Item_Duration_Permanent": "Permanen",
    "NewPlayerBonus_Gift": "Hadiah",
    "Common_Game_item_purchase": "Beli Menggunakan Kartu Item. Kamu Punya {num} Kartu Item",
    "Common_Game_item_purchaseoverbuy": "Kamu Hanya Bisa Menukar {num} Kali Per Permainan",
    "Common_Game_itemcard_notenought": "Kartu Item Kurang. Beli Lagi Dari Toko?",
    "Lobby_mini": "Peta Mini",
    "Common_IOS_Shop_LessConins": "Koinmu Kurang. Kamu Bisa Dapetin Koin Lewat Event Loh!",
    "ComputerAndLocal": "AI&Lokal",
    "Common_Game_Undo_Lack": "kurang",
    "Common_Game_Undo_Lack_Tip": "Tidak Bisa Membatalkan Karena Gem Kurang",
    "Common_Game_Undo_Left": "Sisa Pembatalan",
    "Common_Game_Undo_Switch": "Pembatalan Aktif",
    "Common_Game_Undo_Title_Enable": "Batalkan Lemparan Dadu",
    "Common_Game_Undo_Title_Disable": "Pembatalan Dinonaktifkan",
    "Common_Game_Undo_Desc_Enable": "Tap Ini Dalam {num} Detik Setelah Melempar Dadu Untuk Membatalkan Hasilnya",
    "Common_Game_Undo_Desc_Disable": "Opsi Pembatalan Udah Dinonaktifkan. Tap Kotak Untuk Mengaktifkannya Lagi",
    "Common_Game_Undo_Desc_Use_Up": "Jatah Membatalkan Habis",
    "Grand_Prix_Entry": "BIAYA MAIN",
    "Grand_Prix_Endsin": "Berakhir Dalam",
    "Grand_Prix_Play": "MAINKAN",
    "Grand_More_Coins": "Tambah Koin",
    "Grand_More_Level": "Lv.{date} Terbuka",
    "Starter_Pack": "Paket Pemula",
    "Gift_Bag_Time": "{date} Jam Tersisa",
    "Lucky_Dice": "Dadu Spesial",
    "Exclusive_Offert": "Penawaran Spesial",
  },
  "AlertText": {
    "Button_Common_Confirm": "Oke",
    "Button_Common_Yes": "Ya",
    "Button_Common_Cancel": "Batalkan",
    "Button_Common_No": "Tidak",
    "Button_Common_Upgrade": "Upgrade",
    "Button_Common_NoUpgrade": "Lain Kali",
    "Button_Common_ExitUpgrade": "Keluar",
    "Bind_FB_Account": "Gagal Menghubungkan Ke Facebook. Coba Lagi Nanti, Ya!",
    "Bind_FB_Account2": "Akun Facebook Ini Sudah Terhubung. Yuk, Coba Pakai Akun Lain!",
    "Common_Game_Online_Leave": "Kamu Akan Dinyatakan Gagal Kalau Keluar Dari Permainan. Tetap Keluar?",
    "Common_Game_Local_Leave": "Keluar Dari Permainan Saat Ini?",
    "Common_Game_Local_SaveGame": "Simpan Permainan Saat Ini?",
    "Common_Game_Computer_SaveGame": "Simpan Permainan Saat Ini?",
    "Common_Game_Computer_EnterBySaveGame": "Ada Permainan Yang Belum Kamu Selesaikan. Muat Permainan?",
    "Common_Notify_Client_Logout": "Akun Ini Sudah Digunakan Untuk Log In Di Perangkat Lain. Yuk, Log In Lagi Buat Lanjut Main Di Perangkat Ini!",
    "Common_Netword_Fail": "Periksa Koneksi Jaringanmu.",
    "Common_Netword_Fail_Offline": "Ada Kesalahan Jaringan. Mau Main Di Mode Lokal Dan AI?",
    "Common_Netword_FailRethy": "Ada Kesalahan Jaringan. Sambungkan Sekarang?",
    "Common_Netword_Fail_timeout": "Waktu Koneksi Jaringan Habis. Coba Lagi Nanti, Ya!",
    "Common_Netword_Fail_Reconnect": "Kamu Harus Memiliki Koneksi Jaringan Untuk Memainkan Mode Online. Sambungkan Sekarang?",
    "Common_Lobby_ReturnGame": "Kamu Sedang Bermain Di Room. Kembali Ke Room?",
    "Common_Lobby_ReturnFailed": "Permainan Terakhir Sudah Selesai.",
    "Common_Scene_Online_LessCoins": "Koinmu Kurang. Yuk, Beli Lagi Di Toko!",
    "Common__Online_Matching_Failed": "Gagal Masuk Room. Coba Lagi Nanti, Ya!",
    "Common_Scene_Online_Matching_TimeOut": "Waktu Habis Saat Mencoba Masuk Ke Room. Coba Lagi Nanti, Ya!",
    "Common_Scene_Online_Sitting_Failed": "Gagal Masuk Ke Room. Coba Lagi Nanti, Ya!",
    "Common_No_Operation": "Kamu Akan Dikeluarkan Dari Permainan Kalau AFK Terlalu Lama.",
    "Common_Delete": "Yakin Mau Menghapus Permainan Tersimpan?",
    "Common_Game_TeamUp_GetUserGuide": "Ada Mode Terbaru Nih! Namanya Mode Tim! Buka Tutorial?",
    "Facebook_Login_Faile": "Gagal Log In Dengan Facebook. Yuk, Cek Koneksimu!",
    "Game_leaderboard_sendBean_success": "Hore! Koinnya Berhasil Dikirim!",
    "Game_leaderboard_sendBean_fail": "Yah, Koinnya Gagal Dikirim",
    "Game_leaderboard_sendBean_Max": "Batas Harian Pengiriman Koin Sudah Tercapai.",
    "Game_Reselect_bet": "Koin yang kamu miliki melebihi batas Harga Tiket. Yuk, mulai permainan baru di Room dengan Harga Tiket lebih tinggi!",
    "Game_chat_Common_Yes": "Aktifkan",
    "Game_chat_Common_MainText": "Jika Chat diaktifkan, pemain lain akan bisa melihat percakapanmu. Aktifkan Chat? Chat bisa dinonaktifkan lagi di Setelan.",
    "Game_Friend_Join_Not_Find": "Room Tidak Ditemukan. Yuk, Cek Lagi ID Room-nya!",
    "Game_Friend_Join_Room_Closed": "Permainan Di Room Ini Udah Selesai. Yuk, Mulai Permainan Baru!",
    "Game_Friend_Join_Not_Enough_Coins": "Koinmu Tidak Cukup Untuk Gabung Ke Room Ini. Beli Koin Dari Toko?",
    "Game_Friend_Join_No_Extra_Seat": "Yah, Room Ini Udah Penuh. Yuk, Mulai Permainan Baru!",
    "Game_Friend_Join_alreadybegin": "Permainan Ini Udah Dimulai. Yuk, Mulai Permainan Baru!",
    "Game_Friend_Leave_Room": "Room Akan Ditutup Kalau Kamu Keluar. Tetap Keluar?",
    "Login_NO_IP": "Yah, Saat Ini Kami Masih Belum Bisa Menyediakan Layanan Di Lokasimu.",
    "Modify_HeadIcon_Fail": "Gagal Memodifikasi. Coba Lagi Nanti, Ya!",
    "Matching_Failed": "Gagal Mencari Lawan. Coba Lagi Nanti, Ya!",
    "No_Operation_ConfirmText": "Tetap Di Sini",
    "No_Operation_CancelText": "Keluar",
    "Quit_Game": "Yakin Mau Keluar Dari Permainan?",
    "Store_buy_tips": "Koinmu Kurang. Yuk, Beli Lagi Di Toko!",
    "Store_buy_latter": "Lain Kali",
    "Store_Open_Failed": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "Store_buy_go": "Gas",
    "Store_Payment_Failed": "Pembayaran Gagal. Kode Error:",
    "Store_Payment_IPFailed": "Pembayaran Gagal. Jangan Khawatir! Kamu Bisa Coba Lagi Lewat PC Instant Game.",
    "ShortCut_go": "Buat Shortcut Layar Beranda?",
    "Client_Low_Version": "Kamu Perlu Menggunakan Versi Terbaru Untuk Gabung Ke Room Ini. Update Sekarang?",
    "Client_High_Version": "Yah, Versi Klienmu Tidak Bisa Memasuki Room Ini.",
    "Client_Deny_Version": "Yah, Versi Klienmu Tidak Bisa Memasuki Room Ini.",
    "Play_Punish_In_Chat": "Kamu Di-mute Sampai {date} Karena Telah Melanggar Peraturan.",
    "Play_Punish_In_Room": "Akunmu Diblokir Sampai {date} Karena Telah Melanggar Peraturan.",
    "Play_Punish_Enter_Room": "Akunmu Diblokir Karena Telah Melanggar Peraturan.",
    "Kicked_Player_Not_Enough_Coins": "Kalau Koinmu Kurang, Kamu Akan Dinyatakan Gagal Begitu Bidakmu Dipulangin Musuh. Beli Koin Dari Toko?",
    "Kicked_Player_Game_Lose": "Kamu Dinyatakan Gagal. Koinmu Tidak Cukup Untuk Melanjutkan Permainan.",
    "Backpack_items_empty": "Belum Ada Item. Beli Item Dari Toko?",
    "Grand_Unlock_level": "Buka Saat Level {date}",
    "Grand_Open_Hint": "Buka Kemenangan Spektakuler Setelah {date}",
    "Grand_Less_Coins_recommend": "Koinmu ({date}) Kurang Dari Yang Disarankan Untuk Memasuki Mode. Tetap Masuk?",
    "Grand_Less_Coins_Hint": "Koinmu Tidak Cukup Untuk Gabung Ke Kemenangan Spektakuler. Beli Koin Di Toko?",
  },
  "Tips": {
    "Ads_times_tips": "Balik Lagi Besok Buat Dapetin Banyak Hadiah, Ya!",
    "Ads_times_tips_Gems": "Balik Lagi Besok Buat Dapetin Gem, Ya!",
    "Ads_coolCd_tips": "Coba Lagi Nanti, Ya!",
    "Ads_none_tips": "Belum Ada Iklan Untuk Ditonton. Coba Lagi Nanti, Ya!",
    "Ads_none_tips1": "Belum Ada Iklan Untuk Ditonton.",
    "Ads_notFull_tips": "Tonton Videonya Sampai Selesai Buat Dapetin Hadiah!",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Pilih Angka",
    "Friend_Err_Fetch_List_Fail": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "Friend_Err_Fetch_Online_Fail": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "Friend_Err_Fetch_Login_Time_Fail": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "Friend_Err_Not_Add_Player": "Pemrosesan Gagal. Coba Lagi Nanti, Ya!",
    "Friend_Err_List_Full": "Jumlah Temanmu Sudah Mencapai Batas. Kalau Mau Menambah Teman, Hapus Temanmu Yang Lain.",
    "Friend_Err_Peer_Friend_List_Full": "Jumlah Teman {name} Sudah Mencapai Batas. Karenanya, Kamu Tidak Bisa Menambahkannya Sebagai Teman.",
    "Friend_Err_Update_Friend_Fail": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "Friend_Err_Player_Refuse_Add": "{name} Tidak Menerima Permintaan Pertemanan.",
    "Friend_Err_Already_In_Add_List": "",
    "Friend_Err_Already_In_Game_List": "Kalian Udah Berteman.",
    "Friend_Err_Already_In_Platform_List": "Kalian Udah Berteman.",
    "Friend_Err_Not_In_List": "Pemrosesan Gagal. Coba Lagi Nanti, Ya!",
    "Friend_Err_Fetch_Game_Record_Fail": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "Friend_Err_Cannot_Add_Self": "Gagal Menambahkan. Coba Lagi Nanti, Ya!",
    "Game_Props_TopTitle_LuckyNumber": "Dadu\nEmas",
    "Game_Props_ItemTips_DoubleDice": "Dadu Kembar: Gunakan untuk melemparkan dua Dadu dengan angka yang sama. Pemain harus maju sebanyak angka yang keluar. Setelah menggunakan Item ini, jika pemain mendapatkan Mata Dadu 6, maka pemain tidak akan mendapatkan bonus melempar Dadu dan tidak bisa menggerakkan Bidak.",
    "Game_Props_ItemTips_AssignDice": "Kontrol Dadu: Pemain memilih jumlah angka yang akan didapatkan di Dadu. Jika mendapatkan angka 6, memulangkan Bidak lawan, atau mencapai Garis Finish, pemain akan mendapatkan bonus jatah melempar Dadu.",
    "Game_Props_ItemTips_Protection": "Tameng: Melindungi semua Bidak agar tidak dipulangkan lawan. Aktif selama 1 Babak.",
    "Game_gift_gift": "Kirim Emoji",
    "Game_gift_giftprice": "100 Koin Per Emoji",
    "Game_gift_sendtoofast": "Rehat Dulu, Yuk!",
    "Game_leaderboard_load_fail_tips": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "Game_classic_newusertips_moveout1": "Dapatkan Angka 6 Untuk Mulai Jalan.",
    "Game_classic_newusertips_mesafe": "Semua Kotak Bintang Adalah Kotak Aman.",
    "Game_classic_newusesrtip_bumptoken": "Yuk, Pulangin Bidak Ini!",
    "Game_Friend_JoinTips_Invalid_RoomCode": "ID Room Tidak Valid. Yuk, Cek Lagi!",
    "Lobby_unfinish_notice": "Fitur Ini Lagi OTW Loh!",
    "shortCut_create_succ": "Hore! Shortcut Berhasil Dibuat!",
    "shortCut_create_fail": "Gagal Membuat Shortcut. Coba Lagi Nanti, Ya!",
    "shortCut_bubble_tips": "Tap Di Sini Untuk Membuat Shortcut Di Layar Beranda",
    "Tips_Longin_Fail": "Log In Gagal. Coba Lagi Nanti, Ya!",
    "Tips_Netword_Fail_TryReconnect": "Ada Kesalahan Jaringan. Sedang Menyambungkan Kembali",
    "Tips_Netword_Fail_Reconnected": "Hore! Akhirnya Tersambung Lagi!",
    "Tips_Game__ThreeSixSkip": "3 Kali Angka 6\nBerturut-turut, Lewati!",
    "Tips_Game_Props_UseTips_DoubleDice": "Dadu Kembar! Angkanya Di-double!",
    "Tips_Game_Props_UseTips_AssignDice": "Dadu Dikontrol! Kamu Mendapatkan",
    "Tips_Game_Props_UseTips_Protection": "Melindungi Semua Bidak Agar Tidak Dipulangkan Lawan. Aktif Selama 1 Babak.",
    "Tips_Game_Props_UseTips_LuckyNumber": "Bonus Lempar Dadu. Yuk, Lempar Lagi!",
    "Tips_Game_Props_UseFail_DoubleDice": "Tidak Ada Bidak Yang Bisa Dipasangi Item Ini.",
    "Tips_Game_Props_UseFail_Protection": "Tidak Ada Bidak Untuk Dilindungi.",
    "Tips_Game_Props_OtherUseTips_DoubleDice": "Dadu Kembar Digunakan!",
    "Tips_Game_Props_OtherUseTips_AssignDice": "Kontrol Dadu Digunakan!",
    "Tips_Not_Whatsapp": "Kamu Perlu Menginstal WhatsApp Untuk Menggunakan Fitur Ini.",
    "Tips_NetWork_Connection": "Menyambungkan",
    "Tips_Game_TeamUp_HelpTeammate": "Yuk, Bantu Temanmu Main!",
    "task_load_fail_tips": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "Tips_Game_addFriendReq": "Mengirimkan Permintaan Pertemanan.",
    "Tips_Game_addFriendReq_accept": "Terima",
    "Tips_Game_addFriendReq_ignore": "Abaikan",
    "Tips_Friend_Req": "Hore! Permintaan Pertemananmu Terkirim!",
    "Tips_Friend_AcceptSucc": "{name} Udah Jadi Temanmu.",
    "Tips_Friend_AcceptFailed": "Gagal Menerima Pertemanan. Kamu Bisa Menerima Permintaan Pertemanan Nanti.",
    "Tips_Friend_IgnoreFailed": "Gagal Mengabaikan Permintaan. Kamu Bisa Mengabaikan Permintaan Pertemanan Nanti.",
    "Tips_Friend_RemoveFriend": "Yakin Mau Menghapus Teman Ini?",
    "Set_Panel_chatclosetips": "Kamu Memblokir Semua Chat.",
    "Tips_Send_Gift": "Tap Di Sini Untuk Mengirim Emoji.",
    "Tips_Send_This_Player_Gift": "Tap Di Sini Untuk Mengirim Emoji Ke Pemain Ini.",
    "Tips_Profile_Add_Friends": "Tap Profil Untuk Menambahkan Sebagai Teman.",
    "Tips_Here_Add_Friends_GamePage": "Tap Di Sini Untuk Menambahkan Sebagai Teman.",
    "Tips_Here_Add_Friends_GameOver": "Tap Di Sini Untuk Menambahkan Sebagai Teman.",
    "Tips_Send_Coin_friends": "Kirim Koin GRATIS Ke Teman.",
    "Tips_Collect_By_Mail": "Ambil Koin GRATIS Dari Teman Lewat Pesan.",
    "Item_Use_Success": "Kamu Udah Pakai {skin}.",
    "Kick_Player_No_Reward_Tips": "Koin {name} Habis Dan Dinyatakan Kalah. Kamu Tidak Dapat Bonus.",
    "Common_Game_Mini_tips": "Dapetin {num} Bintang Biar Dinyatakan Berhasil! Pulangkan Bidak Lawan Atau Capai Garis Finish Buat Dapetin Satu Bintang.",
    "Lobby_mini_tips": "Padat & Jelas",
  },
  "Chat": {
    "Game_emoji": "Emoji",
    "Game_chat": "Chat",
    "Game_chat_title": "Chat Cepat",
    "Game_chat_content1": "Hai hai!",
    "Game_chat_content2": "Gas banter!",
    "Game_chat_content3": "Ya ampun!",
    "Game_chat_content4": "GGWP",
    "Game_chat_content5": "Yang bener aje!",
    "Game_chat_content6": "Sorry guys!",
    "Game_chat_tips": "Ketik Pesan",
    "Game_chat_send": "Kirim",
  },
  "DailyBonus": {
    "Lobby_Bonus_title": "Bonus Harian",
    "Lobby_Bonus_detail": "Dapetin Koin GRATIS Setiap Hari!",
    "Lobby_Bonus_collect": "Ambil",
    "Lobby_Bonus_collected_tips": "Balik Lagi Besok Ya! Dijamin Dapet Koin!",
    "Lobby_Bonus_collect_failed": "Gagal Mengambil. Coba Lagi Nanti, Ya!",
    "Lobby_Bonus_reqFailed": "Gagal Mengambil Bonus Harian. Coba Lagi Nanti, Ya!",
    "Lobby_Bonus_Day": "Hari Ke-{num}",
    "Lobby_Bonus_Day_1": ""
  },
  "Props_Guide": {
    "Game_Props_TopTitle_Great": "Mantep",
    "Game_Props_TopTitle_LuckyNumber": "Dadu\nEmas",
    "Game_Props_ItemTips_DoubleDice": "Dadu Kembar: Gunakan untuk melemparkan dua Dadu dengan angka yang sama. Pemain harus maju sebanyak angka yang keluar. Setelah menggunakan Item ini, jika pemain mendapatkan Mata Dadu 6, maka pemain tidak akan mendapatkan bonus melempar Dadu dan tidak bisa menggerakkan Bidak.",
    "Game_Props_ItemTips_AssignDice": "Kontrol Dadu: Pemain memilih jumlah angka yang akan didapatkan di Dadu. Jika mendapatkan angka 6, memulangkan Bidak lawan, atau mencapai Garis Finish, pemain akan mendapatkan bonus jatah melempar Dadu.",
    "Game_Props_ItemTips_Protection": "Tameng: Melindungi semua Bidak agar tidak dipulangkan lawan. Aktif selama 1 Babak.",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Pilih Angka",
    "Common_Game_Props_UserGuide_GoldenNo": "11",
    "Common_Game_Props_UserGuide_GoldenNo_content": "Dapatkan Tambahan Jatah Melempar Dadu Saat Mencapai Kotak Ini.",
    "Common_Game_Props_UserGuide_continue": "Tap Untuk Melanjutkan",
    "Common_Game_Props_UserGuide_begin_title": "Mode Power",
    "Common_Game_Props_UserGuide_begin_content": "Halo, guys! Kenalin, aku Ludo World. Aku mau kasih tips cara main Mode Power, nih!",
    "Common_Game_Props_UserGuide_roaditem": "Kamu bisa dapat berbagai Item Power dari papan.",
    "Common_Game_Props_UserGuide_Items": "Yuk, kita cek ada Item Power apa aja!",
    "Common_Game_Props_UserGuide_Dicecontrol_title": "Kontrol Dadu",
    "Common_Game_Props_UserGuide_Dicecontrol_content": "Kamu bisa mengatur angka berapa yang ingin kamu dapatkan!",
    "Common_Game_Props_UserGuide_Dicecontrol_tips": "Dapet angka 6? Mantep!",
    "Common_Game_Props_UserGuide_Doubledistance_title": "Dadu Kembar",
    "Common_Game_Props_UserGuide_Doubledistance_content": "Dadumu jadi dua, dan angka yang kamu dapatkan bakal sama!",
    "Common_Game_Props_UserGuide_GoldenNo_title": "Bonus Putar Dadu",
    "Common_Game_Props_UserGuide_GoldenNo_tips": "Dapetin jatah lempar Dadu tambahan saat mencapai Garis Finish. Yang GRATIS gini pasti laris manis!",
    "Common_Game_Props_UserGuide_BumpProtection_title": "Tameng Perlindungan",
    "Common_Game_Props_UserGuide_BumpProtection_content": "Lindungi Dadumu dari Bidak jail lawan selama 1 putaran.",
    "Common_Game_Props_UserGuide_BumpProtection_effect": "Mantep! Sekarang Bidakmu kebal!",
    "Common_Game_Props_UserGuide_finish_title": "Siap pulangin lawan!",
    "Common_Game_Props_UserGuide_finish_content": "Karena kamu udah paham Itemnya, sekarang saatnya unjuk gigi!",
    "Common_Game_Props_UserGuide_finish_botton": "Gas, kita main!",
    "Common_Game_Props_GetUserGuide": "Baru pertama kali main Mode Power? Kamu bisa cek tutorialnya.",
  },
  "Feedback": {
    "Set_Feedbeck_Title": "Feedback",
    "Set_Feedbeck_Tips": "Terima Kasih Atas Feedback Dan Dukunganmu!",
    "Set_Feedbeck_Submit": "Kirim",
    "Set_Feedbeck_Submit_Succeed": "Hore! Feedback Kamu Udah Terkirim!",
    "Set_Feedbeck_Submit_No": "Kamu Perlu Mengetik Feedback Kamu Di Sini",
  },
  "TeamUp_Guide": {
    "Common_Game_teamup_UserGuide_begin_title": "Tim",
    "Common_Game_teamup_UserGuide_begin_content": "Yuk Bentuk Tim! Ini Nih Peraturannya.",
    "Common_Game_teamup_UserGuide_teammate": "Pemain dengan warna Hijau di sisi diagonal kamu adalah rekan timmu.",
    "Common_Game_teamup_UserGuide_competitor": "Tim Merah & Kuning adalah lawanmu.",
    "Common_Game_teamup_UserGuide_pawnstack": "Bidak rekan tim bisa berada di dalam kotak yang sama.",
    "Common_Game_teamup_UserGuide_onefinish": "Bantu Rekan Tim Setelah Keempat Bidakmu Sudah Berada Di Garis Finish.",
    "Common_Game_TeamUp_UserGuide_finish_title": "Nais!",
    "Common_Game_TeamUp_UserGuide_finish_content": "Kamu sudah mempelajari cara main Mode Tim. Yuk, cobain langsung!",
  },
  "SharePresentLottery": {
    "Lobby_Lottery_Hint": "Tonton Iklan Buat Dapetin Jatah Spin GRATIS",
    "Lobby_Lottery_Btn_Share": "Main Buat Jatah Spin",
    "Lobby_Lottery_Btn_spin": "Spin",
    "Lobby_Lottery_Upper_Limit": "Balik Lagi Besok Buat Spin Roda Gacha, Ya!",
    "Lobby_Lottery_Close": "Roda Diputar!",
  },
  "ShareText": {
    "TitleTurnplate": "Siap Main Ludo? Mabar Kuy!",
    "TitlePropsShare": "Main Ludo World Seru Loh! Masa Nggak Mau Nyobain Sih?",
    "TitleOver": "Aku Jadi Juragan Koin Di Ludo World. Mabar Yuk!",
    "FriendRoomInviteText": "{name} mengajakmu bermain Ludo World. ID Room {RoomCode}.",
    "RankShareContent": "Aku menang {num} Match minggu ini. Siapa berani lawan aku?!",
    "Invite_gift_text1": "Halo, guys! Aku lagi main Ludo World nih. Mau mabar nggak?",
    "Invite_gift_text2": "Mau nantangin aku? Maju sini!",
    "Invite_gift_text3": "Hore! Temanmu Membuka Link Yang Kamu Bagikan, Jadi Kamu Bisa Dapet Hadiah!",
    "friend_invite_details": "Yuk mabar Ludo World. ID Room: {Number}. Klik untuk download atau masuk ke Room.",
  },
  "LoginMainLabel": {
    "LoginMainLabel_Facebook": "Facebook",
    "LoginMainLabel_Google": "Google",
    "LoginMainLabel_Description": "Dengan melanjutkan, aku mengizinkan Moon Active menyimpan dan mengolah dataku sesuai dengan Kebijakan Privasi.",
    "LoginMainLabel_Guest": "Tamu",
    "LoginMainLabel_Continue_Sure": "Yakin?",
    "LoginMainLabel_Continue_Express": "Tamu Tidak Bisa Bermain Dengan Teman...",
    "LoginMainLabel_Continue_AsGuest": "Main Sebagai Tamu",
    "LoginMainLabel_Continue_FbAward": "Tamu Tidak Bisa Bermain Dengan Teman Atau Mendapatkan Bonus {coins} Koin...",
    "LoginMainLabel_RewardPrompt": "{coins} Koin GRATIS!",
    "LoginMainLabel_Continue_Warning": "Dengan tap \"Setuju\", aku mengonfirmasi bahwa aku sudah membaca dan menyetujui KEBIJAKAN PRIVASI dan PERJANJIAN PENGGUNA TENCENT GAMES",
    "LoginMainLabel_Continue": "<u><b>Lanjut sebagai Tamu<u><b>",
    "LoginMainLabel_Select": "Pilih Metode Log In",
    "FacebookConnect_Content1": "<b><color=#444987>Log In Dengan Facebook：</color></b>",
    "FacebookConnect_Content2": "<b><color=#444987>1.Main bareng teman\n2.Simpan progresmu\n3.Dapetin <color=#d16004>{num}<color=#444987> Koin GRATIS<b>",
    "FacebookConnect_Content3": "<u><b><color = #3f59b7 click=\"handler\">Log In Dengan Facebook</color></b></u>",
    "FacebookConnect_Content4": "<b><color=#444987>Log in sebagai Tamu dan<color=#d16004> tidak bisa <color=#d16004>",
  },
  "PropsPromtText": {
    "Game_classic_newusertips_dicecontrolmoveout": "Kontrol Angka Dadumu\nDan Mulai Permainannya!",
    "Game_classic_newusertips_dicecontrolbump": "Kontrol Angka Dadumu\nDan Pulangin Bidak Lawan!",
    "Game_classic_newusertips_dicecontrolfinish": "Kontrol Angka Dadumu Biar\nBidakmu Sampai Ke Garis Finish!",
    "Game_classic_newusertips_doubledistance": "Gandakan Angka Di Dadumu!",
    "Game_classic_newusertips_shild": "Lindungi Bidakmu!",
    "Game_classic_newusertips_dicecontrolrun": "Kontrol Angka Dadumu Dan Mulai Permainannya.",
    "Game_item_purchasetips": "Tap Untuk Mendapatkan Item",
  },
  "MailPanel": {
    "Mail_Title": "Pesan",
    "Mail_firend": "Teman",
    "Mail_system": "Sistem",
    "Mail_collect": "Ambil",
    "Mail_check": "Periksa",
    "Mail_collectAll": "Ambil Semua",
    "Mail_Firend_Preservation_tips": "Simpan 60 Pesan Selama 30 Hari.",
    "Mail_System_Preservation_tips": "Simpan 60 Pesan Selama 30 Hari.",
    "Mail_NoMail_tips": "Tidak Ada Pesan Lagi.",
    "MailInfo_Title": "Detail",
    "MailInfo_firend_Gift": "Mengirim Hadiah",
    "Mail_firend_Get_limit": "Kamu udah mengambil Hadiah dari {num} teman hari ini. Buka lagi besok buat ambil Hadiah lainnya.",
    "MailInfo_get_Failure": "Gagal Mengambil Hadiah. Coba Lagi Nanti, Ya!",
    "Mail_delete_Failure": "Gagal Menghapus. Coba Lagi Nanti, Ya!",
    "MailInfo_delete": "Hapus",
  },
  "PrivacyPolicy": {
    "PrivacyPolicy_join1": "Saya sudah membaca dan menyetujui",
    "PrivacyPolicy_join2": "KEBIJAKAN PRIVASI",
    "PrivacyPolicy_join3": "dan",
    "PrivacyPolicy_join4": "PERJANJIAN PENGGUNA",
    "SelectNone": "Dengan tap Setuju, aku mengonfirmasi bahwa aku telah membaca dan menyetujui KEBIJAKAN PRIVASI dan PERJANJIAN PENGGUNA",
  },
  "HelpText": {
    "Game_classic_userguide_tokens": "Bidak: Terdapat 4 jenis Bidak, dan masing-masing dimiliki oleh tiap pemain.",
    "Game_classic_userguide_startpoint": "Base: Ini adalah posisi awal.",
    "Game_classic_userguide_finishline": "Garis Finish: Bidak harus mengelilingi papan sebelum mencapai Garis Finish.",
    "Game_classic_userguide_safeplace": "Kotak Aman: 8 Kotak yang bertandakan bintang adalah Kotak Aman, dan Bidakmu tidak akan kembali ke Base jika bertemu Bidak lawan di Kotak ini.",
    "Game_classic_userguide_dice": "Dadu: Setiap sisi Dadu memiliki jumlah titik yang berbeda, dari 1 sampai 6 titik.",
    "Game_classic_userguide_firsthand": "Giliran pertama: Giliran pertama dipilih secara acak, dan giliran selanjutnya mengikuti arah jarum jam.",
    "Game_classic_userguide_moveout": "Keluar Base: Bidak hanya bisa keluar dari Base jika pemain mendapatkan Dadu berangka 6.",
    "Game_classic_userguide_move": "Maju: Setelah melempar Dadu, pilih Bidak yang mau kamu gerakkan sesuai dengan angka yang didapatkan.",
    "Game_classic_userguide_automove": "Maju otomatis: Bidak maju secara otomatis jika tidak ada Bidak lain yang tersedia.",
    "Game_classic_userguide_sixbonus": "Bonus 6: Pemain akan memperoleh satu tambahan jatah melempar Dadu jika mendapatkan angka 6 pada Dadu. Jika terus mendapatkan angka 6 hingga 3 kali berturut-turut, pemain tidak akan mendapatkan jatah tambahan lagi.",
    "Game_classic_userguide_bumpbonus": "Bonus memulangkan Bidak: Pemain memperoleh satu tambahan jatah melempar Dadu jika berhasil memulangkan Bidak lawan.",
    "Game_classic_userguide_finishbonus": "Bonus saat mencapai Garis Finish: Pemain memperoleh satu tambahan jatah melempar Dadu jika berhasil mencapai Garis Finish.",
    "Game_classic_userguide_bump": "Pulangkan Bidak: Jika Bidak maju dan berada di dalam satu kotak yang sama dengan Bidak lawan (selain Kotak Aman), Bidak yang pertama sampai akan dipulangkan ke Base. Tapi jika ada lebih dari 1 Bidak dengan warna yang sama di dalam kotak, Bidak akan tetap aman.",
    "Game_classic_userguide_finish": "Bidak hanya bisa mencapai Garis Finish jika angka Dadu yang didapatkan sama dengan jumlah kotak yang dibutuhkan untuk mencapai Garis Finish. Jika lebih besar, Bidak tidak akan maju.",
    "Game_classic_userguide_winner": "Pemenang: Pemain yang semua Bidaknya mencapai Garis Finish pertama kali akan dinyatakan berhasil. Dalam Match dengan 4 pemain, pemain pertama dan kedua yang semua Bidaknya mencapai Garis Finish akan dinyatakan berhasil.",
    "Game_classic_userguide_time": "Waktu: 10 Detik untuk melempar Dadu, 10 Detik untuk maju.",
    "Game_classic_userguide_autohosted": "Maju Otomatis: Jika waktumu habis atau koneksimu terputus, AI akan menggantikanmu. Tap untuk kembali mengontrol permainan.",
    "Set_Help_newuser_powermode_begin": "Berdasarkan Mode Klasik, tambahkan Item berikut biar permainannya lebih seru!",
    "Set_Help_newuser_powermode_step1": "Dadu Kembar: Gunakan untuk melemparkan dua Dadu dengan angka yang sama. Kamu jadi bisa cepat sampai Garis Finish!\nNamun, bonus jatah lempar Dadu setelah mendapatkan angka 6 tidak berlaku jika menggunakan Item ini.",
    "Set_Help_newuser_powermode_step2": "Kontrol Dadu: Atur angka berapa yang ingin kamu dapatkan.",
    "Set_Help_newuser_powermode_step3": "Tameng Perlindungan: Lindungi Bidakmu dari Bidak jail lawan selama 1 putaran.",
    "Set_Help_newuser_powermode_step4": "Bonus Lempar Dadu: Dapatkan jatah lempar Dadu saat ada Bidak yang mencapai Garis Finish.",
    "Set_Panel_Help_teamup_1": "Aturan 1: Kamu dan pemain di posisi diagonalmu masuk dalam satu tim (Biru & Hijau VS Merah & Kuning).",
    "Set_Panel_Help_teamup_2": "Aturan 2: Jika Bidak kalian berada dalam 1 kotak yang sama, Bidak lawan tidak bisa memulangkan Bidakmu.",
    "Set_Panel_Help_teamup_3": "Aturan 3: Bidak timmu tidak akan bisa dipulangkan saat sedang rehat.",
    "Set_Panel_Help_teamup_4": "Aturan 4: Setelah semua Bidakmu mencapai Garis Finish, kamu bisa melempar Dadu dan rekan timmu.",
    "Set_Panel_Help_teamup_5": "Aturan 5: 8 Bidak timmu harus mencapai Garis Finish terlebih dahulu agar dinyatakan berhasil.",
  },
  "PropGuidePanel": {
    "PropGuidePanel_TitleText": "Mode Power!",
    "PropGuidePanel_ContentText": "Yuk Cobain\nMode Unik Ludo Sekarang Juga!",
    "PropGuidePanel_PlayBntText": "Mulai",
    "PropGuidePanel_AwardHint": "Koin GRATIS!",
    "NewHandGuide_AwardHint": "Kamu Menuntaskan Tutorial Mode Power!",
    "NewHandGuide_Get_Failure": "Gagal Mengambil. Coba Lagi Nanti, Ya!",
    "PropGuideTipsOpenText": "Tips Item Dibuka",
    "PropGuideTipsCloseText": "Tips Item Ditutup",
  },
  "GameGuide": {
    "GameGuideText1": "Welcome!",
    "GameGuideText2": "Mabar Mode Online Bareng Pemain Lain, Yuk!",
  },
  "GameGuideText": {
    "GameGuideTitle": "Pilih Mode",
    "GameGuideContent": "Udah Pernah Nyoba Ludo? Cobain",
    "GameGuideClassicModeContent": "Klasik",
    "GameGuidePowerModeContent": "Senior",
    "GameGuidePowerMode": "Power",
    "GameGuidePlay": "Yuk Main!",
    "GameGuideClassicMode": "Klasik",
    "GameGuideInnovative": "Nggak Ada Duanya",
  },
  "GameTxpText": {
    "GameNoGetExp": "Tidak mendapatkan EXP karena kamu tidak memulangkan Bidak lawan atau mencapai Garis Finish.",
    "CloseTips": "Tap Untuk Menutup",
    "ShareLevelTips": "Main Ludo World Seru Loh! Masa Nggak Mau Nyobain Sih?",
  },
  "AssessPanelText": {
    "Rate_title": "Suka Gamenya?",
    "Rate_content": "Kalau Suka, Kasih Rating, Yuk!",
    "Rate_Button": "Beri Rating",
    "Rate_Button2": "Lain Kali",
    "ShareGame_exp_fail": "Gagal Mendapatkan EXP. Coba Lagi Nanti, Ya!",
    "ShareGame_exp_Exceed": "Kamu Mendapatkan Terlalu Banyak EXP. Balik Lagi Besok, Ya!",
  },
  "TaskPanel": {
    "Task_Title": "Misi",
    "Task_Daily": "Misi Harian",
    "Task_Growth": "Misi Progres",
    "Task_collect": "Ambil",
    "Task_Play": "Gas",
    "Task_Playing": "Sedang Berlangsung",
    "Task_get_award_failed": "Gagal Mengambil. Coba Lagi Nanti, Ya!",
    "Task_Tips": "Misi Harian Di-refresh Jam 24:00",
    "Task_Timeout": "Gagal Mengambil. Waktu Misi Habis.",
    "Task_Coins": "Koin",
  },
  "TaskName": {
    "task_0": "Log In",
    "task_1": "Kirim Hadiah Ke Pemain\nLain 5 Kali Di\nMode Online",
    "task_2": "Kirim Koin Ke Teman\nDi Daftar Teman\n5 Kali.",
    "task_3": "Pulangin Bidak Lawan 5 Kali Di\nMode Teman",
    "task_4": "Gerakkan Bidak Sampai Ke\nGaris Finish 3 Kali\nDi Mode Teman",
    "task_5": "Menangkan 1 Match\nDi Mode\nTeman-Klasik",
    "task_6": "Menangkan 1 Match\nDi Mode\nTeman-Power",
    "task_7": "Menangkan 1 Match\nDi Mode Teman",
    "task_8": "Menangkan 5 Match\nDi Mode\nOnline-Klasik-2 Pemain",
    "task_9": "Menangkan 3 Match\nDi Mode\nOnline-Klasik-4 Pemain",
    "task_10": "Menangkan 3 Match\nDi Mode\nOnline-Klasik-2v2",
    "task_11": "Menangkan 5 Match\nDi Mode\nOnline-Power-2 Pemain",
    "task_12": "Menangkan 3 Match\nDi Mode\nOnline-Klasik-4 Pemain",
    "task_13": "Menangkan 3 Match\nDi Mode\nOnline-Power-2v2",
    "task_14": "Menangkan 5 Match\nDi Mode Online",
    "task_15": "Gunakan Dadu Kembar\n10 Kali Di Mode\nOnline-Power",
    "task_16": "Gunakan Kontrol Dadu\n10 Kali Di Mode\nOnline-Power",
    "task_17": "Gunakan Tameng Dadu\n10 Kali Di Mode\nOnline-Power",
    "task_18": "Pulangin Bidak Lawan 5 Kali Di\nMode Online",
    "task_19": "Gerakkan Bidak Sampai Ke\nGaris Finish 3 Kali\nDi Mode Online",
    "task_20": "",
    "task_21": "Naik Ke Level %{num}",
    "task_22": "Log In Total %{num} Hari",
    "task_23": "Menangkan %{num} Match\nDi Mode Online",
    "task_24": "Menangkan %{num} Match\nDi Mode AI",
    "task_25": "Pulangin Bidak Lawan %{num} Kali\n Di Mode Online",
  },
  "TeamUp2V2": {
    "Common_Choose_Number_Team": "Tim",
    "Common_Choose_Number_2v2_titlepower": "Power 2V2",
    "Common_Choose_Number_2v2_titleclassic": "Klasik 2V2",
    "Teamup_choose_tips1": "Ajak Teman Atau Cari Lawan Otomatis",
    "Teamup_choose_tips2": "Kamu Bisa Mulai Main",
    "Teamup_choose_betchange_title": "Harga Tiket Diubah",
    "Teamup_choose_betchange_content": "Harga Tiket Disesuaikan Menjadi {coins} Karena Koin Temanmu Kurang.",
    "Teamup_choose_join_leave_title": "Keluar Dari Permainan?",
    "Teamup_choose_join_leave_content": "Tim Akan Dibubarkan. Tetap Mau Keluar?",
    "Teamup_Matching_leave_content": "Udah Menemukan Lawan. Kamu Tidak Bisa Keluar Room.",
    "Teamup_Game_inviting": "{name} Mengajakmu Membentuk Tim Untuk Main Mode Online-2V2.",
  },
  "Region": {
    "Disgree_Content": "Sayangnya, saat ini kami belum bisa menyediakan layanan Ludo World untuk kamu. Data kami tersimpan di luar Wilayah Ekonomi Eropa (EEA) dan Tim Dukungan kami harus mengakses data tersebut dari wilayah lain untuk menyediakan layanan Ludo World.",
    "Back": "Kembali",
    "Data_Agreement_Content_APK": "Ludo World adalah produk yang ditawarkan oleh Proxima Beta Pte. Ltd., sebuah perusahaan Republik Singapura yang akan memproses data kamu di luar Wilayah Ekonomi Eropa (termasuk di Republik Rakyat Tiongkok) untuk menyediakan layanan ini. Harap diperhatikan bahwa ada risiko terkait pemindahan data ini, termasuk kemungkinan data kamu tunduk pada aturan hukum lain dan mungkin tidak mendapatkan tingkat perlindungan yang sama seperti di negara tempatmu berada.Untuk informasi selengkapnya, silakan baca <b><u><i click=\"handler\">Kebijakan Privasi</i></u></b> kami. Dengan tap \Setuju\, kamu menyetujui pemindahan datamu ke luar Wilayah Ekonomi Eropa (EEA).",
    "Data_Agreement_Content_FB": "Ludo World merupakan produk yang disediakan oleh High Morale Development Limited, perusahaan Hong Kong yang akan memproses data kamu di luar Wilayah Ekonomi Eropa atau EEA (termasuk di Republik Rakyat Tiongkok) untuk menyediakan layanan ini. Harap diperhatikan bahwa ada risiko terkait pemindahan data ini, termasuk kemungkinan data kamu tunduk pada aturan hukum lain dan mungkin tidak mendapatkan tingkat perlindungan yang sama seperti di negara tempatmu berada.Untuk informasi selengkapnya, silakan baca <b><u><i click=\"handler\">Kebijakan Privasi</i></u></b> kami. Dengan tap \Setuju\, kamu menyetujui pemindahan datamu ke luar Wilayah Ekonomi Eropa (EEA).",
    "Agree": "Setuju",
    "Disagree": "Tidak Setuju",
    "Under_Age_Content": "Karena kamu masih di bawah usia {age} tahun, kamu belum bisa memainkan Ludo World untuk saat ini.",
    "Data_Outside_Content": "Apakah kamu setuju untuk memindahkan datamu ke luar Wilayah Ekonomi Eropa (EEA)?",
    "Data_Outside_Title": "Pemindahan Data Ke Luar EEA",
    "Delete_Notice_Title": "Pemberitahuan",
    "Delete_Notice_Content": "Sayangnya, saat ini kami belum bisa menyediakan layanan Ludo World untuk kamu. Data kami tersimpan di luar Wilayah Ekonomi Eropa (EEA) dan Tim Dukungan kami harus mengakses data tersebut dari wilayah lain untuk menyediakan layanan Ludo World. Tap \"Kembali\"untuk mempertimbangkan kembali atau tap \Hapus Akun\ untuk menghapus akunmu.",
    "Delete_Account": "Hapus Akun",
    "Delete_Delete": "Hapus",
    "Delete_Content": "Apakah kamu ingin menghapus akunmu? Sistem akan secara otomatis menghapus akun dan datamu setelah 7 Hari. Kamu bisa membatalkan penghapusan akun dengan log in kembali dalam periode 7 Hari tersebut.",
    "Chat_Off_Title": "Aktifkan Chat?",
    "Chat_Off_Content": "Jika Chat diaktifkan, pemain lain akan bisa melihat percakapanmu. Chat bisa dinonaktifkan lagi di Setelan.",
    "Region_Title": "Wilayah",
    "Region_Content": "Pilih Wilayah/Negara Tempatmu\nBerada.",
    "Agree_Title": "Kelahiran",
    "Agree_Content": "Agar kami bisa mengoptimalkan pengalamanmu, harap konfirmasi bahwa kamu berusia {age} tahun ke atas.",
    "Privacy_Title": "Kebijakan Privasi",
    "Privacy_Content": "Dengan tap \"Setuju\", aku mengonfirmasi bahwa\naku sudah membaca dan menyetujui\n<b><u><color = #535BBF click=\"handler\">Kebijakan Privasi</color></u></b> Ludo World",
    "Privacy_Disagree": "Sayangnya, jika kamu tidak menyetujui Kebijakan Privasi, kamu belum bisa memainkan Ludo World.",
    "Agreement_Title": "Perjanjian Lisensi Pengguna Akhir",
    "Agreement_Content": "Dengan tap \"Setuju\", aku mengonfirmasi bahwa\naku sudah membaca dan menyetujui\n<b><u><color = #535BBF click=\"handler\">Perjanjian Lisensi Pengguna Akhir</color></u></b> Ludo World.",
    "Agreement_Disagree": "Sayangnya, jika kamu tidak menyetujui Perjanjian Lisensi Pengguna Akhir, kamu belum bisa memainkan Ludo World.",
    "YES": "Ya",
    "NO": "Tidak",
  },
  "FriendSystem": {
    "Friend_Main_title": "Teman",
    "Friend_Main_list": "Daftar",
    "Friend_Main_add": "Tambah",
    "Friend_Main_request": "Permintaan",
    "Friend_Main_list_FB": "Teman FB",
    "Friend_Main_list_Game": "Teman Game",
    "Friend_Main_list_reciveandsend": "Kirim Semua",
    "Friend_Main_list_reciveandsend_Detail": "Koin Yang Dikirim Ke Teman Tidak Akan Mengurangi Saldomu.",
    "Friend_Main_Add_Recent": "Terbaru",
    "Friend_Select_Tip_NewRequest": "{num} Permintaan Pertemanan",
    "Friend_Main_Request_Num_Tip": "Hanya Simpan 99 Permintaan Terakhir.",
    "Friend_list_nofbfirends": "Belum Ada Teman Facebook Yang Main Ludo,\nAjak Yuk!",
    "Friend_list_invitefirends": "Mau mabar Ludo World sama aku sekarang?",
    "Friend_list_nogamefirends": "Belum Ada Teman Game,\nYuk, Tambahkan Teman Melalui Tab 'Tambah'!",
    "Friend_Add_NoRecent": "Belum Ada",
    "Friend_Request_NoRequest": "Belum Ada Permintaan Pertemanan",
    "Friend_list_online": "Online",
    "Friend_list_offline": "Offline",
    "Friend_list_playing": "Lagi Main",
    "Friend_Not_Accept": "Tidak Menerima Permintaan Pertemanan Lagi.",
    "Friend_sendcoins_succeed": "Kirim 100 Koin Ke {name}",
    "Friend_sendcoins_fail": "Yah, Kamu Udah Mencapai Batas Harian Pengiriman Hadiah.",
    "Friend_collectandsendall_succeed": "Kirim {num} Koin",
    "Friend_collectandsendall_nofirendtosend": "Belum Ada Teman Untuk Dikirimi",
    "Friend_invite_title": "Ajakan",
    "Friend_invite_bottoningame": "Dalam Game",
    "Friend_invite_whoinvite": "{name} Ngajak Kamu Mabar!",
    "Friend_invite_reject": "Tolak",
    "Friend_invite_accept": "Terima",
    "Friend_invite_friendpower": "Teman-Power",
    "Friend_invite_friendclassic": "Teman-Klasik",
    "Friend_invite_teamuppower": "Teman-Power-2V2",
    "Friend_invite_teamupclassic": "Teman-Klasik-2V2",
    "Friend_invite_sentsucceed": "Ajakan Dikirim",
    "Friend_invite_sentfail": "Gagal Mengajak",
    "Friend_invite_more_btn": "Ajak Yang Lain:",
    "Friend_collectcoins_fail": "Hari Ini Kamu Udah Mengambil Koin Dari {num} Teman. Balik Besok Buat Ambil Koin Lagi, Ya!",
    "Friend_collectall_succeed": "Yuk, Ambil {coins} Koin Dari Teman!",
    "Friend_Add_Recent_Source1": "Online-Klasik-2 Pemain",
    "Friend_Add_Recent_Source2": "Online-Klasik-4 Pemain",
    "Friend_Add_Recent_Source3": "Online-Power-2 Pemain",
    "Friend_Add_Recent_Source4": "Online-Power-4 Pemain",
    "Friend_Add_Recent_Source5": "Online-Klasik-2V2",
    "Friend_Add_Recent_Source6": "Online-Power-2V2",
    "Friend_Add_Recent_Source7": "Teman-Klasik",
    "Friend_Add_Recent_Source8": "Teman-Power",
    "Friend_Add_Recent_Source9": "Teman-Klasik-2V2",
    "Friend_Add_Recent_Source10": "Teman-Power-2V2",
    "Friend_Request_Source_Recent": "Permainan Terbaru",
    "Friend_Request_Source_Suggested": "Rekomendasi",
    "Friend_Request_Source_Leaderboard": "Papan Peringkat",
    "Friend_gametime-year": "{num} Tahun Lalu",
    "Friend_gametime-day": "{num} Hari Lalu",
    "Friend_gametime-hour": "{num} Jam Lalu",
    "Friend_gametime-minitue": "{num} Menit Lalu",

  },
  "APPAdsText": {
    "ItemsAddOne": "Item+1",
  },
  "Common": {
    "Lobby_Bonus_collecet": "Ambil",
    "Common_Game_teamup_UserGuide_finish_title": "Nais!",
    "Game_friends_invite_start": "Kamu Bisa Mulai Main.",
    "": "",
    "Title_ModifyInfo": "Ubah Info",
    "shortCut_create_success": "Hore! Shortcut Berhasil Dibuat!",
    "MainScenes_Ranking": "Peringkat",
    "MainScenes_FreeCoins": "Koin GRATIS",
    "MainScenes_Mission": "Misi",
    "Settings_on": "Aktif",
    "Settings_off": "Nonaktif",
    "Game_EndOrder_Congratulations": "Selamat!",
    "EM_ERR_FETCH_FRIEND_FAIL = -10002": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "EM_ERR_FETCH_ONLINE_FAIL = -10003": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "EM_ERR_FETCH_LOGIN_TIME_FAIL = -10004": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "EM_ERR_NOT_ADD_PLAYER = -10005": "Pemrosesan Gagal. Coba Lagi Nanti, Ya!",
    "EM_ERR_FRIEND_LIST_FULL = -10006": "Jumlah Temanmu Sudah Mencapai Batas. Kalau Mau Menambah Teman, Hapus Temanmu Yang Lain.",
    "EM_ERR_PEER_FRIEND_LIST_FULL = -10007": "Jumlah Teman {name} Sudah Mencapai Batas. Karenanya, Kamu Tidak Bisa Menambahkannya Sebagai Teman.",
    "EM_ERR_UPDATE_FRIEND_FAIL = -10008": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "EM_ERR_PLAYER_REFUSE_ADD = -10009": "{name} Tidak Menerima Permintaan Pertemanan.",
    "EM_ERR_ALREADY_IN_ADD_LIST = -10010": "",
    "EM_ERR_ALREADY_IN_GAME_FRIEND_LIST = -10011": "Kalian Udah Berteman.",
    "EM_ERR_ALREADY_IN_PLAT_FRIEND_LIST = -10012": "Kalian Udah Berteman.",
    "EM_ERR_NOT_IN_FRIEND_LIST = -10013, //": "Pemrosesan Gagal. Coba Lagi Nanti, Ya!",
    "EM_ERR_FETCH_GAME_RECORD_FAIL = -10014": "Gagal Memuat Data. Coba Lagi Nanti, Ya!",
    "EM_ERR_CANNOT_ADD_SELF = -10015": "Gagal Menambahkan. Coba Lagi Nanti, Ya!",
    "LoginMainLabel_Guest_Title": "Log In Sebagai Tamu Dan Tidak Bisa",
    "Language_type": "Indonesia",
  },
  "GoodsName": {
    "GoodsName_Cricket": "Cricket",
    "GoodsName_Jewelry": "Jewelry",
    "GoodsName_Airdrop_box": "Airdrop",
    "GoodsName_Cupid": "Cupid",
    "GoodsName_Cat": "Cat",
    "GoodsName_Planet": "Planet",
    "GoodsName_Default": "Default",
    "Shop_luckybox": "Kotak Spesial",
    "Shop_luckybox_GiftCardtitle": "Kartu Hadiah",
    "Shop_luckybox_GiftCard": "Kamu Bisa Cek Kartu Hadiah Lewat Pesan Dalam Game.",
    "GoodsName_Item_Cards": "Kartu Item",
    "GoodsName_Item_Cards_num": "Kartu Item x{num}",
    "GoodsName_Neon": "Neon",
    "GoodsName_Chick": "Chick",
    "GoodsName_First_AidKit": "First Aid Kit",
    "GoodsName_Machinery": "Machinery",
    "GoodsName_Diwali": "Diwali",
    "GoodsName_Christmas": "Natal",
    "GoodsName_Gems": "Gem",
  },
  "AdsText": {
    "Btn_Lucky_Show_Ad": "Tonton Iklan",
    "Lab_Lucky_Next": "Hadiah Selanjutnya:",
    "Lab_Lucky_Declare": "Tonton Iklan Buat Dapetin Jatah Spin GRATIS Tiap Hari!",
    "Btn_Double_Reward": "Bonus Berlipat Ganda",
    "Btn_Reward_x2": "Dapatkan 2x!",
    "Btn_No_Thanks": "Nggak, Makasih",
    "Ad_Confirm_Cions": "Tonton Iklan Buat Dapetin {num} Koin.",
    "Ad_Confirm_Item": "Tonton Iklan Buat Dapetin Tiap Item.",
    "Ad_Confirm_Task": "Tonton Iklan Buat Melanjutkan Misi.",
    "Ad_Confirm_Spin": "Tonton Iklan Buat Dapetin {spin}.",
  },
  "NewUserText": {
    "NewPlayerBonus_Title": "Bonus Pemain Baru",
    "NewPlayerBonus_Day": "Hari",
    "NewPlayerBonus_Collect": "Ambil",
    "NewPlayerBonus_Collected": "Diambil",
    "NewPlayerBonus_LoginTips": "Kamu Udah Log In Selama {num} Hari!",
    "NewPlayerBonus_EventTime": "Periode Event:",
    "NewPlayerBonus_Coins": "Koin",
    "NewPlayerBonus_Skins": "Skin",

  },
  "Shop": {
    "Shop_Tab_Coins": "Koin",
    "Shop_Tab_Spin": "Skin",
    "Shop_Tab_Items": "Item",
    "Shop_Tab_Spin_BubbleTab": "Bubble",
    "Shop_Tab_Spin_DiceTab": "Dadu",
    "Shop_Tab_Spin_ThemeTab": "Latar",
    "Shop_Airdrop_box": "Airdrop",
    "Shop_Coins": "{num}",
    "Shop_Airdrop_box_day": "Airdrop ({num} Hari)",
    "Shop_Cricket": "Cricket",
    "Shop_Cricket_day": "Cricket ({num} Hari)",
    "Shop_Cupid": "Cupid",
    "Shop_Cupid_day": "Cupid ({num} Hari)",
    "Shop_Jewelry": "Jewelry",
    "Shop_Jewelry_day": "Jewelry ({num} Hari)",
    "Shop_Cat": "Cat",
    "Shop_Cat_day": "Cat ({num} Hari)",
    "Shop_Planet": "Planet",
    "Shop_Planet_day": "Planet ({num} Hari)",
    "Shop_Neon": "Neon",
    "Shop_Neon_day": "Neon ({num} Hari)",
    "Shop_Chick": "Chick",
    "Shop_Chick_day": "Chick ({num} Hari)",
    "Shop_First_AidKit": "First Aid Kit",
    "Shop_First_AidKit_day": "First Aid Kit ({num} Hari)",
    "Shop_Machinery": "Machinery",
    "Shop_Machinery_day": "Machinery ({num} Hari)",
    "Shop_Diwali": "Diwali",
    "Shop_Diwali_day": "Diwali ({num} Hari)",
    "Shop_Christmas": "Natal",
    "Shop_Christmas_day": "Natal ({num} Hari)",
    "Shop_Item": "Kartu Item ({num} Hari)",
    "Shop_Label_New": "Baru",
    "Shop_Label_Hot": "Trending",
    "Shop_Label_Off": "Nonaktif",
    "Shop_Label_Extar": "Tambahan",
    "Shop_Label_BestDeal": "Penawaran Terbaik",
    "Shop_Day_day": "Hari",
    "Shop_Buy_Success": "Hore! Pembelian Berhasil! Kamu Udah Menggunakan {spin}.",
    "Shop_Backpack_Tip": "Yuk, Gunakan Item Di Ransel",
    "Button_Reload": "Muat Ulang",
    "Button_AD_Free": "GRATIS",
    "Shop_Lucky": "Spesial",
    "Shop_BuyGift_Success": "Hore! Pembelian Berhasil! Yuk, Gunakan Item Di Ransel!",
    "Shop_Airdrop_box_Permanent": "Airdrop (Permanen)",
    "Shop_Cricket_Permanent": "Cricket (Permanen)",
    "Shop_Cupid_Permanent": "Cupid (Permanen)",
    "Shop_Jewelry_Permanent": "Jewelry (Permanen)",
    "Shop_Cat_Permanent": "Cat (Permanen)",
    "Shop_Planet_Permanent": "Planet (Permanen)",
    "Shop_Neon_Permanent": "Neon (Permanen)",
    "Shop_Chick_Permanent": "Chick (Permanen)",
    "Shop_First_ AidKit_Permanent": "First Aid Kit (Permanen)",
    "Shop_Machinery_Permanent": "Machinery (Permanen)",
    "Shop_Diwali_Permanent": "Diwali (Permanen)",
    "Shop_Lucky_Detail": "Cricket (1 Hari), Jewelry (1 Hari), Planet (1 Hari)",
    "Shop_WatchTV_Detail": "Tonton Iklan Buat Dapetin Item GRATIS!",
    "Shop_Buy_Fail": "Pembelian Gagal. Coba Lagi Nanti, Ya!",
    "Shop_Buy_ItemFail": "Pengiriman Item Gagal. Coba Lagi Nanti, Ya!",
    "Shop_Buy_Success_Prop": "Hore! Pembelian Berhasil!",
    "Shop_Buy_Prop_Describe": "Item Bisa Ditukar Dengan Kartu Item",
    "Shop_itemcard": "Kartu Item",
    "Shop_itemcard_number": "{num} Kartu",
    "Shop_Tab_Name": "Toko",
  },
  "ReportText": {
    "Report_Panel": "Laporkan",
    "Report_Title": "Laporkan",
    "Report_People": "Laporkan {name}",
    "Report_Content1": "Pelecehan Verbal",
    "Report_Content2": "Curang",
    "Report_Content3": "Lainnya",
    "Report_Success": "Laporan Terkirim",
    "Report_Res_Title": "Hasil",
    "Report_Res_Content": "Pemain yang kamu laporkan, {name}, di-mute/ditangguhkan.",
  },
  "RetainUser": {
    "newsuserA_classic_tips": "Mau Yang Seru? Yuk, Cobain Mode Power!",
    "newsuserA_power_tips": "Mau Yang Gampang? Yuk, Cobain Mode Klasik!",
    "newsuserA_tips_quit": "Keluar",
    "newsuserA_tips_try": "Coba",
    "newsuserB_tips_stay": "Tuntaskan {num1} Permainan ({num2}/{num3}) Buat Dapetin Peti Hijau.",
    "newsuserB_tips_minitips": "Undi Dan Raih Peluang Mendapatkan Amazon Gift Card Senilai ₹100 Atau Koin!",
    "newsuserB_tips_getluckybox_title": "Peti Hijau",
    "newsuserB_tips_getluckybox_content": "Undi Dan Raih Peluang Mendapatkan Amazon Gift Card Senilai ₹100 Atau Koin!\nCek Dulu Yuk Di Ransel!",
    "newsuserB_tips_getluckybox_tips": "Undi Dan Raih Peluang Mendapatkan Amazon Gift Card Senilai ₹100 Atau Koin!",
    "newsuserB_tips_getluckybox_cannotopen": "Buka Setelah {num}",
    "newsuserB_tips_getluckybox_openfail": "Gagal Membuka. Coba Lagi Nanti, Ya!",
    "newsuserB_tips_getluckyboxopen": "Buka Peti Spesial Sekarang Lalu Undi Dan Raih\nPeluang Mendapatkan Amazon Gift Card Senilai ₹100 Atau Koin!",
    "newsuserA_tips_stay": "Tetap Di Sini",
    "newsuserA_tips_leave": "Keluar?",
    "newsuserA_tips_open": "Buka",
  },
  "MainChat": {
    "Button_Team_SendTeamRecruitment": "Kirim Ajakan Gabung Tim",
    "Chat_World_NoChatTypeTips": "[Jenis Pesan Ini Tidak Didukung.]",
    "Chat_World_EmptyTips": "Pesan Tidak Boleh Kosong.",
    "Chat_NoMessage_Tips": "Klik Di Sini Untuk Chat",
    "Chat_Tab_World": "Global",
    "Chat_Tab_Team": "Tim",
    "Chat_Tab_Friends": "Teman",
    "Chat_World_DefaltTips": "Ketik Pesan",
    "Button_Chat_Send": "Kirim",
    "Chat_Team_Send_WorldChat": "Kirim Ke Chat Global",
    "Chat_Team_Join": "Gabung",
    "Chat_Local_Tips": "Hanya Chat Lokal",
    "Chat_Friends_NewMessageTips": "Pesan Baru",
    "Chat_Friends_ClickTips": "Tap Teman Untuk Memulai Chat.",
    "Chat_Friends_NoFriendsTips": "Kamu Perlu Menambahkan Teman Dulu.",
    "Chat_World_LocalTips": "Tap Di Sini Untuk Masuk Ke Chat Lokal",
    "Chat_Low_Level": "Mainkan Lebih Banyak Match Untuk Mencapai Level {num} Biar Bisa Chat!",
    "Chat_World_JoinTips": "Kamu Gabung Ke Chat Global",
    "Chat_Local_JoinTips": "Kamu Gabung Ke Chat Lokal",
    "Chat_Close_Tips": "Aktifkan Chat?",
    "Tips_Team_SendSuccess": "Ajakan Gabung Tim Dikirim Ke Chat Global.",
    "Chat_SendTooFast": "Kamu Bicara Terlalu Cepat. Coba Lagi Nanti, Ya!",
  },
  "RedEnvelope": {
    "HB_Bag_Title": "Tas Spesial",
    "HB_Coins_Tips": "{num1}~{num2} Koin",
    "HB_Coins_Tipstop": "{num1} Koin",
    "HB_Image_Text": "Bagi-Bagi Keberuntunganmu Dan Buka Tas Spesial.",
    "HB_Open_Require": "Yuk, Ajak Temanmu Buat Buka Bareng-Bareng!",
    "HB_Open_Tips": "Makin Banyak Teman Yang Gabung, Makin Banyak Pula Koin Yang Kamu Dapetin!",
    "HB_NoOpen_Tips1": "Menunggu Temanmu Gabung Lewat Link.",
    "HB_NoOpen_Tips2": "Waktu Ada Teman Yang Gabung Lewat Link, Kamu Bisa Buka Tas Spesial.",
    "HB_Join_One": "Makin Banyak Teman Yang Gabung, Makin Banyak Pula Koin Yang Kamu Dapetin!",
    "HB_Join_More": "Makin Banyak Teman Yang Gabung, Makin Banyak Pula Koin Yang Kamu Dapetin!",
    "HB_Can_Open_Tips": "Buka Tas Spesial Hari Ini",
    "HB_Share_Title1": "Koin Di Ludo World, Buka Tas Koin Buat Ambil Hadiahmu.",
    "HB_Share_Title2": "Tas Spesial Di Ludo World, Buka Aja, Siapa Tau Lagi Beruntung!",
    "HB_Btn_Open": "Buka",
    "HB_Btn_Open_noinvite": "Ajak",
    "HB_Collect_Fail": "Yahh, Koinnya Habis.",
  },
  "LuckyBag": {
    "Clearing_Win_Share_Title": "Kotak Rahasia",
    "Clearing_Win_Share_Content": "Ajak Teman Buat Mengumpulkan Bareng-Bareng",
    "Clearing_Loser_Share_Title": "Koin GRATIS",
    "Clearing_Loser_Share_Content": "Ajak Teman Mengumpulkan Bareng-Bareng",
    "Clearing_Win_Ads_Title": "Kotak Rahasia",
    "Clearing_Win_Ads_Content": "Tonton Iklan Untuk Mendapatkan",
    "Clearing_Loser_Ads_Title": "Koin GRATIS",
    "Clearing_Loser_Ads_Content": "Tonton Iklan Untuk Mendapatkan",
    "Clearing_Welfare_Share_Title": "Ajak Teman Mengumpulkan",
    "Clearing_Share_Finish": "Tap Link Yang Baru Aja Kamu Bagikan Dalam {num} Detik Untuk Mendapatkan Hadiah!",
    "Clearing_Welfare_Ads_Title": "Perlu Tambahan Koin?",
    "Clearing_Welfare_Ads_Content": "Tonton Iklan Untuk Raih",
    "Clearing_Share_Loser": "Link Yang Dibagikan Tidak Valid, Kirim Lagi Linknya",
  },
  "LuckSeven": {
    "Un_Lock_tips": "Perlu {num1} Lemparan Lagi Buat Buka Lebih Banyak!",
    "Not_Enough_Gold": "Koin Kurang",
    "High_Laid": "Kamu Udah Mencapai Level Tertinggi!",
    "Low_Laid": "Kamu Udah Mencapai Level Terendah!",
    "Show_FreeBet": "Tiket GRATIS {num2} Kali!",
    "Coins": "KOIN",
    "laid_start_To_end": "{start} SAMPAI {end}",
    "WIN": "MENANG",
    "Get_Free_Bet": "Dapatkan Tiket GRATIS!",
    "Double": "Double {point}",
    "Error": "Terjadi Kesalahan Data. Yuk, Buka Lagi Halamannya!",
  },
  "EliminatGame": {
    "Select_Hint": "Yuk, Pilih Koin Yang Mau Kamu Bayarkan!",
    "Not_Coins": "Koinmu Kurang. Yuk, Beli Lagi Di Toko!",
    "Min_Coins": "Sudah Mencapai Koin Minimum",
    "Max_Coins": "Sudah Mencapai Koin Maksimum",
    "Win": "MENANG",
    "Big_Win": "Kemenangan Spektakuler",
    "Super_Winner": "Pemenang Super",
    "Total_Win": "Total Menang",
    "Fish_Party": "Tantangan Ikan",
    "Quit_Hint": "Kamu Sedang Dalam Match. Yakin Mau Keluar?",
    "AllIn": "Semuanya",
    "Auto": "Otomatis",
    "Start": "Mulai",
    "EliminatGameTitle": "Petunjuk Mode",
    "Game_Rules": "Aturan Game",
    "Explain": "Petunjuk Tantangan Ikan",
    "Party_Text": "Gabungkan tiga ikan yang sama dalam satu baris untuk menghilangkannya dan mendapatkan Hadiah!\n\nSetelah ikan dihilangkan, game akan terus mengisi ulang ikan sampai tidak ada lagi yang bisa dihilangkan.",
    "Select_Fish": "Pilih Ikan Yang Mau Kamu Dukung",
    "Eliminate_Award": "Hilangkan Dan Dapatkan Koin!",
    "Records": "Lihat Hadiah Dan Rekor",
    "Settlement_Rules": "Penghitungan Hadiah",
    "Settlement_Rules_Text": "Gabungkan tiga ikan yang sama dalam satu baris untuk menghilangkannya dan mendapatkan Hadiah!\nSetiap ikan akan dihitung secara terpisah untuk menentukan Hadiah.\nJenis ikan dan jumlah yang dihilangkan akan memengaruhi Hadiah yang diterima.\nHadiahmu akan dikalikan dengan pengali berikut.\nSemakin banyak ikan yang dihilangkan dalam satu baris, semakin banyak pula Hadiahnya!",
    "Back_Game": "Kembali Ke Game",
    "Game_Name": "Pesta Ikan",
    "Activity_Ended": "Aktivitas Sudah Selesai.",
  },
  "NewDiBao": {
    "NewDiBaoTitle": "PAKET SPESIAL",
    "Tip": "Dapatkan Koin Spesial Hari Ini",
    "mulit": "Ambil",
    "extra": "EKSTRA",
    "basic": "DASAR",
    "coins": "KOIN",
    "togle": "Tontok Iklan Dan Dapatkan {num} Koin!",
    "Before_Game_GoldEnough": "Yahh, Koinmu Kurang",
    "StartGame": "Mulai Game",
  },
  "InsufficientCoin": {
    "title": "Kamu Perlu Setidaknya {num} Koin Untuk Main.",
    "tip": "Sekarang Kamu Punya {haveCoin} Koin",
    "goScene": "Mode Direkomendasikan",
    "toOtherModel": "Koinmu ({coins}) Tidak Cukup Untuk Main Mode Ini, Mau Pilih Mode Lain?",
    "friend": "Teman",
    "computer": "AI",
    "toOfferPlay": "Koinmu Kurang. Buka Mode Direkomendasikan?",
  }
}
let loadMessage = function(language, dataID, isChange) {

};
exports.loadMessage = loadMessage;