'use strict';
if (!window.i18n) {
  window.i18n = {};
}

if (!window.i18n.languages) {
  window.i18n.languages = {};
}

window.i18n.languages['LatinAmericanSpanish'] = {
  "label_text": {
    "Ads_getRewards_Title": "Obtener recompensas",
    "Ads_CountDown_tips": "Próxima recompensa en:",
    "Ads_watchAd_Title": "Ver anuncio",
    "Auto_Game": "Automático",
    "Button_Guest_Facebook": "Iniciar sesión con Facebook",
    "Button_Guest_Continue": "Seguir como invitado",
    "Button_Common_Confirm": "OK",
    "Button_Common_Yes": "Sí",
    "Button_Common_No": "No",
    "Button_Common_Next": "Siguiente",
    "Button_Common_Restart": "Reiniciar",
    "Button_Common_Return": "Atrás",
    "Button_Common_Share": "Compartir",
    "Button_Common_Start": "Empezar",
    "Button_Common_Facebook": "Iniciar sesión con Facebook",
    "Button_Common_Guest": "Invitado",
    "Common_Guest_BindAccount": "¿Quieres vincular tu cuenta de Facebook?",
    "Common_Guest_BindAccountFail": "La conexión con Facebook falló. Intenta de nuevo más tarde.",
    "Common_Guest_RepeatBind": "Ya vinculaste una cuenta de Facebook. ¿Quieres iniciar sesión con esa cuenta?",
    "Common_Guest_Confirm": "Te conectaste como invitado y no puedes jugar con tus amistades. \nInicia sesión con Facebook para: \n1. Jugar con amistades \n2. Usar tu foto de perfil en el juego \n3. Jugar en varios dispositivos con la misma cuenta. Te conectaste como invitado y no puedes jugar con tus amistades.",
    "Common_Online_ShareContent": "¡Quedé en el puesto {1} en {0} y gané {2} monedas!",
    "Common_Scene_Teamup_Teammateturn": "¡Ya puedes seguir jugando y ayudar a tu colega!",
    "Common_Game_Props_GetTipsTitle_DoubleDice": "Distancia doble",
    "Common_Game_Props_GetTipsContent_DoubleDice": "Lanza los dados para avanzar el doble.",
    "Common_Game_Props_GetTipsTitle_AssignDice": "Dado controlado",
    "Common_Game_Props_GetTipsContent_AssignDice": "Elige el número que quieres en los dados",
    "Common_Game_Props_GetTipsTitle_Protection": "Escudo protector",
    "Common_Game_Props_GetTipsContent_Protection": "Te protege de las otras fichas por 1 turno",
    "Common_Game_Props_GetTipsTitle_LuckyNumber": "Número dorado",
    "Common_Game_Props_GetTipsContent_LuckyNumber": "Durante 1 ronda, cualquier persona que saque este número puede volver a tirar.",
    "Common_Scene_Props_Introduce_Title": "Conocer Modo potenciado",
    "Common_Scene_Props_introduce_luckyNumber": "Número dorado",
    "Common_Scene_Props_introduce_luckyNumber_": "Durante 1 ronda, cualquier persona que saque este número puede volver a tirar. Se aplica de forma inmediata para todas las personas.",
    "Common_Scene_Props_introduce_DoubleDice": "Distancia doble",
    "Common_Scene_Props_introduce_DoubleDice_": "Duplica el número obtenido. Se debe avanzar esa cantidad de espacios de inmediato. Luego de usar este objeto, sacar un 6 no otorga tiradas extra ni permite eliminar fichas.",
    "Common_Scene_Props_introduce_AssignDice": "Dado controlado",
    "Common_Scene_Props_introduce_AssignDice_": "Elige el número del dado. Al sacar un 6, capturar una ficha o alcanzar la meta, hay una tirada adicional disponible.",
    "Common_Scene_Props_introduce_Protection": "Escudo",
    "Common_Scene_Props_introduce_Protection_": "Evita que capturen tus fichas durante 1 turno.",
    "Common_Game_Props_ShowTips_LuckyNumber": "Tirada extra",
    "Common_Game_Props_ShowTips_LuckyNumber_": "Obtén una tirada adicional al llegar",
    "Common_Game_Props_ShowTips_DoubleDice": "Distancia doble",
    "Common_Game_Props_ShowTips_DoubleDice_": "Avanza el doble del número que sacas en los dados.",
    "Common_Game_Props_ShowTips_AssignDice": "Dado controlado",
    "Common_Game_Props_ShowTips_AssignDice_": "Elige el número que quieres en los dados",
    "Common_Game_Props_ShowTips_Protection": "Escudo protector",
    "Common_Game_Props_ShowTips_Protection_": "Te protege de las otras fichas por 1 turno",
    "Common_Game_Props_Haved": "Los potenciadores solo se pueden usar antes de lanzar los dados.",
    "Common_Game_Props_NotHaved": "No tienes este potenciador.",
    "Common_Team": "Equipo",
    "Common_Choose_Color": "Elegir color",
    "Common_Game_Online_MyPlace": "¡Estás aquí!",
    "Common_Choose_Number": "Elegir participantes",
    "Common_Choose_Bet": "Elegir apuesta",
    "Common_Choose_Mode": "Elegir modo",
    "Common_Choose_Number_players": "Participantes",
    "Common_Choose_Win": "Gana:",
    "Common_Choose_Entry": "Apuesta:",
    "Common_Choose_Number_two": "2",
    "Common_Choose_Number_four": "4",
    "Common_Choose_Number_multi": "2-4",
    "Common_Choose_Number_Team": "Formar equipo",
    "Common_Choose_Number_2v2": "2v2",
    "Common_Game_Props_share": "¡Comparte y consigue\nartículos!",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Elegir número",
    "Common_Game_Props_sharetogetprops_title": "¡Comparte con amistades para obtener 3 potenciadores gratis!",
    "Common_Game_Props_sharetogetprops_share": "Compartir",
    "Common_Game_Props_sharetogetprops_aftershare": "Cada juego solo se puede compartir una vez",
    "Friend_Room_Entering": "Entrando a la sala...",
    "Friends_Invite": "Invitar por:",
    "GameName": "Ludo World",
    "Game_Common_start": "Inicio del juego",
    "Game_EndTitle_Win": "Victoria",
    "Game_EndTitle_Lose": "Derrota",
    "Game_EndOrder_1": "1.º",
    "Game_EndOrder_2": "2.º",
    "Game_EndOrder_3": "3.º",
    "Game_EndOrder_Win": "Victoria",
    "Game_EndOrder_4": "4.º",
    "Game_EndOrder_5": "5.°",
    "Game_EndOrder_6": "6.°",
    "Game_EndOrder_Lose": "Derrota",
    "Game_EndOrder_Playing": "Jugando",
    "local_Result_title": "Resultado",
    "Game_Online_Auto1": "Movimiento automático",
    "Game_Online_Auto2": "Toca aquí para parar",
    "Game_Props_TopTitle_LuckyNumber": "Número\n dorado",
    "Game_Props_ItemTips_DoubleDice": "Distancia doble: duplica el número obtenido. Se debe avanzar esa cantidad de espacios de inmediato. Luego de usar este objeto, sacar un 6 no otorga tiradas extra ni permite eliminar fichas.",
    "Game_Props_ItemTips_AssignDice": "Dado controlado: elige el número del dado. Al sacar un 6, capturar una ficha o alcanzar la meta, hay una tirada adicional disponible.",
    "Game_Props_ItemTips_Protection": "Escudo: evita que capturen tus fichas durante 1 turno.",
    "Game_leaderboard_title": "Clasificación",
    "Game_leaderboard_global": "General",
    "Game_leaderboard_NotRanked": "Sin clasificación",
    "Game_leaderboard_tips": "Las estadísticas se actualizarán todos los lunes.",
    "Game_leaderboard_tips2": "Solo se cuentan los juegos en línea.",
    "Game_leaderboard_tipsoneline": "Las estadísticas (juegos en línea) se actualizan todos los lunes.",
    "Game_Computer_PlayerName1": "CPU1",
    "Game_Computer_PlayerName2": "CPU2",
    "Game_Computer_PlayerName3": "CPU3",
    "Game_Computer_level_choose": "Elegir nivel",
    "Game_Computer_Self": "Tú",
    "Game_Computer_level_easy": "Fácil",
    "Game_Computer_level_normal": "Normal",
    "Game_Computer_level_hard": "Difícil",
    "Game_Computer_PlayerNameEasy": "Computadora{num} fácil",
    "Game_Computer_PlayerNamenormal": "Computadora{num} normal",
    "Game_Computer_PlayerNamehard": "Computadora{num} difícil",

    "Game_local_Remove_comfirm": "¿Quieres eliminar a esta persona?",
    "Game_local_Remove_guide_title": "Eliminar participante",
    "Game_local_Remove_guide_content1": "¿Quién no quiere jugar?",
    "Game_Friend_Pnael_Title": "Jugar con amistades",
    "Game_Friend_Select_Mode": "Elegir modo",
    "Game_Friend_Create": "Crear",
    "Game_Friend_Join": "Unirse",
    "Game_Friend_Join_Clear": "Borrar",
    "Game_Friend_GameMode": "Elegir modo",
    "Game_Friend_Enter_RoomCode": "Ingresa el código de la sala",
    "Game_friends_invite_code": "Código de la sala",
    "Game_friends_invite_tips_cannot": "Esperando que se unan...",
    "Game_friends_invite_tips_can": "Esperar más o empezar ya.",
    "Game_friends_join_tips": "Ingresa el código de la sala",
    "Game_friends_join_join": "Unirse",
    "Game_friends_join_wait": "Esperando a {who} para empezar",
    "Game_friends_choose_classic": "Clásico",
    "Game_friends_choose_power": "Potenciado",
    "Game_friends_choose_mode": "Modo",
    "Game_friends_invite_waiting": "Esperando que se unan...",
    "Game_friends_invite_waitormore": "Esperar más o empezar ya",
    "Game_friends_invite_start2V2": "Puedes empezar el juego",
    "Game_friends_invite_share": "Comparte el código de la sala para invitar a amistades",
    "Game_Ready": "¡Listo!",
    "Guest_Username": "Invitado",
    "help_classic_title": "Clásico",
    "help_powerUp_title": "Potenciado",
    "InGame_PlayerInfo_Match": "Partida",
    "InGame_PlayerInfo_Win": "Victoria",
    "InGame_PlayerInfo_Gift": "Regalo (100 monedas por regalo)",
    "introduce_friendModel": "jugar solo con amistades",
    "LevelUp_Panel": "Subir de nivel",
    "LevelProgressPanelExp": "EXP",
    "LoadGame_Button_Load": "Cargar",
    "Login_loading": "Iniciando sesión...",
    "Lobby_receive_award_coins": "Monedas",
    "Lobby_invite_detail1": "Invita a amistades y gana {num} monedas por cada una que se una con este enlace",
    "Lobby_invite_detail2": "Recibirás una recompensa por correo cada vez que tus amistades se conecten por Facebook (hasta {times} veces por día)",
    "Lobby_invite_btn": "Invitar",
    "Lobby_invite_title": "¿Necesitas más monedas?",
    "Lobby_invite_guestlogin": "¿Conectar tu cuenta de Facebook para continuar?",
    "MainScenes_Fackback": "Comentarios",
    "MainScenes_Ranking": "Clasificación",
    "MainScenes_Invite": "Invitar",
    "MainScenes_FreeCoins": "Monedas gratis",
    "MainScenes_Mission": "Misión",
    "modify_title": "Editar perfil",
    "Notice_Panel_Title": "Aviso",
    "Notice_Panel": "Cargando",
    "NotLogin": "Error de inicio de sesión. Intenta de nuevo más tarde.",
    "Offline_TeamA": "equipo A",
    "Offline_TeamB": "equipo B",
    "OffLine_PanelPlayer": "Participantes",
    "PropsShareTips": "¡Comparte y consigue \n artículos!",
    "Props_ShowTips": "EJEMPLO",
    "PersonalInfo_Win": "Victoria",
    "PersonalInfo_Total": "Total",
    "PersonalInfo_WinRate": "Tasa de victorias",
    "PersonalInfo_Edit": "Editar",
    "PersonalInfo_Computer": "Computadora",
    "PersonalInfo_ClassicOnline": "Modo clásico",
    "PersonalInfo_PropsOnline": "Modo potenciado",
    "PersonalInfo_Props2V2": "Modo 2v2 potenciado",
    "PersonalInfo_Classic2V2": "Modo 2v2 clásico",
    "PersonalInfo_Notenough_player": "Esperando a {Number} personas más",
    "PersonalInfo_Friend": "Amistades",
    "PersonalInfo_Level": "Nv.",
    "PersonalInfo_ClassicOnlineTitle": "Clásico en línea",
    "PersonalInfo_PropsOnlineTitle": "Potenciado en línea",
    "PersonalInfo_TeamUpOnline": "Modo en equipo",
    "PersonalInfo_MiniMapOnline": "Modo minimapa",
    "PlayerProfile_LoginFB": "Iniciar sesión con Facebook",
    "PlayerProfile_Continue": "Continuar",
    "Rank_PanelWin": "Victoria",
    "Select_Robot": "Se necesitan al menos 2 humanos.",
    "SaveGame_Content": "¿Quieres terminar el juego?",
    "SaveGame_Save": "Guardar",
    "ShareGame_EXP": "Comparte y obtén 10 de EXP",
    "share_window_invite": "Invitar amistades",
    "Scene_Online_Title": "En línea",
    "Scene_local_Title": "Local",
    "Scene_local_ChooseMode": "Elegir modo",
    "Scene_local_ChooseMode_Classic": "Clásico",
    "Scene_local_ChooseMode_Props": "Potenciado",
    "Scene_local_ChooseMode_TeamUp": "En equipo",
    "Scene_local_ChooseMode_TeamPower": "En equipo potenciado",
    "Scene_local_ChooseMode_TeamClassic": "En equipo clásico",
    "Scene_local_ChooseColorAndName": "Elegir color y nombre",
    "Scene_Online_ChooseBet": "Elige tu apuesta",
    "Scene_local_ChoosePlaers": "Elegir participantes",
    "Scene_local_ChoosePlaers_2P": "2 participantes",
    "Scene_local_ChoosePlaers_3P": "3 participantes",
    "Scene_local_ChoosePlaers_4P": "4 participantes",
    "Scene_local_PlayerName1": "Participante 1",
    "Scene_local_PlayerName2": "Participante 2",
    "Scene_local_PlayerName3": "Participante 3",
    "Scene_local_PlayerName4": "Participante 4",
    "Scene_local_ChooseTeam": "Elegir equipo",
    "Scene_ClassicOnline_Title": "Clásico",
    "Scene_PropsOnline_Title": "Potenciador",
    "Scene_MiniMapOnline_Title": "Minimapa",
    "Scene_TeamUpOnline_Title": "En equipo",
    "Scene_Computer_Title": "Computadora",
    "Scene_Friend_Title": "Amistades",
    "Scene_Online_ChoosePlaers_2P": "2 participantes",
    "Scene_Online_ChoosePlaers_4P": "4 participantes",
    "Scene_Online_matching": "Esperando a otras personas...",
    "Set_Panel_Title": "Configuración",
    "Set_Panel_Music": "Música",
    "Set_Panel_Sound": "Sonido",
    "Set_Panel_Version": "Versión",
    "Set_Panel_About": "Acerca de",
    "Set_Panel_About_Detail": "¡Gracias por apoyar\nLudo World! Si tienes\nalgún comentario,\nescribe a\nhpludoworld@gmail.com",
    "Set_Panel_Help": "Ayuda",
    "Set_Panel_Feedback": "Comentarios",
    "Set_Panel_US": "Me gusta",
    "Set_Panel_RATE": "Califícanos",
    "Set_Panel_Privacy": "Política de privacidad",
    "Set_Panel_Terms": "Términos de servicio",
    "Set_FB_Login": "Iniciar sesión",
    "Set_FB_Logout": "Cerrar sesión",
    "Set_FB_Bind": "Conectar",
    "Set_Panel_Vibrate": "Vibración",
    "Set_Panel_Chat": "Chatear",
    "Set_Panel_Help_minimap": "Mismas reglas que el modo clásico.\nMapa más pequeño, ritmo más rápido.\nSolo 4 casillas seguras, una en cada punto de partida de cada color.",
    "Title_Load_Game": "Cargar juego",
    "Title_PlayerProfile": "Perfil",
    "Tips_Game__ThreeSixSkip": "¡3 veces seguidas\nseis, saltar!",
    "Lucky_Wheel_Name": "Rueda de la fortuna",
    "Game_info_block": "Bloquear",
    "Game_info_unblock": "Desbloquear",
    "Button_Item_Use": "Usar",
    "Button_Item_Using": "Usando",
    "Button_Item_gotouse": "Ir a usar",
    "Main_Backpack": "Mochila",
    "Item_Duration_Duration": "Duración:",
    "Item_Duration_Day": "d",
    "Item_Duration_Hour": "h",
    "Item_Duration_Min": "min",
    "Item_Duration_S": "s",
    "Item_Duration_Year": "a",
    "Item_Duration_Permanent": "Permanente",
    "NewPlayerBonus_Gift": "Regalo",
    "Common_Game_item_purchase": "Compra mediante tarjetas de objetos, tienes {num} más",
    "Common_Game_item_purchaseoverbuy": "Solo puedes intercambiar {num} veces por juego",
    "Common_Game_itemcard_notenought": "¡Cartas de artículos insuficientes! ¿Comprar más en la tienda?",
    "Lobby_mini": "Minimapa",
    "Common_IOS_Shop_LessConins": "No te alcanzan las monedas. Participa en el evento para obtener más.",
    "ComputerAndLocal": "Computadora y local",
    "Common_Game_Undo_Lack": "falta",
    "Common_Game_Undo_Lack_Tip": "No te alcanzan las gemas para anular el movimiento",
    "Common_Game_Undo_Left": "Anulaciones restantes",
    "Common_Game_Undo_Switch": "Anulación activada",
    "Common_Game_Undo_Title_Enable": "Anular tirada de dado",
    "Common_Game_Undo_Title_Disable": "La anulación está DESACTIVADA",
    "Common_Game_Undo_Desc_Enable": "Si tocas aquí antes de que pasen {num} segundos tras tirar el dado, podrás anular el resultado",
    "Common_Game_Undo_Desc_Disable": "Desactivaste la opción \"Anular\"; toca el recuadro para volver a activarla",
    "Common_Game_Undo_Desc_Use_Up": "No quedan anulaciones",
    "Grand_Prix_Entry": "COSTO DE ENTRADA",
    "Grand_Prix_Endsin": "Termina en",
    "Grand_Prix_Play": "JUGAR",
    "Grand_More_Coins": "Más monedas",
    "Grand_More_Level": "Nv. {date} disponible",
    "Starter_Pack": "Paquete inicial",
    "Gift_Bag_Time": "Quedan {date} horas",
    "Lucky_Dice": "Dado de la suerte",
    "Exclusive_Offert": "Oferta exclusiva",
  },
  "AlertText": {
    "Button_Common_Confirm": "OK",
    "Button_Common_Yes": "Sí",
    "Button_Common_Cancel": "Cancelar",
    "Button_Common_No": "No",
    "Button_Common_Upgrade": "Mejorar",
    "Button_Common_NoUpgrade": "Más tarde",
    "Button_Common_ExitUpgrade": "Salir del juego",
    "Bind_FB_Account": "La conexión con Facebook falló. Intenta de nuevo más tarde.",
    "Bind_FB_Account2": "Esta cuenta de Facebook ya está conectada. Intenta de nuevo con otra cuenta.",
    "Common_Game_Online_Leave": "Si abandonas el juego perderás. ¿Igual quieres salir?",
    "Common_Game_Local_Leave": "¿Salir del juego actual?",
    "Common_Game_Local_SaveGame": "¿Guardar la partida actual?",
    "Common_Game_Computer_SaveGame": "¿Guardar la partida actual?",
    "Common_Game_Computer_EnterBySaveGame": "Tienes un juego empezado. ¿Quieres cargarlo?",
    "Common_Notify_Client_Logout": "Esta cuenta está en uso en otro dispositivo. Inicia sesión otra vez para seguir jugando en este dispositivo.",
    "Common_Netword_Fail": "Verifica tu conexión de red.",
    "Common_Netword_Fail_Offline": "Falló la conexión de red. ¿Jugar en modo local y computadora?",
    "Common_Netword_FailRethy": "Falló la conexión de red. ¿Conectarse ahora?",
    "Common_Netword_Fail_timeout": "La conexión de red expiró. Intenta de nuevo más tarde.",
    "Common_Netword_Fail_Reconnect": "Tienes que conectarte a la red para jugar en línea. ¿Conectar ahora?",
    "Common_Lobby_ReturnGame": "Estás jugando en una sala. ¿Regresar a la sala?",
    "Common_Lobby_ReturnFailed": "Finalizó tu última partida.",
    "Common_Scene_Online_LessCoins": "Monedas insuficientes. Compra más en la tienda.",
    "Common__Online_Matching_Failed": "Error al entrar a la sala. Intenta de nuevo más tarde.",
    "Common_Scene_Online_Matching_TimeOut": "Se agotó el tiempo para entrar a la sala. Intenta de nuevo más tarde.",
    "Common_Scene_Online_Sitting_Failed": "Error al sentarse. Intenta de nuevo más tarde.",
    "Common_No_Operation": "Se te eliminará del juego si permaneces demasiado tiempo sin actividad.",
    "Common_Delete": "¿Quieres eliminar el juego guardado?",
    "Common_Game_TeamUp_GetUserGuide": "¡En equipo es un modo nuevo! ¿Ir al tutorial?",
    "Facebook_Login_Faile": "Error al iniciar sesión en Facebook. Verifica tu red.",
    "Game_leaderboard_sendBean_success": "Se regalaron las monedas con éxito",
    "Game_leaderboard_sendBean_fail": "Error al enviar monedas",
    "Game_leaderboard_sendBean_Max": "Alcanzaste el número máximo de monedas de regalo de hoy.",
    "Game_Reselect_bet": "Tus monedas superan el límite de apuesta. Inicia una nueva partida en una sala de apuestas superior.",
    "Game_chat_Common_Yes": "Activar",
    "Game_chat_Common_MainText": "Cuando el chat está activado, otras personas pueden ver tus conversaciones. ¿Activar chat ahora? Puede desactivarse luego desde la configuración.",
    "Game_Friend_Join_Not_Find": "Sala no encontrada. Verifica el código de sala.",
    "Game_Friend_Join_Room_Closed": "La sala ya está disuelta. Inicia un nuevo juego.",
    "Game_Friend_Join_Not_Enough_Coins": "Tus monedas no alcanzan para unirte a la sala. ¿Conseguir más en la tienda?",
    "Game_Friend_Join_No_Extra_Seat": "Vaya, la sala está llena. Inicia una nueva partida.",
    "Game_Friend_Join_alreadybegin": "La partida ya comenzó. Inicia una nueva partida.",
    "Game_Friend_Leave_Room": "Si te vas, la sala se cerrará. ¿Salir de todos modos?",
    "Login_NO_IP": "Lamentablemente, dada tu ubicación actual, por el momento no podemos ofrecerte nuestros servicios.",
    "Modify_HeadIcon_Fail": "Error al modificar, intenta más tarde.",
    "Matching_Failed": "Error de emparejamiento. Intenta de nuevo más tarde.",
    "No_Operation_ConfirmText": "Quedarme",
    "No_Operation_CancelText": "Salir",
    "Quit_Game": "¿Quieres salir del juego?",
    "Store_buy_tips": "Monedas insuficientes. ¿Conseguir más en la tienda?",
    "Store_buy_latter": "¡Más tarde!",
    "Store_Open_Failed": "Error al cargar datos. Intenta de nuevo más tarde.",
    "Store_buy_go": "Ir",
    "Store_Payment_Failed": "Pago fallido. Código de error:",
    "Store_Payment_IPFailed": "Pago fallido. Puedes intentar pagar por PC Instant Game.",
    "ShortCut_go": "¿Crear un acceso directo en la pantalla de inicio?",
    "Client_Low_Version": "La sala requiere la última versión. ¿Actualizar ahora?",
    "Client_High_Version": "Ups, tu versión del cliente no puede entrar en la sala.",
    "Client_Deny_Version": "Ups, tu versión del cliente no puede entrar en la sala.",
    "Play_Punish_In_Chat": "Te silenciaron hasta el {date} por infringir las reglas.",
    "Play_Punish_In_Room": "Tu cuenta está suspendida hasta el {date} por infringir las reglas.",
    "Play_Punish_Enter_Room": "Tu cuenta fue suspendida por infringir las reglas.",
    "Kicked_Player_Not_Enough_Coins": "Cuando no tengas suficientes monedas, perderás la partida si te capturan. ¿Conseguir más en la tienda?",
    "Kicked_Player_Game_Lose": "Perdiste. No tienes monedas suficientes para continuar el juego.",
    "Backpack_items_empty": "Todavía no hay objetos. ¿Conseguir en la tienda?",
    "Grand_Unlock_level": "Se desbloquea al alcanzar el nivel {date}",
    "Grand_Open_Hint": "Abre el gran pozo después de {date}",
    "Grand_Less_Coins_recommend": "Tienes menos de la cantidad recomendada de monedas ({date}) para entrar al juego. ¿Continuar?",
    "Grand_Less_Coins_Hint": "Tus monedas no te alcanzan para unirte al gran pozo. ¿Quieres conseguir más en la tienda?",
  },
  "Tips": {
    "Ads_times_tips": "Vuelve mañana por más recompensas.",
    "Ads_times_tips_Gems": "Vuelve mañana para obtener más gemas.",
    "Ads_coolCd_tips": "Intenta de nuevo más tarde.",
    "Ads_none_tips": "No hay anuncios para ver ahora. Prueba más tarde.",
    "Ads_none_tips1": "No hay anuncios para ver ahora.",
    "Ads_notFull_tips": "¡Mira el video completo para obtener recompensas!",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Elegir número",
    "Friend_Err_Fetch_List_Fail": "Error al cargar datos. Intenta de nuevo más tarde.",
    "Friend_Err_Fetch_Online_Fail": "Error al cargar datos. Intenta de nuevo más tarde.",
    "Friend_Err_Fetch_Login_Time_Fail": "Error al cargar datos. Intenta de nuevo más tarde.",
    "Friend_Err_Not_Add_Player": "Error al procesar, intenta de nuevo más tarde.",
    "Friend_Err_List_Full": "Alcanzaste el número máximo de amistades. Para agregar a esta persona, debes eliminar a otras.",
    "Friend_Err_Peer_Friend_List_Full": "{name} alcanzó el número máximo de amistades y no puede agregarse.",
    "Friend_Err_Update_Friend_Fail": "Error al cargar datos. Intenta de nuevo más tarde.",
    "Friend_Err_Player_Refuse_Add": "{name} no está aceptando solicitudes de amistad.",
    "Friend_Err_Already_In_Add_List": "",
    "Friend_Err_Already_In_Game_List": "Ya son amistades.",
    "Friend_Err_Already_In_Platform_List": "Ya son amistades.",
    "Friend_Err_Not_In_List": "Error al procesar, intenta de nuevo más tarde.",
    "Friend_Err_Fetch_Game_Record_Fail": "Error al cargar datos. Intenta de nuevo más tarde.",
    "Friend_Err_Cannot_Add_Self": "Error al agregar. Intenta de nuevo más tarde.",
    "Game_Props_TopTitle_LuckyNumber": "Número\n dorado",
    "Game_Props_ItemTips_DoubleDice": "Distancia doble: duplica el número obtenido. Se debe avanzar esa cantidad de espacios de inmediato. Luego de usar este objeto, sacar un 6 no otorga tiradas extra ni permite eliminar fichas.",
    "Game_Props_ItemTips_AssignDice": "Dado controlado: elige el número del dado. Al sacar un 6, capturar una ficha o alcanzar la meta, hay una tirada adicional disponible.",
    "Game_Props_ItemTips_Protection": "Escudo: evita que capturen tus fichas durante 1 turno.",
    "Game_gift_gift": "¡Enviar emoji!",
    "Game_gift_giftprice": "100 monedas por emoji",
    "Game_gift_sendtoofast": "Toma un descanso.",
    "Game_leaderboard_load_fail_tips": "Error al cargar datos. Intenta de nuevo más tarde.",
    "Game_classic_newusertips_moveout1": "¡Saca un 6 para despegar!",
    "Game_classic_newusertips_mesafe": "¡Las casillas con estrella son seguras!",
    "Game_classic_newusesrtip_bumptoken": "¡Patea esta ficha!",
    "Game_Friend_JoinTips_Invalid_RoomCode": "El código de la sala es inválido. Revísalo.",
    "Lobby_unfinish_notice": "¡La función llegará pronto!",
    "shortCut_create_succ": "Creación de acceso directo exitosa.",
    "shortCut_create_fail": "Error al crear acceso directo. Intenta de nuevo",
    "shortCut_bubble_tips": "Toca aquí para crear el acceso directo en el inicio",
    "Tips_Longin_Fail": "Error al iniciar sesión. ¡Intenta más tarde!",
    "Tips_Netword_Fail_TryReconnect": "Falló la conexión de red; reconectando",
    "Tips_Netword_Fail_Reconnected": "¡Conexión restablecida!",
    "Tips_Game__ThreeSixSkip": "¡3 veces seguidas\nseis, saltar!",
    "Tips_Game_Props_UseTips_DoubleDice": "¡Distancia doble! ¡Tirada duplicada!",
    "Tips_Game_Props_UseTips_AssignDice": "¡Dado controlado! Sacaste un",
    "Tips_Game_Props_UseTips_Protection": "Evita que capturen tus fichas durante 1 turno.",
    "Tips_Game_Props_UseTips_LuckyNumber": "Tirada extra, ¡tira de nuevo!",
    "Tips_Game_Props_UseFail_DoubleDice": "¡No hay fichas para usar este artículo!",
    "Tips_Game_Props_UseFail_Protection": "¡No hay fichas que proteger!",
    "Tips_Game_Props_OtherUseTips_DoubleDice": "¡Distancia doble usada!",
    "Tips_Game_Props_OtherUseTips_AssignDice": "¡Dado controlado usado!",
    "Tips_Not_Whatsapp": "Esta función requiere tener instalado WhatsApp.",
    "Tips_NetWork_Connection": "Conectando",
    "Tips_Game_TeamUp_HelpTeammate": "¡Sigue jugando por tu colega!",
    "task_load_fail_tips": "Error al cargar datos. Intenta de nuevo más tarde.",
    "Tips_Game_addFriendReq": "Solicitud de amistad.",
    "Tips_Game_addFriendReq_accept": "Aceptar",
    "Tips_Game_addFriendReq_ignore": "Ignorar",
    "Tips_Friend_Req": "Solicitud de amistad enviada",
    "Tips_Friend_AcceptSucc": "{name} se agregó a tus amistades.",
    "Tips_Friend_AcceptFailed": "Error al aceptar. Prueba más tarde desde Solicitudes de amistad.",
    "Tips_Friend_IgnoreFailed": "Error al ignorar. Prueba más tarde desde Solicitudes de amistad.",
    "Tips_Friend_RemoveFriend": "¿Quieres eliminar a esta amistad?",
    "Set_Panel_chatclosetips": "Bloqueaste todos los chats.",
    "Tips_Send_Gift": "Toca aquí para enviar emojis.",
    "Tips_Send_This_Player_Gift": "Toca aquí para enviar emojis a esta persona.",
    "Tips_Profile_Add_Friends": "Toca Perfil para agregar.",
    "Tips_Here_Add_Friends_GamePage": "Toca aquí para agregar.",
    "Tips_Here_Add_Friends_GameOver": "Toca aquí para agregar.",
    "Tips_Send_Coin_friends": "Regala monedas a tus amistades.",
    "Tips_Collect_By_Mail": "Obtén monedas de tus amistades por correo.",
    "Item_Use_Success": "Usaste {skin}.",
    "Kick_Player_No_Reward_Tips": "{name} se quedó sin monedas y perdió. No hay bonus.",
    "Common_Game_Mini_tips": "¡Obtén {num} estrellas para ganar! Capturar una ficha o llegar a la meta te da una estrella.",
    "Lobby_mini_tips": "Compacto e intenso",
  },
  "Chat": {
    "Game_emoji": "Emoji",
    "Game_chat": "Chatear",
    "Game_chat_title": "Chat rápido",
    "Game_chat_content1": "¡Hola!",
    "Game_chat_content2": "¡Juega rápido!",
    "Game_chat_content3": "¡Vaya!",
    "Game_chat_content4": "Bien jugado",
    "Game_chat_content5": "¡Por qué!",
    "Game_chat_content6": "¡Perdón!",
    "Game_chat_tips": "Ingresar mensaje",
    "Game_chat_send": "Enviar",
  },
  "DailyBonus": {
    "Lobby_Bonus_title": "Bonus diario",
    "Lobby_Bonus_detail": "¡Monedas gratis todos los días!",
    "Lobby_Bonus_collect": "Recoger",
    "Lobby_Bonus_collected_tips": "Vuelve mañana por más monedas.",
    "Lobby_Bonus_collect_failed": "Error al recoger. Intenta de nuevo más tarde.",
    "Lobby_Bonus_reqFailed": "Error al obtener el bonus diario. Intenta de nuevo más tarde.",
    "Lobby_Bonus_Day": "Día {num}",
    "Lobby_Bonus_Day_1": ""
  },
  "Props_Guide": {
    "Game_Props_TopTitle_Great": "Genial",
    "Game_Props_TopTitle_LuckyNumber": "Número\n dorado",
    "Game_Props_ItemTips_DoubleDice": "Distancia doble: duplica el número obtenido. Se debe avanzar esa cantidad de espacios de inmediato. Luego de usar este objeto, sacar un 6 no otorga tiradas extra ni permite eliminar fichas.",
    "Game_Props_ItemTips_AssignDice": "Dado controlado: elige el número del dado. Al sacar un 6, capturar una ficha o alcanzar la meta, hay una tirada adicional disponible.",
    "Game_Props_ItemTips_Protection": "Escudo: evita que capturen tus fichas durante 1 turno.",
    "Common_Game_Props_UseChooseNumber_AssignDice": "Elegir número",
    "Common_Game_Props_UserGuide_GoldenNo": "Este es el número dorado. ¡Sácalo para volver a tirar!",
    "Common_Game_Props_UserGuide_GoldenNo_content": "Obtén una tirada extra al llegar aquí.",
    "Common_Game_Props_UserGuide_continue": "Toca para continuar",
    "Common_Game_Props_UserGuide_begin_title": "Modo potenciado",
    "Common_Game_Props_UserGuide_begin_content": "¡Hola, soy Ludo World! ¡Te enseñaré cómo jugar en el modo potenciado!",
    "Common_Game_Props_UserGuide_roaditem": "Pueden obtener potenciadores en el tablero.",
    "Common_Game_Props_UserGuide_Items": "Estos son todos tus potenciadores.",
    "Common_Game_Props_UserGuide_Dicecontrol_title": "Dado controlado",
    "Common_Game_Props_UserGuide_Dicecontrol_content": "¡Puedes elegir qué número quieres en los dados!",
    "Common_Game_Props_UserGuide_Dicecontrol_tips": "¡Saca un 6! ¡Gran comienzo!",
    "Common_Game_Props_UserGuide_Doubledistance_title": "Distancia doble",
    "Common_Game_Props_UserGuide_Doubledistance_content": "Duplica el número obtenido. ¡Avanza el doble!",
    "Common_Game_Props_UserGuide_GoldenNo_title": "Tirada extra",
    "Common_Game_Props_UserGuide_GoldenNo_tips": "Obtén una tirada adicional al llegar. ¡Lo que todos quieren!",
    "Common_Game_Props_UserGuide_BumpProtection_title": "Escudo protector",
    "Common_Game_Props_UserGuide_BumpProtection_content": "Te protege de las otras fichas furtivas por 1 turno.",
    "Common_Game_Props_UserGuide_BumpProtection_effect": "¡Genial! ¡Tu ficha está protegida!",
    "Common_Game_Props_UserGuide_finish_title": "¡Todo listo!",
    "Common_Game_Props_UserGuide_finish_content": "Ahora que sabes todo sobre los objetos, ¡es hora de jugar!",
    "Common_Game_Props_UserGuide_finish_botton": "¡Vamos!",
    "Common_Game_Props_GetUserGuide": "¿Primera vez que juegas al modo potenciado? Mira nuestro tutorial.",
  },
  "Feedback": {
    "Set_Feedbeck_Title": "Comentarios",
    "Set_Feedbeck_Tips": "¡Gracias por tus comentarios y tu apoyo!",
    "Set_Feedbeck_Submit": "Enviar",
    "Set_Feedbeck_Submit_Succeed": "Tus comentarios se enviaron con éxito.",
    "Set_Feedbeck_Submit_No": "Ingresa tus comentarios aquí.",
  },
  "TeamUp_Guide": {
    "Common_Game_teamup_UserGuide_begin_title": "En equipo",
    "Common_Game_teamup_UserGuide_begin_content": "¡Juguemos en equipo! Estas son las reglas.",
    "Common_Game_teamup_UserGuide_teammate": "Formas equipo con el participante verde de la esquina opuesta.",
    "Common_Game_teamup_UserGuide_competitor": "El equipo rojo y amarillo es tu oponente.",
    "Common_Game_teamup_UserGuide_pawnstack": "Las fichas de un mismo equipo pueden estar juntas.",
    "Common_Game_teamup_UserGuide_onefinish": "Ayuda a tu compañero una vez que tus 4 fichas estén en la meta.",
    "Common_Game_TeamUp_UserGuide_finish_title": "¡Bien hecho!",
    "Common_Game_TeamUp_UserGuide_finish_content": "Aprendiste a jugar en equipo. ¡Ahora juguemos de verdad!",
  },
  "SharePresentLottery": {
    "Lobby_Lottery_Hint": "Mira un anuncio y gira gratis.",
    "Lobby_Lottery_Btn_Share": "Juega y gana",
    "Lobby_Lottery_Btn_spin": "Gira",
    "Lobby_Lottery_Upper_Limit": "¡Vuelve mañana a la rueda de la fortuna!",
    "Lobby_Lottery_Close": "¡La rueda está girando!",
  },
  "ShareText": {
    "TitleTurnplate": "¿Quieres jugar Ludo? ¡Juguemos ahora!",
    "TitlePropsShare": "¡Es tan divertido jugar Ludo World! ¡Juguemos!",
    "TitleOver": "¡Acabo de ganar en Ludo World! ¡Ven conmigo ahora!",
    "FriendRoomInviteText": "{name} te invita a jugar Ludo World, código de sala {RoomCode}.",
    "RankShareContent": "Gané {num} [partida|partidas] esta semana. ¡Ven a desafiarme!",
    "Invite_gift_text1": "¡Hola! Estoy jugando Ludo World, ¡ven a jugar conmigo!",
    "Invite_gift_text2": "¡Ven a desafiarme y veamos quién gana!",
    "Invite_gift_text3": "Cuando tus amistades hagan clic en el enlace que compartiste, recibirás una recompensa.",
    "friend_invite_details": "Juega Ludo World conmigo. Código de sala: {Number}. Haz clic para descargar o entrar a la sala.",
  },
  "LoginMainLabel": {
    "LoginMainLabel_Facebook": "Facebook",
    "LoginMainLabel_Google": "Google",
    "LoginMainLabel_Description": "Al continuar, acepto que Moon Active almacene y procese mi información de acuerdo con la política de privacidad.",
    "LoginMainLabel_Guest": "Invitado",
    "LoginMainLabel_Continue_Sure": "¿Confirmas?",
    "LoginMainLabel_Continue_Express": "Los invitados no pueden jugar con amistades.",
    "LoginMainLabel_Continue_AsGuest": "Jugar como invitado",
    "LoginMainLabel_Continue_FbAward": "Los invitados no pueden jugar con amistades ni ganar {coins} monedas.",
    "LoginMainLabel_RewardPrompt": "¡{coins} monedas gratis!",
    "LoginMainLabel_Continue_Warning": "Al tocar \"Aceptar\", confirmo que leí y acepto la POLÍTICA DE PRIVACIDAD y el ACUERDO DE USUARIO de TENCENT GAMES",
    "LoginMainLabel_Continue": "<u><b>Seguir como invitado<u><b>",
    "LoginMainLabel_Select": "Iniciar sesión mediante",
    "FacebookConnect_Content1": "<b><color=#444987>Iniciar sesión con Facebook:</color></b>",
    "FacebookConnect_Content2": "<b><color=#444987>1. Juega con amistades\n2. Guarda tu progreso\n3. Obtén <color=#d16004>{num}<color=#444987> monedas gratis<b>",
    "FacebookConnect_Content3": "<u><b><color = #3f59b7 click=\"handler\">Iniciar sesión con Facebook</color></b></u>",
    "FacebookConnect_Content4": "<b><color=#444987>Conectado como invitado<color=#d16004> <color=#d16004>",
  },
  "PropsPromtText": {
    "Game_classic_newusertips_dicecontrolmoveout": "¡Controla tus dados\n para despegar!",
    "Game_classic_newusertips_dicecontrolbump": "¡Controla tus dados \npara capturar!",
    "Game_classic_newusertips_dicecontrolfinish": "¡Controla tus dados para meterte \nen el inicio!",
    "Game_classic_newusertips_doubledistance": "¡Duplica tu distancia!",
    "Game_classic_newusertips_shild": "¡Protege tus fichas!",
    "Game_classic_newusertips_dicecontrolrun": "Controla tus dados para correr.",
    "Game_item_purchasetips": "Haz clic para obtener objetos.",
  },
  "MailPanel": {
    "Mail_Title": "Correo",
    "Mail_firend": "Amistades",
    "Mail_system": "Sistema",
    "Mail_collect": "Recoger",
    "Mail_check": "Verificar",
    "Mail_collectAll": "Recoger todo",
    "Mail_Firend_Preservation_tips": "Guardar 60 mensajes y guardar por 30 días.",
    "Mail_System_Preservation_tips": "Guardar 60 mensajes y guardar por 30 días.",
    "Mail_NoMail_tips": "No hay más correos.",
    "MailInfo_Title": "Detalles",
    "MailInfo_firend_Gift": "dio un regalo",
    "Mail_firend_Get_limit": "Ya recogiste regalos de {num} amistades hoy. Regresa mañana para recoger más.",
    "MailInfo_get_Failure": "Error al recoger recompensas. Intenta de nuevo más tarde.",
    "Mail_delete_Failure": "Error al eliminar. Intenta de nuevo más tarde.",
    "MailInfo_delete": "Eliminar",
  },
  "PrivacyPolicy": {
    "PrivacyPolicy_join1": "He leído y aceptado la",
    "PrivacyPolicy_join2": "POLÍTICA DE PRIVACIDAD",
    "PrivacyPolicy_join3": "y",
    "PrivacyPolicy_join4": "el ACUERDO DE USUARIO",
    "SelectNone": "Al tocar Aceptar, confirmo que leí y acepto la POLÍTICA DE PRIVACIDAD y el ACUERDO DE USUARIO",
  },
  "HelpText": {
    "Game_classic_userguide_tokens": "Fichas: hay 4 grupos de fichas, cada uno de un color.",
    "Game_classic_userguide_startpoint": "Posición inicial: es el punto de inicio.",
    "Game_classic_userguide_finishline": "Llegada: las fichas deben recorrer el tablero antes de entrar a la casilla de llegada.",
    "Game_classic_userguide_safeplace": "Lugares seguros: hay 8 casilleros seguros donde las fichas no pueden eliminarse.",
    "Game_classic_userguide_dice": "Dados: cada una de las 6 caras tiene distinto número de puntos del 1 al 6.",
    "Game_classic_userguide_firsthand": "Primera mano: primero al azar, y se continúa en sentido horario.",
    "Game_classic_userguide_moveout": "Salir: hay que sacar un 6 para empezar a jugar.",
    "Game_classic_userguide_move": "Mover: luego de tirar los dados, elegir una ficha para mover los puntos correspondientes.",
    "Game_classic_userguide_automove": "Movimiento automático: la ficha se mueve de forma automática cuando no hay otra opción.",
    "Game_classic_userguide_sixbonus": "Bonificación de 6: al sacar un 6, se obtiene otra tirada. Si se saca un 6 tres veces seguidas, se saltea el tercer turno.",
    "Game_classic_userguide_bumpbonus": "Bonificación por captura: se obtiene otro turno al capturar una ficha.",
    "Game_classic_userguide_finishbonus": "Bonificación de meta: se obtiene otro turno cuando una ficha llega a la casilla de llegada.",
    "Game_classic_userguide_bump": "Captura: si una ficha cae sobre otra al moverse, y no están en un lugar seguro, la ficha del oponente se envía de vuelta al inicio. Pero si dos o más fichas del mismo color están en la misma casilla, son inmunes a ser capturadas.",
    "Game_classic_userguide_finish": "Una ficha puede entrar a la casilla de llegada si el dado marca la distancia exacta. Si el número es mayor, la ficha no se mueve.",
    "Game_classic_userguide_winner": "Ganador: gana quien consiga llevar las 4 fichas a la casilla de llegada primero. En partidas de 4 personas, ganan tanto la 1.a como la 2.a.",
    "Game_classic_userguide_time": "Tiempo: 10 s para tirar, 10 s para mover.",
    "Game_classic_userguide_autohosted": "Movimiento automático: si te desconectas o el tiempo se agota, el juego jugará por ti. Haz clic para retomar el control.",
    "Set_Help_newuser_powermode_begin": "¡Sobre la base del modo clásico, agrega estos elementos para hacer el juego más divertido!",
    "Set_Help_newuser_powermode_step1": "Distancia doble: avanza el doble del número que sacas en los dados. ¡Viaja al doble de velocidad! \nTen en cuenta que el turno extra al sacar un 6 no será aplicable después de usar Distancia doble.",
    "Set_Help_newuser_powermode_step2": "Dados controlados: elige el número que quieres en los dados.",
    "Set_Help_newuser_powermode_step3": "Escudo protector: te protege de las otras fichas por 1 turno.",
    "Set_Help_newuser_powermode_step4": "Tirada extra: obtén una tirada adicional al llegar.",
    "Set_Panel_Help_teamup_1": "Regla 1: formas equipo con el participante en diagonal (azul y verde contra rojo y amarillo).",
    "Set_Panel_Help_teamup_2": "Regla 2: cuando las fichas de tu equipo están juntas, las fichas del oponente no pueden unirse para capturarlas.",
    "Set_Panel_Help_teamup_3": "Regla 3: las fichas de tu equipo no serán capturadas cuando se separen.",
    "Set_Panel_Help_teamup_4": "Regla 4: una vez que tus 4 fichas hayan llegado a la meta, puedes usar tus tiradas para mover las fichas de tu compañero.",
    "Set_Panel_Help_teamup_5": "Regla 5: tu equipo debe mover las 8 fichas hasta la llegada para ganar.",
  },
  "PropGuidePanel": {
    "PropGuidePanel_TitleText": "¡Modo potenciado!",
    "PropGuidePanel_ContentText": "¡Ven a probar \nnuestro modo único de Ludo!",
    "PropGuidePanel_PlayBntText": "Empezar",
    "PropGuidePanel_AwardHint": "¡Monedas gratis!",
    "NewHandGuide_AwardHint": "¡Terminaste el tutorial del modo potenciado!",
    "NewHandGuide_Get_Failure": "Error al recoger. Intenta de nuevo más tarde.",
    "PropGuideTipsOpenText": "Consejos de objetos abiertos",
    "PropGuideTipsCloseText": "Consejos de objetos cerrados",
  },
  "GameGuide": {
    "GameGuideText1": "¡Te damos la bienvenida!",
    "GameGuideText2": "¡Juguemos en línea con más gente!",
  },
  "GameGuideText": {
    "GameGuideTitle": "Elegir modo",
    "GameGuideContent": "¿Conoces el Ludo? Prueba",
    "GameGuideClassicModeContent": "Clásico",
    "GameGuidePowerModeContent": "Experto",
    "GameGuidePowerMode": "Potenciado",
    "GameGuidePlay": "¡Juguemos!",
    "GameGuideClassicMode": "Clásico",
    "GameGuideInnovative": "Innovador",
  },
  "GameTxpText": {
    "GameNoGetExp": "Sin capturar ni llegar a la meta, no ganas EXP.",
    "CloseTips": "Toca para cerrar",
    "ShareLevelTips": "¡Es tan divertido jugar Ludo World! ¡Juguemos!",
  },
  "AssessPanelText": {
    "Rate_title": "¿Te gusta el juego?",
    "Rate_content": "¡Si te gusta, califícanos!",
    "Rate_Button": "Califícanos",
    "Rate_Button2": "Más tarde",
    "ShareGame_exp_fail": "Error al obtener EXP, intenta más tarde.",
    "ShareGame_exp_Exceed": "Ya ganaste demasiada EXP hoy. Regresa mañana.",
  },
  "TaskPanel": {
    "Task_Title": "Misión",
    "Task_Daily": "Misión diaria",
    "Task_Growth": "Misión de crecimiento",
    "Task_collect": "Recoger",
    "Task_Play": "Ir",
    "Task_Playing": "En proceso",
    "Task_get_award_failed": "Error al recoger. Intenta de nuevo más tarde.",
    "Task_Tips": "La misión diaria se actualiza a las 00:00",
    "Task_Timeout": "Error al recoger, la misión expiró.",
    "Task_Coins": "Monedas",
  },
  "TaskName": {
    "task_0": "Iniciar sesión",
    "task_1": "Envía regalos a otras\npersonas 5 veces en\nmodo en línea",
    "task_2": "Envía monedas a amistades\n5 veces en la lista\n de amistades",
    "task_3": "Captura 5 veces en\nel modo Amistades",
    "task_4": "Mueve fichas a\nla meta 3 veces en\nel modo Amistades",
    "task_5": "Gana 1 partida en\nel modo Amistades-\nclásico",
    "task_6": "Gana 1 partida en\nmodo Amistades-potenciado",
    "task_7": "Gana 1 partida en\nmodo Amistades",
    "task_8": "Gana 5 partidas en\nmodo en línea-\nclásico-2j",
    "task_9": "Gana 3 partidas en\nmodo en línea-\nclásico-4j",
    "task_10": "Gana 3 partidas en\nmodo en línea-\nclásico-2c2",
    "task_11": "Gana 5 partidas en\nmodo\nen línea-potenciado-2j",
    "task_12": "Gana 3 partidas en\nmodo en línea-\npotenciado-4j",
    "task_13": "Gana 3 partidas en\nmodo en línea-\npotenciado-2c2",
    "task_14": "Gana 5 partidas en\nmodo en línea",
    "task_15": "Usa Distancia doble\n10 veces en modo\nen línea-potenciado",
    "task_16": "Usa Dado controlado 10\nveces en modo\npotenciado",
    "task_17": "Usa Escudo protector\n 10 veces en modo en línea-\n potenciado",
    "task_18": "Captura 5 veces en\nmodo en línea",
    "task_19": "Mueve fichas a\nla meta 3 veces en\nmodo en línea",
    "task_20": "",
    "task_21": "Sube hasta el nivel %{num}",
    "task_22": "Inicia sesión %{num} días",
    "task_23": "Gana %{num} partidas\nen modo en línea",
    "task_24": "Gana %{num} partidas\nen computadora",
    "task_25": "Captura %{num} veces en\nmodo en línea",
  },
  "TeamUp2V2": {
    "Common_Choose_Number_Team": "Formar equipo",
    "Common_Choose_Number_2v2_titlepower": "Potenciado 2v2",
    "Common_Choose_Number_2v2_titleclassic": "Clásico 2v2",
    "Teamup_choose_tips1": "Invitar amistad o emparejamiento automático",
    "Teamup_choose_tips2": "Ya puedes empezar",
    "Teamup_choose_betchange_title": "Cambió la apuesta",
    "Teamup_choose_betchange_content": "Se ajustó la apuesta a {coins} porque tu amistad no tiene suficientes monedas.",
    "Teamup_choose_join_leave_title": "¿Salir del juego?",
    "Teamup_choose_join_leave_content": "Tu equipo se disolverá. ¿Aún quieres salir?",
    "Teamup_Matching_leave_content": "Ya tienes oponente, no puedes salir ahora.",
    "Teamup_Game_inviting": "{name} te invita a formar equipo en el modo en línea-2v2.",
  },
  "Region": {
    "Disgree_Content": "Lamentablemente, no podemos ofrecerte Ludo World en este momento. Nuestros datos se almacenan fuera del EEE y nuestros equipos de soporte deben acceder a ellos desde otras jurisdicciones para brindarte el servicio.",
    "Back": "Atrás",
    "Data_Agreement_Content_APK": "Ludo World es un producto ofrecido por Proxima Beta PTE. Limited, una empresa de la República de Singapur que procesará tus datos fuera del Espacio Económico Europeo (incluida la República Popular China) para brindar el servicio. Ten en cuenta que este tipo de transferencia conlleva ciertos riesgos, como que tus datos estén sujetos a regímenes legales diferentes que podrían no ofrecer el mismo nivel de protección que en tu país de residencia.Para más información, consulta nuestra <b><u><i click=\"handler\">Política de privacidad</i></u></b>. Al hacer clic en \"Aceptar\" a continuación, aceptas la transferencia de tus datos fuera del Espacio Económico Europeo.",
    "Data_Agreement_Content_FB": "Ludo World es un producto ofrecido por High Morale Development Limited, una empresa de la Hong Kong que procesará tus datos fuera del Espacio Económico Europeo (incluida la República Popular China) para brindar el servicio. Ten en cuenta que este tipo de transferencia conlleva ciertos riesgos, como que tus datos estén sujetos a regímenes legales diferentes que podrían no ofrecer el mismo nivel de protección que en tu país de residencia.Para más información, consulta nuestra <b><u><i click=\"handler\">Política de privacidad</i></u></b>. Al hacer clic en \"Aceptar\" a continuación, aceptas la transferencia de tus datos fuera del Espacio Económico Europeo.",
    "Agree": "Aceptar",
    "Disagree": "Rechazar",
    "Under_Age_Content": "Como tienes menos de {age} años, lamentablemente no podemos ofrecerte el servicio de Ludo World en este momento.",
    "Data_Outside_Content": "¿Aceptas la transferencia de tus datos fuera del Espacio Económico Europeo?",
    "Data_Outside_Title": "Transferencia de datos fuera del EEE",
    "Delete_Notice_Title": "Aviso",
    "Delete_Notice_Content": "Lamentablemente, no podemos ofrecerte Ludo World en este momento. Nuestros datos se almacenan fuera del EEE y nuestros equipos de soporte deben acceder a ellos desde otras jurisdicciones para brindarte el servicio. Haz clic en \"Volver\" para reconsiderarlo o en \"Eliminar cuenta\" para borrarla.",
    "Delete_Account": "Eliminar cuenta",
    "Delete_Delete": "Eliminar",
    "Delete_Content": "¿Deseas eliminar tu cuenta? El sistema eliminará automáticamente tu cuenta y datos después de 7 días. Puedes cancelar la eliminación volviendo a iniciar sesión en el juego dentro de los 7 días.",
    "Chat_Off_Title": "¿Activar el chat ahora?",
    "Chat_Off_Content": "Cuando el chat está activado, otras personas pueden ver tus conversaciones. Puede desactivarse luego desde la configuración.",
    "Region_Title": "Región",
    "Region_Content": "Selecciona la región/país donde\nte encuentras principalmente.",
    "Agree_Title": "Fecha de nacimiento",
    "Agree_Content": "Para poder optimizar tu experiencia, ¿podrías decirnos si tienes al menos {age} años?",
    "Privacy_Title": "Política de privacidad",
    "Privacy_Content": "Al tocar \"Aceptar\" a continuación, confirmo que\nleí y acepté la\n<b><u><color = #535BBF click=\"handler\">Política de Privacidad de Ludo World</color>.</u></b>",
    "Privacy_Disagree": "Lamentablemente, sin tu acuerdo con la política de privacidad, no podemos ofrecerte los servicios de Ludo World en este momento.",
    "Agreement_Title": "Acuerdo de licencia de usuario final",
    "Agreement_Content": "Al tocar \"Aceptar\" a continuación, confirmo que\nleí y acepté el\n<b><u><color = #535BBF click=\"handler\"> Acuerdo de licencia de usuario final de Ludo World</color>.</u></b>",
    "Agreement_Disagree": "Lamentablemente, sin tu aceptación del acuerdo de licencia de usuario final, no podemos ofrecerte los servicios de Ludo World en este momento.",
    "YES": "Sí",
    "NO": "NO",
  },
  "FriendSystem": {
    "Friend_Main_title": "Amistades",
    "Friend_Main_list": "Lista",
    "Friend_Main_add": "Añadir",
    "Friend_Main_request": "Solicitud",
    "Friend_Main_list_FB": "Amistades de FB",
    "Friend_Main_list_Game": "Amistades del juego",
    "Friend_Main_list_reciveandsend": "Enviar todo",
    "Friend_Main_list_reciveandsend_Detail": "Las monedas que les envíes a tus amistades no se descontarán de tu saldo.",
    "Friend_Main_Add_Recent": "Reciente",
    "Friend_Select_Tip_NewRequest": "{num} [Solicitud de amistad|Solicitudes de amistad]",
    "Friend_Main_Request_Num_Tip": "Guardar solo las últimas 99 solicitudes.",
    "Friend_list_nofbfirends": "Aún no hay amistades de Facebook jugando,\n¡invítalos ahora!",
    "Friend_list_invitefirends": "¡Juega conmigo a Ludo World ahora!",
    "Friend_list_nogamefirends": "No tienes amistades en el juego,\nagrega desde \"Añadir\".",
    "Friend_Add_NoRecent": "Ninguna persona reciente.",
    "Friend_Request_NoRequest": "Sin solicitudes de amistad.",
    "Friend_list_online": "En línea",
    "Friend_list_offline": "Desconectado",
    "Friend_list_playing": "Jugando",
    "Friend_Not_Accept": "No aceptar más solicitudes de amistad.",
    "Friend_sendcoins_succeed": "Enviar 100 monedas a {name}",
    "Friend_sendcoins_fail": "Enviaste el número máximo de regalos de hoy.",
    "Friend_collectandsendall_succeed": "Enviar {num} monedas",
    "Friend_collectandsendall_nofirendtosend": "No hay amistades para enviar",
    "Friend_invite_title": "Invitación",
    "Friend_invite_bottoningame": "En el juego",
    "Friend_invite_whoinvite": "¡{name} te invita a jugar!",
    "Friend_invite_reject": "Rechazar",
    "Friend_invite_accept": "Aceptar",
    "Friend_invite_friendpower": "Amistades-potenciado",
    "Friend_invite_friendclassic": "Amistades-clásico",
    "Friend_invite_teamuppower": "Amistades-potenciado-2v2",
    "Friend_invite_teamupclassic": "Amistades-clásico-2v2",
    "Friend_invite_sentsucceed": "Invitación enviada",
    "Friend_invite_sentfail": "Invitación fallida",
    "Friend_invite_more_btn": "Invitar a más:",
    "Friend_collectcoins_fail": "Ya recogiste monedas de {num} amistades hoy. Regresa mañana para recoger más.",
    "Friend_collectall_succeed": "¡Recoge {coins} monedas de amistades!",
    "Friend_Add_Recent_Source1": "En línea-clásico-2j",
    "Friend_Add_Recent_Source2": "En línea-clásico-4j",
    "Friend_Add_Recent_Source3": "En línea-potenciado-2j",
    "Friend_Add_Recent_Source4": "En línea-potenciado-4j",
    "Friend_Add_Recent_Source5": "En línea-clásico-2v2",
    "Friend_Add_Recent_Source6": "En línea-potenciado-2v2",
    "Friend_Add_Recent_Source7": "Amistades-clásico",
    "Friend_Add_Recent_Source8": "Amistades-potenciado",
    "Friend_Add_Recent_Source9": "Amistades-clásico-2v2",
    "Friend_Add_Recent_Source10": "Amistades-potenciado-2v2",
    "Friend_Request_Source_Recent": "Juego reciente",
    "Friend_Request_Source_Suggested": "Sugerido",
    "Friend_Request_Source_Leaderboard": "Clasificación",
    "Friend_gametime-year": "hace {num} a",
    "Friend_gametime-day": "hace {num} d",
    "Friend_gametime-hour": "hace {num} h",
    "Friend_gametime-minitue": "hace {num} min",

  },
  "APPAdsText": {
    "ItemsAddOne": "Objetos+1",
  },
  "Common": {
    "Lobby_Bonus_collecet": "Recoger",
    "Common_Game_teamup_UserGuide_finish_title": "¡Bien hecho!",
    "Game_friends_invite_start": "Puedes empezar ahora.",
    "": "",
    "Title_ModifyInfo": "Modificar info.",
    "shortCut_create_success": "Creación de acceso directo exitosa.",
    "MainScenes_Ranking": "Clasificación",
    "MainScenes_FreeCoins": "Monedas gratis",
    "MainScenes_Mission": "Misión",
    "Settings_on": "Sí",
    "Settings_off": "No",
    "Game_EndOrder_Congratulations": "Felicitaciones",
    "EM_ERR_FETCH_FRIEND_FAIL = -10002": "Error al cargar datos. Intenta de nuevo más tarde.",
    "EM_ERR_FETCH_ONLINE_FAIL = -10003": "Error al cargar datos. Intenta de nuevo más tarde.",
    "EM_ERR_FETCH_LOGIN_TIME_FAIL = -10004": "Error al cargar datos. Intenta de nuevo más tarde.",
    "EM_ERR_NOT_ADD_PLAYER = -10005": "Error al procesar, intenta de nuevo más tarde.",
    "EM_ERR_FRIEND_LIST_FULL = -10006": "Alcanzaste el número máximo de amistades. Para agregar a esta persona, debes eliminar a otras.",
    "EM_ERR_PEER_FRIEND_LIST_FULL = -10007": "{name} alcanzó el número máximo de amistades y no puede agregarse.",
    "EM_ERR_UPDATE_FRIEND_FAIL = -10008": "Error al cargar datos. Intenta de nuevo más tarde.",
    "EM_ERR_PLAYER_REFUSE_ADD = -10009": "{name} no está aceptando solicitudes de amistad.",
    "EM_ERR_ALREADY_IN_ADD_LIST = -10010": "",
    "EM_ERR_ALREADY_IN_GAME_FRIEND_LIST = -10011": "Ya son amistades.",
    "EM_ERR_ALREADY_IN_PLAT_FRIEND_LIST = -10012": "Ya son amistades.",
    "EM_ERR_NOT_IN_FRIEND_LIST = -10013, //": "Error al procesar, intenta de nuevo más tarde.",
    "EM_ERR_FETCH_GAME_RECORD_FAIL = -10014": "Error al cargar datos. Intenta de nuevo más tarde.",
    "EM_ERR_CANNOT_ADD_SELF = -10015": "Error al agregar. Intenta de nuevo más tarde.",
    "LoginMainLabel_Guest_Title": "Inicia sesión como invitado y no puedes",
    "Language_type": "Español",
  },
  "GoodsName": {
    "GoodsName_Cricket": "Críquet",
    "GoodsName_Jewelry": "Joyas",
    "GoodsName_Airdrop_box": "Suministros",
    "GoodsName_Cupid": "Cupido",
    "GoodsName_Cat": "Gato",
    "GoodsName_Planet": "Planeta",
    "GoodsName_Default": "Predeterminado",
    "Shop_luckybox": "Cofre de la suerte",
    "Shop_luckybox_GiftCardtitle": "Tarjeta de regalo",
    "Shop_luckybox_GiftCard": "Recibe la tarjeta de regalo en el correo del juego.",
    "GoodsName_Item_Cards": "Cartas de objetos",
    "GoodsName_Item_Cards_num": "Cartas de objetos x{num}",
    "GoodsName_Neon": "Neón",
    "GoodsName_Chick": "Pollito",
    "GoodsName_First_AidKit": "Botiquín",
    "GoodsName_Machinery": "Maquinaria",
    "GoodsName_Diwali": "Diwali",
    "GoodsName_Christmas": "Navidad",
    "GoodsName_Gems": "Gemas",
  },
  "AdsText": {
    "Btn_Lucky_Show_Ad": "Ver anuncio",
    "Lab_Lucky_Next": "Próxima recompensa:",
    "Lab_Lucky_Declare": "¡Mira anuncios para girar gratis todos los días!",
    "Btn_Double_Reward": "Bonificación doble",
    "Btn_Reward_x2": "¡Obtén x2!",
    "Btn_No_Thanks": "No, gracias",
    "Ad_Confirm_Cions": "Ver anuncios para obtener {num} monedas.",
    "Ad_Confirm_Item": "Ver anuncios para obtener 1 de cada objeto.",
    "Ad_Confirm_Task": "Ver anuncios para avanzar en las misiones.",
    "Ad_Confirm_Spin": "Ver anuncios para obtener {spin}.",
  },
  "NewUserText": {
    "NewPlayerBonus_Title": "Bonificación para gente nueva",
    "NewPlayerBonus_Day": "Día",
    "NewPlayerBonus_Collect": "Recoger",
    "NewPlayerBonus_Collected": "Recogido",
    "NewPlayerBonus_LoginTips": "Iniciaste sesión durante {num} [día|días] ~",
    "NewPlayerBonus_EventTime": "Duración del evento:",
    "NewPlayerBonus_Coins": "Monedas",
    "NewPlayerBonus_Skins": "Apariencia",

  },
  "Shop": {
    "Shop_Tab_Coins": "Monedas",
    "Shop_Tab_Spin": "Apariencia",
    "Shop_Tab_Items": "Objetos",
    "Shop_Tab_Spin_BubbleTab": "Burbuja",
    "Shop_Tab_Spin_DiceTab": "Dados",
    "Shop_Tab_Spin_ThemeTab": "Tema",
    "Shop_Airdrop_box": "Suministros",
    "Shop_Coins": "{num}",
    "Shop_Airdrop_box_day": "Suministros ({num}d)",
    "Shop_Cricket": "Críquet",
    "Shop_Cricket_day": "Críquet ({num}d)",
    "Shop_Cupid": "Cupido",
    "Shop_Cupid_day": "Cupido ({num}d)",
    "Shop_Jewelry": "Joyas",
    "Shop_Jewelry_day": "Joyas ({num}d)",
    "Shop_Cat": "Gato",
    "Shop_Cat_day": "Gato ({num}d)",
    "Shop_Planet": "Planeta",
    "Shop_Planet_day": "Planeta ({num}d)",
    "Shop_Neon": "Neón",
    "Shop_Neon_day": "Neón ({num}d)",
    "Shop_Chick": "Pollito",
    "Shop_Chick_day": "Pollito ({num}d)",
    "Shop_First_AidKit": "Botiquín",
    "Shop_First_AidKit_day": "Botiquín ({num}d)",
    "Shop_Machinery": "Maquinaria",
    "Shop_Machinery_day": "Maquinaria ({num}d)",
    "Shop_Diwali": "Diwali",
    "Shop_Diwali_day": "Diwali ({num}d)",
    "Shop_Christmas": "Navidad",
    "Shop_Christmas_day": "Navidad ({num}d)",
    "Shop_Item": "Cartas de objetos ({num})",
    "Shop_Label_New": "Nuevo",
    "Shop_Label_Hot": "Popular",
    "Shop_Label_Off": "No",
    "Shop_Label_Extar": "Extra",
    "Shop_Label_BestDeal": "Mejor oferta",
    "Shop_Day_day": "día",
    "Shop_Buy_Success": "Compra exitosa, utilizaste {spin}.",
    "Shop_Backpack_Tip": "Ve a usar los objetos de la mochila.",
    "Button_Reload": "Recargar",
    "Button_AD_Free": "Gratis",
    "Shop_Lucky": "Suerte",
    "Shop_BuyGift_Success": "Compra exitosa, ve a usar en la mochila.",
    "Shop_Airdrop_box_Permanent": "Suministros (permanente)",
    "Shop_Cricket_Permanent": "Críquet (permanente)",
    "Shop_Cupid_Permanent": "Cupido (permanente)",
    "Shop_Jewelry_Permanent": "Joyas (permanente)",
    "Shop_Cat_Permanent": "Gato (permanente)",
    "Shop_Planet_Permanent": "Planeta (permanente)",
    "Shop_Neon_Permanent": "Neón (permanente)",
    "Shop_Chick_Permanent": "Pollito (permanente)",
    "Shop_First_ AidKit_Permanent": "Botiquín (permanente)",
    "Shop_Machinery_Permanent": "Maquinaria (permanente)",
    "Shop_Diwali_Permanent": "Diwali (permanente)",
    "Shop_Lucky_Detail": "Cricket(1d), Joyas(1d), Planeta(1d)",
    "Shop_WatchTV_Detail": "Mira anuncios para obtener un regalo.",
    "Shop_Buy_Fail": "Compra fallida, intenta de nuevo más tarde.",
    "Shop_Buy_ItemFail": "No se pudo enviar el objeto. Intenta más tarde.",
    "Shop_Buy_Success_Prop": "Compra exitosa.",
    "Shop_Buy_Prop_Describe": "Las cartas de objeto se pueden canjear por objetos.",
    "Shop_itemcard": "Cartas de objetos",
    "Shop_itemcard_number": "{num} [carta|cartas]",
    "Shop_Tab_Name": "Tienda",
  },
  "ReportText": {
    "Report_Panel": "Denunciar",
    "Report_Title": "Denunciar",
    "Report_People": "Denunciar a {name}",
    "Report_Content1": "Abuso verbal",
    "Report_Content2": "Trampa",
    "Report_Content3": "Otros",
    "Report_Success": "Denunciado",
    "Report_Res_Title": "Resultado",
    "Report_Res_Content": "Se silenció/suspendió a {name}, a quien denunciaste.",
  },
  "RetainUser": {
    "newsuserA_classic_tips": "Prueba el modo potenciado. ¡Es más divertido!",
    "newsuserA_power_tips": "Prueba el modo clásico. ¡Es más fácil!",
    "newsuserA_tips_quit": "Salir",
    "newsuserA_tips_try": "Probar",
    "newsuserB_tips_stay": "Completa {num1} partidas ({num2}/{num3}) para obtener la Caja verde.",
    "newsuserB_tips_minitips": "¡Gana una tarjeta de regalo de Amazon de ₹100 o monedas!",
    "newsuserB_tips_getluckybox_title": "Caja verde",
    "newsuserB_tips_getluckybox_content": "¡Gana una tarjeta de regalo de Amazon de ₹100 o \nmonedas! Busca en tu mochila.",
    "newsuserB_tips_getluckybox_tips": "¡Gana una tarjeta de regalo de Amazon de ₹100 o monedas!",
    "newsuserB_tips_getluckybox_cannotopen": "Abrir después de {num}",
    "newsuserB_tips_getluckybox_openfail": "Error al abrir, intenta de nuevo más tarde.",
    "newsuserB_tips_getluckyboxopen": "¡Abre el Cofre de la suerte para obtener una \ntarjeta de regalo de Amazon de ₹100 o monedas!",
    "newsuserA_tips_stay": "Quedarme",
    "newsuserA_tips_leave": "¿Salir?",
    "newsuserA_tips_open": "Abrir",
  },
  "MainChat": {
    "Button_Team_SendTeamRecruitment": "Enviar invitación al equipo",
    "Chat_World_NoChatTypeTips": "(Este tipo de mensaje no es compatible.)",
    "Chat_World_EmptyTips": "El mensaje no puede estar vacío.",
    "Chat_NoMessage_Tips": "Haz clic aquí para chatear",
    "Chat_Tab_World": "Global",
    "Chat_Tab_Team": "Equipo",
    "Chat_Tab_Friends": "Amistades",
    "Chat_World_DefaltTips": "Ingresar mensaje",
    "Button_Chat_Send": "Enviar",
    "Chat_Team_Send_WorldChat": "Enviar al chat global",
    "Chat_Team_Join": "Unirse",
    "Chat_Local_Tips": "Solo chat local",
    "Chat_Friends_NewMessageTips": "Nuevo mensaje",
    "Chat_Friends_ClickTips": "Pulsa una amistad para chatear.",
    "Chat_Friends_NoFriendsTips": "Necesitas algunas amistades.",
    "Chat_World_LocalTips": "Toca aquí para entrar al chat local.",
    "Chat_Low_Level": "¡Juega más partidas para alcanzar el nv. {num} y chatear!",
    "Chat_World_JoinTips": "Te uniste al chat global",
    "Chat_Local_JoinTips": "Te uniste al chat local",
    "Chat_Close_Tips": "¿Activar el chat ahora?",
    "Tips_Team_SendSuccess": "Se envió la invitación al equipo en el chat global.",
    "Chat_SendTooFast": "No puedes enviar tantos mensajes seguidos. Vuelve a intentarlo más tarde.",
  },
  "RedEnvelope": {
    "HB_Bag_Title": "Bolsa de la suerte",
    "HB_Coins_Tips": "{num1}~{num2} monedas",
    "HB_Coins_Tipstop": "{num1} monedas",
    "HB_Image_Text": "Comparte tu suerte y abre la bolsa de la suerte.",
    "HB_Open_Require": "¡Invita a tus amistades y ábranla en grupo!",
    "HB_Open_Tips": "Cuantas más amistades se unan, ¡más monedas ganarás!",
    "HB_NoOpen_Tips1": "Esperando a que tus amistades se unan mediante el enlace.",
    "HB_NoOpen_Tips2": "Si una amistad se une con este enlace, podrán abrir la bolsa de la suerte.",
    "HB_Join_One": "Cuantas más amistades se unan, ¡más monedas ganarás!",
    "HB_Join_More": "Cuantas más amistades se unan, ¡más monedas ganarás!",
    "HB_Can_Open_Tips": "Abre la bolsa de la suerte hoy",
    "HB_Share_Title1": "¡Gana monedas en Ludo World! Abre la bolsa de la suerte para obtener tus recompensas.",
    "HB_Share_Title2": "¡Aquí tienes tu bolsa de la suerte de Ludo World! Ábrela y pon tu suerte a prueba",
    "HB_Btn_Open": "Abrir",
    "HB_Btn_Open_noinvite": "Invitar",
    "HB_Collect_Fail": "¡Uy! Ya no quedan más monedas.",
  },
  "LuckyBag": {
    "Clearing_Win_Share_Title": "Caja secreta",
    "Clearing_Win_Share_Content": "Invita a tus amistades y disfruten sus recompensas",
    "Clearing_Loser_Share_Title": "Monedas gratis",
    "Clearing_Loser_Share_Content": "Invita a tus amistades y disfruten sus recompensas",
    "Clearing_Win_Ads_Title": "Caja secreta",
    "Clearing_Win_Ads_Content": "Mira un anuncio para obtener esta recompensa",
    "Clearing_Loser_Ads_Title": "Monedas gratis",
    "Clearing_Loser_Ads_Content": "Mira un anuncio para obtener esta recompensa",
    "Clearing_Welfare_Share_Title": "Invita a tus amistades y disfruta las recompensas",
    "Clearing_Share_Finish": "¡Toca el enlace que acabas de compartir antes de que pasen {num} segundos para recibir tu recompensa!",
    "Clearing_Welfare_Ads_Title": "¿Necesitas más monedas?",
    "Clearing_Welfare_Ads_Content": "Mira un anuncio para obtener esta recompensa",
    "Clearing_Share_Loser": "El enlace compartido no es válido; vuelve a enviar el enlace compartido",
  },
  "LuckSeven": {
    "Un_Lock_tips": "¡Tira el dado {num1} veces más para desbloquear más!",
    "Not_Enough_Gold": "Monedas insuficientes",
    "High_Laid": "¡Se alcanzó la marcha más alta!",
    "Low_Laid": "¡Se alcanzó la marcha más baja!",
    "Show_FreeBet": "¡Apuesta {num2} veces más gratis!",
    "Coins": "MONEDAS",
    "laid_start_To_end": "{start} PARA {end}",
    "WIN": "VICTORIA",
    "Get_Free_Bet": "¡Obtén apuestas gratis!",
    "Double": "Doble {point}",
    "Error": "Error de datos; vuelve a cargar la página",
  },
  "EliminatGame": {
    "Select_Hint": "Elige la cantidad de monedas que apostarás",
    "Not_Coins": "No te alcanzan las monedas. ¿Quieres conseguir más en la tienda?",
    "Min_Coins": "Alcanzaste la cantidad mínima de monedas",
    "Max_Coins": "Alcanzaste la cantidad máxima de monedas",
    "Win": "VICTORIA",
    "Big_Win": "Premio mayor",
    "Super_Winner": "Supercampeón",
    "Total_Win": "Premios totales",
    "Fish_Party": "Pescamanía",
    "Quit_Hint": "Estás en una partida. ¿Confirmas que quieres abandonarla?",
    "AllIn": "Apuesta máxima",
    "Auto": "Automático",
    "Start": "Empezar",
    "EliminatGameTitle": "Instrucciones del juego",
    "Game_Rules": "Reglas del juego",
    "Explain": "Instrucciones del modo pescamanía",
    "Party_Text": "Tres peces iguales compiten en el mismo carril uno junto al otro. Si uno queda eliminado, ganarás recompensas.\n\nDespués de la eliminación, el juego seguirá agregando peces hasta que no se puedan eliminar más.",
    "Select_Fish": "Elige un pez al que apostar",
    "Eliminate_Award": "¡Elimina al resto y gana monedas!",
    "Records": "Consulta las recompensas y los récords",
    "Settlement_Rules": "Reglas de pago",
    "Settlement_Rules_Text": "Tres peces iguales compiten en el mismo carril uno junto al otro. Si uno queda eliminado, ganarás recompensas.\nLa recompensa se calcula sobre la base de cada pez.\nEl tipo de pez y la cantidad de eliminaciones afectarán la recompensa.\nLas ganancias se multiplican en función del siguiente multiplicador.\n¡Cuantos más peces elimines del carril, más recompensas ganarás!",
    "Back_Game": "Volver al juego",
    "Game_Name": "Pescamanía",
    "Activity_Ended": "La actividad finalizó.",
  },
  "NewDiBao": {
    "NewDiBaoTitle": "PAQUETE DE LA SUERTE",
    "Tip": "Obtén las monedas de la suerte de hoy",
    "mulit": "Recoger",
    "extra": "EXTRA",
    "basic": "BÁSICO",
    "coins": "MONEDAS",
    "togle": "¡Mira un anuncio y obtén {num} monedas!",
    "Before_Game_GoldEnough": "No te alcanzan las monedas",
    "StartGame": "Empezar juego",
  },
  "InsufficientCoin": {
    "title": "Necesitas al menos {num} monedas para jugar.",
    "tip": "Ahora tienes {haveCoin} monedas",
    "goScene": "Juego recomendado",
    "toOtherModel": "No tienes suficiente {coins} de oro para iniciar juegos. ¿Elegir otro modo?",
    "friend": "Amistades",
    "computer": "Computadora",
    "toOfferPlay": "No te alcanzan las monedas. ¿Quieres ir al modo de juego recomendado?",
  }
}
let loadMessage = function(language, dataID, isChange) {

};
exports.loadMessage = loadMessage;